<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>如此生活|星星杀</title>
	<meta name="viewport" content="width=device-width, initial-scale=1,maximum-scale=1,user-scalable=0">
	<meta name="apple-mobile-web-app-capable" content="yes">
	<meta name="apple-mobile-web-app-status-bar-style" content="black">	
	<link rel="stylesheet" type="text/css" href="/public/ext/css/soo.m.ui.css"/>
	<link rel="stylesheet" href="/public/ext/css/download.css">
	<link rel="stylesheet" href="/public/ext/css/swiper.css">
	<link rel="stylesheet" type="text/css" href="/public/css/starkill/common.css"/>
</head>
<body>
<div class="details_wrap">
	<div class="header">
		<a href="/starkill/mystar.html"><img class="arrow"  src="/public/img/starkill/icon/Group 36.png " ></a>
		<span class="head_title">星星杀</span> 
	</div>
	<!-- 下载框 -->
	<!-- <div class="download_box" id="download-nav">
		<div class="remove" id="download-nav-hide"><img src="../public/img/common/icon_close@3x.png" alt=""></div>
		<div class="logo"><img src="../public/img/common/logo@3x.png" alt=""></div>
		<div class="word">下载如此生活客户端</div>
		<div class="sure" id="download-nav-sure"><div>下载</div></div>
	</div> -->
	{% if buy['data']%}
	<div class="state_con">
    	 {% if buy['data']['sku_album']%}
		<div class="swiper-container details-container">
			<div class="swiper-wrapper">
				{% for d in  buy['data']['sku_album'] %}
				<div class="swiper-slide"> 
					<img class="state_img" src="{{d}}">
				</div>
				{% endfor %}
			</div>
			<!-- 分页效果 -->
			<div class="pagination"></div>
		</div>
        {% endif %}
        <div>
        	<p class="active_title">{{buy['data']['name']}}</p>
			<div class="active_txt">
				<input type="hidden" name="" class="buystamp" value="{{buy['data']['selling_end_date']}}" />
				<span class="differ_txt">距活动结束还有:</span>
				<span class="differ_time stamp"></span>
			</div>
			<p class="detail_low">￥{{buy['data']['now_price']}}</p>
			<p class="detail_price buy_price">￥{{buy['data']['life_price']}}</p>
			<p class="detail_wait">已参加{{buy['data']['qty']}}人</p>
        </div>
        <div class="details_img">
    	    {{buy['data']['spu_pictures']}}
        </div>
    </div>
	{% if buy['data']['status'] == 3 %}
        <a class="detail_buy">立即购买</a>
	{% else %}
        <a class="buy_soldout" href ="javascript:return false;" onclick="return false;">已售罄</a>
	{% endif %}
    {% endif %}

    <!-- 弹框 hide-->

    <div  class="alert_wrap hide">
    {% if buy['data']%}
        <input type="hidden"  name="" value="{{buy['data']['url']}}" id="url" />
        <input type="hidden"  name="" value="{{buy['data']['sku_id']}}" class="starkill_id" />
        <input type="hidden"  name="" value="{{buy['data']['redeem_code']}}" class="redeem_code" />
	    <div class="alert_bg"></div>
    	<div id="buy_box" class="alert_box">
	    	<p class="alert_coin" id="buy_sum">
	    	    <input type="hidden" class="rule" value=" {{buy['data']['now_price']}}" name="" />
		    	<span>￥</span><span class="coin_sum"></span>
	    	</p>
	    	<div class="alert_change">
		    	<div id="minus" class="change_wrap">
		    		<img   src="/public/img/starkill/icon/icon_jianhao.png"> 
		    	</div>
	    		<input id="result" type="number" name="" value="1" readonly="readonly" disabled="disabled"/>
	    		<div id="plus" class="change_wrap">
	    			<img  src="/public/img/starkill/icon/Group.png">
	    		</div>
	    	</div>
	    	<p class="alert_total"><span>最多优惠购买</span><span id="qty_num">{{buy['data']['actual_qty']}}</span><span>件</span></p>
	    	<a  id="suc_buy" class="alert_suc">确认</a>
	    </div>
	    <div id="alert_coin" class="hide">
	    	
	    </div>
	{% endif %}    
    </div>
</div>
</body>
</html>
<script src="/public/js/rem.js"></script> 
<script src="/public/ext/js/jquery-1.8.3.min.js"></script>
<script src="/public/ext/js/download.js"></script>
<script src="/public/js/jquery.base64.js"></script>
<script type="text/javascript" src="/public/ext/js/swiper.min.js"></script>
<script src="/public/js/starkill/buy.js"></script>