<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1,maximum-scale=1,user-scalable=no">
		<link rel="stylesheet" type="text/css" href="/public/css/getbag.css"/>
		<title>领取红包</title>
	</head>
	<body class="ljj_getredpacket">
		<div id="ljj_wrap">
		   <div class="header" url_member={{url_member}}>
		   	   <img class="redpacket" src="/public/img/starfans/img1/领取红包-3_02.png"/>
		   </div>
			<!-- <div class="text">
				<p class="click">点击 <a href="#"><span>【领取红包】</span></a>完成注册</p>
			                <p class="cash"><span>20元现金红包</span>将自动放入您的钱包</p>
			                <p class="recommend">推荐好友并注册成功，<span>再得10元！</span> 分享越多，赚得越多！</p>
			</div> -->
			<div class="text">
				<p class="click">活动已结束</p>
                <p class="cash"><span>20元现金红包活动已结束，请等待下一波红包到来！</span></p>
                <p class="recommend"></p>
			</div>
			 <div class="gap" member_id="{{member_id}}"></div>
              <!-- foot 立即领取 -->
              <div class="foot">
              	<!-- <div class="draw"><a>立刻领取 </a> </div> -->
              </div>
		</div>
	</body>
</html>
<script src="/public/ext/js/jquery-1.8.3.min.js"></script>
<script src="/public/js/index/soolife.getbag.js"></script>
<script src="/public/js/rem.js"></script>
<script src="/public/js/sdk.2.2.js"></script>