<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	 <meta name="viewport" content="width=device-width, initial-scale=1,maximum-scale=1,user-scalable=no">
	<link rel="stylesheet" type="text/css" href="/theme/activity/2016_09_Pentacles/mobile/css/Pen.css"/>
		<link rel="stylesheet" type="text/css" href="/public/mobile/css/foot.css" />

	<title>Pentaclesapp</title>
</head>
<body>
	<div class="lj_wrap">
		<!-- 头部显示 静图 -->
		 <div class="lj_header">
		 	<img src="/theme/activity/2016_09_Pentacles/mobile/img/headerf.jpg"/>
		 	<img src="/theme/activity/2016_09_Pentacles/mobile/img/headers.jpg"/>
		 	<img src="/theme/activity/2016_09_Pentacles/mobile/img/headerthree.jpg"/>
		 	<img src="/theme/activity/2016_09_Pentacles/mobile/img/hreaderfour.jpg"/>
		 	<img src="/theme/activity/2016_09_Pentacles/mobile/img/headerfive.jpg"/>
		 </div>
		 <!--中间商品部分-->
		 <div class="lj_whole">
		 <div class="lj_centerfirst">
		 	<ul>
		 		<li id="lj_one">
		 				<a href="http://item.soolife.cn/m/23292.html"><img src="/theme/activity/2016_09_Pentacles/mobile/img/cup.jpg" data="opengoodsdetail" />
						<img id="imgs" src="/theme/activity/2016_09_Pentacles/mobile/img/siftone.jpg" data="openinstantbuy" />
						<p class="oldprice">原价：106.0元</p>
						<p class="brand">施密特灵动直杯360 </p>
						<p class="trait">时尚设计 放心材质</p>
						</a>
		 		</li>
		 		<li  id="lj_one">
		 				<a href="http://item.soolife.cn/m/5121.html"><img src="/theme/activity/2016_09_Pentacles/mobile/img/lazyback.jpg" data="opengoodsdetail" />
						<img id="imgs" src="/theme/activity/2016_09_Pentacles/mobile/img/sifttwo.jpg" data="openinstantbuy" />
						<p class="oldprice">原价：156.0元</p>
						<p class="brand">敲敲乐颈肩按摩器</p>
						<p class="trait">明星产品 全新升级</p>
						</a>
		 		</li>
		 		<li>
		 				<a href="http://item.soolife.cn/m/13624.html"><img src="/theme/activity/2016_09_Pentacles/mobile/img/toiletry.jpg" data="opengoodsdetail" />
						<img id="imgs" src="/theme/activity/2016_09_Pentacles/mobile/img/siftthree.jpg"  data="openinstantbuy"/>
						<p class="oldprice">原价：169.5元</p>
						<p class="brand">科夫氏 超能蜗牛霜</p>
						<p class="trait">收缩毛孔 提拉紧致</p>
						</a>
		 		</li>
		 		<li>
		 				<a href="http://item.soolife.cn/m/32758.html"><img src="/theme/activity/2016_09_Pentacles/mobile/img/bauble.jpg" data="opengoodsdetail" />
						<img id="imgs" src="/theme/activity/2016_09_Pentacles/mobile/img/siftfour.jpg" data="openinstantbuy" />
						<p class="oldprice">原价：79.90元</p>
						<p class="brand">悠悠琦奇大咀猴 </p>
						<p class="trait">别样礼物 多色可选</p>
						</a>
		 		</li>
		 	</ul>
		 	</div>
		 	<!--发现全球好品牌-->
		 	<div class="lj_centertwo">
		 	<ul >
		 		<li>
		 			    <a href="http://item.soolife.cn/m/35977.html"><img src="/theme/activity/2016_09_Pentacles/mobile/img/Donlim.jpg" data="opengoodsdetail" />
						<img id="imgs" src="/theme/activity/2016_09_Pentacles/mobile/img/findone.jpg"  data="openinstantbuy"/>
						<p class="oldprice">原价：299元</p>
						<p class="brand">九阳豆浆机</p>
						<p class="trait">经典升级 让爱豆留</p>
						</a>
		 		</li>
		 		<li>
		 			    <a href="http://item.soolife.cn/m/36349.html"><img src="/theme/activity/2016_09_Pentacles/mobile/img/Luggage.jpg" data="opengoodsdetail" />
						<img id="imgs" src="/theme/activity/2016_09_Pentacles/mobile/img/findtwo.jpg" data="openinstantbuy" />
						<p class="oldprice">原价：239元</p>
						<p class="brand">经典镜面款拉杆箱 </p>
						<p class="trait">实用设计 简约气质</p>
						</a>
		 		</li>
		 		<li>
		 				<a href="http://item.soolife.cn/m/11136.html"><img src="/theme/activity/2016_09_Pentacles/mobile/img/footspa.jpg" data="opengoodsdetail" />
						<img id="imgs" src="/theme/activity/2016_09_Pentacles/mobile/img/findthree.jpg" data="openinstantbuy" />
						<p class="oldprice">原价：398.0元</p>
						<p class="brand">自动按摩足浴盆</p>
						<p class="trait">一键控制 温热按摩</p>
						</a>
		 		</li>
		 		<li>
		 			    <a href="http://item.soolife.cn/m/21198.html"><img src="/theme/activity/2016_09_Pentacles/mobile/img/Air.jpg" data="opengoodsdetail" />
					    <img id="imgs" src="/theme/activity/2016_09_Pentacles/mobile/img/findfour.jpg" data="openinstantbuy" />
						<p class="oldprice">原价：599.0</p>
						<p class="brand">甩脂塑腰美臀机 </p>
						<p class="trait">舒服享受 美臀塑型</p>
						</a>
		 		</li>
		 	</ul>
		 	</div>
		 	<!--美食美酒 不能让嘴停下来-->
		 	<div class="lj_centerthree">
		 	<ul class="center_food">
		 		<li>
		 				<a href="http://item.soolife.cn/m/13976.html"><img src="/theme/activity/2016_09_Pentacles/mobile/img/whitewine.jpg" data="opengoodsdetail" />
						<img id="imgs" src="/theme/activity/2016_09_Pentacles/mobile/img/food_one.jpg" data="openinstantbuy" />
						<p class="oldprice">原价：70.0元</p>
						<p class="brand">白甜型起泡葡萄酒</p>
						<p class="trait">闲暇优雅 品质情调</p>
						</a>
		 		</li>
		 		<li>
		 				<a href="http://item.soolife.cn/m/30904.html"><img src="/theme/activity/2016_09_Pentacles/mobile/img/cookie.jpg" data="opengoodsdetail" />
						<img id="imgs" src="/theme/activity/2016_09_Pentacles/mobile/img/food_two.jpg" data="openinstantbuy" />
						<p class="oldprice">原价：14.9元</p>
						<p class="brand">青稞膳食纤维饼干 </p>
						<p class="trait">膳食纤维 蔓越莓味</p>
						</a>
		 		</li>
		 		<li>
		 				<a href="http://item.soolife.cn/m/23329.html"><img src="/theme/activity/2016_09_Pentacles/mobile/img/bearclaw.jpg" data="opengoodsdetail" />
						<img id="imgs" src="/theme/activity/2016_09_Pentacles/mobile/img/food_three.jpg" data="openinstantbuy" />
						<p class="oldprice">原价：128.0元</p>
						<p class="brand">江苏裕德隆 熊掌菇</p>
						<p class="trait">肉质肥厚 营养丰富 </p>
						</a>
		 		</li>
		 		<li>
		 			    <a href="http://item.soolife.cn/m/34007.html"><img src="/theme/activity/2016_09_Pentacles/mobile/img/medlar.jpg" data="opengoodsdetail" />
						<img id="imgs" src="/theme/activity/2016_09_Pentacles/mobile/img/food_four.jpg" data="openinstantbuy" />
						<p class="oldprice">原价：338.0元</p>
						<p class="brand">森淼冻干枸杞贡果级</p>
						<p class="trait">冻干枸杞 粒大味甜</p>
						</a>
		 		</li>
		 		<li>
		 				<a href="http://item.soolife.cn/m/31036.html"><img src="/theme/activity/2016_09_Pentacles/mobile/img/lehua.jpg" data="opengoodsdetail" />
						<img id="imgs" src="/theme/activity/2016_09_Pentacles/mobile/img/food_five.jpg" data="openinstantbuy" />
						<p class="oldprice">原价：150.0元</p>
						<p class="brand">乐华红葡萄酒 </p>
						<p class="trait">口感甘甜 入口顺滑</p>
						</a>
		 		</li>
		 		<li>
		 				<a href="http://item.soolife.cn/m/13979.html"><img src="/theme/activity/2016_09_Pentacles/mobile/img/spumante.jpg" data="opengoodsdetail" />
						<img id="imgs" src="/theme/activity/2016_09_Pentacles/mobile/img/food_six.jpg" data="openinstantbuy" />
						<p class="oldprice">原价：90.0元</p>
						<p class="brand">绝干起泡葡萄酒</p>
						<p class="trait">原装进口 回味悠长</p>
						</a>
		 		</li>
		 		<li>
		 				<a href="http://item.soolife.cn/m/13980.html"><img src="/theme/activity/2016_09_Pentacles/mobile/img/whitewines.jpg" data="opengoodsdetail" />
						<img id="imgs" src="/theme/activity/2016_09_Pentacles/mobile/img/food_seven.jpg" data="openinstantbuy" />
						<p class="oldprice">原价：180.0元</p>
						<p class="brand">高泡起泡葡萄酒</p>
						<p class="trait">味道甜美 口感温和</p>
						</a>
		 		</li>
		 		<li>
						<a href="http://item.soolife.cn/m/28350.html"><img src="/theme/activity/2016_09_Pentacles/mobile/img/honeydate.jpg" data="opengoodsdetail" />
						<img id="imgs" src="/theme/activity/2016_09_Pentacles/mobile/img/food_eight.jpg" data="openinstantbuy" />
						<p class="oldprice">原价：60.0元</p>
						<p class="brand">江中阿胶蜜枣</p>
						<p class="trait">甜糯可口 甜而不腻</p>
						</a>
				</li>
		 	</ul>
		 	</div>
		 	<!-- 个护彩妆 -->
		 	<div class="lj_person">
		 		<ul class="center_cosmetics">
		 			<li>
		 				<a href="http://item.soolife.cn/m/15444.html"><img src="/theme/activity/2016_09_Pentacles/mobile/img/apitoxin.jpg" data="opengoodsdetail" />
						<img id="imgs" src="/theme/activity/2016_09_Pentacles/mobile/img/cosmeticsone.jpg" data="openinstantbuy" />
						<p class="oldprice">原价：750.0元</p>
						<p class="brand">蜂毒原液超值5件套</p>
						<p class="trait">留住青春 锁住滋润</p>
						</a>
		 			</li>
		 			<li>
		 				<a href="http://item.soolife.cn/m/27289.html"><img src="/theme/activity/2016_09_Pentacles/mobile/img/dentifrices.jpg" data="opengoodsdetail" />
						<img id="imgs" src="/theme/activity/2016_09_Pentacles/mobile/img/cosmeticstwo.jpg" data="openinstantbuy" />
						<p class="oldprice">原价：19.0元</p>
						<p class="brand">2080 青龈茶牙膏</p>
						<p class="trait">清新口气 健康生活</p>
						</a>
		 			</li>
		 			<li>
		 				<a href="http://item.soolife.cn/m/27146.html"><img src="/theme/activity/2016_09_Pentacles/mobile/img/shampoo.jpg" data="opengoodsdetail" />
						<img id="imgs" src="/theme/activity/2016_09_Pentacles/mobile/img/cosmeticsthree.jpg" data="openinstantbuy" />
						<p class="oldprice">原价：59.9元</p>
						<p class="brand">自然雅舍水果香波</p>
						<p class="trait">柔顺易梳 远离静电</p>
						</a>
		 			</li>
		 			<li>
		 				<a href="http://item.soolife.cn/m/28917.html"><img src="/theme/activity/2016_09_Pentacles/mobile/img/nature.jpg" data="opengoodsdetail" />
						<img id="imgs" src="/theme/activity/2016_09_Pentacles/mobile/img/cosmeticsfour.jpg" data="openinstantbuy" />
						<p class="oldprice">原价：765.0元</p>
						<p class="brand">自然系列套装</p>
						<p class="trait">水润肌肤 超强保湿</p>
						</a>
		 			</li>
		 		</ul>
		 	</div>
		 	<!--日用百货 力推好物抢先购-->
		 	 <div class="lj_department">
		 	 	<ul class="center_department">
		 	 		<li>
		 	 			<a href="http://item.soolife.cn/m/34168.html"><img src="/theme/activity/2016_09_Pentacles/mobile/img/watera.jpg" data="opengoodsdetail" />
						<img id="imgs" src="/theme/activity/2016_09_Pentacles/mobile/img/sear_onea.jpg" data="openinstantbuy" />
						<p class="oldprice">原价：79.0元</p>
						<p class="brand">凝彩水具5件套</p>
						<p class="trait">健康环保  厚实耐用</p>
						</a>
		 	 		</li>
		 	 		<li>
		 	 			<a href="http://item.soolife.cn/m/31777.html"><img src="/theme/activity/2016_09_Pentacles/mobile/img/shampoos.jpg" data="opengoodsdetail" />
						<img id="imgs" src="/theme/activity/2016_09_Pentacles/mobile/img/sear_oneb.jpg" data="openinstantbuy" />
						<p class="oldprice">原价：68.0元</p>
						<p class="brand">AEG双效洗衣露</p>
						<p class="trait">双效洁净  衣服更白</p>
						</a>
		 	 		</li>
		 	 		<li>
		 	 			<a href="http://item.soolife.cn/m/35574.html"><img src="/theme/activity/2016_09_Pentacles/mobile/img/towel.jpg" data="opengoodsdetail" />
						<img id="imgs" src="/theme/activity/2016_09_Pentacles/mobile/img/sear_one.jpg" data="openinstantbuy" />
						<p class="oldprice">原价：55.0元</p>
						<p class="brand">多功能清洁布擦手巾</p>
						<p class="trait">耐磨易洗 吸水性强</p>
						</a>
		 	 		</li>
		 	 		<li>
		 	 			<a href="http://item.soolife.cn/m/33834.html"><img src="/theme/activity/2016_09_Pentacles/mobile/img/decanter.jpg" data="opengoodsdetail" />
						<img id="imgs" src="/theme/activity/2016_09_Pentacles/mobile/img/sear_two.jpg" data="openinstantbuy" />
						<p class="oldprice">原价：135.0元</p>
						<p class="brand">快速醒酒器珍藏版</p>
						<p class="trait">流体设计 中心进气</p>
						</a>
		 	 		</li>
		 	 		<li>
		 	 			<a href="http://item.soolife.cn/m/34132.html"><img src="/theme/activity/2016_09_Pentacles/mobile/img/crisper.jpg" data="opengoodsdetail" />
						<img id="imgs" src="/theme/activity/2016_09_Pentacles/mobile/img/sear_three.jpg" data="openinstantbuy" />
						<p class="oldprice">原价：69.0元</p>
						<p class="brand">玻璃保鲜盒三件套</p>
						<p class="trait">简易方便 抗磨性好</p>
						</a>
		 	 		</li>
		 	 		<li>
		 	 			<a href="http://item.soolife.cn/m/34146.html"><img src="/theme/activity/2016_09_Pentacles/mobile/img/goblet.jpg" data="opengoodsdetail" />
						<img id="imgs" src="/theme/activity/2016_09_Pentacles/mobile/img/sear_four.jpg" data="openinstantbuy" />
						<p class="oldprice">原价：44.9元</p>
						<p class="brand">品味高脚杯</p>
						<p class="trait">时尚耐用 手感舒适</p>
						</a>
		 	 		</li>
		 	 	</ul>
		 	 </div>
		 	 </div>
		 	 <div class="footer"><img src="/theme/activity/2016_09_Pentacles/mobile/img/footers.jpg" /></div>
		 </div>
</body>
<script src="js/resize.js" type="text/javascript" charset="utf-8"></script>
</html>