<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>重阳节</title>
    <link href="/theme/activity/2016_09_DoubleNinthFestival/pc/css/base.css" rel="stylesheet">
    <link href="/theme/activity/2016_09_DoubleNinthFestival/pc/css/index.css" rel="stylesheet">
</head>
<body>
<div class="c_banner clearfix">
    <a href="#"><img src="/theme/activity/2016_09_DoubleNinthFestival/pc/img/c_banner_01.jpg"></a>
    <a href="#"><img src="/theme/activity/2016_09_DoubleNinthFestival/pc/img/c_banner_02.jpg"></a>
</div>
<div class="c_content">
    <div class="inner">
        <div class="item">
            <div class="ac">
                <a href="#"><img src="/theme/activity/2016_09_DoubleNinthFestival/pc/img/c_content_01.jpg"></a>
            </div>
            <div class="particulars">
                <div class="list">
                    <a href="http://item.soolife.cn/29554.html" target="_blank"><img src="/theme/activity/2016_09_DoubleNinthFestival/pc/img/c_content_02.jpg"></a>
                    <a class="ac" href="http://item.soolife.cn/29554.html" target="_blank">
                        <h2>洁斯家食品保鲜膜</h2>
                        <p class="desc">多种用途 方便易用</p>
                        <p class="activity"><span>重阳价</span> 9.9元</p>
                        <p class="price">原价:12.8元</p>
                    </a>
                </div>
                <div class="list">
                    <a href="http://item.soolife.cn/34109.html" target="_blank"><img src="/theme/activity/2016_09_DoubleNinthFestival/pc/img/c_content_03.jpg"></a>
                    <a class="ac" href="http://item.soolife.cn/34109.html" target="_blank">
                    <h2>洁斯家食品保鲜膜</h2>
                    <p class="desc">多种用途 方便易用</p>
                    <p class="activity"><span>重阳价</span> 9.9元</p>
                    <p class="price">原价:12.8元</p>
                    </a>
                </div>
                <div class="list">
                    <a href="http://item.soolife.cn/29432.html" target="_blank"><img src="/theme/activity/2016_09_DoubleNinthFestival/pc/img/c_content_04.jpg"></a>
                    <a class="ac" href="http://item.soolife.cn/29432.html" target="_blank">
                    <h2>洁斯家食品保鲜膜</h2>
                    <p class="desc">多种用途 方便易用</p>
                    <p class="activity"><span>重阳价</span> 9.9元</p>
                    <p class="price">原价:12.8元</p></a>
                </div>
                <div class="list">
                    <a href="http://item.soolife.cn/29454.html" target="_blank"><img src="/theme/activity/2016_09_DoubleNinthFestival/pc/img/c_content_05.jpg"></a>
                    <a class="ac" href="http://item.soolife.cn/29454.html" target="_blank">
                    <h2>洁斯家食品保鲜膜</h2>
                    <p class="desc">多种用途 方便易用</p>
                    <p class="activity"><span>重阳价</span> 9.9元</p>
                    <p class="price">原价:12.8元</p></a>
                </div>
            </div>
        </div>
        <div class="item">
            <div class="ac">
                <a href="#"><img src="/theme/activity/2016_09_DoubleNinthFestival/pc/img/c_content_06.jpg"></a>
            </div>
            <div class="particulars">
                <div class="list">
                    <a href="http://item.soolife.cn/12966.html" target="_blank"><img src="/theme/activity/2016_09_DoubleNinthFestival/pc/img/c_content_07.jpg"></a>
                    <!--<div class="ac">-->
                    <a class="ac" href="http://item.soolife.cn/12966.html" target="_blank">
                        <h2>去屑洗护套装</h2>
                        <p class="desc">洗护搭配 效果更佳</p>
                        <p class="activity"><span>重阳价</span> 188元</p>
                        <p class="price">原价:368元</p></a>
                    <!--</div>-->
                </div>
                <div class="list">
                    <a href="http://item.soolife.cn/15455.html" target="_blank"><img src="/theme/activity/2016_09_DoubleNinthFestival/pc/img/c_content_08.jpg"></a>
                    <a class="ac" href="http://item.soolife.cn/15455.html" target="_blank">
                    <h2>菁漾全然补水组合</h2>
                    <p class="desc">水润滋养 亮白肌肤</p>
                    <p class="activity"><span>重阳价</span> 336.7元</p>
                    <p class="price">原价:528元</p></a>
                </div>
                <div class="list">
                    <a href="http://item.soolife.cn/29211.html" target="_blank"><img src="/theme/activity/2016_09_DoubleNinthFestival/pc/img/c_content_09.jpg"></a>
                    <a class="ac" href="http://item.soolife.cn/29211.html" target="_blank">
                    <h2>黄马仕保湿礼盒</h2>
                    <p class="desc">酷爽洁净 劲能保湿</p>
                    <p class="activity"><span>重阳价</span> 85元</p>
                    <p class="price">原价:170元</p></a>
                </div>
                <div class="list">
                    <a href="http://item.soolife.cn/28036.html" target="_blank"><img src="/theme/activity/2016_09_DoubleNinthFestival/pc/img/c_content_10.jpg"></a>
                    <a class="ac" href="http://item.soolife.cn/28036.html" target="_blank">
                    <h2>亚麻籽油礼盒装</h2>
                    <p class="desc">厂家直供 亲民价格</p>
                    <p class="activity"><span>重阳价</span> 145元</p>
                    <p class="price">原价:290元</p></a>
                </div>
            </div>
        </div>
        <div class="item">
            <div class="ac">
                <a href="#"><img src="/theme/activity/2016_09_DoubleNinthFestival/pc/img/c_content_11.jpg"></a>
            </div>
            <div class="particulars">
                <div class="list">
                    <a href="http://item.soolife.cn/28329.html" target="_blank"><img src="/theme/activity/2016_09_DoubleNinthFestival/pc/img/c_content_12.jpg"></a>
                    <a class="ac" href="http://item.soolife.cn/28329.html" target="_blank">
                        <h2>恒大兴安香米一号</h2>
                        <p class="desc">莹润饱满 颗粒分明</p>
                        <p class="activity"><span>重阳价</span> 88元</p>
                        <p class="price">原价:90元</p>
                   </a>
                </div>
                <div class="list">
                    <a href="http://item.soolife.cn/33988.html"target="_blank"><img src="/theme/activity/2016_09_DoubleNinthFestival/pc/img/c_content_13.jpg"></a>
                    <a class="ac" href="http://item.soolife.cn/33988.html" target="_blank">
                    <h2>美之扣碎菜器</h2>
                    <p class="desc">原滋原味 品质升级</p>
                    <p class="activity"><span>重阳价</span> 59.85元</p>
                    <p class="price">原价:100元</p></a>
                </div>
                <div class="list">
                    <a href="http://item.soolife.cn/13467.html" target="_blank"><img src="/theme/activity/2016_09_DoubleNinthFestival/pc/img/c_content_14.jpg"></a>
                    <a class="ac" href="http://item.soolife.cn/13467.html" target="_blank">
                    <h2>无铅陶瓷泡茶壶</h2>
                    <p class="desc">层层堆叠 丝丝暖意</p>
                    <p class="activity"><span>重阳价</span> 215.2元</p>
                    <p class="price">原价:76.8元</p></a>
                </div>
                <div class="list">
                    <a href="http://item.soolife.cn/27234.html" target="_blank"><img src="/theme/activity/2016_09_DoubleNinthFestival/pc/img/c_content_15.jpg"></a>
                    <a class="ac" href="http://item.soolife.cn/27234.html" target="_blank">
                    <h2>素馨花补水面劲膜</h2>
                    <p class="desc">卓越品质 源自天然</p>
                    <p class="activity"><span>重阳价</span> 76.8元</p>
                    <p class="price">原价:128元</p></a>
                </div>
            </div>
        </div>
        <div class="item">
            <div class="ac">
                <a href="#"><img src="/theme/activity/2016_09_DoubleNinthFestival/pc/img/c_content_16.jpg"></a>
            </div>
            <div class="particulars">
                <div class="list">
                    <a href="http://item.soolife.cn/11139.html" target="_blank"><img src="/theme/activity/2016_09_DoubleNinthFestival/pc/img/c_content_17.jpg"></a>
                    <a class="ac" href="http://item.soolife.cn/11139.html" target="_blank">
                        <h2>滚轮按摩足浴盆</h2>
                        <p class="desc">足浴同时 尽享生活</p>
                        <p class="activity"><span>重阳价</span> 388元</p>
                        <p class="price">原价:588元</p></a>
                </div>
                <div class="list">
                    <a href="http://item.soolife.cn/11111.html" target="_blank"><img src="/theme/activity/2016_09_DoubleNinthFestival/pc/img/c_content_18.jpg"></a>
                    <a class="ac" href="http://item.soolife.cn/11111.html" target="_blank">
                    <h2>超强电动按摩锤</h2>
                    <p class="desc">超强按摩 强劲机芯</p>
                    <p class="activity"><span>重阳价</span> 119元</p>
                    <p class="price">原价:169元</p></a>
                </div>
                <div class="list">
                    <a href="http://item.soolife.cn/11143.html" target="_blank"><img src="/theme/activity/2016_09_DoubleNinthFestival/pc/img/c_content_19.jpg"></a>
                    <a class="ac" href="http://item.soolife.cn/11143.html" target="_blank">
                    <h2>深桶多功能足浴盆</h2>
                    <p class="desc">循环加热 立体按摩</p>
                    <p class="activity"><span>重阳价</span> 629.3元</p>
                    <p class="price">原价:899元</p></a>
                </div>
                <div class="list">
                    <a href="http://item.soolife.cn/5280.html" target="_blank"><img src="/theme/activity/2016_09_DoubleNinthFestival/pc/img/c_content_20.jpg"></a>
                    <a class="ac" href="http://item.soolife.cn/5280.html" target="_blank">
                    <h2>披肩腰带按摩器</h2>
                    <p class="desc">外观时尚 使用方便</p>
                    <p class="activity"><span>重阳价</span> 179元</p>
                    <p class="price">原价:346元</p></a>
                </div>
            </div>
        </div>
        <div class="item">
            <div class="ac">
                <a href="#"><img src="/theme/activity/2016_09_DoubleNinthFestival/pc/img/c_content_21.jpg"></a>
            </div>
            <div class="particulars">
                <div class="list">
                    <a href="http://item.soolife.cn/35921.html" target="_blank"><img src="/theme/activity/2016_09_DoubleNinthFestival/pc/img/c_content_23.jpg"></a>
                    <a class="ac" href="http://item.soolife.cn/35921.html" target="_blank">
                        <h2>至洁消毒洗衣液</h2>
                        <p class="desc">去污消毒 一步完成</p>
                        <p class="activity"><span>重阳价</span> 99元</p>
                        <p class="price">原价:198元</p>
                        </a>
                </div>
                <div class="list">
                    <a href="http://item.soolife.cn/27289.html" target="_blank"><img src="/theme/activity/2016_09_DoubleNinthFestival/pc/img/c_content_24.jpg"></a>
                    <a class="ac" href="http://item.soolife.cn/27289.html" target="_blank">
                    <h2>2080青龈茶牙膏</h2>
                    <p class="desc">韩国品牌 值得信赖</p>
                    <p class="activity"><span>重阳价</span> 19元</p>
                    <p class="price">原价:21元</p></a>
                </div>
                <div class="list">
                    <a href="http://item.soolife.cn/25767.html" target="_blank"><img src="/theme/activity/2016_09_DoubleNinthFestival/pc/img/c_content_25.jpg"></a>
                    <a class="ac" href="http://item.soolife.cn/25767.html" target="_blank">
                    <h2>熊屋牌有机蜜</h2>
                    <p class="desc">蓝瓶品质 蜂味十足</p>
                    <p class="activity"><span>重阳价</span> 100元</p>
                    <p class="price">原价:100元</p></a>
                </div>
                <div class="list">
                    <a href="http://item.soolife.cn/28034.html" target="_blank"><img src="/theme/activity/2016_09_DoubleNinthFestival/pc/img/c_content_26.jpg"></a>
                    <a class="ac" href="http://item.soolife.cn/28034.html" target="_blank">
                    <h2>亚麻籽油礼盒装</h2>
                    <p class="desc">天然洁净 安全享用</p>
                    <p class="activity"><span>重阳价</span> 98元</p>
                    <p class="price">原价:98元</p></a>
                </div>
            </div>
        </div>
    </div>
    <div class="c_content_bottom">
        <img src="/theme/activity/2016_09_DoubleNinthFestival/pc/img/c_content_27.jpg">
    </div>
</div>

</body>
</html>