<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>账单详情|如此生活</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
  <!--   <meta name="viewport" content="width=device-width, initial-scale=1,maximum-scale=1,user-scalable=no">    -->
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <link rel="stylesheet" href="/public/ext/css/soo.m.ui.css">
    <!-- <link rel="stylesheet" href="/public/css/huilife/common.css"> -->
    <!-- <link rel="stylesheet" href="/public/css/huilife/index.css"> -->
	<link rel="stylesheet" href="/public/css/me/index.css">
</head>
<body id="bde_me_cash">


<!-- 头部 -->
<div id="ba-new-header">
	<div class="header-left fl-left">
		<a onclick="window.history.go(-1)"> <img src="../public/img/common/shop_back_black@2x.png" alt=""></a>
	</div>
	<!-- <div id="header-center">领星币</div> -->
	<div class="header-center fl-left">账单详情</div>
	<div class="header-right"></div>
</div>
<div class="details">
	<div class="heading">
		<p class="names">{{data['msg']}}</p>
		<p class="price">{{data['money']}}</p>
	</div>
	<div class="describe">
		<div class="flowing">
			<p class="fl-left text-l ">交易流水号：</p>
			<p class="content text-r">{{data['id']}}</p>
		</div>
		<div class="flowing">
			<p class="fl-left text-l ">创建时间：</p>
			<p class="content text-r">{{data['time']}}</p>
		</div>
	</div>
</div>
<!-- <div class="relation">
		<div class="flowing">
			<p class="fl-left text-l ">交易流水号：</p>
			<p class="content text-r">21645765464</p>
		</div>
			<div class="flowing ">
			<p class="text-l ">关联商品：</p>
			<div class="scroll">
				<div class="picture">
				<img src="../public/img/newcoller/pingjia@2x.png">
				<img src="../public/img/newcoller/pingjia@2x.png">
				<img src="../public/img/newcoller/pingjia@2x.png">
				<img src="../public/img/newcoller/pingjia@2x.png">
                <img src="../public/img/newcoller/pingjia@2x.png">
                <img src="../public/img/newcoller/pingjia@2x.png">

			</div>	
			</div>
		
		</div>
</div> -->
<script>

</script>

<script src="/public/ext/js/jquery-1.8.3.min.js"></script>
<script src="/public/ext/js/download.js"></script>
<script src="/public/ext/js/soo.m.ui.js"></script>
<script src="/public/ext/js/jquery.base64.js"></script>
<script src="/public/js/huilife/life.index.js"></script>
<script src="/public/ext/js/rem.js"></script>
<script src="/public/js/me/index.js"></script>
</body>
</html>