<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>新人专场|如此生活</title>

    <meta name="viewport" content="width=device-width, initial-scale=1,maximum-scale=1,user-scalable=no">   
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <link rel="stylesheet" href="/public/ext/css/soo.m.ui.css">
    <!-- <link rel="stylesheet" href="/public/css/huilife/common.css"> -->
    <!-- <link rel="stylesheet" href="/public/css/huilife/index.css"> -->
	<link rel="stylesheet" href="/public/css/me/index.css">
</head>
<body id="wi_me_cash">


<!-- 头部 -->
<div id="ba-new-header">
	<div class="header-left fl-left">
		<a onclick="window.history.go(-1)"> <img src="../public/img/common/shop_back_black@2x.png" alt=""></a>
	</div>
	<!-- <div id="header-center">领星币</div> -->
	<div class="header-center fl-left">售后申请</div>
	<div class="header-right"><img src="../public/img/me/Group3.png"></div>
</div>
<div class="subject">
	<div class="careful">
		<p class="examine">请如实填写下方内容，以便如此生活顺利进行审核</p>
		<p class="return">如果您的商品有任何质量问题，可以进行退货；海外精品暂不支持无理由退货</p>
	</div>
	<div class="commodity">
		
	</div>
</div>
<script>

</script>

<script src="/public/ext/js/jquery-1.8.3.min.js"></script>
<script src="/public/ext/js/download.js"></script>
<script src="/public/ext/js/soo.m.ui.js"></script>
<script src="/public/ext/js/jquery.base64.js"></script>
<script src="/public/js/huilife/life.index.js"></script>
<script src="/public/ext/js/rem.js"></script>
<script src="/public/js/me/index.js"></script>
</body>
</html>