<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
	<title>Title</title>
	<link href="/theme/activity/2016_10_infantmom/mobile/css/base.css" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="/public/mobile/css/foot.css" />

</head>
<body>
	<div class="cao_banner">
		<img src="/theme/activity/2016_10_infantmom/mobile/img/cao_banner_01.jpg" class="ac" data="opengoodsdetail"/>
	</div>
	<div id="cao_content">
		<div class="floor_one clearfix">
			<div class="title">
				<img src="/theme/activity/2016_10_infantmom/mobile/img/cao_content_02.jpg" data="opengoodsdetail"/>
			</div>
			<div class="floor_one_overbalance clearfix">
				<div class="left">
					<a href="http://item.soolife.cn/m/38409.html"><img src="/theme/activity/2016_10_infantmom/mobile/img/cao_content_03.jpg" data="opengoodsdetail"/></a>
				</div>
				<div class="right ">
					<h3>爱得利</h3>
					<p class="aa">
						婴儿卫生柔湿巾
					</p>
					<p class="desc">
						品牌直销 超值赠品
					</p>
					<span style="padding-left: 15%;padding-bottom: 10%;display: block;">(限量500件)</span>
				</div>
			</div>
		</div>
		<!--////////////////////////////////////////////////////////////////////////////////////////////////////1F-->
		<div class="floor clearfix">
			<div class="title">
				<img src="/theme/activity/2016_10_infantmom/mobile/img/cao_content_04.jpg" data="opengoodsdetail"/>
			</div>
			<a href="http://item.soolife.cn/m/6084.html" class="grow clearfix"style="display: block">
			<div class="left">
				<h2 style="margin-top: 10%">可换向婴儿推车</h2>
				<p class="desc">
					婴儿推车 舒适安全
				</p>
				<p class="price" style="padding-top: 5%">
					活动价:<span>498</span><span class="original">原价:1078</span>
				</p>
				<span class="ac" data="openinstantbuy">立即购买</span>
			</div>
			<div class="right">
				<img src="/theme/activity/2016_10_infantmom/mobile/img/cao_content_05.jpg" data="opengoodsdetail"/>
			</div> </a>
			<a href="http://item.soolife.cn/m/13220.html" class="list">
			<div class="pic">
				<img src="/theme/activity/2016_10_infantmom/mobile/img/cao_content_06.jpg" data="opengoodsdetail"/>
			</div>
			<div class="desc">
				<h2>Lite5婴儿推车</h2>
				<p class="desc">
					收放自如 安心保护
				</p>
				<p class="price">
					活动价:<span style="font-size: 1.6em">318</span><span class="original">原价:709</span>
				</p>
				<span class="ac" data="openinstantbuy">立即购买</span>
			</div> </a>
			<a href="http://item.soolife.cn/m/13227.html" class="list">
			<div class="pic">
				<img src="/theme/activity/2016_10_infantmom/mobile/img/cao_content_07.jpg" data="opengoodsdetail"/>
			</div>
			<div class="desc">
				<h2>ziibra婴儿推车</h2>
				<p class="desc">
					天然温和 强韧耐用
				</p>
				<p class="price">
					活动价:<span style="font-size: 1.6em">248</span><span class="original">原价:480</span>
				</p>
				<span class="ac" data="openinstantbuy">立即购买</span>
			</div> </a>
			<a href="http://item.soolife.cn/m/6325.html" class="list">
			<div class="pic">
				<img src="/theme/activity/2016_10_infantmom/mobile/img/cao_content_08.jpg" data="opengoodsdetail"/>
			</div>
			<div class="desc">
				<h2>蒙古包</h2>
				<p class="desc">
					便捷舒心 四季适用
				</p>
				<p class="price">
					活动价:<span style="font-size: 1.6em">228</span><span class="original">原价:488</span>
				</p>
				<span class="ac" data="openinstantbuy">立即购买</span>
			</div> </a>
			<a class="list" href="http://item.soolife.cn/m/13240.html">
			<div class="pic">
				<img src="/theme/activity/2016_10_infantmom/mobile/img/cao_content_09.jpg" data="opengoodsdetail"/>
			</div>
			<div class="desc">
				<h2>婴儿隔尿垫</h2>
				<p class="desc">
					纯棉面料 环保印染
				</p>
				<p class="price">
					活动价:<span style="font-size: 1.6em">68</span><span class="original">原价:196.00</span>
				</p>
				<span class="ac" data="openinstantbuy">立即购买</span>
			</div> </a>

			<!--//////////////////////////////////////////////////////////////////2F-->
			<div class="title">
				<img src="/theme/activity/2016_10_infantmom/mobile/img/cao_content_10.jpg" data="opengoodsdetail"/>
			</div>
			<a href="http://item.soolife.cn/m/34930.html" class="grow clearfix"style="display: block">34974
			<div class="left">
				<h2 style="margin-top: 10%">多功能纯棉纱巾</h2>
				<p class="desc">
					柔软亲肤 安全天然
				</p>
				<p class="price" style="padding-top: 5%">
					活动价:<span>378</span><span class="original">原价:599</span>
				</p>
				<span class="ac" data="openinstantbuy">立即购买</span>
			</div>
			<div class="right">
				<img src="/theme/activity/2016_10_infantmom/mobile/img/cao_content_11.jpg" data="opengoodsdetail"/>
			</div> </a>
			<a  href="http://item.soolife.cn/m/35028.html" class="list">
			<div class="pic">
				<img src="/theme/activity/2016_10_infantmom/mobile/img/cao_content_12.jpg" data="opengoodsdetail"/>
			</div>
			<div class="desc">
				<h2>婴儿纱布毯</h2>
				<p class="desc">
					纯竹纤维 柔软呵护
				</p>
				<p class="price">
					活动价:<span style="font-size: 1.6em">188</span><span class="original">原价:399</span>
				</p>
				<span class="ac" data="openinstantbuy">立即购买</span>
			</div> </a>
			<a class="list" href="http://item.soolife.cn/m/34974.html">
			<div class="pic">
				<img src="/theme/activity/2016_10_infantmom/mobile/img/cao_content_13.jpg" data="opengoodsdetail"/>
			</div>
			<div class="desc">
				<h2>透气蜂窝毯</h2>
				<p class="desc">
					吸湿透气 抗菌抑菌
				</p>
				<p class="price">
					活动价:<span style="font-size: 1.6em">228</span><span class="original">原价:528</span>
				</p>
				<span class="ac" data="openinstantbuy">立即购买</span>
			</div> </a>
			<a href="http://item.soolife.cn/m/34684.html" class="list">
			<div class="pic">
				<img src="/theme/activity/2016_10_infantmom/mobile/img/cao_content_14.jpg" data="opengoodsdetail"/>
			</div>
			<div class="desc">
				<h2>竹棉针织毯礼盒</h2>
				<p class="desc">
					澳洲进口 品质保证
				</p>
				<p class="price">
					活动价:<span style="font-size: 1.6em">698</span><span class="original">原价:799</span>
				</p>
				<span class="ac" data="openinstantbuy">立即购买</span>
			</div> </a>
			<a class="list"  href="http://item.soolife.cn/m/34915.html">
			<div class="pic">
				<img src="/theme/activity/2016_10_infantmom/mobile/img/cao_content_15.jpg" data="opengoodsdetail"/>
			</div>
			<div class="desc">
				<h2>纯竹纤维薄纱布</h2>
				<p class="desc">
					丝般触感 贴身放心
				</p>
				<p class="price">
					活动价:<span style="font-size: 1.6em">498</span><span class="original">原价:698</span>
				</p>
				<span class="ac" data="openinstantbuy">立即购买</span>
			</div> </a>

			<!--///////////////////////////////////////////////////////////////////////3F-->
			<div class="title">
				<img src="/theme/activity/2016_10_infantmom/mobile/img/cao_content_16.jpg" data="opengoodsdetail"/>
			</div>
			<a class="grow clearfix"style="display: block" href="http://item.soolife.cn/m/34100.html">
			<div class="left">
				<h2 style="margin-top: 10%">儿童立体百科全书</h2>
				<p class="desc">
					伟大发明 百科全书
				</p>
				<p class="price" style="padding-top: 5%">
					活动价:<span>57.3</span><span class="original">原价:98.8</span>
				</p>
				<span class="ac" data="openinstantbuy">立即购买</span>
			</div>
			<div class="right">
				<img src="/theme/activity/2016_10_infantmom/mobile/img/cao_content_17.jpg" data="opengoodsdetail"/>
			</div> </a>
			<a class="list" href="http://item.soolife.cn/m/34102.html">
			<div class="pic">
				<img src="/theme/activity/2016_10_infantmom/mobile/img/cao_content_18.jpg" data="opengoodsdetail"/>
			</div>
			<div class="desc">
				<h2>神奇赛车故事书</h2>
				<p class="desc">
					乐乐趣赛车总动员
				</p>
				<p class="price">
					活动价:<span style="font-size: 1.6em">109</span><span class="original">原价:188</span>
				</p>
				<span class="ac" data="openinstantbuy"style="padding-bottom: 0;margin-bottom: 8%">立即购买</span>
			</div> </a>
			<a class="list" href="http://item.soolife.cn/m/37546.html">
			<div class="pic">
				<img src="/theme/activity/2016_10_infantmom/mobile/img/cao_content_19.jpg" data="opengoodsdetail"/>
			</div>
			<div class="desc">
				<h2></h2>看里面低幼版套装</h2>
				<p class="desc">
					因为品质 所以卓越
				</p>
				<p class="price">
					活动价:<span style="font-size: 1.6em">275.2</span><span class="original">原价:299</span>
				</p>
				<span class="ac" data="openinstantbuy">立即购买</span>
			</div> </a>
			<a class="list" href="http://item.soolife.cn/m/10044.html">
			<div class="pic">
				<img src="/theme/activity/2016_10_infantmom/mobile/img/cao_content_20.jpg" data="opengoodsdetail"/>
			</div>
			<div class="desc">
				<h2>汉婗喂奶巾</h2>
				<p class="desc">
					哺乳遮巾 使用方便
				</p>
				<p class="price">
					活动价:<span style="font-size: 1.6em">118</span><span class="original">原价:188</span>
				</p>
				<span class="ac" data="openinstantbuy">立即购买</span>
			</div> </a>
			<a class="list" href="http://item.soolife.cn/m/31132.html">
			<div class="pic">
				<img src="/theme/activity/2016_10_infantmom/mobile/img/cao_content_21.jpg" data="opengoodsdetail"/>
			</div>
			<div class="desc">
				<h2>孕妇连衣裙</h2>
				<p class="desc">
					新品上市 现货抢购
				</p>
				<p class="price">
					活动价:<span style="font-size: 1.6em">68</span><span class="original">原价:75</span>
				</p>
				<span class="ac" data="openinstantbuy">立即购买</span>
			</div> </a>
			<!--///////////////////////////////////////////////////////////////////////////////////////////////////4F-->
			<div class="title">
				<img src="/theme/activity/2016_10_infantmom/mobile/img/cao_content_22.jpg" data="opengoodsdetail"/>
			</div>
			<a class="grow clearfix"style="display: block"  href="http://item.soolife.cn/m/29535.html">
			<div class="left">
				<h2 style="margin-top: 10%">狗狗敲击台</h2>
				<p class="desc">
					进口水漆 安全无毒
				</p>
				<p class="price" style="padding-top: 5%">
					活动价:<span>180</span><span class="original">原价:360</span>
				</p>
				<span class="ac" data="openinstantbuy">立即购买</span>
			</div>
			<div class="right">
				<img src="/theme/activity/2016_10_infantmom/mobile/img/cao_content_23.jpg" data="opengoodsdetail"/>
			</div> </a>
			<a class="list" href="http://item.soolife.cn/m/28375.html">
			<div class="pic">
				<img src="/theme/activity/2016_10_infantmom/mobile/img/cao_content_24.jpg" data="opengoodsdetail"/>
			</div>
			<div class="desc">
				<h2>益智磁力片套组</h2>
				<p class="desc">
					创造力和智力的开发
				</p>
				<p class="price">
					活动价:<span style="font-size: 1.6em">498</span><span class="original">原价:598</span>
				</p>
				<span class="ac" data="openinstantbuy">立即购买</span>
			</div> </a>
			<a class="list" href="http://item.soolife.cn/m/28384.html">
			<div class="pic">
				<img src="/theme/activity/2016_10_infantmom/mobile/img/cao_content_25.jpg" data="opengoodsdetail"/>
			</div>
			<div class="desc">
				<h2>益智磁力片14片</h2>
				<p class="desc">
					百变造型 超越想象
				</p>
				<p class="price">
					活动价:<span style="font-size: 1.6em">258</span><span class="original">原价:288</span>
				</p>
				<span class="ac" data="openinstantbuy">立即购买</span>
			</div> </a>
			<a class="list" href="http://item.soolife.cn/m/32201.html">
			<div class="pic">
				<img src="/theme/activity/2016_10_infantmom/mobile/img/cao_content_26.jpg" data="opengoodsdetail"/>
			</div>
			<div class="desc">
				<h2>逻辑关联拼图</h2>
				<p class="desc">
					爱的智慧 寓教于乐
				</p>
				<p class="price">
					活动价:<span style="font-size: 1.6em">34</span><span class="original">原价:68</span>
				</p>
				<span class="ac" data="openinstantbuy">立即购买</span>
			</div> </a>
			<a class="list" href="http://item.soolife.cn/m/29530.html">
			<div class="pic">
				<img src="/theme/activity/2016_10_infantmom/mobile/img/cao_content_27.jpg" data="opengoodsdetail"/>
			</div>
			<div class="desc">
				<h2>小狗字母拼图</h2>
				<p class="desc">
					益智娱乐 字幕拼图
				</p>
				<p class="price">
					活动价:<span style="font-size: 1.6em">44</span><span class="original">原价:88</span>
				</p>
				<span class="ac" data="openinstantbuy">立即购买</span>
			</div> </a>

		</div>
	</div>
	<script src="/public/mobile/js/jquery-3.0.0.min.js"></script>
	<script src="/public/js/sdk.js"></script>
	<script src="/public/mobile/js/websdk.js"></script>

</body>
