<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>如此生活|绑定注册</title>
	<meta name="viewport" content="width=device-width, initial-scale=1,maximum-scale=1,user-scalable=no">
	<meta name="apple-mobile-web-app-capable" content="yes">
	<meta name="apple-mobile-web-app-status-bar-style" content="black">
	<link rel="stylesheet" type="text/css" href="/public/css/bound/bound.css"/>
</head>
<body>
	<div class="wrap">
		<div class="header" id="header">
			<span onclick="window.history.go(-1)">
				<img src="/public/img/brandhui/xingxingsha_back@2x.png " class="lefter">
			</span>
			<span class="lj_srt">绑定注册</span> 
		</div>
		<div class="void"></div>
		<div class="kong">
			<div class="iphone">
				<input type="text" name="iphone" maxlength="11" placeholder="请输入手机号">
			</div>
			<div class="iphone  security">  
				<input type="text" name="vcode" maxlength="6" placeholder="请输入验证码">
				<div id="btn" name="" >获取验证码</div>
				<div id="s_box" ></div>
			</div>
			<div class="iphone">
				<input type="password" name="password1" maxlength="20" placeholder="输入新的6-20位数字、字母组合">
			</div>
			<div class="ensure">绑定</div>
			<div class="alreadys">
				<a href="">已有账号</a>
			</div>
		</div>
		
	</div>
</body>
<script src="/public/js/rem.js"></script> 
<script src="/public/ext/js/jquery-1.8.3.min.js"></script>
</html>