<?php
$css = $this -> assets -> get('header');
$css -> addCss("public/v3.0.1/css/pc.market.css");

$js = $this -> assets -> get('footer');
$js -> addJs("public/v3.0.1/js/pc.market.js");

$style = '';
if (!empty($banner))
{
	$item = current($banner);
	$style = @"background: {$item['bgcolor']} url('{$this->utility->get_advert_picture($item['bgimage'])}') no-repeat center center;";
}
?>
<div id="banner" class="row-container" style="{{ style }}">
	<div class="market_banner">
		<!-- begin carousel -->
		<div id="carousel-index"  class="carousel slide" data-ride="carousel">
			<ol class="carousel-indicators">
				{% if banner %}
					{% for d in banner %}
						<li data-target="#carousel-index" data-slide-to="{{loop.index0}}" {% if loop.first %} class="active" {% endif %}></li>
					{% endfor %}
				{% endif %}
			</ol>
			<div class="carousel-inner" role="listbox">
				{% if banner %}
					{% for d in banner %}
					<div class="item  {% if loop.first %} active {% endif %}" 
						data-bgcolor="{{d['bgcolor']}}" 
						data-bgimage="<?php echo $this->utility->get_advert_picture($d['bgimage']); ?>"
						data-link="{{d['link']}}" 
						data-id="{{d['id']}}">
							
						<a href="{{d['link']}}" target="_blank">
							<img class="carousel-images" src="<?php echo $this->utility->get_advert_picture($d['picture']); ?>" alt="{{d['title']}}">
						</a>
						<div class="carousel-floated">
							<ul>
								<li class="frame">
									<div class="move">
										<?php echo $this->utility->get_advert_html('first',$d['sidebar']['first'],FALSE); ?>
									</div>
								</li>
								<li class="frame">
									<div class="move">
										<?php echo $this->utility->get_advert_html('second',$d['sidebar']['second'],FALSE); ?>
									</div>
								</li>
							</ul>
						</div>
					</div>
					{% endfor %}
				{% endif %}
			</div>
		</div>
		<!-- end carousel -->
	</div>
</div>

<div class="row-container clearfix">
	<div class="market_content main-container">
			<ul>
				<li class="frame">
					<div class="largen">
						<?php echo $this->utility->get_advert_html('pc.market.banner.005',$ads); ?>
					</div>
				</li>
				<li class="frame">
					<div class="largen">
						<?php echo $this->utility->get_advert_html('pc.market.banner.006',$ads); ?>
					</div>
				</li>
				<li class="wide frame">
					<div class="largen">
						<?php echo $this->utility->get_advert_html('pc.market.banner.007',$ads); ?>
					</div>
				</li>
				<li class="frame">
					<div class="largen">
						<?php echo $this->utility->get_advert_html('pc.market.banner.008',$ads); ?>
					</div>
				</li>
				<li class="frame">
					<div class="largen">
						<?php echo $this->utility->get_advert_html('pc.market.banner.009',$ads); ?>
					</div>
				</li>
			</ul>
	</div>
	<div class="full-column main-container">
		<?php echo $this->utility->get_advert_direct('pc.market.banner.column',$ads); ?>
	</div>
</div>


<!-- 陪你疯 -->
<div id="crazy" class="row-container clearfix">
	<div class="crazy main-container">
		<div class="crazy_title">
			<span>陪你疯</span>
		</div>
		<div class="crazy_content">
			<div class="leftside">
				<ul class="slither">
					{% if ads['pc.market.crazy.001'] %}
						{% for d in ads['pc.market.crazy.001'] %}
							<li {{ ( loop.first )? "class='open'":'' }}>
								<a href="{{d['pc_link']}}" target="_blank" title="{{d['title']}}">
					 				<img class="lazy" src="/public/v3.0.1/img/s.gif" data-original="<?php echo $this->utility->get_advert_picture($d['picture']); ?>" title="{{d['title']}}" alt="{{d['title']}}" />
					 			</a>
							</li>
						{% endfor %}
					{% endif %}
				</ul>
			</div>
			<div class="rightside">
				<ul>
					<li class="frame">
						<div class="move">
							<?php echo $this->utility->get_advert_html('pc.market.crazy.002',$ads); ?>
						</div>
					</li>
					<li class="frame">
						<div class="move">
							<?php echo $this->utility->get_advert_html('pc.market.crazy.003',$ads); ?>
						</div>
					</li>
					<li class="frame">
						<div class="move">
							<?php echo $this->utility->get_advert_html('pc.market.crazy.004',$ads); ?>
						</div>
					</li>
					<li class="frame">
						<div class="move">
							<?php echo $this->utility->get_advert_html('pc.market.crazy.005',$ads); ?>
						</div>
					</li>
					<li class="frame">
						<div class="move">
							<?php echo $this->utility->get_advert_html('pc.market.crazy.006',$ads); ?>
						</div>
					</li>
					<li class="frame">
						<div class="move">
							<?php echo $this->utility->get_advert_html('pc.market.crazy.007',$ads); ?>
						</div>
					</li>
					<li class="frame">
						<div class="move">
							<?php echo $this->utility->get_advert_html('pc.market.crazy.008',$ads); ?>
						</div>
					</li>
					<li class="frame">
						<div class="move">
							<?php echo $this->utility->get_advert_html('pc.market.crazy.009',$ads); ?>
						</div>
					</li>
				</ul>
			</div>
		</div>
		<div class="clearfix"></div>
	</div>
	<div class="full-column main-container">
		<?php echo $this->utility->get_advert_direct('pc.market.crazy.column',$ads); ?>
	</div>
</div>


<!-- 任你购 -->
<div id="caprice" class="row-container clearfix">
	<div class="caprice main-container">
		<div class="caprice_title">
			<span>任你购</span>
		</div>
		<div class="caprice_content">
			<ul>
				<li class="frame">
					<div class="move">
						<?php echo $this->utility->get_advert_html('pc.market.caprice.001',$ads); ?>
					</div>
				</li>
				<li class="frame">
					<div class="move">
						<?php echo $this->utility->get_advert_html('pc.market.caprice.002',$ads); ?>
					</div>
				</li>
				<li class="frame">
					<div class="move">
						<?php echo $this->utility->get_advert_html('pc.market.caprice.003',$ads); ?>
					</div>
				</li>
				<li class="frame">
					<div class="move">
						<?php echo $this->utility->get_advert_html('pc.market.caprice.004',$ads); ?>
					</div>
				</li>
				<li class="frame">
					<div class="move">
						<?php echo $this->utility->get_advert_html('pc.market.caprice.005',$ads); ?>
					</div>
				</li>
				<li class="frame">
					<div class="move">
						<?php echo $this->utility->get_advert_html('pc.market.caprice.006',$ads); ?>
					</div>
				</li>
			</ul>
		</div>
	</div>
	<div class="full-column main-container">
		<?php echo $this->utility->get_advert_direct('pc.market.caprice.column',$ads); ?>
	</div>
</div>


<!--/ 食品酒水 /-->
<div id="floor01" class="row-container clearfix">
	<div class="floor main-container">
		<div class="floor_title">
			<span>/ 食品酒水 /</span>
		</div>
		<div class="floor_content">
			<div class="leftside">
				<?php echo $this->utility->get_advert_html('pc.market.floor.001.goods01',$ads); ?>
			</div>
			<div class="rightside">
				<ul>
					<li class="frame">
						<div class="move">
							<?php echo $this->utility->get_advert_html('pc.market.floor.001.goods02',$ads); ?>
						</div>
					</li>
					<li class="frame">
						<div class="move">
							<?php echo $this->utility->get_advert_html('pc.market.floor.001.goods03',$ads); ?>
						</div>
					</li>
					<li class="frame">
						<div class="move">
							<?php echo $this->utility->get_advert_html('pc.market.floor.001.goods04',$ads); ?>
						</div>
					</li>
					<li class="frame">
						<div class="move">
							<?php echo $this->utility->get_advert_html('pc.market.floor.001.goods05',$ads); ?>
						</div>
					</li>
					<li class="frame">
						<div class="move">
							<?php echo $this->utility->get_advert_html('pc.market.floor.001.goods06',$ads); ?>
						</div>
					</li>
					<li class="frame">
						<div class="move">
							<?php echo $this->utility->get_advert_html('pc.market.floor.001.goods07',$ads); ?>
						</div>
					</li>
					<li class="frame">
						<div class="move">
							<?php echo $this->utility->get_advert_html('pc.market.floor.001.goods08',$ads); ?>
						</div>
					</li>
					<li class="frame">
						<div class="move">
							<?php echo $this->utility->get_advert_html('pc.market.floor.001.goods09',$ads); ?>
						</div>
					</li>
				</ul>
			</div>
		</div>
		<div class="clearfix"></div>
	</div>
	<div class="full-column main-container">
		<?php echo $this->utility->get_advert_direct('pc.market.floor.001.column',$ads); ?>
	</div>
</div>


<!--/ 智能电配 /-->
<div id="floor02" class="row-container clearfix">
	<div class="floor main-container">
		<div class="floor_title">
			<span>/ 智能电配 /</span>
		</div>
		<div class="floor_content">
			<div class="leftside">
				<?php echo $this->utility->get_advert_html('pc.market.floor.002.goods01',$ads); ?>
			</div>
			<div class="rightside">
				<ul>
					<li class="frame">
						<div class="move">
							<?php echo $this->utility->get_advert_html('pc.market.floor.002.goods02',$ads); ?>
						</div>
					</li>
					<li class="frame">
						<div class="move">
							<?php echo $this->utility->get_advert_html('pc.market.floor.002.goods03',$ads); ?>
						</div>
					</li>
					<li class="frame">
						<div class="move">
							<?php echo $this->utility->get_advert_html('pc.market.floor.002.goods04',$ads); ?>
						</div>
					</li>
					<li class="frame">
						<div class="move">
							<?php echo $this->utility->get_advert_html('pc.market.floor.002.goods05',$ads); ?>
						</div>
					</li>
					<li class="frame">
						<div class="move">
							<?php echo $this->utility->get_advert_html('pc.market.floor.002.goods06',$ads); ?>
						</div>
					</li>
					<li class="frame">
						<div class="move">
							<?php echo $this->utility->get_advert_html('pc.market.floor.002.goods07',$ads); ?>
						</div>
					</li>
					<li class="frame">
						<div class="move">
							<?php echo $this->utility->get_advert_html('pc.market.floor.002.goods08',$ads); ?>
						</div>
					</li>
					<li class="frame">
						<div class="move">
							<?php echo $this->utility->get_advert_html('pc.market.floor.002.goods09',$ads); ?>
						</div>
					</li>
				</ul>
			</div>
		</div>
		<div class="clearfix"></div>
	</div>
	<div class="full-column main-container">
		<?php echo $this->utility->get_advert_direct('pc.market.floor.002.column',$ads); ?>
	</div>
</div>


<!--/ 日用百货 /-->
<div id="floor03" class="row-container clearfix">
	<div class="floor main-container">
		<div class="floor_title">
			<span>/ 日用百货 /</span>
		</div>
		<div class="floor_content">
			<div class="leftside">
				<?php echo $this->utility->get_advert_html('pc.market.floor.003.goods01',$ads); ?>
			</div>
			<div class="rightside">
				<ul>
					<li class="frame">
						<div class="move">
							<?php echo $this->utility->get_advert_html('pc.market.floor.003.goods02',$ads); ?>
						</div>
					</li>
					<li class="frame">
						<div class="move">
							<?php echo $this->utility->get_advert_html('pc.market.floor.003.goods03',$ads); ?>
						</div>
					</li>
					<li class="frame">
						<div class="move">
							<?php echo $this->utility->get_advert_html('pc.market.floor.003.goods04',$ads); ?>
						</div>
					</li>
					<li class="frame">
						<div class="move">
							<?php echo $this->utility->get_advert_html('pc.market.floor.003.goods05',$ads); ?>
						</div>
					</li>
					<li class="frame">
						<div class="move">
							<?php echo $this->utility->get_advert_html('pc.market.floor.003.goods06',$ads); ?>
						</div>
					</li>
					<li class="frame">
						<div class="move">
							<?php echo $this->utility->get_advert_html('pc.market.floor.003.goods07',$ads); ?>
						</div>
					</li>
					<li class="frame">
						<div class="move">
							<?php echo $this->utility->get_advert_html('pc.market.floor.003.goods08',$ads); ?>
						</div>
					</li>
					<li class="frame">
						<div class="move">
							<?php echo $this->utility->get_advert_html('pc.market.floor.003.goods09',$ads); ?>
						</div>
					</li>
				</ul>
			</div>
		</div>
		<div class="clearfix"></div>
	</div>
	<div class="full-column main-container">
		<?php echo $this->utility->get_advert_direct('pc.market.floor.003.column',$ads); ?>
	</div>
</div>


<!--/ 母婴玩具 /-->
<div id="floor04" class="row-container clearfix">
	<div class="floor main-container">
		<div class="floor_title">
			<span>/ 母婴玩具 /</span>
		</div>
		<div class="floor_content">
			<div class="leftside">
				<?php echo $this->utility->get_advert_html('pc.market.floor.004.goods01',$ads); ?>
			</div>
			<div class="rightside">
				<ul>
					<li class="frame">
						<div class="move">
							<?php echo $this->utility->get_advert_html('pc.market.floor.004.goods02',$ads); ?>
						</div>
					</li>
					<li class="frame">
						<div class="move">
							<?php echo $this->utility->get_advert_html('pc.market.floor.004.goods03',$ads); ?>
						</div>
					</li>
					<li class="frame">
						<div class="move">
							<?php echo $this->utility->get_advert_html('pc.market.floor.004.goods04',$ads); ?>
						</div>
					</li>
					<li class="frame">
						<div class="move">
							<?php echo $this->utility->get_advert_html('pc.market.floor.004.goods05',$ads); ?>
						</div>
					</li>
					<li class="frame">
						<div class="move">
							<?php echo $this->utility->get_advert_html('pc.market.floor.004.goods06',$ads); ?>
						</div>
					</li>
					<li class="frame">
						<div class="move">
							<?php echo $this->utility->get_advert_html('pc.market.floor.004.goods07',$ads); ?>
						</div>
					</li>
					<li class="frame">
						<div class="move">
							<?php echo $this->utility->get_advert_html('pc.market.floor.004.goods08',$ads); ?>
						</div>
					</li>
					<li class="frame">
						<div class="move">
							<?php echo $this->utility->get_advert_html('pc.market.floor.004.goods09',$ads); ?>
						</div>
					</li>
				</ul>
			</div>
		</div>
		<div class="clearfix"></div>
	</div>
	<div class="full-column main-container">
		<?php echo $this->utility->get_advert_direct('pc.market.floor.004.column',$ads); ?>
	</div>
</div>