<!DOCTYPE html>
<html>

	<head>
		<meta charset="utf-8" />
		<title>惊喜狂欢购</title>
		<link rel="stylesheet" href="/theme/activity/2016_09_purchasing/pc/css/index.css" />
	</head>

	<body>
		<div class="f_pc_carnival_purchasing">
			<div class="f_carnival_banner">
				<img src="/theme/activity/2016_09_purchasing/pc/img/banner/banner_one.jpg" alt="" align="top" />
				<img src="/theme/activity/2016_09_purchasing/pc/img/banner/banner_two.jpg" alt="" align="top" />
				<img src="/theme/activity/2016_09_purchasing/pc/img/banner/banner_three.jpg" alt="" align="top" />
				<img src="/theme/activity/2016_09_purchasing/pc/img/banner/banner_four.jpg" alt="" align="top" />
				<img src="/theme/activity/2016_09_purchasing/pc/img/banner/banner_five.jpg" alt="" align="top" />
				<img src="/theme/activity/2016_09_purchasing/pc/img/banner/banner_six.jpg" alt="" align="top" />
				<img src="/theme/activity/2016_09_purchasing/pc/img/banner/banner_seven.jpg" alt="" align="top" />
				<img src="/theme/activity/2016_09_purchasing/pc/img/banner/banner_eight.jpg" alt="" align="top" />
			</div>
			<div class="f_content">
				<div class="f_caigo">
					<div class="f_ta_matters">
						<ul>
							<li>
								<a href="http://item.soolife.cn/36779.html">
									<img src="/theme/activity/2016_09_purchasing/pc/img/ta_matters/matters_one.jpg" alt="" align="top" data="opengoodsdetail"/>
								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/36790.html">
									<img src="/theme/activity/2016_09_purchasing/pc/img/ta_matters/matters_two.jpg" alt="" align="top" data="opengoodsdetail"/>
								</a>
							</li>
						</ul>
					</div>
					<div class="f_product">
						<ul>
							<li>
								<a href="http://item.soolife.cn/36790.html">
									<img src="/theme/activity/2016_09_purchasing/pc/img/ta_matters/matters_three.jpg" alt="" align="top" data="opengoodsdetail"/>
								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/36256.html">
									<img src="/theme/activity/2016_09_purchasing/pc/img/ta_matters/matters_four.jpg" alt="" align="top" data="opengoodsdetail"/>
								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/36308.html">
									<img src="/theme/activity/2016_09_purchasing/pc/img/ta_matters/matters_five.jpg" alt="" align="top" data="opengoodsdetail"/>
								</a>
							</li>
						</ul>
					</div>
				</div>
				<!--ta是采购大王-->
				<div id="ta_purchase">
					<ul>
						<li>
							<a href="http://item.soolife.cn/31174.html">
								<img src="/theme/activity/2016_09_purchasing/pc/img/ta_purchase/purchase_one.jpg" alt="" align="top"data="opengoodsdetail" />
							</a>
						</li>
						<li>
							<a href="http://item.soolife.cn/31219.html">
								<img src="/theme/activity/2016_09_purchasing/pc/img/ta_purchase/purchase_two.jpg" alt="" align="top"data="opengoodsdetail" />
							</a>
						</li>
					</ul>
				</div>
				<div class="thirst">
					<ul>
						<li>
							<a href="http://item.soolife.cn/31208.html">
								<img src="/theme/activity/2016_09_purchasing/pc/img/ta_purchase/purchase_three.jpg" alt="" align="top" data="opengoodsdetail"/>
							</a>
						</li>
						<li>
							<a href="http://item.soolife.cn/29186.html">
								<img src="/theme/activity/2016_09_purchasing/pc/img/ta_purchase/purchase_four.jpg" alt="" align="top" data="opengoodsdetail"/>
							</a>
						</li>
						<li>
							<a href="http://item.soolife.cn/29262.html">
								<img src="/theme/activity/2016_09_purchasing/pc/img/ta_purchase/purchase_five.jpg" alt="" align="top" data="opengoodsdetail"/>
							</a>
						</li>
					</ul>
				</div>
				<!--ta是新鲜达人-->
				<div class="">
					<div class="ta_fresh">
						<img src="/theme/activity/2016_09_purchasing/pc/img/ta_fresh/fresh_banner.png" alt="" />
					</div>
					<div class="f_fresh">
						<ul>
							<li>
								<a href="http://item.soolife.cn/36777.html">
									<img src="/theme/activity/2016_09_purchasing/pc/img/ta_fresh/fresh_one.png" alt="" data="opengoodsdetail"/>
								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/31744.html">
									<img src="/theme/activity/2016_09_purchasing/pc/img/ta_fresh/fresh_two.jpg" alt="" data="opengoodsdetail"/>
								</a>
							</li>
						</ul>
					</div>
				</div>
				<div class="f_product">
						<ul>
							<li>
								<a href="http://item.soolife.cn/34181.html">
									<img src="/theme/activity/2016_09_purchasing/pc/img/ta_fresh/fresh_three.png" alt="" align="top" data="opengoodsdetail"/>
								</a>
							</li>
							<li class="second">
								<a href="http://item.soolife.cn/34108.html">
									<img src="/theme/activity/2016_09_purchasing/pc/img/ta_fresh/fresh_four.png" alt="" align="top" data="opengoodsdetail"/>
								</a>
							</li>
							<li class="thirty">
								<a href="http://item.soolife.cn/33419.html">
									<img src="/theme/activity/2016_09_purchasing/pc/img/ta_fresh/fresh_five.png" alt="" align="top" data="opengoodsdetail"/>
								</a>
							</li>
						</ul>
					</div>
				
				<!--ta是时尚掌门人-->
				<div id="ta_purchase">
					<ul>
						<li class="two_side">
							<a href="http://item.soolife.cn/15455.html">
								<img src="/theme/activity/2016_09_purchasing/pc/img/ta_fashion/fashion_one.jpg" alt="" align="top" data="opengoodsdetail"/>
							</a>
						</li>
						<li class="one_side">
							<a href="http://item.soolife.cn/27221.html">
								<img src="/theme/activity/2016_09_purchasing/pc/img/ta_fashion/fashion_two.jpg" alt="" align="top" data="opengoodsdetail"/>
							</a>
						</li>
					</ul>
				</div>
				<div class="thirst_one">
					<ul>
						<li>
							<a href="http://item.soolife.cn/27192.html">
								<img src="/theme/activity/2016_09_purchasing/pc/img/ta_fashion/fashion_three.jpg" alt="" align="top"data="opengoodsdetail" />
							</a>
						</li>
						<li >
							<a href="http://item.soolife.cn/12911.html">
								<img src="/theme/activity/2016_09_purchasing/pc/img/ta_fashion/fashion_four.jpg" alt="" align="top" data="opengoodsdetail"/>
							</a>
						</li>
						<li>
							<a href="http://item.soolife.cn/27288.html">
								<img src="/theme/activity/2016_09_purchasing/pc/img/ta_fashion/fashion_five.jpg" alt="" align="top" data="opengoodsdetail"/>
							</a>
						</li>
					</ul>
				</div>
			
				<!--ta是凑单达人-->
				<div class="">
					<div class="ta_fresh">
						<img src="/theme/activity/2016_09_purchasing/pc/img/ta_gather_ together/gather_ together_banner.png" alt="" />
					</div>
					<div class="f_fresh">
						<ul>
							<li>
								<a href="http://item.soolife.cn/27678.html">
									<img src="/theme/activity/2016_09_purchasing/pc/img/ta_gather_ together/gather_ together_one.jpg" alt="" data="opengoodsdetail"/>
								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/27687.html">
									<img src="/theme/activity/2016_09_purchasing/pc/img/ta_gather_ together/gather_ together_two.jpg" alt="" data="opengoodsdetail"/>
								</a>
							</li>
						</ul>
					</div>
				</div>
				<div class="f_product chocolate">
						<ul>
							<li class="chocolate_one">
								<a href="http://item.soolife.cn/26433.html">
									<img src="/theme/activity/2016_09_purchasing/pc/img/ta_gather_ together/gather_ together_three.png" alt="" align="top" data="opengoodsdetail"/>
								</a>
							</li>
							<li class="chocolate_two">
								<a href="http://item.soolife.cn/26939.html">
									<img src="/theme/activity/2016_09_purchasing/pc/img/ta_gather_ together/gather_ together_four.png" alt="" align="top" data="opengoodsdetail"/>
								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/26434.html">
									<img src="/theme/activity/2016_09_purchasing/pc/img/ta_gather_ together/gather_ together_five.png" alt="" align="top" data="opengoodsdetail"/>
								</a>
							</li>
						</ul>
					</div>
					<!--ta是家庭主妇-->
					<div id="bathroom">
					<ul>
						<li class="bathroom_one">
							<a href="http://item.soolife.cn/29613.html">
								<img src="/theme/activity/2016_09_purchasing/pc/img/ta_housewife/housewife_one.png" alt="" align="top" data="opengoodsdetail"/>
							</a>
						</li>
						<li class="bathroom_two">
							<a href="http://item.soolife.cn/29604.html">
								<img src="/theme/activity/2016_09_purchasing/pc/img/ta_housewife/housewife_two.jpg" alt="" align="top" data="opengoodsdetail" />
							</a>
						</li>
					</ul>
				</div>
				<div class="thirst">
					<ul>
						<li>
							<a href="http://item.soolife.cn/35919.html">
								<img src="/theme/activity/2016_09_purchasing/pc/img/ta_housewife/housewife_three.jpg" alt="" align="top" data="opengoodsdetail"/>
							</a>
						</li>
						<li>
							<a href="http://item.soolife.cn/35921.html">
								<img src="/theme/activity/2016_09_purchasing/pc/img/ta_housewife/housewife_four.jpg" alt="" align="top" data="opengoodsdetail"/>
							</a>
						</li>
						<li>
							<a href="http://item.soolife.cn/35934.html">
								<img src="/theme/activity/2016_09_purchasing/pc/img/ta_housewife/housewife_five.jpg" alt="" align="top" data="opengoodsdetail"/>
							</a>
						</li>
					</ul>
				</div>
				</div>
		</div>
		</div>
	</body>

</html>