<style type="text/css">
    .Alreadylogin{
        display: none;
    }
</style>
<div id="header">
    <div class="mainBox clearfix" >
        <div class="leftflo">
            <?php
            $return_url = "http://" . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'];
            if (empty($return_url)) {
                $return_url = rtrim(strtr(base64_encode($this -> config -> application -> href_url), '+/', '-_'), '=');
            } else {
                $i = strrpos($return_url, "?");
                if ($i != "") {
                    $return_url = substr($return_url, 0, $i);
                }
                $return_url = rtrim(strtr(base64_encode($return_url), '+/', '-_'), '=');
            }
            ?>
            <label class="nologin">Hi, 欢迎来到如此生活</label>
            <a class="nologin" href="/login.html?return_url=<?php echo $return_url; ?>">登录</a><em class="separator nologin">|</em>
            <a class="nologin" href="/register.html">免费注册</a><em class="separator nologin">|</em>
            <label class="Alreadylogin">
                <font class="loginname">星粉</font>,
                欢迎来到如此生活(<a href="/zone.html" target="_blank">星币</a>:<span class="credit">0</span><i class="xingbiicon"></i>)
            </label>
            <em class="separator Alreadylogin">|</em>
            <a href="/account/loginout" class="Alreadylogin">退出</a><em class="separator Alreadylogin">|</em>
        </div>
        <div class="weixin" data-toggle="modal" data-target="#codeweixin">
            <div class="hide_weixin" style="display: none;">
                <div class="img-weixin"></div>
            </div>
        </div>
        <div class="sina" data-toggle="modal" data-target="#codesina">
            <div class="hide_sina" style="display: none;">
                <div class="img-sina"></div>
            </div>
        </div>
        <div class="rightflo">
            <div class="center">
                <label><span><a href="{{url_member}} ">我的生活</a></span></label>
                <div class="hide_center">
                    <a href="{{url_member}}/Home/Order/myOrders.html?type=1">我的订单</a>
                    <a href="{{url_member}}/Home/MemberAsset/memberCoin.html">星币查询</a>
                    <a href="{{url_member}}/Home/StarRelation/coupon.html">我的优惠券</a>
                </div>
            </div>
            <em class="separator leftflo">|</em>
            <div class="headhelp">
                <label><span><a href="{{url_help}}">帮助中心</a></span></label>
                <div class="hide_headhelp">
                    <a href="{{url_help}}">帮助首页</a>
                    <a href="/">我要投诉</a>
                    <a href="/">售后服务</a>
                </div>
            </div>
            <em class="separator leftflo">|</em>
            <div class="businessor">
                <a href="{{url_sop}}" target="_blank">商家入驻</a>
            </div>
            <em class="separator leftflo">|</em>

            <dl class="navmore">
                <dt>
                    更多导航<i class=" icon-chevron-down"></i>
                </dt>
                <dd>
                    <a target="_blank" href="{{url_website}}/index.html">首页</a>
                </dd>
                <dd>
                    <a target="_blank" href="{{url_website}}/market.html">星超市</a>
                </dd>
                <dd>
                    <a target="_blank" href="{{url_website}}/mall.html">星商城</a>
                </dd>
                <dd>
                    <a target="_blank" href="{{url_website}}/clothes.html">服饰鞋包</a>
                </dd>
                <dd>
                    <a target="_blank" href="{{url_website}}/discount.html">品牌特惠</a>
                </dd>
                <dd>
                    <a target="_blank" href="http://www.soolife.cn/zone.html">星粉专区</a>
                </dd>
            </dl>

            <div class="clear"></div>
        </div>
    </div>
    <div id="codeweixin" class="modal fade modal-qrcode" style="display: none;" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button data-dismiss="modal" class="close" type="button">
                        <span aria-hidden="true">×</span><span class="sr-only">Close</span>
                    </button>
                    <h4 id="myModalLabel" class="modal-title">关注<b class="color-orange">如此生活</b>官方微信</h4>
                </div>
                <div class="modal-body">
                    <div class="code-weixin">
                        <img src="http://static.soolife.cn/asset/img/weixinbig.jpg" alt="关注如此生活官方微信">
                    </div>
                </div>
                <div class="modal-footer">
                    <a data-dismiss="modal" class="cancel_btn"> 关闭 </a>
                </div>
            </div>
        </div>
    </div>
    <div id="codesina" class="modal fade modal-qrcode">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button data-dismiss="modal" class="close" type="button">
                        <span aria-hidden="true">×</span><span class="sr-only">Close</span>
                    </button>
                    <h4 id="myModalLabel" class="modal-title">关注<b class="color-orange">如此生活</b>官方微博</h4>
                </div>
                <div class="modal-body">
                    <div class="code-sina">
                        <img src="http://static.soolife.cn/asset/img/sinabig.jpg" alt="关注如此生活官方微博">
                    </div>
                </div>
                <div class="modal-footer">
                    <a data-dismiss="modal" class="cancel_btn"> 关闭 </a>
                </div>
            </div>
        </div>
    </div>
</div>
