<div class="pindiv clearfix" style="display:none">
	<div class="mainBox clearfix">
		<div class="leftflo">
			<a class="pindiv-logo" href="/index.html"></a>
		</div>
		<div class="rightflo">
			<form class="mallSearch-form">
				<fieldset>
					<div class="mallSearch-input clearfix">
						<div class="s-combobox">
							<input type="text" class="s-combobox-input" title="请输入搜索文字" />
							<label class="s-combobox-placeholder"></label>
						</div>
						<button type="button">
							搜索
						</button>
					</div>
				</fieldset>
			</form>
		</div>
	</div>
</div>