<?php
	$css = $this->assets->get('header');
	$css -> addCss("public/css/p/view.newindex.css");
	$js  = $this->assets->get('footer');
    $js -> addJs("public/js/p/newcityagent.js");
?>
<div class="brandbanner">
	<img src="../public/img/partner/brandinvestment01.1.png" alt="如此生活">
	<img src="../public/img/partner/brandinvestment01.2.png" alt="如此生活">
</div>
<div class="brandcontent">
	<div class="title">
		<div>
			<h3>欢迎全品类产品入驻<br> 只要你的产品有品质、有特色，我们就能给你量</h3>
		</div>
		<ul class="clearfix">
			<li>
				<img src="../public/img/partner/brandinvestment02.png" alt="如此生活">
				<div>
					<h3>食品饮料</h3>
					<p>Food beverage</p>
				</div>
			</li>
			<li>
				<img src="../public/img/partner/brandinvestment03.png" alt="如此生活">
				<div>
					<h3>服饰鞋靴</h3>
					<p>Dress shoes</p>
				</div>
			</li>
			<li>
				<img src="../public/img/partner/brandinvestment04.png" alt="如此生活">
				<div>
					<h3>箱包配饰</h3>
					<p>Luggage accessories</p>
				</div>
			</li>
			<li>
				<img src="../public/img/partner/brandinvestment05.png" alt="如此生活">
				<div>
					<h3>运动户外</h3>
					<p>Outdoor sports</p>
				</div>
			</li>
			<li>
				<img src="../public/img/partner/brandinvestment06.png" alt="如此生活">
				<div>
					<h3>日用百货</h3>
					<p>General merchandise</p>
				</div>
			</li>
			<li>
				<img src="../public/img/partner/brandinvestment07.png" alt="如此生活">
				<div>
					<h3>智能电配</h3>
					<p>Intelligent power distribution</p>
				</div>
			</li>
			<li>
				<img src="../public/img/partner/brandinvestment08.png" alt="如此生活">
				<div>
					<h3>母婴玩具</h3>
					<p>Baby toys</p>
				</div>
			</li>
			<li>
				<img src="../public/img/partner/brandinvestment09.png" alt="如此生活">
				<div>
					<h3>个护化妆</h3>
					<p>Make up</p>
				</div>
			</li>
		</ul>
	</div>
	<div>
		<img src="../public/img/partner/brandinvestment10.png" alt="如此生活" style="width: 100%;">
	</div>
	<div class="clx">
		<ul class="info clearfix">
		<li style="padding-left: 25%;margin-top: 60px;margin-bottom: 80px;font-size: 14px;color: #333; ">我们有全自主开发PC端商城、APP，流量大、快转化、高销量帮您线上销售，开设网店 </li>
		<li>
			<img src="../public/img/partner/brandinvestment11.png" alt="如此生活">
		</li>
		<li style="padding-left: 10%;">
			<img src="../public/img/partner/brandinvestment12.png" alt="如此生活">
		</li>
	</ul>
	<ul class="info clearfix">
		<li style="padding-left: 25%;margin-top: 60px;margin-bottom: 80px;font-size: 14px;color: #333; ">我们有全国连锁3000-5000平米大型连锁体验店分布在万达、宝龙、月星等一线地产 </li>
		<li>
			<img src="../public/img/partner/brandinvestment14.png" alt="如此生活">
		</li>
		<li>
			<img src="../public/img/partner/brandinvestment13.png" alt="如此生活">
		</li>
	</ul>
	</div>
	
	<div class="teamwork" style="width: 1200px;margin: 0 auto">
		<div>
			<h3>合作优势</h3>
		</div>
		<ul class="clearfix">
			<li>
			<img src="../public/img/partner/brandinvestment15.png" alt="如此生活">
			</li>
			<li>
			<img src="../public/img/partner/brandinvestment16.png" alt="如此生活">
			</li>
			<li>
			<img src="../public/img/partner/brandinvestment17.png" alt="如此生活">
			</li>
			<li>
			<img src="../public/img/partner/brandinvestment18.png" alt="如此生活">
			</li>
			<li>
			<img src="../public/img/partner/brandinvestment19.png" alt="如此生活">
			</li>
		</ul>
	</div>
	<div class="partner">
		<div>
			<h3>他们都在与如此生活合作</h3>
			<p>与如此生活合作的品牌 <br>总数超过4000家 </p>
		</div>
		<ul class="clearfix">
			<li>
			<img src="../public/img/partner/brandinvestment20.png" alt="如此生活">
			</li>
			<li>
			<img src="../public/img/partner/brandinvestment21.png" alt="如此生活">
			</li>
			<li>
			<img src="../public/img/partner/brandinvestment22.png" alt="如此生活">
			</li>
			<li>
			<img src="../public/img/partner/brandinvestment23.png" alt="如此生活">
			</li>
		</ul>
	</div>
	<div class="partner">
		<div>
			<h3>未来三年，如此生活前途不可限量</h3>
		</div>
		<ul class="clearfix" style="padding-bottom: 80px;">
			<li>
			<img src="../public/img/partner/brandinvestment24.png" alt="如此生活">
			</li>
			<li>
			<img src="../public/img/partner/brandinvestment25.png" alt="如此生活">
			</li>
		</ul>
	</div>
</div>
<div class="xl_footer">
    <img src="../public/img/partner/newcityagent11.png">
    <div class=" xl_info">
    	<div style="text-align: center;">
	  <div class="title">
		<h3>加盟留言表</h3>
		<p>join guestbook</p>
	  </div>
      <div style="margin-bottom:30px;">
        <div style="width:140px;text-align:right;display:inline-block;font-size: 24px;">姓名:</div>
        <input type="text" placeholder="请填入姓名" name="name" style="width:400px;height: 40px; border:1px solid #0068b6;border-radius:6px;text-indent:10px;color: #333;"/>
      </div>
       <div style="margin-bottom:30px;">
        <div style="width:140px;text-align:right;display:inline-block;font-size: 24px;">电话:</div>
        <input type="text" placeholder="请填入电话" name="phone" style="width:400px;height: 40px; border:1px solid #0068b6;border-radius:6px;text-indent:10px;color: #333;""/>
      </div>
       <div style="margin-bottom:30px;">
        <div style="width:140px;text-align:right;display:inline-block;font-size: 24px;">所在城市:</div>
        <input type="text" placeholder="如:上海市长宁区" name="region" style="width:400px;height: 40px; border:1px solid #0068b6;border-radius:6px;text-indent:10px;color: #333;""/>
      </div>
       <div style="margin-bottom:30px;">
        <div style="width:140px;text-align:right;display:inline-block;font-size: 24px;">邮箱:</div>
        <input type="text" placeholder="请填入邮箱" name="email" style="width:400px;height: 40px; border:1px solid #0068b6;border-radius:6px;text-indent:10px;color: #333;""/>
      </div>
      <div style="margin-bottom:86px; ">
        		<div style="width:140px;text-align:right;display: inline-block; font-size: 24px; position: absolute;left: 17.3%;">业务板块:</div>
                <select id="seclectp"
                        style="width:172px;height: 40px;margin:0;padding:0;vertical-align: top;border:1px solid #0068b6;border-radius:6px;color: #666;color: #333; margin-left: 286px;float: left;">
                     
                <option value="1">我对品牌入驻感兴趣</option>
                <option value="2">我对城市代理感兴趣</option>   
                <option value="3">我对体验店加盟感兴趣</option>
                </select>
                <select class="twoselect1"
                        style="width:180px;height: 40px;margin:0;padding:0;vertical-align: top;border:1px solid #0068b6;border-radius:6px;color: #666;float: left;margin-left: 10px;">
                    <option value="1">我是品牌商</option>
                    <option value="2">我是厂商</option>
                    <option value="3">我是代理商</option>
                    <option value="4">我是经销商</option>
                </select>
                <div class="twoselect2" style="display:none; float: left;margin-top: 8px;margin-left: 8px;">
                    <span class="sec_wen">有销售团队</span>
                    <select class="twoselectbtn"
                            style="width:44px;margin:0;padding:0;vertical-align: top;border:1px solid #0068b6;border-radius:2px;color: #666;">
                        <option value="0">否</option>
                        <option value="1">是</option>
                    </select>
                    <select class="twoselect21"
                            style="width:99px;margin:0;padding:0;vertical-align: top;border:1px solid #0068b6;border-radius:2px;display:none;color: #666;">
                        <option value="1">10人以下</option>
                        <option value="2">10~20人</option>
                        <option value="3">20人以上</option>
                    </select>
                </div>
            </div>
      <div style="margin-bottom:30px;">
        <div style="width:140px;text-align:right;display:inline-block;font-size: 24px;">留言框:</div>
        <textarea rows="5" name="content" placeholder="您要说的话..." style="width:400px;vertical-align: top;border:1px solid #0068b6;border-radius:6px;color: #333;""></textarea>
      </div>
      <div style="padding-left:142px;padding-top: 12px;padding-bottom: 50px;">
        <button class="submit" style="margin:0 auto;width:400px;height: 40px;border-radius:6px; border:none;background-color:#fff;color:#666;font-size: 18px;">提交</button>
      </div>
      <div  style="border-top: 1px solid #fff;width: 100%;">
	  	<p style="padding-top: 30px;font-size: 18px;">咨询联系:<span style="padding-left:10px;">4006699878</span></p>
	  </div>
  </div>

    </div>
    
</div>
 