<?php
	$css = $this->assets->get('header');
	$css -> addCss("public/css/p/view.index.css");
	$js  = $this->assets->get('footer');
  $js -> addJs("public/js/p/cityagent.js");
?>

<div style="line-height: 24px;">
<div class="row">
  <div class="col-xs-6 col-md-6">
  	<ul style="margin-left:60px;margin-top:100px;">
  		<li>您还在苦苦寻找更好的合作商机吗？</li>
  		<li>您还在踌躇满志，期望开拓一番天地吗？</li>
  		<li>您还在犹豫不决，决定是否进入互联网领域吗？</li>
  		<li>您如果满足以下条件：</li>
  		<li>1、有一个优秀的销售团队。</li>
  		<li>2、有丰富的当地品牌商，代理商，经销商资源。</li>
  		<li>3、有成就事业之心。</li>
  		<li>4、有一定的经济实力。</li>
  		<li>那么您就有机会成为“如此生活”平台的城市独家代理商。</li>
  	</ul>
  </div>
  <div class="col-xs-6 col-md-6">
	<img src="/public/img/partner/cityagent(1).jpg" alt="如此生活">
  </div>
</div>
<div class="row">
  <div class="col-xs-6 col-md-6">
	<img src="/public/img/partner/cityagent(2).jpg" alt="如此生活">
  </div>
  <div class="col-xs-6 col-md-6">
  	<ul>
  		<li>作为城市独家代理商您只需将当地的品牌商，代理商，经销商引进给平台，维护好客户关系，由“如此生活”平台负责品牌商整体运营，平台将于城市代理商一起共同开拓市场，分享利润。</li>
  		<li>给您十个做如此生活代理商的理由：</li>
  		<li>1、平台协助您帮助本地品牌商家解决生意难做的窘境。</li>
  		<li>2、每个城市只招一个独家代理商，独家享有城市众多资源导入。</li>
  		<li>3、新零售经济时代，新的商业模式迎来新的商机，帮助商家成功转型互联网零售。</li>
  		<li>4、公司天使轮8000万，A轮洽谈中预计2个亿，有机会与新的独角兽公司一起合作，进入互联网电商崭新领域。</li>
  		<li>5、项目低风险，易操作，市场投入少，回报率高。</li>
		<li>6、稳定持续的长期回报，签约商家一次签约，城市代理商可持续获得长久收益保障。</li>
		<li>7、开启线上线下全渠道零售的崭新事业。</li>
		<li>8、全新资源共享平台，大数据对接，一手掌握市场前沿动态。</li>
		<li>9、独居特色的体验分享功能，让更多人参与，更多人成为创业者。</li>
		<li>10、可以与平台全国代理商共享优秀的管理、市场，营销等信息，接触互联网大咖，接触瞬息万变的互联网市场前沿。</li>
  	</ul>
  </div>
</div>
<div class="row" style="margin-bottom:120px;">
  <div class="col-xs-6 col-md-6">
  	<ul style="width:536px">
		<li>1、全年不低于二次上门培训，食宿及差旅费由代理商承担，同时进行不定期的远程培训协助。</li>
		<li>2、平台提供完整的招商工具：招商手册，DM单内容，宣传片等。</li>
		<li>3、代理商当地召开招商会，平台提供人员讲师及策划支持，费用代理商承担；组织招商会在上海召开，平台提供协助，费用代理商提供。</li>
		<li>4、平台提供完整销售系统支持：外呼系统+EC软件系统。</li>硬件需代理商自行采购。</li>
		<li>5、每月10日前支付代理商上月收益。</li>
		<li>6、平台官网为代理商做相应的宣传推广。</li>
		<li>7、市场共享机制：优秀的市场开发方式，工具，方法的分享学习。</li>
		<li>8、代理商超额完成年度任务的部分，平台予以签约额3%的额外奖励。</li>
		<li>9、一次签约，三年收益，客户续约，代理商也有优厚回报！</li>
		<li>10、第二个合同年开始，平台提供给代理商10家免费入驻的名额，仅限线上。</li>
		<li style="text-align: center;">如过您是一个心怀梦想的人，如果您想成就一个伟大的梦，那么请致电或留言给我们。</li>
		<li style="text-align: center;">如此生活平台愿携手与您一起创造财富梦想。</li>
  	</ul>
  </div>
  <div class="col-xs-6 col-md-6">
      <div style="margin-bottom:20px;">
        <div style="width:100px;text-align:right;display:inline-block;"><span style="color:red;">*</span>姓名：</div>
        <input type="text" placeholder="请填入姓名" name="name" style="width:280px;border:1px solid #0068b6;border-radius:2px;text-indent:10px;"/>
      </div>
      <div style="margin-bottom:20px;">
        <div style="width:100px;text-align:right;display:inline-block;"><span style="color:red;">*</span>电话：</div>
        <input type="text" placeholder="请输入联系电话" name="phone" style="width:280px;border:1px solid #0068b6;border-radius:2px;text-indent:10px;"/>
      </div>
      <div style="margin-bottom:20px;">
        <div style="width:100px;text-align:right;display:inline-block;"><span style="color:red;">*</span>所在城市：</div>
        <input type="text" placeholder="如：上海市长宁区" name="region" style="width:280px;border:1px solid #0068b6;border-radius:2px;text-indent:10px;"/>
      </div>
      <div style="margin-bottom:20px;">
        <div style="width:100px;text-align:right;display:inline-block;"><span style="color:red;">*</span>邮箱：</div>
        <input type="text" placeholder="请输入邮箱地址" name="email" style="width:280px;border:1px solid #0068b6;border-radius:2px;text-indent:10px;"/>
      </div>
      <div style="margin-bottom:20px;">
        <div style="width:100px;text-align:right;display:inline-block;"><span style="color:red;">*</span>业务板块：</div>
        <select id="seclectp" style="width:138px;margin:0;padding:0;vertical-align: top;border:1px solid #0068b6;border-radius:2px;">
          <option value="1">我对品牌入驻感兴趣</option>
          <option value="2">我对城市代理感兴趣</option>
          <option value="3">我对体验店加盟感兴趣</option>
        </select>
        <select class="twoselect1" style="width:138px;margin:0;padding:0;vertical-align: top;border:1px solid #0068b6;border-radius:2px;">
          <option value="1">我是品牌商</option>
          <option value="2">我是厂商</option>
          <option value="3">我是代理商</option>
          <option value="4">我是经销商</option>
        </select>
        <div class="twoselect2" style="display:none;">
            <span class="sec_wen">有销售团队</span>
            <select class="twoselectbtn" style="width:64px;margin:0;padding:0;vertical-align: top;border:1px solid #0068b6;border-radius:2px;">
              <option value="0">否</option>
              <option value="1">是</option>
            </select>
            <select class="twoselect21" style="width:138px;margin:0;padding:0;vertical-align: top;border:1px solid #0068b6;border-radius:2px;display:none;">
              <option value="1">10人以下</option>
              <option value="2">10~20人</option>
              <option value="3">20人以上</option>
            </select>
        </div>
      </div>
      <div>
        <div style="width:100px;text-align:right;display:inline-block;">留言框：</div>
        <textarea rows="5" name="content" placeholder="您要说的话..." style="width:280px;vertical-align: top;border:1px solid #0068b6;border-radius:2px;"></textarea>
      </div>
      <div style="padding-left:100px;padding-left: 104px;padding-top: 12px;">
        <button class="submit" style="margin:0 auto;width:280px;border:none;background-color:#f6aa00;color:#fff;">提交</button>
      </div>
  </div>
</div>
</div>