<?php
	$css = $this->assets->get('header');
	$css -> addCss("public/css/p/view.newindex.css");
	$js  = $this->assets->get('footer');
    $js -> addJs("public/js/p/newcityagent.js");
?>
<div class="brandbanner">
	<img alt="如此生活" src="../public/img/partner/experience01.png" >
	<img alt="如此生活" src="../public/img/partner/experience02.png" >
</div>
<div class="experiencecontent">
	<div class="title">
		<div class="subheading">
			<h3>零售新时代的开启</h3>
			<p>Opening up a new era of retail</p>
		</div>
		<ul class="clearfix">
			<li>
				<img alt="如此生活" src="../public/img/partner/experience03.png" >
				<div>
					<h3>线上</h3>
					<p>On-line</p>
				</div>
			</li>
			<li>
				<img alt="如此生活" src="../public/img/partner/experience04.png" >
				<div>
					<h3>线下大型体验店</h3>
					<p>Experience store</p>
				</div>
			</li>
			<li>
				<img alt="如此生活" src="../public/img/partner/experience05.png" >
				<div>
					<h3>运营</h3>
					<p>Operate</p>
				</div>
			</li>
			<li>
				<img alt="如此生活" src="../public/img/partner/experience06.png" >
				<div>
					<h3>管理</h3>
					<p>manage</p>
				</div>
			</li>
		</ul>
	</div>
	<div class="strategiclayout">
		<img alt="如此生活" src="../public/img/partner/experience07.png" >
		<div class="clearfix">
			<div class="title">
				<h3>战略布局</h3>
				<p>Strategic layout</p>
			</div>
			<div class="layout">
				<ul>
					<li style="padding-top: 26px;">如此生活总部：上海</li>
					<li> 仓储五大区： </li>
					<li>华东区、 华北区、华南区、华中区、上海 </li>
					<li>营销中心： </li>
					<li>上海、北京、重庆、广州、深圳</li>
				</ul>
			</div>
		</div>
	</div>
	<div class="joincondition">
		<div class="title">
			<h3>目前体验店加盟情况</h3>
			<p>Current experience store franchise</p>
		</div>
		<h4>直营店面</h4>
		<ul class="clearfix">
			<li>
				<img alt="如此生活" src="../public/img/partner/experience08.png" >
				<div style="margin-top: 10px;">
					<h3>松江店</h3>
				</div>
			</li>
			<li>
				<img alt="如此生活" src="../public/img/partner/experience09.png" >
				<div style="margin-top: 10px;">
					<h3>嘉定店</h3>
				</div>
			</li>
			<li>
				<img alt="如此生活" src="../public/img/partner/experience10.png" >
				<div style="margin-top: 10px;">
					<h3>镇江店</h3>
				</div>
			</li>
			<li>
				<img alt="如此生活" src="../public/img/partner/experience11.png" >
				<div style="margin-top: 10px;">
					<h3>厦门店</h3>
				</div>
			</li>
			<li>
				<img alt="如此生活" src="../public/img/partner/experience12.png" >
				<div style="margin-top: 10px;">
					<h3>苏州店</h3>
				</div>
			</li>
		</ul>
	</div>
	<div class="joincondition">
		<div class="title">
			<h3>体验店加盟盈利分析（松江万达）</h3>
			<p>Experience store franchise profit analysis (Songjiang Wanda)</p>
		</div>
		<div class="sheet" style="width: 100%;">
			<table>
				<thead>
					<tr>
						<th>开业时间</th>
						<th>营业面积</th>
						<th>可入驻品牌数</th>
						<th>实际入驻品牌数</th>
						<th>运营费用</th>
						<th>实际收到入驻服务费</th>
						<th>实际销售额</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>2016年<br>12月18日</td>
						<td>4000平米</td>
						<td>624个</td>
						<td>383个</td>
						<td>200万</td>
						<td>1976万</td>
						<td>577万<br>（三个月）</td>
					</tr>
					<tr>
						<td>截至目前共运营4个月时间</td>
						<td>万达松江店四楼,楼下好孩子店及苏宁易购,侧面是电影院及永辉超 市</td>
						<td>VIVO OPPO 纤莉秀fendi海尔高岛屋意大利轻奢品等多个大品牌已入驻。</td>
						<td>招商工作于2016年8月份展开，截止2017年1月20日的数据。</td>
						<td>包含装修设计，刀具设计制作，人员工资(该店30名员工)等多项经营费用。</td>
						<td>部分品牌为免费品牌及部分品牌为特约收费,收费较少。</td>
						<td>目前店面销量还没有起来,因为人气不够,主要靠营销活动带动。</td>
					</tr>
				</tbody>
		</table>
		</div>
		
		<p style="text-align: right;padding-right: 25%;padding-top: 18px;"><span style="color: red;">*</span>注：截止2017年5月25日</p>
		<div class="pictrue" style="width: 100%;">
			<ul class="pic clearfix" style="width: 1200px;margin: 0 auto; padding-left: 0;">
				<li>
					<img alt="如此生活" src="../public/img/partner/experience13.png" >
				</li>
				<li>
					<img alt="如此生活" src="../public/img/partner/experience14.png" >
				</li>
				<li>
					<img alt="如此生活" src="../public/img/partner/experience15.png" >
				</li>
			</ul>
		</div>
		
		<ul class="pictwo clearfix">
			<li style="margin-top: 230px;">
				<img alt="如此生活" src="../public/img/partner/experience17.png" >
				你想做“<span>领跑者</span>”还是“<span>陪跑员</span>”，请拥有独到市场嗅觉<br> &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp的你，加入我们“<span>新零售</span>”的大家庭一起“奔跑，冲刺” <br> &nbsp&nbsp&nbsp&nbsp
				&nbsp&nbsp（请认真评估自身条件是否达到合作要求及标准)
			</li>
			<li style="margin-top: 125px;margin-bottom: 80px;">
				<img alt="如此生活" src="../public/img/partner/experience16.png" >
			</li>
		</ul>
	</div>
</div>
<div class="xl_footer">
    <img alt="如此生活" src="../public/img/partner/newcityagent11.png">
    <div class=" xl_info">
    	<div style="text-align: center;">
	  <div class="title">
		<h3>加盟留言表</h3>
		<p>join guestbook</p>
	  </div>
      <div style="margin-bottom:30px;">
        <div style="width:140px;text-align:right;display:inline-block;font-size: 24px;">姓名:</div>
        <input type="text" placeholder="请填入姓名" name="name" style="width:400px;height: 40px; border:1px solid #0068b6;border-radius:6px;text-indent:10px;color: #333;"/>
      </div>
       <div style="margin-bottom:30px;">
        <div style="width:140px;text-align:right;display:inline-block;font-size: 24px;">电话:</div>
        <input type="text" placeholder="请填入电话" name="phone" style="width:400px;height: 40px; border:1px solid #0068b6;border-radius:6px;text-indent:10px;color: #333;""/>
      </div>
       <div style="margin-bottom:30px;">
        <div style="width:140px;text-align:right;display:inline-block;font-size: 24px;">所在城市:</div>
        <input type="text" placeholder="如:上海市长宁区" name="region" style="width:400px;height: 40px; border:1px solid #0068b6;border-radius:6px;text-indent:10px;color: #333;""/>
      </div>
       <div style="margin-bottom:30px;">
        <div style="width:140px;text-align:right;display:inline-block;font-size: 24px;">邮箱:</div>
        <input type="text" placeholder="请填入邮箱" name="email" style="width:400px;height: 40px; border:1px solid #0068b6;border-radius:6px;text-indent:10px;color: #333;""/>
      </div>
      <div style="margin-bottom:86px; ">
        		<div style="width:140px;text-align:right;display: inline-block; font-size: 24px; position: absolute;left: 17.3%;">业务板块:</div>
                <select id="seclectp"
                        style="width:172px;height: 40px;margin:0;padding:0;vertical-align: top;border:1px solid #0068b6;border-radius:6px;color: #666;color: #333; margin-left: 286px;float: left;">
                     
                <option value="1">我对品牌入驻感兴趣</option>
                <option value="2">我对城市代理感兴趣</option>   
                <option value="3">我对体验店加盟感兴趣</option>
                </select>
                <select class="twoselect1"
                        style="width:180px;height: 40px;margin:0;padding:0;vertical-align: top;border:1px solid #0068b6;border-radius:6px;color: #666;float: left;margin-left: 10px;">
                    <option value="1">我是品牌商</option>
                    <option value="2">我是厂商</option>
                    <option value="3">我是代理商</option>
                    <option value="4">我是经销商</option>
                </select>
                <div class="twoselect2" style="display:none; float: left;margin-top: 8px;margin-left: 8px;">
                    <span class="sec_wen">有销售团队</span>
                    <select class="twoselectbtn"
                            style="width:44px;margin:0;padding:0;vertical-align: top;border:1px solid #0068b6;border-radius:2px;color: #666;">
                        <option value="0">否</option>
                        <option value="1">是</option>
                    </select>
                    <select class="twoselect21"
                            style="width:99px;margin:0;padding:0;vertical-align: top;border:1px solid #0068b6;border-radius:2px;display:none;color: #666;">
                        <option value="1">10人以下</option>
                        <option value="2">10~20人</option>
                        <option value="3">20人以上</option>
                    </select>
                </div>
            </div>
      <div style="margin-bottom:30px;">
        <div style="width:140px;text-align:right;display:inline-block;font-size: 24px;">留言框:</div>
        <textarea rows="5" name="content" placeholder="您要说的话..." style="width:400px;vertical-align: top;border:1px solid #0068b6;border-radius:6px;color: #333;""></textarea>
      </div>
      <div style="padding-left:142px;padding-top: 12px;padding-bottom: 50px;">
        <button class="submit" style="margin:0 auto;width:400px;height: 40px;border-radius:6px; border:none;background-color:#fff;color:#666;font-size: 18px;">提交</button>
      </div>
      <div  style="border-top: 1px solid #fff;width: 100%;">
	  	<p style="padding-top: 30px;font-size: 18px;">咨询联系:<span style="padding-left:10px;">刘先生 18321122505  微信号：tianpingye </span></p>
	  </div>
  </div>

    </div>
    
</div>









































