<?php
	$css = $this->assets->get('header');
	$css -> addCss("public/css/p/view.index.css");
	$js  = $this->assets->get('footer');
?>
<div class="row">
	<div class="col-xs-6 col-md-6">
		<img alt="如此生活" src="/public/img/partner/map.png" alt="">
	</div>
	<div class="col-xs-6 col-md-6 lj_share">
		如此生活”平台2017年全年计划全国新开30家大型线下体验店，覆盖中国主要的一线及部分省会城市，为此需要优秀的投资人和投资机构与我们一起共享丰盛，现全国招募投资人和投资机构。
	</div>
</div>
<div class="lj_policy">
	<p class="lj_bule"></p>
	<div class="lj_bule2">
		<h3>体验店加盟政策</h1>
		<p>K-Point joining policy</p>
	</div>
</div>
<div class="row">
<div class="col-xs-1"></div>
<div class="col-xs-10">
	<table class="table table-bordered">
		<tr class="lj_hed" align="center">
			<td style="vertical-align: middle">合作授权费</td>
			<td style="vertical-align: middle">体验店启动费用</td>
			<td style="vertical-align: middle">体验店运营时间</td>
			<td style="vertical-align: middle">退出机制</td>
			<td style="vertical-align: middle" class="lj_jia">加盟收益</td>
			<td style="vertical-align: middle" class="lj_part">合作年限</td>
		</tr>
		<tr class="lj_hed2">
			<td>
				<p class="lj_heds">用途：用于总部品牌招商及针对品牌的市场推广等费用。</p>
			</td>
			<td>
				<p class="lj_heds">
					用途：选址差旅费、效果图设计费用、体验店装修费用、陈列道具设计及制作费用、软装成本、安防弱电及其他设备成本。
				</p>
			</td>
			<td>
				<p class="lj_heds">体验店开业前需6个月的准备期。体验店开业前准备包括：体验店选址、效果图设计、道具设计及制作、品牌商招商工作、运营人员招聘及培训等。</p>
			</td>
			<td>
				<p class="lj_heds">投资人可在第一个经营年结束后一个月内向公司申请选择退出。
				投资人退出，公司退还投资人服务费用。同时，进行股权变更，合作人股东身份注销。
				</p>
			</td>
			<td>
				<p class="lj_hedser">
					1. 投资人享有投资体验店49%的股权;享有体验店49%的利润。
					利润构成：商品销售扣点+品牌商入驻体验店的服务费用-实际运营成本
				</p>
			</td>
			<td>
				<p class="lj_hedsd">六年</p>
			</td>
		</tr>
		<tr>
			<td colspan="6" class="lj_ramark">
				<div class="lj_res">
					<p>备注</p>
					<p>经营年：指体验店开始正式运营开始，连续12个自然月为一个经营年。</p>
					<p>第一个经营年为18个月，包含了自签约之日起到体验店正式开业前的运营准备时间。</p>
				</div>
			</td>
		</tr>
		<tr>
			<td colspan="6" class="lj_ramark">
				<div class="lj_res">
					<p>体验店合作选择</p>
					<p class="lj_selet">由如此生活平台提供指定体验店选项，合作人在选项内选择体验店，每家体验店面积为3000-5000平米。</p>
				</div>
			</td>
		</tr>
		<tr>
			<td colspan="6" class="lj_ramark">
				<div class="lj_resd">
					<p>合作流程：1双方确定合作意向—签定合同—体验店选址（城市不限）—成立体验店项目公司—股权变更—体验店准备工作开始。</p>
				</div>
			</td>
		</tr>
	</table>
</div>
<div class="col-xs-1"></div>
</div>
<div class="row lj_inve">
	<div class="col-xs-1"></div>
	<div class="col-xs-4 col-md-4 ">
		<p class="lj_investor">投资人投资加盟体验店的优势与保障:</p>
		<ul class="lj_good">
			<li>1.收益高，6年收益合计超2000万。</li>
			<li>2.收益稳定，每个财务年都进行回报结算。</li>
			<li>3.收益有保障，每个店都有百人团队为的盈利负责。</li>
			<li>4.投资风险低，首年可以做无风险全额退出。</li>
			<li>5.机会好，市场上这种盈利方式目前是具有唯一性。</li>
		</ul>
	</div>
	<div class="col-xs-5 col-md-5">
		<img alt="如此生活" src="/public/img/partner/keep.png" alt="">
	</div>
</div>
<div class="row lj_wo">
	<div class="col-xs-1"></div>
	<div class="col-xs-10 col-md-10 lj_zon ">
		<p>综合以上，如此生活在三年之内将建设500家大型体验店，我们希望有更多优秀的投资人加入到我们的队伍中，带给您的将是巨大的回报。</p>
		<p class="lj_now">目前已投资加盟店面：</p>
		<ul class="lj_shop">
			<li>松江万达店</li>
			<li>厦门万达店</li>
			<li>镇江宝龙店</li>
		</ul>
		<p class="lj_now">目前尚未投资的体验店：</p>
		<ul class="lj_shop">
			<li>苏州国贸大厦店</li>
			<li>嘉定宝龙店</li>
			<li>2017年投资机会：</li>
			<li>30家大型“如此生活”体验店期待您的投资与合作。</li>
		</ul>
	</div>
</div>