<?php
	$css = $this->assets->get('header');
	$css -> addCss("public/css/p/view.newindex.css");
	$js  = $this->assets->get('footer');
    $js -> addJs("public/js/p/newcityagent.js");
?>
<div class="banner">
		<img alt="如此生活" src="../public/img/partner/newcityagent01.png" alt="">
		<h2>如此生活,开启新零售时代财富蓝海</h2>
</div>
<div class="xl_content">
	<div class="describe">
		<div class="title">
			<div>
				<h3>创意 创业 创新</h3>
				<p >creative venture innovation</p>
			</div>
			<span>如此生活</span>
		</div>
		<div class="xl_main clearfix">
			<ul class="left clearfix">
				<li class="overstriking">产业聚变雷霆万钧</li>
				<li class="overstriking">产业聚变雷霆万钧 英雄结盟共襄盛举</li>
				<li>一个被开启的全新时代</li>
				<li>一个变革后的新兴产业</li>
				<li>一个实力雄厚、光彩四溢的品牌</li>
				<li>一个引领社会进步、兼容的平台</li>
				<li>我们始终坚信——</li>
				<li>在这个产业聚变,群雄逐鹿的时代</li>
				<li>顺势而为,时事必能造英雄!</li>
				<li>我们必能用智慧策划成功!</li>
			</ul>
			<ul class="right clearfix">
				<li>
					<img alt="如此生活" src="../public/img/partner/newcityagent02.png">
				</li>
				<li>
					<img alt="如此生活" src="../public/img/partner/newcityagent03.png">
				</li>
				<li>
					<img alt="如此生活" src="../public/img/partner/newcityagent04.png">
				</li>
			</ul>
		</div>
	</div>
	<div class="bannerone">
		<img alt="如此生活" src="../public/img/partner/newcityagent05.png" alt="">
		<div class="title">
			<h3>一个颠覆行业</h3>
			<p class="en">开创超高回报率的商业模式</p>
			<ul>
				<li>一个平台+N个外围产品 </li>
				<li>从一个核心平台开始，外延无数产业机会，赚钱一劳永逸。</li>
				<li>一个旗舰店+N个标准店 </li>
				<li>一个城市一个旗舰店，N个标准店，完成一线城市布局，辐</li>
				<li> 射全国，未来三年开设500家门店，所有费用公司投</li>
				<li>一个代理商+N个品牌加盟商 </li>
				<li>保证区域代理商开发品牌加盟数量，不断扩大平台规模， </li>
				<li> 用生态圈模式赚钱，利润多元化。</li>
			</ul>
		</div>
	</div>
	<div class="narrate">
		<div class="clearfix narrateone">
			<p>如此生活,独领新零售时代行业鳌头,公司帮你出钱开店,区域<br>合伙人承接当地品牌商入驻服务,收益长期收账。<br>
			这二年中国传统行业老板受到互联网冲击生意越来越难做,
			不转型<br>等死,转型又怕被转死,前途迷茫担忧,现在如此生活帮运营商出<br>
			本钱、实现利润分成；运营商在省、市、县独家经营时收益稳步递<br>增,譬如之前投资100万开设店面,到如今不需要投资一分钱即可<br>
			以经营一座城。
			</p>
			<img alt="如此生活" src="../public/img/partner/newcityagent06.png" alt="">
		</div>
		<div class="narratetwo">
			<div class="title">
				<h3>360度立体传播</h3>
				<p>如此生活深入大众视野</p>
			</div>
			<ul>
				<li>
					<img alt="如此生活" src="../public/img/partner/newcityagent07.png">
				</li>
				<li>
					<img alt="如此生活" src="../public/img/partner/newcityagent08.png">
				</li>
			</ul>
		</div>
		<div class="narratetwo">
			<div class="title">
				<h3>专注创造财富 选择决定未来</h3>
				<p>在你成长的道路上 提供全方位的扶持</p>
			</div>
			<p class="explain">如此生活为代理商、加盟商打造一套完善的培训体系，包括行业培训、技术培训、维护<br> 培训、运营培训、销售培训等，真正教会你怎样来运营</p>
			<ul>
				<li>
					<img alt="如此生活" src="../public/img/partner/newcityagent09.png">
				</li>
				<li>
					<img alt="如此生活" src="../public/img/partner/newcityagent10.png">
				</li>
			</ul>
		</div>
	</div>
</div>
<div class="xl_footer">
    <img alt="如此生活" src="../public/img/partner/newcityagent11.png">
    <div class=" xl_info">
        <div style="text-align: center;">
            <div class="title">
                <h3>加盟留言表</h3>
                <p>join guestbook</p>
            </div>
            <div style="margin-bottom:30px;">
                <div style="width:140px;text-align:right;display:inline-block;font-size: 24px;">姓名:</div>
                <input type="text" placeholder="请填入姓名" name="name"
                       style="width:400px;height: 40px; border:1px solid #0068b6;border-radius:6px;text-indent:10px;color: #333;"/>
            </div>
            <div style="margin-bottom:30px;">
                <div style="width:140px;text-align:right;display:inline-block;font-size: 24px;">电话:</div>
                <input type="text" placeholder="请填入电话" name="phone"
                       style="width:400px;height: 40px; border:1px solid #0068b6;border-radius:6px;text-indent:10px;color: #333;""/>
            </div>
            <div style="margin-bottom:30px;">
                <div style="width:140px;text-align:right;display:inline-block;font-size: 24px;">所在城市:</div>
                <input type="text" placeholder="如:上海市长宁区" name="region"
                       style="width:400px;height: 40px; border:1px solid #0068b6;border-radius:6px;text-indent:10px;color: #333;""/>
            </div>
            <div style="margin-bottom:30px;">
                <div style="width:140px;text-align:right;display:inline-block;font-size: 24px;">邮箱:</div>
                <input type="text" placeholder="请填入邮箱" name="email"
                       style="width:400px;height: 40px; border:1px solid #0068b6;border-radius:6px;text-indent:10px;color: #333;""/>
            </div>
            <div style="margin-bottom:86px; ">
        		<div style="width:140px;text-align:right;display: inline-block; font-size: 24px; position: absolute;left: 17.3%;">业务板块:</div>
                <select id="seclectp"
                        style="width:172px;height: 40px;margin:0;padding:0;vertical-align: top;border:1px solid #0068b6;border-radius:6px;color: #666;color: #333; margin-left: 286px;float: left;">
                     
                <option value="1">我对品牌入驻感兴趣</option>
                <option value="2">我对城市代理感兴趣</option>   
                <option value="3">我对体验店加盟感兴趣</option>
                </select>
                <select class="twoselect1"
                        style="width:180px;height: 40px;margin:0;padding:0;vertical-align: top;border:1px solid #0068b6;border-radius:6px;color: #666;float: left;margin-left: 10px;">
                    <option value="1">我是品牌商</option>
                    <option value="2">我是厂商</option>
                    <option value="3">我是代理商</option>
                    <option value="4">我是经销商</option>
                </select>
                <div class="twoselect2" style="display:none; float: left;margin-top: 8px;margin-left: 8px;">
                    <span class="sec_wen">有销售团队</span>
                    <select class="twoselectbtn"
                            style="width:44px;margin:0;padding:0;vertical-align: top;border:1px solid #0068b6;border-radius:2px;color: #666;">
                        <option value="0">否</option>
                        <option value="1">是</option>
                    </select>
                    <select class="twoselect21"
                            style="width:99px;margin:0;padding:0;vertical-align: top;border:1px solid #0068b6;border-radius:2px;display:none;color: #666;">
                        <option value="1">10人以下</option>
                        <option value="2">10~20人</option>
                        <option value="3">20人以上</option>
                    </select>
                </div>
            </div>
            <div style="padding-left:142px;padding-top: 12px;padding-bottom: 50px;">
                <button class="submit"
                        style="margin:0 auto;width:400px;height: 40px;border-radius:6px; border:none;background-color:#fff;color:#666;font-size: 18px;">
                    提交
                </button>
            </div>
            <div style="border-top: 1px solid #fff;width: 100%;">
                <img alt="如此生活" src="../public/img/partner/experience18.png" alt="" style="padding: 30px 0;">
                <p style="font-size: 18px;">咨询联系:<span style="padding-left:10px;">4006699878</span></p>
            </div>
        </div>
    </div>
</div>
	