<?php
	$css = $this->assets->get('header');
	$css -> addCss("public/css/p/view.index.css");
	$js  = $this->assets->get('footer');
?>
<div style="line-height: 24px;">
	<div class="row">
	  <div class="col-xs-6 col-md-6">
		<img alt="如此生活" src="/public/img/partner/tenants(1).jpg" alt="">
	  </div>
	  <div class="col-xs-6 col-md-6">
	  	<ul style="margin-top:25px;">
			<li>顺应时代潮流趋势，响应中国互联网+战略；</li>
			<li>中国经济展翅腾飞，让众多中小企业进入发展的快车道；</li>
			<li>面对电商新机遇，传统零售障碍重重，让您的生意举步维艰？</li>
			<li>&nbsp;</li>
			<li>1.生意越来越淡</li>
			<li>2.毛利越来越薄</li>
			<li>3.成本越来越高</li>
			<li>4.管理越来越难</li>
			<li>5.人越来越难留</li>
			<li>6.压力越来越大</li>
			<li>7.钱越来越难赚</li>
	  	</ul>
	  </div>
	</div>
	<div class="row">
	  <div class="col-xs-6 col-md-6">
	  	<h5 style="margin-top:100px;font-weight: bold;">与“如此生活”平台牵手合作，我们将为您解决</h5>
	  	<ul>
			<li>1.组建专业的营销团队，帮您产品线上搭建旗舰店，提供设计、文案、美工、策划、销售；线下店面展示及销售，提供免费的品牌宣导员，免费的品牌营销，推广，活动展示等。</li>
			<li>2.线下线上免费的流量导入服务，免费的市场品牌推广服务。</li>
			<li>3.免费的仓储服务及性价比更高的物流快递服务。</li>
			<li>4.超低价格提供宝龙、万达广场等成熟商圈的产品展示空间。</li>
			<li>5.负责帮您拓展全球代理商、分销商。</li>
			<li>6.负责帮您发展移动微商等新型互联网分销渠道。</li>
	  	</ul>
	  </div>
	  <div class="col-xs-6 col-md-6">
		<img alt="如此生活" src="/public/img/partner/tenants(2).jpg" alt="">
	  </div>
	</div>
	<div class="row" style="margin-bottom:120px;">
	  <div class="col-xs-6 col-md-6">
	  	<ul>
			<li>1全年不低于二次上门培训，食宿及差旅费由代理商承担，同时进行不定期的远程培训协助。</li>
			<li>2平台提供完整的招商工具：招商手册，DM单内容，宣传片等。</li>
			<li>3代理商当地召开招商会，平台提供人员讲师及策划支持，费用代理商承担；组织招商会在上海召开，平台提供协助，费用代理商提供。</li>
			<li>4平台提供完整销售系统支持：外呼系统+EC软件系统。</li>硬件需代理商自行采购。</li>
			<li>5每月10日前支付代理商上月收益。</li>
			<li>6平台官网为代理商做相应的宣传推广。</li>
			<li>7市场共享机制：优秀的市场开发方式，工具，方法的分享学习。</li>
			<li>8代理商超额完成年度任务的部分，平台予以签约额3%的额外奖励。</li>
			<li>9一次签约，三年收益，客户续约，代理商也有优厚回报！</li>
			<li>10 第二个合同年开始，平台提供给代理商10家免费入驻的名额，仅限线上。</li>
			<li>如过您是一个心怀梦想的人，如果您想成就一个伟大的梦，那么请致电或留言给我们。</li>
			<li>如此生活平台愿携手与您一起创造财富梦想。</li>
	  	</ul>
	  </div>
	</div>
	<div style="margin-bottom:100px;">
	  <ul>
			<li>您只要负责产品质量、市场价格、售后服务和及时供货，其他事情由平台全权承办，全年仅仅一个销售员的工资，让您的产品线上线下全渠道展示销售，同时节省至少10个人的开销以及巨额的推广成本。</li>
			<li>如果您正深处困境，如果您正遇转型之苦，如果您正对未来茫然，如果您高瞻远瞩，那么请与如此生活平台合作，我们将竭诚为您服务！</li>
	  	
	  </ul>
	</div>
</div>