<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>分享记录|如此生活</title>
    <meta name="viewport" content="width=device-width, initial-scale=1,maximum-scale=1,user-scalable=no">   
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <link rel="stylesheet" href="/public/ext/css/soo.m.ui.css">
    <link rel="stylesheet" href="/public/ext/css/download.css">
    <link rel="stylesheet" href="/public/css/starfans/newstarfans.css">
</head>
<body>


<!-- 头部 -->
<div id="soo-header">
    <div id="header-left" onclick="window.history.go(-1)">
        <!-- <a href="/starfans/index.html">  -->
            <img src="../public/img/starfans/icon_back@1x.png" alt=""/>
        <!-- </a> -->
    </div>
    <div id="header-center">邀请记录</div>
</div>
<!-- 下载框 -->
<div class="download_box" id="download-nav">
	<div class="remove" id="download-nav-hide"><img src="../public/img/common/icon_close@3x.png" alt=""></div>
	<div class="logo"><img src="../public/img/common/logo@3x.png" alt=""></div>
	<div class="word">下载如此生活客户端</div>
	<div class="sure" id="download-nav-sure"><div>下载</div></div>
</div>
<!-- 内容区 -->
<div class="share_con">
    <!-- 分享记录 -->
    {% if inviterelist %}
	<ul class="record clearfix">
	    {% for i,d in inviterelist['data'] %}
		<li class="out_li">
			<ul class="news clearfix">
				<li>
					<img src="{{d['accepter_avatar']}}" class="headportrait">
				</li>
				<li>
					<h2>{{d['nick_name']}}</h2>
					<p>{{d['title']}}</p>
				</li>
				<li>
					<span>+{{d['award']}}</span>
				</li>
			</ul>
		</li>
		{% endfor %}
	</ul>
	{% endif %}
</div>
<script>
	var _hmt = _hmt || [];
	(function() {
	  var hm = document.createElement("script");
	  hm.src = "https://hm.baidu.com/hm.js?826cba0598fb59fb393282dd20e7d118";
	  var s = document.getElementsByTagName("script")[0]; 
	  s.parentNode.insertBefore(hm, s);
	})();
</script>
<script src="/public/ext/js/rem.js"></script>
<script src="/public/ext/js/jquery-1.8.3.min.js"></script>
<script src="/public/ext/js/download.js"></script>
<script src="/public/ext/js/soo.m.ui.js"></script>
<script src="/public/ext/js/jquery.base64.js"></script>
</body>
</html>