
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>领红包|如此生活</title>
    <meta name="viewport" content="width=device-width, initial-scale=1,maximum-scale=1,user-scalable=no">   
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <link rel="stylesheet" href="/public/ext/css/soo.m.ui.css">
    <link rel="stylesheet" href="/public/ext/css/download.css">
    <link rel="stylesheet" href="/public/css/starfans/newstarfans.css">
</head>
<body>



<div id="soo-header">
    <div id="header-left" onclick="window.history.go(-1)">
        <!-- <a href="/starfans/share.html">  -->
            <img src="../public/img/starfans/icon_back@1x.png" alt=""/>
        <!-- </a> -->
    </div>
    <div id="header-center">领红包</div>
</div>
<!-- 下载框 -->
<div class="download_box" id="download-nav">
	<div class="remove" id="download-nav-hide"><img src="../public/img/common/icon_close@3x.png" alt=""></div>
	<div class="logo"><img src="../public/img/common/logo@3x.png" alt=""></div>
	<div class="word">下载如此生活客户端</div>
	<div class="sure" id="download-nav-sure"><div>下载</div></div>
</div>
<div class="getpacketmain">
    <div class="banner">
		<img src="../public/img/starfans/bg_ying ling xing bi.png" alt="">
		<div class="packetnew">
			<h3>

				{% if id == 1 %}
			        您已经是注册用户啦~
				{% else %}
				    恭喜! 红包
				{% endif %}

			</h3>
			<p>
			    {% if id == 1 %}
			        邀请身边好友注册领取奖励吧
				{% else %}
				    已经放进您的手机账户中
				{% endif %}
			</p>
			    {% if id == 1 %}
			        <a id="share_btn">发送我的邀请链接</a>
				{% else %}
				    <a href="/index.html">立即使用</a>
				{% endif %}
		</div>
	</div>
{% if sharepage %}
	{% if sharepage['hot_goods'] %}
	<div class="hotsell">
		<h3>如此生活今日热销</h3>
		<ul class="clearfix">
		{% for d in sharepage['hot_goods']%}
			<li>
			    <a href="{{url_goods}}/{{d['Sku_ID']}}.html">
					<img src="{{d['S_Logo']}}" alt="">
					<p class="hotsell_p">{{d['S_Name']}}</p>
					<p>￥{{d['S_ShopPrice']}}</p>
				</a>
			</li>
		{% endfor %}
		</ul>
	</div>
	{% endif %}
	{% endif %}
</div>
<div id="footer">
	<h2>用户须知</h2>
	<div>
		<p>1、活动开始星粉则可以转发活动界面连接，邀请好友参加分享。</p>
		<p>2、星粉转发获得的邀请红包金额可累计使用，但不可提现。</p>
		<p>3、红包使用范围只限如此生活线上线下商城内所有在售产品。</p>
		<p>4、每个新会员仅可获得一次新人红包。</p>
		<p>5、如若恶意注册、作弊领取、恶意批发、恶意刷单、盗用或冒用他人信息参加活动此ID用户则被取消活动资格。</p>
		<p>6、红包限量1000份，送完即止。</p>
		<p>7、最终解释权归如此生活所有。</p>
	</div>
</div>

<script>
	var _hmt = _hmt || [];
	(function() {
	  var hm = document.createElement("script");
	  hm.src = "https://hm.baidu.com/hm.js?826cba0598fb59fb393282dd20e7d118";
	  var s = document.getElementsByTagName("script")[0]; 
	  s.parentNode.insertBefore(hm, s);
	})();
</script>
<script src="/public/ext/js/rem.js"></script>
<script src="/public/ext/js/jquery-1.8.3.min.js"></script>
<script src="/public/ext/js/download.js"></script>
<script src="/public/ext/js/soo.m.ui.js"></script>
<script src="/public/ext/js/jquery.base64.js"></script>
<script src="/public/js/starfans/download.js"></script>
</body>
</html>
















































