<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>如此生活|惠赚钱</title>
    <meta name="viewport" content="width=device-width, initial-scale=1,maximum-scale=1,user-scalable=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
   <!--  <link rel="stylesheet" type="text/css" href="/public/css/mui.min.css"/> -->
    <link rel="stylesheet" type="text/css" href="/public/css/money/money.css"/>
</head>
<body class="lcy_money">
<!-- 惠赚钱主体 -->
<div class="money_main">
    <!-- 头部 -->
    <header class="head">
        <div class="back"></div>
        <div class="title">惠赚钱</div>
        <div class="back2"></div>
    </header>
    
    <!-- 小banner -->
    <div class="money_banner">
        <a href="">
            <img src="/public/img/makemoney1.png" alt="">           
        </a>
    </div>
    <!-- nav -->
    <div class="head_nav">
        <ul>
            <li class="active"><a href="#">服装鞋靴</a></li>
            <li><a href="#">服装鞋靴</a></li>
            <li><a href="#">服装鞋靴</a></li>
            <li><a href="#">服装鞋靴</a></li>
            <li><a href="#">服装鞋靴</a></li>
            <li><a href="#">服装鞋靴</a></li>
            <li><a href="#">服装鞋靴</a></li>
            <li><a href="#">服装鞋靴</a></li>
            <li><a href="#">服装鞋靴</a></li>
            <li><a href="#">服装鞋靴</a></li>
            <li><a href="#">服装鞋靴</a></li>
        </ul>
    </div>    
    <!-- 添加商品 -->
    <div class="addgoods">
        <!-- 小top -->
        <div class="addgoods_top">&nbsp;&nbsp;|&nbsp;佣金</div>
        <div class="classify">
            <ul>
                <li><a href="#" class="active_num">0-100元</a></li>
                <li><a href="#">100-500元</a></li>
                <li><a href="#">500-1000元</a></li>
                <li><a href="#">1000-5000元</a></li>
                <li><a href="#">5000元以上</a></li>
                <li><a href="#">不限</a></li>
            </ul>
        </div>
        <div class="goodslist">
        <!-- 循环 -->
            <div class="goodsbox">
                <div class="goods_img">
                    <img src="/public/img/m_goods1.png" alt="">
                </div>
                <div class="goods_content">
                    <p class="word">
                        要想在别人面前表现的毫不费力，你必须更加努力现的毫不费力，你必须更加努力现的毫不费力，你必须更加努力现的毫不费力，你必须更加努力现的毫不费力，你必须更加努力现的毫不费力，你必须更加努力现的毫不费力，你必须更加努力!
                    </p>
                    <div class="content_l">
                        <p class="piece">
                            ￥<span>89</span>
                            <span class="get_money">赚<span>25元</span></span>
                        </p>
                        <p class="date">截止日期：<span>2016-9-21</span></p>
                    </div>
                    <div class="content_r">
                        <p class="add">添加 
                        <span class="fly_good"></span></p>
                    </div>                   
                </div>               
            </div>
        <!-- 循环结束 -->
        <!-- 循环 -->
            <div class="goodsbox">
                <div class="goods_img">
                    <img src="/public/img/m_goods2.png" alt="">
                </div>
                <div class="goods_content">
                    <p class="word">
                        要想在别人面前表现的毫不费力，你必须更加努力现的毫不费力，你必须更加努力现的毫不费力，你必须更加努力现的毫不费力，你必须更加努力现的毫不费力，你必须更加努力现的毫不费力，你必须更加努力现的毫不费力，你必须更加努力!
                    </p>
                    <div class="content_l">
                        <p class="piece">
                            ￥<span>89</span>
                            <span class="get_money">赚<span>25元</span></span>
                        </p>
                        <p class="date">截止日期：<span>2016-9-21</span></p>
                    </div>
                    <div class="content_r">
                        <p class="add">添加 
                        <span class="fly_good"></span></p>
                    </div>                   
                </div>               
            </div>
        <!-- 循环结束 -->
        <!-- 循环 -->
            <div class="goodsbox">
                <div class="goods_img">
                    <img src="/public/img/m_goods3.png" alt="">
                </div>
                <div class="goods_content">
                    <p class="word">
                        要想在别人面前表现的毫不费力，你必须更加努力现的毫不费力，你必须更加努力现的毫不费力，你必须更加努力现的毫不费力，你必须更加努力现的毫不费力，你必须更加努力现的毫不费力，你必须更加努力现的毫不费力，你必须更加努力!
                    </p>
                    <div class="content_l">
                        <p class="piece">
                            ￥<span>89</span>
                            <span class="get_money">赚<span>25元</span></span>
                        </p>
                        <p class="date">截止日期：<span>2016-9-21</span></p>
                    </div>
                    <div class="content_r">
                        <p class="add">添加 </p>
                    </div>                   
                </div>               
            </div>
        <!-- 循环结束 -->

        </div>
    </div>
    <!-- 底部 -->
    <div class="bottom">
        <div class="bottom_shop"><span class="num" id="end">10</span></div>
        <a href="http://172.16.4.134/myshop.html"><div class="bottom_go">添加完毕</div></a>
    </div>   
</div>
</body>
</html>
<script src="/public/ext/js/jquery-1.8.3.min.js"></script>
<script src="/public/js/rem.js"></script>
<script src="/public/js/money/fly.js"></script>
<script src="/public/js/money/money.js"></script>
<script src="/public/js/m_analytics.js"></script>
<script src="/public/js/sdk.2.2.js"></script>
