<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>如此生活|星店铺-商品详情</title>
    <meta name="viewport" content="width=device-width, initial-scale=1,maximum-scale=1,user-scalable=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <link rel="stylesheet" type="text/css" href="/public/css/mui.min.css"/> 
    <link rel="stylesheet" type="text/css" href="/public/css/money/moneydetail.css"/>
</head>
<body class="lcy_moneydetail">
    <header class="head">
        <div class="back"></div>
        <div class="title"></div>
        <div class="back2">
        	<div class="mark">
        		<div class="arrow_top"></div> 
        		<ul>
        			<li><a href="#" class="b_mark1">首页</a></li>
        			<li><a href="#" class="b_mark2">分享</a></li>
        			<li><a href="#" class="b_mark3">搜索</a></li>
        			<li><a href="#" class="b_mark4">星店铺</a></li>
        		</ul>
        	</div>
        </div>
    </header>
	<div class="mui-content">
	    <div class="mui-slider">
	        <div class="mui-slider-group mui-slider-loop">
	        	<!-- 额外增加的一个节点 -->
	            <div class="mui-slider-item mui-slider-item-duplicate">
	                <ul class="mui-table-view mui-grid-view">
	                    <li class="mui-table-view-cell mui-media mui-col-xs-12">
	                    	<a href="#">
	                    		<img class="mui-media-object" src="/public/img/m_d_goods.png">
	                   		</a>
	                    </li>
	                </ul>
	            </div>
	            <!-- 轮播循环 -->
	            <div class="mui-slider-item">
	                <ul class="mui-table-view mui-grid-view">
	                    <li class="mui-table-view-cell mui-media mui-col-xs-12">
	                    	<a href="#">
	                    		<img class="mui-media-object" src="/public/img/m_d_goods.png">
	                    	</a>
	                    </li>
	                </ul>
	            </div>
	            <!-- 循环结束 -->
	            <!-- 轮播循环 -->
	            <div class="mui-slider-item">
	                <ul class="mui-table-view mui-grid-view">
	                    <li class="mui-table-view-cell mui-media mui-col-xs-12">
	                    	<a href="#">
	                    		<img class="mui-media-object" src="/public/img/m_d_goods.png">
	                    	</a>
	                    </li>
	                </ul>
	            </div>
	            <!-- 循环结束 -->
	            <!-- 轮播循环 -->
	            <div class="mui-slider-item">
	                <ul class="mui-table-view mui-grid-view">
	                    <li class="mui-table-view-cell mui-media mui-col-xs-12">
	                    	<a href="#">
	                    		<img class="mui-media-object" src="/public/img/m_d_goods.png">
	                    	</a>
	                    </li>
	                </ul>
	            </div>
	            <!-- 循环结束 -->
	            <!-- 额外增加的一个节点 -->
	            <div class="mui-slider-item mui-slider-item-duplicate">
	                <ul class="mui-table-view mui-grid-view">
	                    <li class="mui-table-view-cell mui-media mui-col-xs-12">
	                    	<a href="#">
	                    		<img class="mui-media-object" src="/public/img/m_d_goods.png">
	                    	</a>
	                    </li>
	                </ul>
	            </div>
	        </div>
	        <div class="mui-slider-indicator" >
	            <div class="mui-number">
	                <span>1</span> / <span class="total">3</span>
	            </div>
	        </div>
	    </div>
	</div>
	<div class="goods_detail">
		<div class="introduce">
			<div class="word">
				更加快乐圣诞节过了多久估计是的福利国家，到付款感觉到舒服了空格键的风格离开教室对方立刻感觉（咖喱苦尽甘来卡的价格）
				<div class="hot">
					<img src="/public/img/m_d_hot.png" alt="">
				</div>
			</div>
		</div>
		<div class="piece">
			<span>￥<span>666.66</span></span>
			<del>市场价：￥666.66</del>
		</div>
		<div class="address">
			<span calss="address_a">上海市</span>
			&gt;<span calss="address_b">长宁区</span>
			&gt;<span calss="address_c">你猜</span>
		</div>
	</div>
	<!-- 详情表 -->
	<div class="goods_data">
		<ul>
			<li><a class="active">商品介绍</a></li>
			<li><a>规格参数</a></li>
			<li><a>包装售后</a></li>
		</ul>
		<div class="goods_intro">
			<img src="/public/img/m-d-goodsb.png" alt="">
			<img src="/public/img/m-d-goodsb.png" alt="">
			<img src="/public/img/m-d-goodsb.png" alt="">
			<img src="/public/img/m-d-goodsb.png" alt="">
		</div>
		<div class="goods_standard">
			<table>
				<tr>
					<td class="td_l"></td>
					<td class="td_r title">主体</td>
				</tr>
				<!-- 规格 -->
				<tr>
					<td class="td_l">品牌</td>
					<td class="td_r">放假啦睡觉</td>
				</tr>
				<!-- 规格 -->
				<tr>
					<td class="td_l">商品编号</td>
					<td class="td_r">1234567</td>
				</tr>
				<!-- 规格 -->
				<tr>
					<td class="td_l">价格区间</td>
					<td class="td_r">23-56</td>
				</tr>
				<!-- 规格 -->
				<tr>
					<td class="td_l">系列</td>
					<td class="td_r">hfskh还得上课</td>
				</tr>
				<!-- 规格 -->
				<tr>
					<td class="td_l">类别</td>
					<td class="td_r">阿苏童企鹅</td>
				</tr>
				<!-- 规格 -->
				<tr>
					<td class="td_l">规格</td>
					<td class="td_r">韩国进口</td>
				</tr>
				<!-- 规格 -->
				<tr>
					<td class="td_l">使用人群</td>
					<td class="td_r">女士</td>
				</tr>
				<!-- 规格 -->
				<tr>
					<td class="td_l">生产日期</td>
					<td class="td_r">2013-4-12</td>
				</tr>
				<!-- 规格 -->
				<tr>
					<td class="td_l">有效期</td>
					<td class="td_r">2017-9-9</td>
				</tr>
				<!-- 规格 -->
				<tr>
					<td class="td_l">生产地</td>
					<td class="td_r">中国人</td>
				</tr>
				<!-- 规格 -->
				<tr>
					<td class="td_l">品牌所属地</td>
					<td class="td_r">主体</td>
				</tr>
			</table>
		</div>
		<div class="goods_para">
			<p class="good_title">包装清单：</p>
			<p class="good_list">天下第一好的洗面脸</p>
			<p class="title_top title">|&nbsp;服务承诺</p>
			<p class="title">如此生活向你承诺：<span>如此生活向您保证销售商品均为正品行货并开具正规发票。凭 如此生活发票，所有商品均可以享受生产厂家的全国联保服务或指定服务商联保服务，如此生活将严格按照国家三包政策以及本《退换货政策》，对所售商品履行换货和退货的义务。 </span></p>
			<p class="title">注：<span>因厂家会在没有任何提前通知的情况下更改产品包装、产地或者一些附件，本司不能确保客户收到的货物与商城图片、产地、附件说明完全一致。网站商品的功能参数仅供参考，请以实物为准，我司只能确保网站经营商品均为原厂正品行货！并且保证与当时市场上同样主流新品一致。若本商城没有及时更新，请大家谅解！</span></p>
		</div>
	</div>
	<!-- 底部 -->
	<div class="bottom">
		<div class="collect"></div>
		<div class="shopcar">
			<span>4</span>
		</div>
		<div class="add"><button>加入购物车</button></div>
		<div class="instant"><button>立即购买</button></div>
	</div>
	<!-- 回到顶部-->
	<div class="go_top"></div>
</body>
</html>
<script src="/public/ext/js/jquery-1.8.3.min.js"></script>
<script src="/public/js/mui.min.js"></script>
<script src="/public/js/rem.js"></script>
<script src="/public/js/money/moneydetail.js"></script>
<script src="/public/js/m_analytics.js"></script>
<script src="/public/js/sdk.2.2.js"></script>
