<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>如此生活|我的店铺</title>
    <meta name="viewport" content="width=device-width, initial-scale=1,maximum-scale=1,user-scalable=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
   <!--  <link rel="stylesheet" type="text/css" href="/public/css/mui.min.css"/> -->
    <link rel="stylesheet" type="text/css" href="/public/css/money/myshop.css"/>
</head>
<body class="lcy_myshop">
	<!-- 头部 -->
    <header class="head">
        <div class="back"></div>
        <div class="title">
        	<div class="search"></div>
        	<input type="text">
        </div>
        <div class="back2">
        	<div class="back2_mark">
        		<div class="back2_btn">
        			<ul class="back2_btn_list">
        				<li>
        					<a href="#" class="btn1"></a>
        					<p>首页</p>
        				</li>
        				<li>
        					<a class="btn2"></a>
        					<p>编辑</p>
        				</li>
        				<li>
        					<a href="http://172.16.4.134/money.html" class="btn3"></a>
        					<p>继续添加</p>
        				</li>
                        <li>
                            <a href="http://172.16.4.134/statistics.html" class="btn4"></a>
                            <p>统计</p>
                        </li>
                        <li>
                            <a href="#" class="btn5"></a>
                            <p>分享</p>
                        </li>
        			</ul>
        		</div>
        	</div>
        </div>
        <div class="back3">
        	<div class="classify_top">
         		<div class="list_top"></div>
        		<ul class="classify_list">
        			<li><a href="#">全部商品</a></li>
        			<li><a href="#">美女</a></li>
        			<li><a href="#">美女</a></li>
        			<li><a href="#">美女</a></li>
        			<li><a href="#">美女</a></li>
        			<li><a href="#">美女</a></li>
        			<li><a href="#">美女</a></li>
        			<li><a href="#">美女</a></li>
        			<li><a href="#">美女</a></li>
        			<li><a href="#">美女</a></li>
        		</ul>
        	</div>
        </div>
    </header>
    <!-- 头像 -->
    <div class="head_pic">
    	<div class="head_img">
    		<img src="/public/img/detalia_t.png" alt="">
    	</div>
    	<div class="message">
    		<p class="name">
    			<span class="name">kitty的小店(龙之梦店)</span>
    		</p>
    		<p class="num"><span class="zhu">90</span>关注<span class="share">90</span>分享</p>
    	</div>
    	<div class="zhu_btn">+关注</div>
        <div class="head_pic_mark">
            <a href="http://172.16.4.134/shopdatum.html"><div class="modify">点击修改个人资料</div></a>
        </div>
    </div>
    <!-- banner -->
    <div class="banner">
    	<img src="/public/img/huibanner1.png" alt="">
    </div>
    <!-- nav -->
      <div class="head_nav">
        <ul>
            <li class="active"><a href="#">服装鞋靴</a></li>
            <li><a href="#">服装鞋靴</a></li>
            <li><a href="#">服装鞋靴</a></li>
            <li><a href="#">服装鞋靴</a></li>
            <li><a href="#">服装鞋靴</a></li>
            <li><a href="#">服装鞋靴</a></li>
            <li><a href="#">服装鞋靴</a></li>
            <li><a href="#">服装鞋靴</a></li>
            <li><a href="#">服装鞋靴</a></li>
            <li><a href="#">服装鞋靴</a></li>
            <li><a href="#">服装鞋靴</a></li>
        </ul>
    </div> 
    <!-- goodslist -->
    <div class="goods_list">
        <!-- 循环开始 -->
        <div class="goods_box">
            <div class="img_box">
                <a href=""><img src="/public/img/shop_goods.png" alt=""></a>
            </div>
            <p class="detail">真是一个好看的姑娘啊真是一个好看的姑娘啊</p>
            <p class="piece">
                <span class="now_piece">￥<span>-949.00</span>元</span>
                <del class="old_piece">￥<span>-949.00</span>元</del>
            </p>
            <div class="goods_mark">
                <div class="delete">
                    <img src="/public/img/money_shop_close.png" alt="">
                </div>
                <div class="up">
                    <img src="/public/img/money_shop_up.png" alt="">
                </div>
                <div class="down">
                    <img src="/public/img/money_shop_down.png" alt="">
                </div>
            </div>
        </div>
        <!-- 循环结束 -->
        <!-- 循环开始 -->
        <div class="goods_box">
            <div class="img_box">
                <a href=""><img src="/public/img/shop_goods.png" alt=""></a>
            </div>
            <p class="detail">真是一个好看的姑娘啊真是一个好看的姑娘啊</p>
            <p class="piece">
                <span class="now_piece">￥<span>-949.00</span>元</span>
                <del class="old_piece">￥<span>-949.00</span>元</del>
            </p>
            <div class="goods_mark">
                <div class="delete">
                    <img src="/public/img/money_shop_close.png" alt="">
                </div>
                <div class="up">
                    <img src="/public/img/money_shop_up.png" alt="">
                </div>
                <div class="down">
                    <img src="/public/img/money_shop_down.png" alt="">
                </div>
            </div>
        </div>
        <!-- 循环结束 -->
        <!-- 循环开始 -->
        <div class="goods_box">
            <div class="img_box">
                <a href=""><img src="/public/img/shop_goods.png" alt=""></a>
            </div>
            <p class="detail">真是一个好看的姑娘啊真是一个好看的姑娘啊</p>
            <p class="piece">
                <span class="now_piece">￥<span>-949.00</span>元</span>
                <del class="old_piece">￥<span>-949.00</span>元</del>
            </p>
            <div class="goods_mark">
                <div class="delete">
                    <img src="/public/img/money_shop_close.png" alt="">
                </div>
                <div class="up">
                    <img src="/public/img/money_shop_up.png" alt="">
                </div>
                <div class="down">
                    <img src="/public/img/money_shop_down.png" alt="">
                </div>
            </div>
        </div>
        <!-- 循环结束 -->
        <!-- 循环开始 -->
        <div class="goods_box">
            <div class="img_box">
                <a href=""><img src="/public/img/shop_goods.png" alt=""></a>
            </div>
            <p class="detail">真是一个好看的姑娘啊真是一个好看的姑娘啊</p>
            <p class="piece">
                <span class="now_piece">￥<span>-949.00</span>元</span>
                <del class="old_piece">￥<span>-949.00</span>元</del>
            </p>
            <div class="goods_mark">
                <div class="delete">
                    <img src="/public/img/money_shop_close.png" alt="">
                </div>
                <div class="up">
                    <img src="/public/img/money_shop_up.png" alt="">
                </div>
                <div class="down">
                    <img src="/public/img/money_shop_down.png" alt="">
                </div>
            </div>
        </div>
        <!-- 循环结束 -->
    </div>
    <!-- 完成按键 -->
    <div class="success">完&nbsp;成</div>
    <!-- 更新商品 -->
    <div class="updata">
        <div class="men_img">
            <div class="men"></div>
            <div class="hide"></div>
        </div>
        <div class="word">有新惠赚钱商品，快去看看呀！</div>
        <div class="updata_b"></div>
    </div>
</body>
</html>
<script src="/public/ext/js/jquery-1.8.3.min.js"></script>
<script src="/public/js/rem.js"></script>
<script src="/public/js/money/myshop.js"></script>
<script src="/public/js/m_analytics.js"></script>
<script src="/public/js/sdk.2.2.js"></script>
