<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>如此生活|充值</title>
    <meta name="viewport" content="width=device-width, initial-scale=1,maximum-scale=1,user-scalable=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <link rel="stylesheet" type="text/css" href="/public/css/mui.min.css"/>
    <link rel="stylesheet" type="text/css" href="/public/css/money/recharge.css"/>
</head>
    <body class="hkl_recharge">
        <!-- 头部 -->
        <header class="mui-bar mui-bar-nav">
            <a href="/index.html"><div class="back_img"></div></a>
            <h4>充值</h4>
        </header>
        <div class="mui-content">   
            <!-- 星换购 -->
            <div class="xing_sale">
                <!-- 三个充值滑动 -->
                <div id="xing_hot_slider" class="mui-slider">
                        <div id="item1mobile" class="mui-control-content mui-active">
                        <!-- 星钱包余额 -->
                            <div class="xing_hot_goods_1">
                                <a href=""><img src="/public/img/recharge/recharge-banner1.jpg" alt=""></a>
                            </div>
                            <div class="superkitty"><span>昵称：</span><span>{{nickname}}</span><!-- <i><img src="/public/img/recharge/recharge-money.png" alt=""></i> --></div>
                            <div class="secharge-money" token={{token}} url_order={{url_order}} url_member={{url_member}}>
                                <ul>
                                <?php  if(!empty($data['data'])) {?>
                                {% for i,d in data['data'] %}
                                    <li class="{{i==0?'secharge-money-back':''}}" pay_value={{d['pay_value']}} virtualgoods_id={{d['virtualgoods_id']}}>{{d['name']}}</li>
                                {% endfor %}
                                <?php  } ?>
                                </ul>
                            </div>
                            <div class="recharge-youhui"><p>优惠价：</p><span>￥<?php echo $data['data'][0]['pay_value'];  ?></span></div>
                            <a class="recharge-promptly" >立即充值</a>
                        </div>
                </div>
            </div>

        </div><!--接上面-->
</body>
</html>
<script src="/public/ext/js/jquery-1.8.3.min.js"></script>
<script src="/public/js/jquery.base64.js"></script>
<script src="/public/js/rem.js"></script>
<script src="/public/js/mui.min.js"></script>
<script src="/public/js/recharge/recharge.js"></script>
<script src="/public/js/m_analytics.js"></script>
<script src="/public/js/sdk.2.2.js"></script>
