<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>邀请记录</title>
    <meta name="viewport" content="width=device-width, initial-scale=1,maximum-scale=1,user-scalable=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <link rel="stylesheet" type="text/css" href="/public/css/record/cord.css"/>
   <!--  <script src="js/resize.js" type="text/javascript" charset="utf-8"></script> -->
</head>
<body>	
<div class="lcy_starfans">
	<!-- 头部 -->
	<header class="head">
		<div class="back" onclick="javascript:history.go(-1)"></div>
		<p>邀请记录</p>
		<div class="back2"></div>
	</header>
	<!-- 注册内容  -->
     <?php if($data['data']) {  ?>
    {% for d in data['data'] %}
    <div class="enroll">
    	<p class="successed">注册成功</p>
        <p class="tasks"><span>好友：{{d['nickname']}}</span> <span class="moneyd">¥：{{d['money']}}</span></p>
        <p class="time"><span>{{d['createtime']}}</span> <span class="award">奖励至钱包余额</span></p>
    </div>
    {% endfor %}
    <?php  }else{ ?>
    <div class="" >
    <img src="/public/img/life/zanwushuju.png" style="width:50%;display:block;margin:0 auto;margin-top:5px;" >
    </div>
    <?php } ?>
</div>
</body>
</html>
<script src="/public/ext/js/jquery-1.8.3.min.js"></script>
<script src="/public/js/rem.js"></script>
<script src="/public/js/m_analytics.js"></script>
<script src="/public/js/sdk.2.2.js"></script>