<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>如此生活|星店铺资料</title>
    <meta name="viewport" content="width=device-width, initial-scale=1,maximum-scale=1,user-scalable=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
   <!--  <link rel="stylesheet" type="text/css" href="/public/css/mui.min.css"/> -->
    <link rel="stylesheet" type="text/css" href="/public/css/money/shopdatum.css"/>
</head>
<body class="lcy_shopdatum">
    <header class="head">
        <div class="back"></div>
        <div class="title">星店铺资料</div>
        <div class="back2"></div>
    </header>
    <div class="contain">
    	<div class="word">店铺logo</div>
    	<div class="logo">
    		<img src="/public/img/detalia_t.png" alt="">
    	</div>
    </div>
    <div class="contain">
    	<div class="word">店铺名称</div>
    	<div class="name">
    		<input type="text" value="回家的孩子">
    	</div>
    </div>
</body>
</html>
<script src="/public/ext/js/jquery-1.8.3.min.js"></script>
<script src="/public/js/rem.js"></script>
<script src="/public/js/m_analytics.js"></script>
<script src="/public/js/sdk.2.2.js"></script>
