<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <title>
        {{title|default('如此生活')}}
    </title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="keywords" content="{{keywords}}">
    <meta name="description" content="{{description}}">
    <meta name="author" content="Tony Wang">
    <meta name="date" content="" />
    <meta http-equiv="content-language" content="zh-CN" />
   
    
</head>
       
<body>
	{{ content }}
	<div class="footbg">
            <ul class="foot">
                <li>
                    <div>
                        <a href="index.html"><img src="/public/mobile/img/minet/icon_home@3x.png"/>
                        </a>
                    </div>
                    
                    <p class="highLight">首页</p>
                </li>
                <li>
                    <div>
                        <a href="classify.html">
                            <img src="/public/mobile/img/minet/icon_category@3x.png"/>
                        </a>
                    </div>
                    <p>分类</p>
                </li>
                <li>
                    <div>
                        <a href="star.html"><img src="/public/mobile/img/minet/icon_coin@3x.png"/></a>
                    </div>
                    <p>惠生活</p>
                </li>
                <li>
                    <div>
                        <a href="cart.html">
                            <img src="/public/mobile/img/minet/icon_cart@3x.png"/>
                        </a>
                    </div>
                    <p>
                        购物车
                    </p>
                    
                <li>
                    <div>
                        <a href="/m/index.html">
                            <img src="/public/mobile/img/minet/icon_my@3x.png"/> 
                            
                        </a>
                    </div>
                    <p>
                        我的
                    </p>
                </li>
            </ul>
        </div>
        <div id="back-to-top" >
            <a href="#search">
            </a>
        </div>
        {{assets.outputJs('footer')}}
</body>

</html>