<!DOCTYPE html>
<html lang="en">
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
	<meta charset="UTF-8">
	<title>分享红包</title>
	<link rel="stylesheet" type="text/css" href="/public/css/reward/fulfill.css">
</head>
<body>
	<div class="wrap">
		<div class="header">
			<span><a href="#"><img src="/public/img/reward/fulfill/lefts.png " class="lefter"></a></span><span>分享红包</span>
		</div>
		<!-- 快上车头部 -->
		<div class="cars">
			<p class="cart"><img src="/public/img/reward/fulfill/car2.png"></p>
			<p class="autos"><img src="/public/img/reward/fulfill/car1.png"></p>
			<p class="banners"><img src="/public/img/reward/fulfill/banner.png"></p>
			<p class="draw"><a href="#"><img src="/public/img/reward/fulfill/hits.png"></a></p>
		</div>
		<!-- 中间规则部分 -->
		<div class="content">
		<!-- 活动规则 -->
			 <div class="rule">
			 <?php if(isset($time)){ ?>
				<p class="own"> 所有红包在 {{ time }} 内领取完毕</p>
			 <?php }else{ ?>
			 	<p class="own"> 所有红包已领取完毕</p>
			 <?php } ?>
			 	 <p class="girl"><img src="/public/img/reward/fulfill/girl.png"></p>
			 	 <p class="pink"><img src="/public/img/reward/fulfill/violet.png"></p>
			 	  <div class="lj_evnet"></div>
			 	 <p class="rocks"><img src="/public/img/reward/fulfill/rock.png"></p>
			 	 <p class="firleft"><img src="/public/img/reward/fulfill/ring.png" class="ring"></p>
			 	 <p class="firright"><img src="/public/img/reward/fulfill/ring.png" class="ring"></p>
			 </div>
           <!-- 流程 -->
           <div class="lj_flow">
           	    <p class="flows"><img src="/public/img/reward/fulfill/con2.png"></p>
           	    <p class="firleft"><img src="/public/img/reward/fulfill/ring.png" class="ring"></p>
			 	 <p class="firright"><img src="/public/img/reward/fulfill/ring.png" class="ring"></p>
           </div>
           <!-- 红包达人 -->
            <div class="person">
            	<div class="personbg main_board">
            		<div class="board_box">
		                <ul>
                        <?php if(!empty($latest) && is_array($latest)){ ?>
        					{% for v in latest %}
        						<li><span>{{ v['mobile'] }}</span>&nbsp;<span>{{ v['content'] }}</span></li>
        					{% endfor %}
                        <?php }else{ ?>
        					<li><span>182****4992</span>&nbsp;<span>领取红包20元</span></li>
        					<li><span>152****4512</span>&nbsp;<span>领取红包20元</span></li>
        					<li><span>134****4232</span>&nbsp;<span>领取红包20元</span></li>
        					<li><span>182****1972</span>&nbsp;<span>领取红包20元</span></li>
        					<li><span>182****1212</span>&nbsp;<span>领取红包20元</span></li>
        					<li><span>133****4712</span>&nbsp;<span>领取红包20元</span></li>
        					<li><span>189****1967</span>&nbsp;<span>领取红包20元</span></li>
                        <?php } ?>
		                </ul>
                    </div>
            	</div>
            </div>
            <!-- 红包达人end -->
            <div class="lj_foot">
	            <div class="lj_gold">
	            	<p class="explain">* 本活动最终解释权归本公司所有</p>
	            </div>
            	 <p class="last_foot">© 2016 如此生活 版权所有 沪ICP备11038000号-2</p>
            </div>
		</div>
	</div>
</body>
<script src="/public/js/rem.js" type="text/javascript" charset="utf-8"></script>
<script src="/public/ext/js/jquery-1.8.3.min.js"></script>
<script src="/public/js/reward/share.js" type="text/javascript"></script>
<script src="/public/js/sdk.2.2.js"></script>
</html>