<!DOCTYPE html>
<html lang="en">
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
	<meta charset="UTF-8">
	<title>领取红包</title>
	<link rel="stylesheet" type="text/css" href="/public/css/reward/share/share.css">
</head>
<body>
	<div class="wrap">
		<div class="header">
			<span><a href="#"><img src="/public/img/reward/invate/lefts.png " class="lefter"></a></span><span>领取红包</span>
		</div>
		<!-- 快上车头部 -->
		<div class="cars">
			<p class="cart"><img src="/public/img/reward/invate/car2.png"></p>
			<p class="autos"><img src="/public/img/reward/invate/car1.png"></p>
			<p class="banners"><img src="/public/img/reward/invate/banner.png"></p>
			<p class="draw">
				<a href="{{ url_member }}/register.html?source={{ source_no | default('') }}&referrer={{ member_id }}" id="register" data-value="{{source_no | default('')}}">
					<img src="/public/img/reward/invate/hits.png">
				</a>
			</p>
		</div>
		<!-- 中间规则部分 -->
		<div class="content">
		<!-- 活动规则 -->
			 <div class="rule">
			 	 <p class="girl"><img src="/public/img/reward/invate/girl.png"></p>
			 	 <p class="pink"><img src="/public/img/reward/invate/violet.png"></p>
			 	  <div class="lj_evnet">
			 	  	  <ol>
			 	  	  	<li>本次活动红包有限，先到先得。</li>
			 	  	  	<li>在“钱包余额”中查看红包。</li>
			 	  	  	<li>钱包仅限于“如此生活”平台购物。</li>
			 	  	  	<li>钱包余额不过期，不可提现，不可作
							其它平台支付使用</li>
			 	  	  </ol>
			 	  </div>
			 	 <p class="rocks"><img src="/public/img/reward/invate/rock.png"></p>
			 	 <p class="firleft"><img src="/public/img/reward/invate/ring.png" class="ring"></p>
			 	 <p class="firright"><img src="/public/img/reward/invate/ring.png" class="ring"></p>
			 </div>
           <!-- 流程 -->
           <div class="lj_flow">
           	    <p class="flows"><img src="/public/img/reward/invate/con2.png"></p>
           	    <p class="firleft"><img src="/public/img/reward/invate/ring.png" class="ring"></p>
			 	<p class="firright"><img src="/public/img/reward/invate/ring.png" class="ring"></p>
           </div>
           <!-- 红包达人 -->
            <div class="person">
            	<div class="personbg main_board">
            		<div class="board_box">
		                <ul>
		                <?php if(!empty($latest) && is_array($latest)){ ?>
							{% for v in latest %}
								<li><span>{{ v['mobile'] }}</span>&nbsp;<span>{{ v['content'] }}</span></li>
							{% endfor %}
		                <?php }else{ ?>
							<li><span>182****4992</span>&nbsp;<span>领取红包20元</span></li>
							<li><span>152****4512</span>&nbsp;<span>领取红包20元</span></li>
							<li><span>134****4232</span>&nbsp;<span>领取红包20元</span></li>
							<li><span>182****1972</span>&nbsp;<span>领取红包20元</span></li>
							<li><span>182****1212</span>&nbsp;<span>领取红包20元</span></li>
							<li><span>133****4712</span>&nbsp;<span>领取红包20元</span></li>
							<li><span>189****1967</span>&nbsp;<span>领取红包20元</span></li>
		                <?php } ?>
		                </ul>
                    </div>
            	</div>
            </div>
            <!-- 红包达人end -->
            <div class="lj_foot">
	            <div class="lj_gold">
	            	<p class="explain">* 本活动最终解释权归本公司所有</p>
	            </div>
            	 <p class="last_foot">© 2016 如此生活 版权所有 沪ICP备11038000号-2</p>
            </div>
		</div>
	</div>
</body>
<script src="/public/js/rem.js" type="text/javascript" charset="utf-8"></script>
<script src="/public/ext/js/jquery-1.8.3.min.js"></script>
<script src="/public/js/reward/share.js" type="text/javascript"></script>
<script src="/public/js/sdk.2.2.js"></script>
</html>