<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
	<title>立即注册</title>
	<link rel="stylesheet" type="text/css" href="/public/css/reward/register/register.css">
</head>
<body>
	<div class="wrap">
		<!--头部设置-->
	   <div class="header">
		    <div class="tobs">
		    	<img src="/public/img/reward/register/ser02.png">
		    </div>
	   </div>
	   <!-- 中间注册部分 -->
	   <div class="lj_content">
	   	   <div class="content_bg">
	   	   	  <p class="tell">
	   	   	  <input type="text" name="" id="inp" placeholder="请输入手机号码">
	   	   	  <span class="notes">*请输入正确的手机号</span>
	   	   	  </p>
	   	   	  <p class="security">
	   	   	  	<input type="text" name="" placeholder="请输入验证码">
	   	   	  	<button id="btn" name="" onclick="settime(this)" >获取验证码</button>
	   	   	  </p>
              <p class="cipher">
              	<input type="password" name="" id="pas" placeholder="请输入密码">
              	<span class="note">*请输入6-15位数字,字母的密码!</span>
              </p>
              <!-- 滑动 -->
                 <div class="slideunlock-wrapper">
			        <input type="hidden" value="" class="slideunlock-lockable"/>
			        <div class="slideunlock-slider">
			            <span class="slideunlock-label" style="color: #fff;"><img src="/public/img/reward/register/ser06.png " class="lj_hes"></span>
			            <span class="slideunlock-lable-tip" style="font-size:0.562963rem; color:#9e9e9e  "></span>
			        </div>
			    </div>
              <!-- 滑动end -->
              <p class="alts">立即注册</p>
	   	   </div>
	   </div>
	   <!-- foot尾部 -->
	   <div class="footer">
	   	    <img src="/public/img/reward/register/ser04.png">
	   </div>
	</div>
</body>
<script src="/public/js/rem.js" type="text/javascript" charset="utf-8"></script>
<script src="/public/ext/js/jquery-1.8.3.min.js"></script>
<script src="/public/js/reward/register/jquery.slideunlock.js" type="text/javascript"></script>
<script src="/public/js/reward/register/register.js" type="text/javascript" charse	t="utf-8"></script>
<script src="/public/js/sdk.2.2.js"></script>
</html>