<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
	<title>注册成功</title>
	<link rel="stylesheet" type="text/css" href="css/success.css">
</head>
<body>
	<div class="wrap">
		<!-- 头部 -->
		<div class="header">
			<img src="img/secess1.png">
		</div>
		<!-- 下载APP -->
			<a href="#">
				<p class="eclipse">下载APP</p>
			</a>
			<p class="hint">
				<span class="snug">温馨提示：</span>
				<span class="packet">已成功领取红包20元</span>
			</p>
			<p class="lj_set">设置支付密码(已领取成功需要设置支付密码)</p>
			<!-- 飞机分享有礼-->
			<p class="lj_share">
				<img src="img/fly1.png">
			</p>
			<div class="step">
				<ul>
					<li><img src="img/seed1.png"></li>
					<li><img src="img/seed2.png"></li>
					<li><img src="img/seed3.png"></li>
				</ul>
			</div>
			<!-- 买买 底部轮播滚动 -->
			<div class="lj_bgfoot">
			    <div class="lj_good">
			    	<img src="img/ssebg.png">
			    </div>
				<div class="lj_setsd">
					<img src="img/buy.png">
				</div>
				<!-- 中间轮播部分begin -->
				  <p class="lj_left"><img src="img/arrows2.png"></p>
				  <p class="lj_right"><img src="img/arrows1.png"></p>
				  <div class="lj_slip">
				  	<ul>
				  		<li>
				  		  <a href="#">
				  			<p class="lj_sell"><img src="img/inphone.png"></p>
				  			<p class="lj_explain">Samsung/三星GalaxyTab3 7.0...</p>
				  			<p class="lj_had">
				  			<img src="img/xing.png" class="lj_xin" >
				  			<span  class="lj_cost">33 + ￥25.80</span>
				  			</p>
				  			</a>
				  		</li>
				  		<li>
				  		  <a href="#">
				  			<p class="lj_sell"><img src="img/inphone.png"></p>
				  			<p class="lj_explain">Samsung/三星GalaxyTab3 7.0...</p>
				  			<p class="lj_had">
				  			<img src="img/xing.png" class="lj_xin" >
				  			<span  class="lj_cost">33 + ￥25.80</span>
				  			</p>
				  			</a>
				  		</li>
				  		<li>
				  		   <a href="#">
				  			<p class="lj_sell"><img src="img/inphone.png"></p>
				  			<p class="lj_explain">Samsung/三星GalaxyTab3 7.0...</p>
				  			<p class="lj_had">
				  			<img src="img/xing.png" class="lj_xin" >
				  			<span  class="lj_cost">33 + ￥25.80</span>
				  			</p>
				  			</a>
				  		</li>
				  		<li>
				  		   <a href="#">
				  			<p class="lj_sell"><img src="img/inphone.png"></p>
				  			<p class="lj_explain">Samsung/三星GalaxyTab3 7.0...</p>
				  			<p class="lj_had">
				  			<img src="img/xing.png" class="lj_xin" >
				  			<span  class="lj_cost">33 + ￥25.80</span>
				  			</p>
				  			</a>
				  		</li>
				  	</ul>
				  </div>
				<!-- 中间轮播部分end -->
				<!-- foot -->
				<div class="lj_foot">
				  <img src="img/sucss2.png">
			    </div> 
			</div>

	</div>
</body>
<script src="js/rem.js" type="text/javascript" charset="utf-8"></script>
<script src="/public/js/sdk.2.2.js"></script>
</html>