

	<head>
		<meta charset="utf-8" />
		<title>开业大典</title>
		<link rel="stylesheet" href="/theme/activity/2016_09_startbusiness/mobile/css/index.css" />
		<link rel="stylesheet" type="text/css" href="/public/mobile/css/foot.css" />
	</head>

	<body>
		<div class="f_start_business">
			<div class="f_start_banner">
				<img src="/theme/activity/2016_09_startbusiness/mobile/img/banner/banner_one.jpg" alt="" align="top" />
				<img src="/theme/activity/2016_09_startbusiness/mobile/img/banner/banner_two.jpg" alt="" align="top" />
				<img src="/theme/activity/2016_09_startbusiness/mobile/img/banner/banner_three.jpg" alt="" align="top" />
				<img src="/theme/activity/2016_09_startbusiness/mobile/img/banner/banner_four.jpg" alt="" align="top" />
				<img src="/theme/activity/2016_09_startbusiness/mobile/img/banner/banner_five.jpg" alt="" align="top" />
				<img src="/theme/activity/2016_09_startbusiness/mobile/img/banner/banner_six.jpg" alt="" align="top" />
				<img src="/theme/activity/2016_09_startbusiness/mobile/img/banner/banner_seven.jpg" alt="" align="top" />
				<img src="/theme/activity/2016_09_startbusiness/mobile/img/banner/banner_eight.jpg" alt="" align="top" />
			</div>
			<div class="f_bg">
				<div id="discount_coupon">
					<ul>
						<li class="first">
							<a href="">
								<img src="/theme/activity/2016_09_startbusiness/mobile/img/discount_coupon/discount_coupon_one.jpg" alt="" />
							</a>
						</li>
						<li>
							<a href="">
								<img src="/theme/activity/2016_09_startbusiness/mobile/img/discount_coupon/discount_coupon_two.jpg" alt="" />
							</a>
						</li>
						<li>
							<a href="">
								<img src="/theme/activity/2016_09_startbusiness/mobile/img/discount_coupon/discount_coupon_three.jpg" alt="" />
							</a>
						</li>

					</ul>
				</div>
				<div id="content">
					<!--热销-->
					<div class="f_hot_sell">
						<img src="/theme/activity/2016_09_startbusiness/mobile/img/hot_sell/hot_sell_banner.png" alt="" />
					</div>
					<div class="hot_style">
						<ul>
							<li>
								<a href="http://item.soolife.cn/m/34943.html">
									<img src="/theme/activity/2016_09_startbusiness/mobile/img/hot_sell/hot_sell_one.png" alt="" data="opengoodsdetail"/>
								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/m/36744.html">
									<img src="/theme/activity/2016_09_startbusiness/mobile/img/hot_sell/hot_sell_two.png" alt="" data="opengoodsdetail"/>
								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/m/27153.html">
									<img src="/theme/activity/2016_09_startbusiness/mobile/img/hot_sell/hot_sell_three.png" alt="" data="opengoodsdetail"/>
								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/m/22413.html">
									<img src="/theme/activity/2016_09_startbusiness/mobile/img/hot_sell/hot_sell_four.png" alt="" data="opengoodsdetail"/>
								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/m/32010.html">
									<img src="/theme/activity/2016_09_startbusiness/mobile/img/hot_sell/hot_sell_five.png" alt="" data="opengoodsdetail"/>
								</a>
							</li>
						</ul>
					</div>
					<!--畅销单品-->
					<div class="f_active_demand">
						<img src="/theme/activity/2016_09_startbusiness/mobile/img/active_demand/active_demand_banner.png" alt="" />
					</div>
					<div class="hot_style">
						<ul>
							<li>
								<a href="http://item.soolife.cn/m/36745.html">
									<img src="/theme/activity/2016_09_startbusiness/mobile/img/active_demand/active_demand_one.png" alt="" data="opengoodsdetail"/>
								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/m/27678.html">
									<img src="/theme/activity/2016_09_startbusiness/mobile/img/active_demand/active_demand_two.png" alt="" data="opengoodsdetail"/>
								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/m/27295.html">
									<img src="/theme/activity/2016_09_startbusiness/mobile/img/active_demand/active_demand_three.png" alt="" data="opengoodsdetail"/>
								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/m/27243.html">
									<img src="/theme/activity/2016_09_startbusiness/mobile/img/active_demand/active_demand_four.png" alt="" data="opengoodsdetail"/>
								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/m/34749.html">
									<img src="/theme/activity/2016_09_startbusiness/mobile/img/active_demand/active_demand_five.png" alt="" data="opengoodsdetail"/>
								</a>
							</li>
						</ul>
					</div>
					<!--精选套餐-->
						<div class="f_combo">
						<img src="/theme/activity/2016_09_startbusiness/mobile/img/combo/combo_banner.png" alt="" />
					</div>
					<div class="hot_style">
						<ul>
							<li>
								<a href="http://item.soolife.cn/m/28917.html">
									<img src="/theme/activity/2016_09_startbusiness/mobile/img/combo/combo_one.png" alt="" data="opengoodsdetail"/>
								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/m/34131.html">
									<img src="/theme/activity/2016_09_startbusiness/mobile/img/combo/combo_two.png" alt="" data="opengoodsdetail"/>
								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/m/34118.html">
									<img src="/theme/activity/2016_09_startbusiness/mobile/img/combo/combo_three.png" alt="" data="opengoodsdetail"/>
								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/m/15454.html">
									<img src="/theme/activity/2016_09_startbusiness/mobile/img/combo/combo_four.png" alt="" data="opengoodsdetail"/>
								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/m/12917.html">
									<img src="/theme/activity/2016_09_startbusiness/mobile/img/combo/combo_five.png" alt="" data="opengoodsdetail"/>
								</a>
							</li>
						</ul>
					</div>
					<!--凑单-->
						<div class="collect">
						<img src="/theme/activity/2016_09_startbusiness/mobile/img/collect/collect_banner.png" alt="" />
					</div>
					<div class="hot_style">
						<ul>
							<li>
								<a href="http://item.soolife.cn/m/27687.html">
									<img src="/theme/activity/2016_09_startbusiness/mobile/img/collect/collect_one.png" alt="" data="opengoodsdetail"/>
								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/m/27310.html">
									<img src="/theme/activity/2016_09_startbusiness/mobile/img/collect/collect_two.png" alt="" data="opengoodsdetail"/>
								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/m/7357.html">
									<img src="/theme/activity/2016_09_startbusiness/mobile/img/collect/collect_three.png" alt=""data="opengoodsdetail" />
								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/m/31777.html">
									<img src="/theme/activity/2016_09_startbusiness/mobile/img/collect/collect_four.png" alt="" data="opengoodsdetail"/>
								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/m/33416.html">
									<img src="/theme/activity/2016_09_startbusiness/mobile/img/collect/collect_five.png" alt="" data="opengoodsdetail"/>
								</a>
							</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</body>

<script src="/public/mobile/js/jquery-3.0.0.min.js"></script>
      <script src="/public/js/sdk.js"></script> 
        <script src="/public/mobile/js/websdk.js"></script>
        