<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>手机网站设计</title>
    <meta name="viewport" content="width=device-width, initial-scale=1,maximum-scale=1,user-scalable=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    {{assets.outputCss('header')}}
</head>
        {{ partial("layouts/inc_header") }}
		{{ content() }}
</body>
	{{assets.outputJs('footer')}}
</html>

