<?php
$css = $this->assets->get('header');
$css -> addCss("public/css/p/view.report.css");

$js  = $this->assets->get('footer');
?>
<div class="xl_new">
    <div class="title">
        <h2>常熟市董浜镇政府领导来如此生活平台考察</h2>
        <h3>就当地有机农副产品与如此生活平台合作事宜进行洽谈</h3>
        <p class="lj_tim">2017-03-29</p>
    </div>
    <ul class="lj_font">
        <li>3月29日，下午4时许，常熟董浜镇政府领导一行来到如此生活总部参观考察。</li>
        <li>常熟董浜镇经过政府的多年布局规划，形成了以3.7万亩蔬菜、1.1万亩水稻、1200亩葡萄为主的种植结构，农业向现代化、科技化、生态化、产业化纵深发展。</li>
        <li>2015年打造现代农业新模式，促进农业增效和产业增值。以曹家桥冷链配送中心、惠健净菜配送公司等农业龙头企业为抓手，以蔬菜专业合作社为主体，发展“公司+合作社+农户”合作模式，积极拓展本地及上海、苏州等周边市场。积极探索农业电子商务和品牌运营，开发“董浜乡情十二品”等特色农产品的市场化运作模式，取得了一定成效。</li>
        <li>此次来如此生活参观考察，旨在为当地特色农副产品寻找新的销售平台，进一步打开市场，实现产业增值。</li>
        <li>
            <div class="lj_new">
                <img alt="如此生活" src="../public/img/report/leadervisit01.png"><br>
                <img alt="如此生活" src="../public/img/report/leadervisit02.png">
                <p>如此生活营销中心总经理孙祥先生、大客户部总监张雪莲女士与镇政府领导进行了深度洽谈</p>
            </div>
        </li>
        <li>
            <div class="lj_new">
                <img alt="如此生活" src="../public/img/report/leadervisit03.png">
                <img alt="如此生活" src="../public/img/report/leadervisit04.png">
                <p>张总监就公司的发展历程及企业文化向各位领导们做了详细介绍， 并陪同参观了公司的文化长廊。 </p>
            </div>
        </li>
        <li style="margin-bottom: 50px">经过长达两个多小时的深度交流，镇政府领导一行主动要求去如此生活线下体验店进行参观。  </li>
        <li>
            <div class="lj_new">
                <img alt="如此生活" src="../public/img/report/leadervisit05.png">
                <img alt="如此生活" src="../public/img/report/leadervisit06.png"><br>
                <img alt="如此生活" src="../public/img/report/leadervisit08.png">
                <img alt="如此生活" src="../public/img/report/leadervisit09.png">
                <p>在体验店，各位领导们饶有兴致的对店内的各个板块都进行了详细考察，并商讨后期有机农产品入住后如何陈列摆放等细节性问题    </p>
            </div>
        </li>
        <li>
            <div class="lj_new">
                <img alt="如此生活" src="../public/img/report/leadervisit.png">
                <p>参观完毕后，双方合影留念 </p>
            </div>
        </li>
        <li style="margin-bottom: 100px">通过对公司理念、模式的了解及对线下体验店的参观考察，各位领导们对如此生活平台的未来一致看好：领导们表示，如此生活在新零售行业走在了市场的前端，对线上线下的布局卓有成效，对公司高层的战略眼光相当欣赏；并表示近期将以政府名义，组织当地农副产品企业相关人员到如此生活平台再次参观考察，届时详细商讨具体合作方案。</li>
    </ul>
</div>