<?php
$css = $this->assets->get('header');
$css -> addCss("public/css/p/view.report.css");

$js  = $this->assets->get('footer');
?>
<div class="lj_rhead">
	<ul>
		<li>
			<a title="如此生活" href="/report/newsspin.html">
				<img alt="如此生活" src="../public/img/report/report(1).png">
				<div class="lj_fot">
					<div class="lj_time">
						<p>2017</p>
						<p>02-21</p>
					</div>
					<div class="lj_title">
						<p>上海家用纺织品行业协会理事...</p>
						<p class="wen">原上海市政协主席、上海市常务副市长、市经团联、市工经联会长、上海纺...</p>
					</div>
				</div>
			</a>
		</li>
		<li>
			<a title="如此生活" href="/report/newscar.html">
				<img alt="如此生活" src="../public/img/report/report(2).png">
				<div class="lj_fot">
					<div class="lj_time">
						<p>2017</p>
						<p>12-17</p>
					</div>
					<div class="lj_title">
						<p>吴存松董事长荣获中国经济杰...</p>
						<p class="wen">在上海交通大学继续教育学院“2017企业家年会”的年度表彰中长吴着全体获...</p>
					</div>
				</div>
			</a>
		</li>
		<li>
			<a title="如此生活" href="/report/newsfirst.html">
				<img alt="如此生活" src="../public/img/report/report(3).png">
				<div class="lj_fot">
					<div class="lj_time">
						<p>2017</p>
						<p>02-10</p>
					</div>
					<div class="lj_title">
						<p>品牌商大会第一财经频道</p>
						<p class="wen">为更好地为会员提供服务，协助会员企业加强互联网电商平台的销售...</p>
					</div>
				</div>
			</a>
		</li>	
	</ul>
</div>