<?php
$css = $this->assets->get('header');
$css -> addCss("public/css/p/view.report.css");

$js  = $this->assets->get('footer');
?>
<div class="lj_new">
	<img alt="如此生活" src="../public/img/report/newsIeather.png">
</div>
<h2>宁波皮革行业协会秘书长走访上海展会及电商平台公司</h2>
<p class="lj_tim">2016-12-07</p>
<div class="lj_font" style="margin-bottom:100px;">
 2016年12月7日，协会秘书长俞万丰赴上海走访了上海汇澳集团和上海进出口商会。协会秘书长就华东（上海）—东欧直销交易平台的相关情况与汇澳董事长刘玉林进行了交流，详细了解了展览方式、费用、当地贸易环境等企业较为关注的事宜。<br><br>
随后，秘书长又走访了鸿惠（上海）信息技术服务有限公司，与该公司董事长吴存松详细交流了“如此生活”电商平台的发展情况，及其运营、品牌合作、未来计划等内容，秘书长表示将与我协会各会员企业进一步宣传并沟通合作事宜。
</div>
