<?php
$css = $this->assets->get('header');
$css -> addCss("public/css/p/view.report.css");

$js  = $this->assets->get('footer');
?>
<div class="lj_new">
	<img alt="如此生活" src="../public/img/report/newsGlory.png">
</div>
<h2>赢战鸡年  共创辉煌</h2>
<p class="lj_tim">2017-01-07</p>
<div class="lj_font" style="margin-bottom:100px;">
 2017年1月7日，如此生活2017年会在佘山月湖会馆盛大举办。如此生活董事长吴存松先生与多位来宾及如此生活全体员工齐聚一堂，共话新春。参加年会的来宾有原上海市副市长刘振元先生、徐州著名慈善企业家吴安君先生、华融集团总经理郭华先生、中国自贸区企业家协会会长庄卫东先生、食品安全专家陈林军老师、徐汇区领导郭德喜主任、绿地集团刘总、上海万达集团黄琳女士、宝龙集团沈向东先生等。
<br><br>
