<?php
$css = $this->assets->get('header');
$css -> addCss("public/css/p/view.report.css");

$js  = $this->assets->get('footer');
?>
<div class="lj_new">
	<img alt="如此生活" src="../public/img/report/newsCommerce.png">
</div>
<h2>如此生活平台参加上海市福清商会庆典活动</h2>
<p class="lj_tim">2017-2-27&nbsp;&nbsp;</p>
<div class="lj_font" style="margin-bottom:100px;">
 如此生活营销中心 CMO 孙祥在上海福清商会招待酒会上发表祝贺词，同时向 500 多位现场的来宾介绍了如此生活平台的商业模式和理念。酒会中大客户部成员和各商 协会领导和企业主进行交流，交换名片，进一步沟通。达到良好的宣传效果。
<br><br>
与上海市福清商会及各地驻上海商会负责人约定 安排时间组织各商会领导及企业 家们集体来如此生活平台体验店和公司总部参观，深入了解，寻求合作共赢。<br><br>
全线开发全国各地商协会结构。为如此生活平台在全国各地的业务拓展打开局面。

