<?php
$css = $this->assets->get('header');
$css -> addCss("public/css/p/view.report.css");

$js  = $this->assets->get('footer');
$js -> addJs("public/js/p/view.video.js");
?>
<div class="lj_video">
	<ul>

		<li data-video="../public/video/video5.mp4">
			<img alt="如此生活" src="../public/img/video/video(7).jpg">
			<div class="lj_op"></div>
			<div class="lj_vtext">上海小童星活动</div>
		</li>
		<li data-video="../public/video/video1.mp4">
			<img alt="如此生活" src="../public/img/video/video(2).png">
			<div class="lj_op"></div>
			<div class="lj_vtext">阳光社区</div>
		</li>
		<li data-video="../public/video/video2.mp4">
			<img alt="如此生活" src="../public/img/video/video(3).png">
			<div class="lj_op"></div>
			<div class="lj_vtext">品牌合作商大会</div>
		</li>
		<li data-video="../public/video/video3.mp4">
			<img alt="如此生活" src="../public/img/video/video(4).png">
			<div class="lj_op"></div>
			<div class="lj_vtext">新零售高峰论坛</div>
		</li>
		<li data-video="../public/video/video4.mp4">
			<img alt="如此生活" src="../public/img/video/video(5).png">
			<div class="lj_op"></div>
			<div class="lj_vtext">如此生活参与华交会</div>
		</li>


	</ul>
</div>
<div class="lj_vmp4">
	<div class="lj_vcenter">
		<div class="lj_vopen">
			<img alt="如此生活" src="../public/img/video/loading.gif" alt="">
		</div>
		<div class="lj_close"><i class="fa fa-times"></i></div>
	</div>	
</div>
