<div class="search_bar clearfix">
	<div class="main-container ">
		<div class="logo left">
			<a class="picture" href="http://www.soolife.cn" target="_blank">如此生活</a>
		</div>
		<div class="control left">
			<div class="box">
				<div class="form-panel">
					<fieldset>
						<div class="input clearfix">
							<div class="s-combobox">
								<div>
									<input type="text" title="请输入搜索文字" class="s-combobox-input" >
								</div>
								<label class="s-combobox-placeholder">打印机</label>
							</div>
							<button>
								搜索
							</button>
						</div>
					</fieldset>
				</div>
				<div class="search-box">
					<!-- 点击显示的搜索的历史记录 -->
				</div>

				<div class="form-tags">
					<ul>
						<li>
							<a href="/search/-*54mb5aW2.html">牛奶</a>
						</li>
						<li>
							<a href="/search/-*5qmE5qaE5rK5.html">橄榄油</a>
						</li>
						<li>
							<a href="/search/-*5YGl6Lqr5Zmo5p2Q.html">健身器材</a>
						</li>
						<li>
							<a href="/search/-*57qi6YWS.html">红酒</a>
						</li>
						<li>
							<a href="/search/-*5oqk6IKk5ZOB.html">护肤品</a>
						</li>
						<li>
							<a href="/search/-*6LGG6LGG6Z6L.html">豆豆鞋</a>
						</li>
						<li>
							<a href="/search/-*6LeR5q2l5py6.html">跑步机</a>
						</li>
						<li>
							<a href="/search/-*56m65rCU5YeA5YyW5Zmo.html">空气净化器</a>
						</li>
					</ul>
				</div>
			</div>
		</div>
		<div class="hotline right">
			<a class="picture" href="http://help.soolife.cn" target="_blank">客服热线 400-068-5151</a>
		</div>
	</div>
</div>