<!-- 底部 -->
<div class="footer clearfix">
	<div class="hr-20 clearfix"></div>
	<div class="helper">
		<div class="nav">
			<ul>
				<li style="width:285px;">
					<dl class="first">
						<dt>新手指南</dt>
						<dd><a href="{{url_help}}/help/help_A_E01.html" target="_blank">免费注册</a></dd>
						<dd><a href="{{url_help}}/help/help_A_E02.html" target="_blank">搜索商品</a></dd>
						<dd><a href="{{url_help}}/help/help_A_E03.html" target="_blank">购买流程</a></dd>
						<dd><a href="{{url_help}}/help/help_A_E05.html" target="_blank">评论晒单</a></dd>
					</dl>
				</li>
				<li style="width:182px;">
					<dl>
						<dt>配送方式</dt>
						<dd><a href="{{url_help}}/help/help_A_B01.html" target="_blank">配送方式</a></dd>
						<dd><a href="{{url_help}}/help/help_A_B02.html" target="_blank">配送时间</a></dd>
					</dl>
				</li>
				<li style="width:180px;">
					<dl>
						<dt>支付方式</dt>
						<dd><a href="{{url_help}}/help/help_A_C01.html" target="_blank">支付宝支付</a></dd>
						<dd><a href="{{url_help}}/help/help_A_C02.html" target="_blank">银联卡支付</a></dd>
					</dl>
				</li>
				<li style="width:165px;">
					<dl>
						<dt>售后服务</dt>
						<dd><a href="{{url_help}}/help/help_A_D01.html" target="_blank">售后政策</a></dd>
						<dd><a href="{{url_help}}/help/help_A_D02.html" target="_blank">退款说明</a></dd>
					</dl>
				</li>
				<li style="width:193px;">
					<dl>
						<dt>招商合作</dt>
						<dd><a target="_blank" href="{{url_sop}}">商家入驻</a></dd>
						<dd><a target="_blank" href="{{url_sop}}">企业会员</a></dd>
					</dl>
				</li>
				<li style="width:160px;">
					<dl>
						<dt>购物指南</dt>
						<dd><a href="{{url_help}}/help/help_A_A03.html" target="_blank">星币说明</a></dd>
						<dd><a href="{{url_help}}/help/help_A_A01.html" target="_blank">交易条款</a></dd>
						<dd><a href="{{url_help}}/help/help_A_A02.html" target="_blank">购物流程</a></dd>
						<dd><a href="{{url_help}}/help/help_A_A08.html" target="_blank">注册流程</a></dd>
						<dd><a href="{{url_help}}/help/help_A_A06.html" target="_blank">常见问题</a></dd>
					</dl>
				</li>
			</ul><div class="clear"></div>
		</div>
	</div>
	<div class="advantage">
		<div class="main-container">
			<a href="{{url_sop}}" title="O2O双线开放" class="s1">O2O双线开放</a>
			<a href="{{url_sop}}" title="免年费返佣金" class="s2">免年费 返佣金</a>
			<a href="{{url_sop}}" title="仓储物流服务" class="s3">仓储物流服务</a>
		</div>
	</div>
	<div class="about">
		<p class="link">
			<a target="_blank" href="{{url_website}}/about/index.html">关于我们 </a> | 
			<a target="_blank" href="{{url_website}}/about/contact.html">联系我们 </a> | 
			<a target="_blank" href="{{url_website}}/about/brand.html">品牌介绍</a> | 
			<a target="_blank" href="{{url_sop}}">商家入驻 </a> | 
			<a target="_blank" href="{{url_website}}/about/links.html">友情链接 </a> | 
			<a target="_blank" href="{{url_website}}/about/law.html">法律声明 </a>
		</p>
		<p class="copyright">
			&copy; 2016-2017 <a href="{{url_website}}">如此生活</a> 版权所有 沪ICP备11038000号-2
		</p>
	</div>
</div>
