<footer class="foot_bottom">
		<ul>
			<li>
				<a href="/index.html">
					<img src="/public/img/icon_home1.png">
					<p class="footer_bottom_color">首页</p>
				</a>
			</li>
			<li>
				<a href="/newcategory.html">
					<img src="/public/img/icon_category.png">
					<p>分类</p>
				</a>
			</li>
			<li>
				<a href="/huilife/index.html">
					<img src="/public/img/icon_coin.png">
					<p>惠生活</p>
				</a>
			</li>
			<li>
				<a href="{{url_order}}/index.html">				
					<div  class="shopcar_n_box">					
						<span class="shopcar_n">
						{{num}}
						</span>
						<img src="/public/img/icon_cart.png">
					</div>
					<p>购物车</p>
				</a>
			</li>
			<li>
				<a href="{{url_member}}/index.html">
					<img src="/public/img/icon_my.png">
					<p>我的</p>
				</a>
			</li>

		</ul>
	</footer>