
		<!-- 底部导航 -->
<footer class="navigation">
	<ul> 
		<li>
			<a href="{{url_m}}/mindex/index.html">
				<img src="../public/img/mindex/Tab_Home@2x.png">
				<p >首页</p>
			</a>
		</li>
		<li>
			<a href="{{url_m}}/newcategory.html">
				<img src="../public/img/mindex/Tab_Menu_pre@2x.png">
				<p class="footer_bottom_color">分类</p>
			</a>
		</li>
		<li>
			<a href="{{url_m}}/huilife/index.html">
				<img src="../public/img/mindex/Tab_Life@2x.png">
				<p>惠生活</p>
			</a>
		</li>
		<li>
			<a href="{{url_order}}/index.html">
				<img src="../public/img/mindex/Tab_Shop@2x.png">
				<p>购物车</p>
				<span class="shopping_car">1</span>
			</a>
		</li>
		<li>
			<a href="{{url_member}}/index.html">
				<img src="../public/img/mindex/Tab_Me@2x.png">
				<p>我的</p> 
			</a>
		</li>
	</ul>
</footer>