
	<head>
		<meta charset="UTF-8">
		<title></title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
		<link rel="stylesheet" href="/theme/activity/2016_09_nopay/mobile/css/index.css" />
				 <link rel="stylesheet" type="text/css" href="/public/mobile/css/foot.css" />

	</head>
	<body>
		<div class="qmd_body">
			<div class="banner">
				<img src="/theme/activity/2016_09_nopay/mobile/img/banner_a.jpg"  align="top"/>
				<img src="/theme/activity/2016_09_nopay/mobile/img/banner_b.jpg"  align="top"/>
			</div>
			<div class="centre">
				<div class="background_yhj">
					<div class="coupon clearfix">
						<div class="left fl" >
							<a href="##"><img src="/theme/activity/2016_09_nopay/mobile/img/juan_a.png" /></a>
						</div> 
						<div class="right fr" id="receive" data-value="0990188201609001">
							<a href="##"><img src="/theme/activity/2016_09_nopay/mobile/img/juan_b.png" /></a>
						</div>
					</div>
				</div>
				<div class="background_relaxation">
					<ul>
						<li>
							<a href="http://item.soolife.cn/m/25433.html">
								<div class="picture">
									<img src="/theme/activity/2016_09_nopay/mobile/img/sp_a.jpg" />
								</div>
								<div class="details">
									<p class="name">头层粒面牛皮皮鞋</p>
									<p class="name">店铺价：399元</p>
									<div class="price clearfix">
										<div class="fl">
											<p class="bazaar">市场价：1199元</p>
										</div>
										<div class="fr lijgo" data="openinstantbuy">
											<img src="/theme/activity/2016_09_nopay/mobile/img/go.jpg" />
										</div>
									</div>
								</div>
							</a>
						</li>
						<li>
							<a href="http://item.soolife.cn/m/25467.html">
								<div class="picture">
									<img src="/theme/activity/2016_09_nopay/mobile/img/sp_b.jpg" />
								</div>
								<div class="details">
									<p class="name">商务休闲男士皮鞋</p>
									<p class="name">店铺价：499元</p>
									<div class="price clearfix">
										<div class="fl">
											<p class="bazaar">市场价：1699元</p>
										</div>
										<div class="fr lijgo" data="openinstantbuy">
											<img src="/theme/activity/2016_09_nopay/mobile/img/go.jpg" />
										</div>
									</div>
								</div>
							</a>
						</li>
						<li>
							<a href="http://item.soolife.cn/m/25528.html">
								<div class="picture">
									<img src="/theme/activity/2016_09_nopay/mobile/img/sp_d.jpg" />
								</div>
								
								<div class="details">
									<p class="name">时尚休闲动感男鞋</p>
									<p class="name">店铺价：429元</p>
									<div class="price clearfix">
										<div class="fl">
											<p class="bazaar">市场价：1699元</p>
										</div>
										<div class="fr lijgo" data="openinstantbuy">
											<img src="/theme/activity/2016_09_nopay/mobile/img/go.jpg" />
										</div>
									</div>
								</div>
							</a>
						</li>
						<li>
							<a href="http://item.soolife.cn/m/25504.html">
								<div class="picture">
									<img src="/theme/activity/2016_09_nopay/mobile/img/sp_c.jpg" />
								</div>
								
								<div class="details">
									<p class="name">时尚休闲男士皮鞋</p>
									<p class="name">店铺价：459元</p>
									<div class="price clearfix">
										<div class="fl">
											<p class="bazaar">市场价：1699元</p>
										</div>
										<div class="fr lijgo" data="openinstantbuy">
											<img src="/theme/activity/2016_09_nopay/mobile/img/go.jpg" />
										</div>
									</div>
								</div>
							</a>
						</li>
						<li>
							<a href="http://item.soolife.cn/m/25472.html">
								<div class="picture">
									<img src="/theme/activity/2016_09_nopay/mobile/img/sp_e.jpg" />
								</div>
								<div class="details">
									<p class="name">现代简约中帮男鞋</p>
									<p class="name">店铺价：529元</p>
									<div class="price clearfix">
										<div class="fl">
											<p class="bazaar">市场价：1599元</p>
										</div>
										<div class="fr lijgo" data="openinstantbuy">
											<img src="/theme/activity/2016_09_nopay/mobile/img/go.jpg" />
										</div>
									</div>
								</div>
							</a>
						</li>
						<li>
							<a href="http://item.soolife.cn/m/25395.html">
								<div class="picture">
									<img src="/theme/activity/2016_09_nopay/mobile/img/sp_f.jpg" />
								</div>
								<div class="details">
									<p class="name">头层牛皮男士皮鞋</p>
									<p class="name">店铺价：399元</p>
									<div class="price clearfix">
										<div class="fl">
											<p class="bazaar">市场价：1099元</p>
										</div>
										<div class="fr lijgo" data="openinstantbuy">
											<img src="/theme/activity/2016_09_nopay/mobile/img/go.jpg" />
										</div>
									</div>
								</div>
							</a>
						</li>
					</ul>
				</div>
				<div class="background_exercise">
					<ul>
						<li>
							<a href="http://item.soolife.cn/m/28596.html">
								<div class="picture">
									<img src="/theme/activity/2016_09_nopay/mobile/img/sp_g.jpg" />
								</div>
								
								<div class="details">
									<p class="name">慢跑运动鞋中性款</p>
									<p class="name">店铺价：119元</p>
									<div class="price clearfix">
										<div class="fl">
											<p class="bazaar">市场价：169元</p>
										</div>
										<div class="fr lijgo" data="openinstantbuy">
											<img src="/theme/activity/2016_09_nopay/mobile/img/go.jpg" />
										</div>
									</div>
								</div>
							</a>
						</li>
						<li>
							<a href="http://item.soolife.cn/m/30707.html">
								<div class="picture">
									<img src="/theme/activity/2016_09_nopay/mobile/img/sp_h.jpg">
								</div>
								
								<div class="details">
									<p class="name">轻质慢跑运动鞋</p>
									<p class="name">店铺价：99元</p>
									<div class="price clearfix">
										<div class="fl">
											<p class="bazaar">市场价：139元</p>
										</div>
										<div class="fr lijgo" data="openinstantbuy">
											<img src="/theme/activity/2016_09_nopay/mobile/img/go.jpg" />
										</div>
									</div>
								</div>
							</a>
						</li>
						<li>
							<a href="http://item.soolife.cn/m/30697.html">
								<div class="picture">
									<img src="/theme/activity/2016_09_nopay/mobile/img/sp_i.jpg">
								</div>
								
								<div class="details">
									<p class="name">轻质慢跑运动鞋</p>
									<p class="name">店铺价：99元</p>
									<div class="price clearfix">
										<div class="fl">
											<p class="bazaar">市场价：139元</p>
										</div>
										<div class="fr lijgo" data="openinstantbuy">
											<img src="/theme/activity/2016_09_nopay/mobile/img/go.jpg" />
										</div>
									</div>
								</div>
							</a>
						</li>
						<li>
							<a href="http://item.soolife.cn/m/28625.html">
								<div class="picture">
									<img src="/theme/activity/2016_09_nopay/mobile/img/sp_j.jpg">
								</div>
								
								<div class="details">
									<p class="name">慢跑运动鞋中性款</p>
									<p class="name">店铺价：119元</p>
									<div class="price clearfix">
										<div class="fl">
											<p class="bazaar">市场价：169元</p>
										</div>
										<div class="fr lijgo" data="openinstantbuy">
											<img src="/theme/activity/2016_09_nopay/mobile/img/go.jpg" />
										</div>
									</div>
								</div>
							</a>
						</li>
						<li>
							<a href="http://item.soolife.cn/m/31934.html">
								<div class="picture">
									<img src="/theme/activity/2016_09_nopay/mobile/img/sp_l.jpg">
								</div>
								
								<div class="details">
									<p class="name">慢跑运动鞋中性款</p>
									<p class="name">店铺价：119元</p>
									<div class="price clearfix">
										<div class="fl">
											<p class="bazaar">市场价：169元</p>
										</div>
										<div class="fr lijgo" data="openinstantbuy">
											<img src="/theme/activity/2016_09_nopay/mobile/img/go.jpg" />
										</div>
									</div>
								</div>
							</a>
						</li>
						<li>
							<a href="http://item.soolife.cn/m/28597.html">
								<div class="picture">
									<img src="/theme/activity/2016_09_nopay/mobile/img/sp_i.jpg">
								</div>
								
								<div class="details">
									<p class="name">超轻慢跑运动鞋</p>
									<p class="name">店铺价：99元</p>
									<div class="price clearfix">
										<div class="fl">
											<p class="bazaar">市场价：139元</p>
										</div>
										<div class="fr lijgo" data="openinstantbuy">
											<img src="/theme/activity/2016_09_nopay/mobile/img/go.jpg" />
										</div>
									</div>
								</div>
							</a>
						</li>
					</ul>
				</div>
			</div>
		</div>
		
	</body>

<script src="/public/mobile/js/jquery-1.11.3.min.js" type="text/javascript" charset="utf-8"></script>

<script src="/public/mobile/js/receive.js" type="text/javascript" charset="utf-8"></script>


