<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>如此生活|关于我们</title>
	<meta name="viewport" content="width=device-width, initial-scale=1,maximum-scale=1,user-scalable=no">
	<meta name="apple-mobile-web-app-capable" content="yes">
	<meta name="apple-mobile-web-app-status-bar-style" content="black">
	<link rel="stylesheet" type="text/css" href="/public/css/setting/aboutus.css"/>
</head>
<body>
	<div class="wrap">
		<div class="header" id="header">
			<span onclick="window.history.go(-1)">
				<img src="/public/img/brandhui/xingxingsha_back@2x.png " class="lefter">
			</span>
			<span class="lj_srt">关于我们</span> 
		</div>
		<div class="void"></div>
		<div class="logo">
			<img src="/public/img/setting/mine_about_soolife@2x.png">
		</div>
		<div class="code">
			<img src="/public/img/setting/b_erweima@2x.png">
		</div>
		<p class="firend">您的朋友可以扫描二维码，下载如此生活客户端哦～</p>
		<div class="content">
			<ul>
				<li>
					<span>Version 2.1.0</span> 
				</li>
				<!-- <li>
					<span>给我评价</span>
					<span class="enter2">
						<img src="/public/img/setting/mine_xiayiye@2x.png">
					</span>
				</li> -->
			</ul>
		</div>
		<div class="versions">©如此生活 版本所有泸ICP备11038000号－2</div>
	</div>
</body>
<script src="/public/js/rem.js"></script> 
<script src="/public/ext/js/jquery-1.8.3.min.js"></script>
</html>