<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>如此生活|修改昵称</title>
	<meta name="viewport" content="width=device-width, initial-scale=1,maximum-scale=1,user-scalable=no">
	<meta name="apple-mobile-web-app-capable" content="yes">
	<meta name="apple-mobile-web-app-status-bar-style" content="black">
	<link rel="stylesheet" type="text/css" href="/public/css/setting/amendname.css"/>
</head>
<body>
	<div class="wrap">
			<div class="header" id="header">
				<span onclick="window.history.go(-1)">
					<img src="/public/img/brandhui/xingxingsha_back@2x.png " class="lefter">
				</span>
				<span class="lj_srt">修改昵称</span> 
			</div>
			<div class="void"></div>
			<div class="name">
				<input type="text" name="nickname" placeholder="请输入您要修改的昵称">
			</div>
			<p class="rule">&nbsp;&nbsp;（可使用中英文、数字和下划线，字数在2-20个字符）</p>
			<div class="finish">完成</div>

			<div id="alert_mark"></div>
	</div>
</body>
<script src="/public/js/rem.js"></script> 
<script src="/public/ext/js/jquery-1.8.3.min.js"></script>
<script type="text/javascript" src="/public/js/setting/amendname.js"></script>
</html>