<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>如此生活|绑定手机</title>
	<meta name="viewport" content="width=device-width, initial-scale=1,maximum-scale=1,user-scalable=no">
	<meta name="apple-mobile-web-app-capable" content="yes">
	<meta name="apple-mobile-web-app-status-bar-style" content="black">
	<link rel="stylesheet" type="text/css" href="/public/css/setting/contextiphone.css"/>
</head>
<body>
	<div class="wrap">
			<div class="header" id="header">
				<span onclick="window.history.go(-1)">
					<img src="/public/img/brandhui/xingxingsha_back@2x.png " class="lefter">
				</span>
				<span class="lj_srt">绑定手机</span> 
			</div>
			<div class="void"></div>
			<div class="bound"> 
				<div class="iphone">
					<div class="iphones">
						<span>手机号:</span>
						<input id="number" class="iphone1" type="text" name="iphone"  value="{{result['phone']}}" >
						<input class="iphonef" type="hidden" name="" value="{{result['phone']}}">
					</div>
				</div>
				<div class="iphone  ">  
					<div class="iphones">
						<input id="code" class="code_one" type="text" name="vcode" maxlength="6" placeholder="验证码"> 
						<div id="btn" name="" >获取验证码</div>
						<div id="s_box" ></div>
					</div>
				</div>
				<div class="text" id="next">下一步</div>
			</div>
			<div class="bound2"> 
				<div class="iphone">
					<div class="iphones">
						<span>手机号:</span>
						<input id="number" class="number2" type="text" name="iphone" maxlength="11" placeholder="请输入新手机号" >
					</div>
				</div>
				<div class="iphone  ">  
					<div class="iphones">
						<input id="code" class="code_two" type="text" name="vcode" maxlength="6" placeholder="请输入验证码">
						<div id="btn" class="btn" name="" >获取验证码</div>
						<div id="s_box" class="s_box" ></div>
					</div>
				</div>
				<div class="text" id="text2">绑定</div>
			</div>
			<div id="alert_mark"></div>
	</div>
	
</body>
<script src="/public/js/rem.js"></script> 
<script src="/public/ext/js/jquery-1.8.3.min.js"></script>
<script type="text/javascript" src="/public/js/setting/contextiphone.js"></script>
</html>