<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>如此生活|意见反馈</title>
	<meta name="viewport" content="width=device-width, initial-scale=1,maximum-scale=1,user-scalable=no">
	<meta name="apple-mobile-web-app-capable" content="yes">
	<meta name="apple-mobile-web-app-status-bar-style" content="black">
	<link rel="stylesheet" type="text/css" href="/public/css/setting/opinion.css"/>
</head>
<body>
	<div class="wrap">
		<div class="header" id="header">
			<span onclick="window.history.go(-1)">
				<img src="/public/img/brandhui/xingxingsha_back@2x.png " class="lefter">
			</span>
			<span class="lj_srt">意见反馈</span> 
			<span class="submit">提交</span>
		</div>
		<div class="void"></div>
		<div class="genre">
			<span class="feedback">反馈类型</span>
			<span class="enter2">
				<span class="effects" >功能建议</span>
				<img src="/public/img/setting/mine_xiayiye@2x.png" class="li_suggest">
			</span>
		</div>
		<div class="big">
			<textarea class="back" placeholder="请输入你对本产品的意见，我们将不断优化，如此生活，如你所愿！"></textarea>
		</div>
		<div class="number"><input type="text" name="" placeholder="请输入您的手机号／邮箱（选填）"></div>

	</div>
		<div class="effect">
			 <div class="select">
			 	 <p class="type_sle">请选择反馈类型</p>
			 	 <div class="page">
			 	 		<ul>
			 	 			<li>
			 	 				 <img class="notyet" data-s="功能建议" data-value="11"  src="/public/img/shopseek/mine_zhifu_d_yuan@2x.png">
			 	 				 <input type="hidden" name="xiaxi" value="功能建议">  
			 	 				 <img class="yet" src="/public/img/setting/Group 2@2x.png">
			 	 			</li>
			 	 			<li>
			 	 				 <img class="notyet" data-s="页面建议" data-value="12"  src="/public/img/setting/mine_zhifu_yuan@2x.png">  
			 	 				  
			 	 				 <img class="yet" src="/public/img/setting/Group 2@2x.png">
			 	 			</li>
			 	 			<li>
			 	 				 <img class="notyet" data-s="其他建议"  data-value="13" src="/public/img/setting/mine_zhifu_yuan@2x.png"> 
			 	 				 <img class="yet" src="/public/img/setting/Group 2@2x.png">
			 	 			</li>
			 	 		</ul> 
			 	 		<ul>
			 	 			<li>功能建议</li>
			 	 			<li>页面建议</li>
			 	 			<li>其它建议</li>
			 	 		</ul>
			 	 </div>
			 	 <div class="lj_sure">确定</div>
			 </div>
		</div>
		<div id="alert_mark"></div>
</body>
<script src="/public/js/rem.js"></script> 
<script src="/public/ext/js/jquery-1.8.3.min.js"></script>
<script src="/public/js/setting/opinion.js"></script>
</html>