<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>如此生活|修改密码</title>
	<meta name="viewport" content="width=device-width, initial-scale=1,maximum-scale=1,user-scalable=no">
	<meta name="apple-mobile-web-app-capable" content="yes">
	<meta name="apple-mobile-web-app-status-bar-style" content="black">
	<link rel="stylesheet" type="text/css" href="/public/css/setting/password.css"/>
</head>
<body>
	<div class="wrap">
			<div class="header" id="header">
				<span onclick="window.history.go(-1)">
					<img src="/public/img/brandhui/xingxingsha_back@2x.png " class="lefter">
				</span>
				<span class="lj_srt">修改密码</span> 
			</div>
			<div class="void"></div>
			<div class="content">
				<ul>
					<li>
						<span>登录密码</span>
						<a href="/setting/loginpassword.html">
							<span class="enter2">
								<img src="/public/img/setting/mine_xiayiye@2x.png">
							</span>
						</a>
					</li>
					<li>
						<span>支付密码</span>
						<a href="/setting/paypassword.html">
							<span class="enter2">
								<img src="/public/img/setting/mine_xiayiye@2x.png">
							</span> 
						</a>
						
					</li>
					<!-- <li>
						<span>所在地区</span>
						<span class="enter2">
							<img src="/public/img/setting/mine_xiayiye@2x.png">
						</span> 
					</li> -->
				</ul>
			</div>
	</div>
</body>
<script src="/public/js/rem.js"></script> 
<script src="/public/ext/js/jquery-1.8.3.min.js"></script>
</html>