<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>如此生活|修改支付密码</title>
	<meta name="viewport" content="width=device-width, initial-scale=1,maximum-scale=1,user-scalable=no">
	<meta name="apple-mobile-web-app-capable" content="yes">
	    <meta name="format-detection" content="telephone=no" />
	<meta name="apple-mobile-web-app-status-bar-style" content="black">
	<link rel="stylesheet" type="text/css" href="/public/css/setting/paypassword.css"/>
</head>
<body>
	<div class="wrap">
		<div class="header" id="header">
			<span onclick="window.history.go(-1)">
				<img src="/public/img/brandhui/xingxingsha_back@2x.png " class="lefter">
			</span>
			<span class="lj_srt">修改支付密码</span> 
		</div>
		<div class="void" type="{{type}}"></div>
		<div class="bound"> 
			<div class="iphoned">
				<div class="iphoneds">
					<span>账号:</span>
					<span class="number">{{result['phone']}}</span> 
					<input class="numberf" type="hidden" name="" value="{{result['phone']}}">
				</div>
			</div>
			<div class="bigiphone">
				<div class="iphone">  
					<div class="iphones">
						<input id="code" type="text" name="vcode" maxlength="6" placeholder="验证码" autoComplete='off'>
						<div id="btn" name="" >获取验证码</div>
						<div id="s_box" ></div>
					</div>
				</div>
				<div class="iphone">
					<div class="iphones"> 
						<input id="number1" type="password" name="iphone" maxlength="11" placeholder="请输入新的支付密码" >
					</div>
				</div>
				<div class="iphone">
					<div class="iphones"> 
						<input id="number2" type="password" name="iphone" maxlength="11" placeholder="请确认密码" >
					</div>
				</div>
			</div> 
			<p class="der">两次密码输入不一致，请重新输入</p>
			<div class="text">提交</div>
		</div>
	</div>
	<div id="alert_mark"></div>
</body>
<script src="/public/js/rem.js"></script> 
<script src="/public/ext/js/jquery-1.8.3.min.js"></script>
<script type="text/javascript" src="/public/js/setting/paypassword.js"></script>
</html>