<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>如此生活|充值钱包</title>
	<meta name="viewport" content="width=device-width, initial-scale=1,maximum-scale=1,user-scalable=no">
	<meta name="apple-mobile-web-app-capable" content="yes">
	<meta name="apple-mobile-web-app-status-bar-style" content="black">
	<link rel="stylesheet" type="text/css" href="/public/css/setting/stockpilewallet.css"/>
</head>
<body>
	<div class="wrap">
		<div class="header" id="header">
			<span onclick="window.history.go(-1)">
				<img src="/public/img/brandhui/xingxingsha_back@2x.png " class="lefter">
			</span>
			<span class="lj_srt">充值钱包</span> 
		</div>
		<div class="void"></div>
		<div class="bound"> 
			<div class="iphoned">
				<div class="iphoneds">
					<span>现金余额:</span>
					<span class="number">2200.00元</span> 
					<input class="numberf" type="hidden" name="" value="2000.00">
				</div>
			</div>
			<div class="bigiphone">
				<!-- <div class="iphone">  
					<div class="iphones">
						<input id="code" type="text" name="vcode" maxlength="6" placeholder="验证码" autoComplete='off'>
						<div id="btn" name="" >获取验证码</div>
						<div id="s_box" ></div>
					</div>
				</div> -->
				<div class="iphone">
					<div class="iphones"> 
						<span>充值余额</span>
						<input id="number1" type="text" name="iphone" autoComplete='off'>
					</div>
				</div>
				<div class="iphone">
					<div class="iphones">
						<span>支付密码</span> 
						<input id="number2" type="password" name="iphone" >
					</div>
				</div>
			</div> 
			<!-- <p class="der">两次密码输入不一致，请重新输入</p> -->
			<div class="text">充值</div>
		</div>
	</div>
</body>
<script src="/public/js/rem.js"></script> 
<script src="/public/ext/js/jquery-1.8.3.min.js"></script>
<script type="text/javascript" src="/public/js/setting/stockpilewallet.js"></script>
</html>