<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>如此生活|签到领星币</title>
	<meta name="viewport" content="width=device-width, initial-scale=1,maximum-scale=1,user-scalable=0">
	<meta name="apple-mobile-web-app-capable" content="yes">
	<meta name="apple-mobile-web-app-status-bar-style" content="black">	
	<link rel="stylesheet" type="text/css" href="/public/ext/css/soo.m.ui.css"/>  
	<link rel="stylesheet" type="text/css" href="/public/css/expstore/expresult.css"/>
	<script src="/public/js/rem2.js"></script> 
</head>
<body>
<div id="filter">
	 <!-- 头部 -->
	<div id="head">
		<div id="head-left"><img src="/public/img/newcategory/Group22Copy2.png" alt=""></div>
		<div id="head-right" > </div>
		<div id="head-center" class="between">签到领星币</div>
	</div>
	<div id="top_place"></div> 
	<!-- 失败	 -->
	<p class="title">感谢您光临如此生活（**店）</p>
	<img class="imghead" src="/public/img/exp/result (1).png">
	<p class="state">领取失败</p>
	<p class="message">很抱歉，您当天已经领取过星币了。</p>
	<!-- 失败	 -->
	<p class="state">领取失败</p>
	<p class="message">很抱歉，您扫的二维码已过期。</p>
	<!-- 成功 -->
	<p class="title">感谢您光临如此生活（**店）</p>
	<img class="imghead" src="/public/img/exp/result (2).png">
	<p class="state">领取成功</p>
	<p class="message">恭喜您获得**个星币！</p> 
 	<!-- 为您推荐 --> 
	<div class="recommend">
		<div class="rtitle"><span>为您推荐</span></div>
	</div> 
	<div class="blockstyle">  	
 		{% for d in guesslike %}	
 		<div class="item bg-white margin-b">
 			<div class="img_box float-l">
 				<a href="{{url_goods}}/m/{{d['act_price']}}.html"><img src="{{d['logo']}}"></a>
 				<!-- <p class="tag">海外精品</p>   -->
 			</div>
 			<div class="wen_box float-l">
 				<p class="name">{{d['sku_name']}}</p>
 				 <!-- <p class="smalltag"><span>海外精品</span></p>  -->
 				<!-- <p class="sales">销量:132</p> -->
 				<p class="piece">￥{{d['act_price']}}</p> 
 			</div>
 		</div> 
 		{% endfor %}  	 
 	</div>


</div>

</body>
</html>
<script src="/public/ext/js/jquery-1.8.3.min.js"></script>   