<head>
	<meta charset="UTF-8">
	<title></title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
	<link rel="stylesheet" href="/theme/activity/2016_09_DoubleNinthFestival/mobile/css/index.css" />
	<link rel="stylesheet" type="text/css" href="/public/mobile/css/foot.css" />
</head>
<body>
	<div class="festival">
		<div class="banner_a">
			<img src="/theme/activity/2016_09_DoubleNinthFestival/mobile/img/banner.jpg" />
		</div>
		<div class="besatisfied">
			<div class="title">
				<img src="/theme/activity/2016_09_DoubleNinthFestival/mobile/img/title_a.jpg" />
			</div>
			<div class="bj_a">
				<div class="centre">
					<ul>
						<li>
							<a href="http://item.soolife.cn/m/29554.html"> <img src="/theme/activity/2016_09_DoubleNinthFestival/mobile/img/sp_a.jpg" data="opengoodsdetail"/>
							<div class="particulars">
								<p class="name">
									洁斯家食品保鲜膜
								</p>
								<p class="result">
									多种用途  方便易用
								</p>
								<img src="/theme/activity/2016_09_DoubleNinthFestival/mobile/img/jg_a.jpg" data="opengoodsdetail"/>
								<p class="price_y">
									原价：12.8元
								</p>
							</div> </a>
						</li>
						<li>
							<a href="http://item.soolife.cn/m/34109.html"> <img src="/theme/activity/2016_09_DoubleNinthFestival/mobile/img/sp_b.jpg" data="opengoodsdetail"/>
							<div class="particulars">
								<p class="name">
									八角直身杯
								</p>
								<p class="result">
									源自法国  质量保证
								</p>
								<img src="/theme/activity/2016_09_DoubleNinthFestival/mobile/img/jg_a.jpg"  data="opengoodsdetail"/>
								<p class="price_y">
									原价：11.9元
								</p>
							</div> </a>
						</li>
						<li>
							<a href="http://item.soolife.cn/m/29432.html"> <img src="/theme/activity/2016_09_DoubleNinthFestival/mobile/img/sp_c.jpg" data="opengoodsdetail"/>
							<div class="particulars">
								<p class="name">
									湘妹子 茶油腐乳
								</p>
								<p class="result">
									湘味难挡  醇香可口
								</p>
								<img src="/theme/activity/2016_09_DoubleNinthFestival/mobile/img/jg_a.jpg" data="opengoodsdetail"/>
								<p class="price_y">
									原价：10.5元
								</p>
							</div> </a>
						</li>
						<li>
							<a href="http://item.soolife.cn/m/29454.html"> <img src="/theme/activity/2016_09_DoubleNinthFestival/mobile/img/sp_d.jpg" data="opengoodsdetail"/>
							<div class="particulars">
								<p class="name">
									王致和 韭花酱
								</p>
								<p class="result">
									安全健康  营养丰富
								</p>
								<img src="/theme/activity/2016_09_DoubleNinthFestival/mobile/img/jg_a.jpg" data="opengoodsdetail"/>
								<p class="price_y">
									原价：10.5元
								</p>
							</div> </a>
						</li>
					</ul>
				</div>
			</div>

		</div>
		<div class="emboitement">
			<div class="title">
				<img src="/theme/activity/2016_09_DoubleNinthFestival/mobile/img/title_b.jpg" />
			</div>
			<div class="bj_b">
				<div class="centre">
					<ul>
						<li>
							<a href="http://item.soolife.cn/m/12966.html"> <img src="/theme/activity/2016_09_DoubleNinthFestival/mobile/img/sp_e.jpg" data="opengoodsdetail"/>
							<div class="particulars">
								<p class="name">
									去屑洗护套装
								</p>
								<p class="result">
									洗护搭配  效果更佳
								</p>
								<img src="/theme/activity/2016_09_DoubleNinthFestival/mobile/img/jg_b.jpg" data="opengoodsdetail"/>
								<p class="price_y">
									原价：368元
								</p>
							</div> </a>
						</li>
						<li>
							<a href="http://item.soolife.cn/m/15455.html"> <img src="/theme/activity/2016_09_DoubleNinthFestival/mobile/img/sp_f.jpg" data="opengoodsdetail"/>
							<div class="particulars">
								<p class="name">
									菁漾全然补水组合
								</p>
								<p class="result">
									水润滋养  亮白肌肤
								</p>
								<img src="/theme/activity/2016_09_DoubleNinthFestival/mobile/img/jg_c.jpg" data="opengoodsdetail"/>
								<p class="price_y">
									原价：528
								</p>
							</div> </a>
						</li>
						<li>
							<a href="http://item.soolife.cn/m/29211.html"> <img src="/theme/activity/2016_09_DoubleNinthFestival/mobile/img/sp_g.jpg" data="opengoodsdetail"/>
							<div class="particulars">
								<p class="name">
									皇马仕保湿礼盒
								</p>
								<p class="result">
									酷爽洁净  劲能保湿
								</p>
								<img src="/theme/activity/2016_09_DoubleNinthFestival/mobile/img/jg_d.jpg" data="opengoodsdetail"/>
								<p class="price_y">
									原价：170
								</p>
							</div> </a>
						</li>
						<li>
							<a href="http://item.soolife.cn/m/28036.html"> <img src="/theme/activity/2016_09_DoubleNinthFestival/mobile/img/sp_h.jpg" data="opengoodsdetail"/>
							<div class="particulars">
								<p class="name">
									亚麻籽油礼盒装
								</p>
								<p class="result">
									厂家直供  亲民价格
								</p>
								<img src="/theme/activity/2016_09_DoubleNinthFestival/mobile/img/jg_e.jpg"  data="opengoodsdetail"/>
								<p class="price_y">
									原价：170
								</p>
							</div> </a>
						</li>
					</ul>
				</div>
			</div>
		</div>
		<div class="burglary">
			<div class="title">
				<img src="/theme/activity/2016_09_DoubleNinthFestival/mobile/img/title_c.jpg" />
			</div>
			<div class="bj_c">
				<div class="centre">
					<ul>
						<li>
							<a href="http://item.soolife.cn/m/28329.html"> <img src="/theme/activity/2016_09_DoubleNinthFestival/mobile/img/sp_i.jpg" data="opengoodsdetail"/>
							<div class="particulars">
								<p class="name">
									恒大兴安香米一号
								</p>
								<p class="result">
									莹润饱满  颗粒分明
								</p>
								<img src="/theme/activity/2016_09_DoubleNinthFestival/mobile/img/jg_f.jpg" data="opengoodsdetail"/>
								<p class="price_y">
									原价：90
								</p>
							</div> </a>
						</li>
						<li>
							<a href="http://item.soolife.cn/m/33988.html"> <img src="/theme/activity/2016_09_DoubleNinthFestival/mobile/img/sp_j.jpg" data="opengoodsdetail"/>
							<div class="particulars">
								<p class="name">
									美之扣碎菜器
								</p>
								<p class="result">
									原汁原味  品质升级
								</p>
								<img src="/theme/activity/2016_09_DoubleNinthFestival/mobile/img/jg_h.jpg" data="opengoodsdetail"/>
								<p class="price_y">
									原价：100
								</p>
							</div> </a>
						</li>
						<li>
							<a href="http://item.soolife.cn/m/13467.html"> <img src="/theme/activity/2016_09_DoubleNinthFestival/mobile/img/sp_o.jpg" data="opengoodsdetail"/>
							<div class="particulars">
								<p class="name">
									无铅陶瓷泡茶壶
								</p>
								<p class="result">
									层层堆叠  丝丝暖意
								</p>
								<img src="/theme/activity/2016_09_DoubleNinthFestival/mobile/img/jg_i.jpg" data="opengoodsdetail"/>
								<p class="price_y">
									原价：269
								</p>
							</div> </a>
						</li>
						<li>
							<a href="http://item.soolife.cn/m/27234.html"> <img src="/theme/activity/2016_09_DoubleNinthFestival/mobile/img/sp_k.jpg" data="opengoodsdetail"/>
							<div class="particulars">
								<p class="name">
									素馨花补水面颈膜
								</p>
								<p class="result">
									卓越品质  源自天然
								</p>
								<img src="/theme/activity/2016_09_DoubleNinthFestival/mobile/img/jg_j.jpg" data="opengoodsdetail"/>
								<p class="price_y">
									原价：128
								</p>
							</div> </a>
						</li>
					</ul>
				</div>
			</div>
		</div>
		<div class="choice">
			<div class="title">
				<img src="/theme/activity/2016_09_DoubleNinthFestival/mobile/img/title_d.jpg"
				</div>
				<div class="bj_d">
				<div class="centre">
				<ul>
				<li>
				<a href="http://item.soolife.cn/m/11139.html">
				<img src="/theme/activity/2016_09_DoubleNinthFestival/mobile/img/sp_q.jpg" data="opengoodsdetail"/>
				<div class="particulars">
				<p class="name">滚轮按摩足浴盆 </p>
				<p class="result">足浴同时  尽享生活</p>
				<img src="/theme/activity/2016_09_DoubleNinthFestival/mobile/img/jg_o.jpg" data="opengoodsdetail"/>
				<p class="price_y">原价：588</p>
				</div>
				</a>
				</li>
				<li>
				<a href="http://item.soolife.cn/m/11111.html">
				<img src="/theme/activity/2016_09_DoubleNinthFestival/mobile/img/sp_p.jpg" data="opengoodsdetail"/>
				<div class="particulars">
				<p class="name">超强电动按摩捶 </p>
				<p class="result">深度按摩  强劲机芯</p>
				<img src="/theme/activity/2016_09_DoubleNinthFestival/mobile/img/jg_k.jpg" data="opengoodsdetail"/>
				<p class="price_y">原价：588</p>
				</div>
				</a>
				</li>
				<li>
				<a href="http://item.soolife.cn/m/11143.html">
				<img src="/theme/activity/2016_09_DoubleNinthFestival/mobile/img/sp_s.jpg" data="opengoodsdetail"/>
				<div class="particulars">
				<p class="name">深桶多功能足浴盆  </p>
				<p class="result">循环加热  立体按摩</p>
				<img src="/theme/activity/2016_09_DoubleNinthFestival/mobile/img/jg_p.jpg" data="opengoodsdetail"/>
				<p class="price_y">原价：899</p>
				</div>
				</a>
				</li>
				<li>
				<a href="http://item.soolife.cn/m/5280.html">
				<img src="/theme/activity/2016_09_DoubleNinthFestival/mobile/img/sp_r.jpg" data="opengoodsdetail"/>
				<div class="particulars">
				<p class="name">披肩腰带按摩器</p>
				<p class="result">外观时尚  使用方便</p>
				<img src="/theme/activity/2016_09_DoubleNinthFestival/mobile/img/jg_m.jpg" data="opengoodsdetail"/>
				<p class="price_y">原价：346</p>
				</div>
				</a>
				</li>
				</ul>
				</div>
				</div>
				</div>
				<div class="gift">
				<div class="title">
				<img src="/theme/activity/2016_09_DoubleNinthFestival/mobile/img/title_e.jpg" />
				</div>
				<div class="bj_e">
				<div class="centre">
					<ul>
						<li>
							<a href="http://item.soolife.cn/m/35921.html"> <img src="/theme/activity/2016_09_DoubleNinthFestival/mobile/img/sp_t.jpg" data="opengoodsdetail"/>
							<div class="particulars">
								<p class="name">
									至洁消毒洗衣液
								</p>
								<p class="result">
									去污消毒  一步完成
								</p>
								<img src="/theme/activity/2016_09_DoubleNinthFestival/mobile/img/jg_s.jpg" data="opengoodsdetail"/>
								<p class="price_y">
									原价：198
								</p>
							</div> </a>
						</li>
						<li>
							<a href="http://item.soolife.cn/m/27289.html"> <img src="/theme/activity/2016_09_DoubleNinthFestival/mobile/img/sp_v.jpg" data="opengoodsdetail"/>
							<div class="particulars">
								<p class="name">
									2080 青龈茶牙膏
								</p>
								<p class="result">
									韩国品牌  值得信赖
								</p>
								<img src="/theme/activity/2016_09_DoubleNinthFestival/mobile/img/jg_r.jpg" data="opengoodsdetail"/>
								<p class="price_y">
									原价：21
								</p>
							</div> </a>
						</li>
						<li>
							<a href="http://item.soolife.cn/m/25767.html"> <img src="/theme/activity/2016_09_DoubleNinthFestival/mobile/img/sp_l.jpg" data="opengoodsdetail"/>
							<div class="particulars">
								<p class="name">
									熊屋牌有机蜜
								</p>
								<p class="result">
									蓝瓶品质  蜂味十足
								</p>
								<img src="/theme/activity/2016_09_DoubleNinthFestival/mobile/img/jg_g.jpg" data="opengoodsdetail"/>
								<p class="price_y">
									原价：100
								</p>
							</div> </a>
						</li>
						<li>
							<a href="http://item.soolife.cn/m/28034.html"> <img src="/theme/activity/2016_09_DoubleNinthFestival/mobile/img/sp_y.jpg" data="opengoodsdetail"/>
							<div class="particulars">
								<p class="name">
									亚麻籽油礼盒装
								</p>
								<p class="result">
									天然洁净  安全享用
								</p>
								<img src="/theme/activity/2016_09_DoubleNinthFestival/mobile/img/jg_v.jpg" data="opengoodsdetail"/>
								<p class="price_y">
									原价：98
								</p>
							</div> </a>
						</li>
					</ul>
				</div>
			</div>
			<div class="dibu">
				<img src="/theme/activity/2016_09_DoubleNinthFestival/mobile/img/dibu.jpg" />
			</div>
		</div>
	</div>
</body>

<script src="/public/mobile/js/jquery-3.0.0.min.js"></script>
<script src="/public/js/sdk.js"></script>
<script src="/public/mobile/js/websdk.js"></script>
