<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>如此生活|星范儿</title>
	<meta name="viewport" content="width=device-width, initial-scale=1,maximum-scale=1,user-scalable=no">
	<meta name="apple-mobile-web-app-capable" content="yes">
	<meta name="apple-mobile-web-app-status-bar-style" content="black">
	<!-- <link rel="stylesheet" type="text/css" href="/public/css/mui.min.css"/> -->
	<link rel="stylesheet" type="text/css" href="/public/css/starstyle.css"/>
</head>
<body class="lcy_starstyle">
<!-- 头部 -->
	<header class="head">
		<div class="head_box">
			<div class="back_img" onclick="javascript:history.go(-1)"></div>
			<span>星范儿</span>
		</div>
	</header>
	<!-- banner1 -->
	<div class="banner">
	     <?php if(!empty($data['app.star.main']['children']['app.star.main.banner']['items'])) { ?>
		 {% for d in data['app.star.main']['children']['app.star.main.banner']['items'] %}
		 <a href="{{d['mobile_link']}}"><img src="{{d['picture']}}" alt=""></a>
		 <?php break; ?>
		 {% endfor %}
         <?php } ?>
	</div>
	<!-- 快速分类 -->
	<div class="classify_box">
		<div class="classify">
			 <?php if(!empty($data['app.star.main']['children']['app.star.main.category01']['items'])) { ?>
			 {% for d in data['app.star.main']['children']['app.star.main.category01']['items'] %}
			 <a href="{{d['mobile_link']}}"><img src="{{d['picture']}}" alt=""></a>
			 <p>{{d['title']}}</p>
			 <?php break; ?>
			 {% endfor %}
	         <?php } ?>
		</div>
		<div class="classify">
			 <?php if(!empty($data['app.star.main']['children']['app.star.main.category02']['items'])) { ?>
			 {% for d in data['app.star.main']['children']['app.star.main.category02']['items'] %}
			 <a href="{{d['mobile_link']}}"><img src="{{d['picture']}}" alt=""></a>
			 <p>{{d['title']}}</p>
			 <?php break; ?>
			 {% endfor %}
	         <?php } ?>
		</div>
		<div class="classify">
			 <?php if(!empty($data['app.star.main']['children']['app.star.main.category03']['items'])) { ?>
			 {% for d in data['app.star.main']['children']['app.star.main.category03']['items'] %}
			 <a href="{{d['mobile_link']}}"><img src="{{d['picture']}}" alt=""></a>
			 <p>{{d['title']}}</p>
			 <?php break; ?>
			 {% endfor %}
	         <?php } ?>
		</div>
		<div class="classify">
			 <?php if(!empty($data['app.star.main']['children']['app.star.main.category04']['items'])) { ?>
			 {% for d in data['app.star.main']['children']['app.star.main.category04']['items'] %}
			 <a href="{{d['mobile_link']}}"><img src="{{d['picture']}}" alt=""></a>
			 <p>{{d['title']}}</p>
			 <?php break; ?>
			 {% endfor %}
	         <?php } ?>
		</div>
		<div class="classify">
			 <?php if(!empty($data['app.star.main']['children']['app.star.main.category05']['items'])) { ?>
			 {% for d in data['app.star.main']['children']['app.star.main.category05']['items'] %}
			 <a href="{{d['mobile_link']}}"><img src="{{d['picture']}}" alt=""></a>
			 <p>{{d['title']}}</p>
			 <?php break; ?>
			 {% endfor %}
	         <?php } ?>
		</div>
		<div class="classify">
			 <?php if(!empty($data['app.star.main']['children']['app.star.main.category06']['items'])) { ?>
			 {% for d in data['app.star.main']['children']['app.star.main.category06']['items'] %}
			 <a href="{{d['mobile_link']}}"><img src="{{d['picture']}}" alt=""></a>
			 <p>{{d['title']}}</p>
			 <?php break; ?>
			 {% endfor %}
	         <?php } ?>
		</div>
		<div class="classify">
			 <?php if(!empty($data['app.star.main']['children']['app.star.main.category07']['items'])) { ?>
			 {% for d in data['app.star.main']['children']['app.star.main.category07']['items'] %}
			 <a href="{{d['mobile_link']}}"><img src="{{d['picture']}}" alt=""></a>
			 <p>{{d['title']}}</p>
			 <?php break; ?>
			 {% endfor %}
	         <?php } ?>
		</div>
		<div class="classify">
			 <?php if(!empty($data['app.star.main']['children']['app.star.main.category08']['items'])) { ?>
			 {% for d in data['app.star.main']['children']['app.star.main.category08']['items'] %}
			 <a href="{{d['mobile_link']}}"><img src="{{d['picture']}}" alt=""></a>
			 <p>{{d['title']}}</p>
			 <?php break; ?>
			 {% endfor %}
	         <?php } ?>
		</div>
		<div class="classify">
			 <?php if(!empty($data['app.star.main']['children']['app.star.main.category09']['items'])) { ?>
			 {% for d in data['app.star.main']['children']['app.star.main.category09']['items'] %}
			 <a href="{{d['mobile_link']}}"><img src="{{d['picture']}}" alt=""></a>
			 <p>{{d['title']}}</p>
			 <?php break; ?>
			 {% endfor %}
	         <?php } ?>
		</div>
		<div class="classify">
			 <?php if(!empty($data['app.star.main']['children']['app.star.main.category10']['items'])) { ?>
			 {% for d in data['app.star.main']['children']['app.star.main.category10']['items'] %}
			 <a href="{{d['mobile_link']}}"><img src="{{d['picture']}}" alt=""></a>
			 <p>{{d['title']}}</p>
			 <?php break; ?>
			 {% endfor %}
	         <?php } ?>
		</div>
	</div>
	<!-- banner2 -->
	<div class="banner">
		 <?php if(!empty($data['app.star.main']['children']['app.star.main.column']['items'])) { ?>
		 {% for d in data['app.star.main']['children']['app.star.main.column']['items'] %}
		 <a href="{{d['mobile_link']}}"><img src="{{d['picture']}}" alt=""></a>
		 <?php break; ?>
		 {% endfor %}
         <?php } ?>
	</div>
	<!-- 第一商品集 -->
	<div class="goods1_box">
		<div class="goods1">
		 <?php if(!empty($data['app.star.main']['children']['app.star.main.goods01']['items'])) { ?>
		 {% for d in data['app.star.main']['children']['app.star.main.goods01']['items'] %}
			 <a href="{{d['mobile_link']}}"><img src="{{d['picture']}}" alt=""></a>
		 <?php break; ?>
		 {% endfor %}
	     <?php } ?>
		</div>
		<div class="goods2">
		  <?php if(!empty($data['app.star.main']['children']['app.star.main.goods02']['items'])) { ?>
		 {% for d in data['app.star.main']['children']['app.star.main.goods02']['items'] %}
			 <a href="{{d['mobile_link']}}"><img src="{{d['picture']}}" alt=""></a>
		 <?php break; ?>
		 {% endfor %}
	     <?php } ?>
		</div>
		<div class="goods2">
		 <?php if(!empty($data['app.star.main']['children']['app.star.main.goods03']['items'])) { ?>
		 {% for d in data['app.star.main']['children']['app.star.main.goods03']['items'] %}
			 <a href="{{d['mobile_link']}}"><img src="{{d['picture']}}" alt=""></a>
		 <?php break; ?>
		 {% endfor %}
	     <?php } ?>
		</div>
	</div>
	<!-- 第二商品集合下面为循环 -->
	<div class="goods2_box">
	 <?php if(!empty($data['app.star.main']['children']['app.star.main.bigcolumn']['items'])) { ?>
	 {% for d in data['app.star.main']['children']['app.star.main.bigcolumn']['items'] %}
		 <a href="{{d['mobile_link']}}"><img src="{{d['picture']}}" alt=""></a>
	 {% endfor %}
     <?php } ?>
	</div>
	
	
</body>
</html>
<script src="/public/js/rem.js"></script>
<script src="/public/js/m_analytics.js"></script>
<script src="/public/js/sdk.2.2.js"></script>
