<?php
    $css = $this -> assets -> get('header');
    $css -> addCss("/public/css/index/lead.css");

    $js = $this -> assets -> get('footer');
    $js -> addJs("public/js/jQuery-3.1.0.js");
    $js -> addJs("public/js/rem.js");
    $js -> addJs("public/js/index/lead.js");

?>
<body class="lcy_lead">
<!-- 广告 -->
<div class="money_ad">
    <div class="ad"><img src="/public/img/ad_01.png" alt=""></div>
    <div class="ad"><img src="/public/img/ad_02.png" alt=""></div>
    <div class="ad"><img src="/public/img/ad_03.png" alt=""></div>
    <div class="ad ad4"><img src="/public/img/ad_04.png" alt="">
    <a href="/agree.html">
        <div class="btn_go"></div>      	        
    </a>
    </div>
</div>

</body>
</html>

