<?php
	require_once ROOT_PATH . "/apps/librarys/weixinshare/jssdk.php";
	$jssdk = new JSSDK("wx6fe7550ec5625a23", "57bdd0bbe290a22b6844673509db0b61");
	$signPackage = $jssdk->GetSignPackage();
?>
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
	<meta content="black" name=" apple-mobile-web-app-status-bar-style"   />
	<meta itemprop="name" content="品牌招商"/>
	<meta itemprop="image" content="https://sales.soolife.cn/public/mobile/img/shi.jpg" />
	<meta name="description" itemprop="description" content="拿来属于你的势!互联网+产业野蛮生长，卖货难问题已成为众多商家的困扰，如此生活创立专业快速渠道，省时省心，与您携手同创共赢之势" />
	<link rel="stylesheet" type="text/css" href="/public/mobile/css/investment/trademark.css">
	<title>品牌招商</title>
</head>
<body>
<!-- 微信分享 -->
	<input type="hidden" name="appId" value="{{ signPackage['appId'] }}" />
	<input type="hidden" name="timestamp" value="{{ signPackage['timestamp'] }}" />
	<input type="hidden" name="nonceStr" value="{{ signPackage['nonceStr'] }}" />
	<input type="hidden" name="signature" value="{{ signPackage['signature'] }}" />
	 <div class="wrap">
	 	<img src="/public/mobile/img/trademark/mark_one/brand_one.jpg">
	 	<img src="/public/mobile/img/trademark/mark_one/brand_two.jpg">
	 	<img src="/public/mobile/img/trademark/mark_one/brand_three.jpg">
	 	<img src="/public/mobile/img/trademark/mark_one/brand_four.jpg">
	 	<img src="/public/mobile/img/trademark/mark_one/brand_five.jpg">
	 	<img src="/public/mobile/img/trademark/mark_one/brand_six.jpg">
	 	<div class="iphone">
	 		<img src="/public/mobile/img/trademark/mark_one/iphone_one.jpg">
	 		<img src="/public/mobile/img/trademark/mark_one/iphone_two.jpg">
	 		<img src="/public/mobile/img/trademark/mark_one/iphone_three.jpg">
	 		<img src="/public/mobile/img/trademark/mark_one/iphone_four.jpg">
	 		<img src="/public/mobile/img/trademark/mark_two/qiye.jpg">
	 	</div>
	 	<div class="oao">
	 		<p>如此生活 全新OAO模式</p>
	 		<p>解决线上线下入口单一运营成本过高问题,</p>
	 		<p><span>体验店、</span><span>移动端、</span><span>仓储服务、</span>一站式服务,</p>
	 		<p>轻松解决卖货难问题</p>
	 	</div>
	 	<div class="city">
	 		<img src="/public/mobile/img/trademark/mark_one/city.jpg">
	 	</div>
	 	<!-- <div class="exper">
			<p class="exp_shop">·&nbsp;&nbsp;体验店端&nbsp;&nbsp;·</p>
			<p>免费线下体验店品牌展示</p>
			<p>去除中间环节</p>
			<p>商家商品直达消费者</p>
		</div> -->
		<div class="enjoy">
			<img src="/public/mobile/img/trademark/mark_two/shop_one.jpg">
			<img src="/public/mobile/img/trademark/mark_two/shop_two.jpg">
			<img src="/public/mobile/img/trademark/mark_two/shop_three.jpg">
			<img src="/public/mobile/img/trademark/mark_two/shop_four.jpg"> 
		</div>
		<div class="card">
			<img src="/public/mobile/img/trademark/mark_one/card_one.jpg">
		 	<img src="/public/mobile/img/trademark/mark_one/card_two.jpg">
		 	<img src="/public/mobile/img/trademark/mark_one/card_three.jpg">
		</div>
		<div class="shops">
			<img src="/public/mobile/img/trademark/mark_two/shops_one.jpg">
			<img src="/public/mobile/img/trademark/mark_two/shops_two.jpg">
			<img src="/public/mobile/img/trademark/mark_two/shops_three.jpg">
			<img src="/public/mobile/img/trademark/mark_two/shops_four.jpg">
		</div>
		<div class="soo">
			<img src="/public/mobile/img/trademark/mark_two/soo_one.jpg">
			<img src="/public/mobile/img/trademark/mark_two/soo_two.jpg">
			<img src="/public/mobile/img/trademark/mark_two/soo_three.jpg">
			<img src="/public/mobile/img/trademark/mark_two/soo_four.jpg">
		</div>
		<div class="have">
			<p>如此生活</p>	
			<p>已拥有</p>	
			<p><span>6家</span>线下体验店</p>	
			<p><span>10大</span>功能体验区</p>	
			<p><span>7大</span>特色品类商品</p>	
		</div>
		<div class="mobile">
			<img src="/public/mobile/img/trademark/mark_one/apple_one.jpg">
		 	<img src="/public/mobile/img/trademark/mark_one/apple_two.jpg">
		 	<img src="/public/mobile/img/trademark/mark_one/apple_three.jpg">
		 	<img src="/public/mobile/img/trademark/mark_one/apple_four.jpg"> 
		</div>
		<div class="app">
			<img src="/public/mobile/img/trademark/mark_three/app_one.jpg">
		 	<img src="/public/mobile/img/trademark/mark_three/app_two.jpg">
		 	<img src="/public/mobile/img/trademark/mark_three/app_three.jpg">
		 	<img src="/public/mobile/img/trademark/mark_three/app_four.jpg">
		 	<img src="/public/mobile/img/trademark/mark_three/app_five.jpg">
		 	<img src="/public/mobile/img/trademark/mark_three/app_six.jpg">
		 	<img src="/public/mobile/img/trademark/mark_three/app_seven.jpg">
		 	<img src="/public/mobile/img/trademark/mark_three/app_eight.jpg">
		</div>
		<div class="have">
			<p>如此生活</p>	
			<p>已拥有</p>	
			<p><span>百万级</span>的星卖家</p>	
			<p><span>千万级</span>的星粉数</p>	
			<p><span>亿级</span>的星币发放量</p>	
		</div>
		<div class="mac">
			<img src="/public/mobile/img/trademark/mark_four/mac.jpg">
		</div>
		<div class="exper">
			<p class="exp_shop">·&nbsp;&nbsp;仓储端&nbsp;&nbsp;·</p>
			<p>免费仓储&nbsp;,管家服务</p>
			<p>代存&nbsp;代管&nbsp;代发</p> 
		</div>
		<div class="car">
			<img src="/public/mobile/img/trademark/mark_three/car_one.jpg"> 
		 	<img src="/public/mobile/img/trademark/mark_three/car_three.jpg">
		 	<img src="/public/mobile/img/trademark/mark_three/car_four.jpg">
		 	<img src="/public/mobile/img/trademark/mark_three/car_five.jpg">
		 	<img src="/public/mobile/img/trademark/mark_three/car_six.jpg">
		</div>
		<div class="have">
			<p>现代化集成大仓</p>	
			<p>货物代存、代管、代发</p>	
			<p>节省成本，安心可靠</p>	
		</div>
		<div class="join">
			<img src="/public/mobile/img/trademark/mark_four/join.jpg">
		</div>
		<div class="lj_join">
			<p>招商合作政策</p>
			<p>·&nbsp;&nbsp;品牌商户合作政策&nbsp;&nbsp;·</p> 
		</div>
		<div class="table">
			<img src="/public/mobile/img/trademark/mark_four/table_one.jpg"> 
		 	<img src="/public/mobile/img/trademark/mark_four/table_two.jpg">
		 	<img src="/public/mobile/img/trademark/mark_four/table_three.jpg">
		 	<img src="/public/mobile/img/trademark/mark_four/table_four.jpg">
		 	<img src="/public/mobile/img/trademark/mark_four/table_five.jpg">
		 	<img src="/public/mobile/img/trademark/mark_four/table_six.jpg">
		</div>
		<div class="flow">
			<img src="/public/mobile/img/trademark/mark_four/flow_one.jpg"> 
		 	<img src="/public/mobile/img/trademark/mark_four/flow_two.jpg">
		 	<img src="/public/mobile/img/trademark/mark_four/flow_three.jpg">
		 	<img src="/public/mobile/img/trademark/mark_four/flow_four.jpg">
		 	<img src="/public/mobile/img/trademark/mark_four/flow_five.jpg">
		 	<img src="/public/mobile/img/trademark/mark_four/flow_six.jpg">
		 	<img src="/public/mobile/img/trademark/mark_four/three.jpg">
		</div>
		<!-- 填写个人资料 -->
		<div class="lj_input tops">
			<input type="text" name="name" placeholder="如何称呼您" class="place_input"/>
			<input type="hidden" name="type" class="place_input" value="1" />
		</div>
		<div class="lj_input top">
			<input type="text" name="iphone" placeholder="如何联系您" class="place_input"/>
		</div>
		<div class="lj_input top">
			<input type="text" name="compny" placeholder="贵公司名称" class="place_input"/>
		</div>
		<input type="hidden" name="types" value="2" />
                <input type="hidden" name="tid" value="<?php  if(isset($_GET['tid'])){ print_r($_GET['tid']); }else{ echo '0'; }?>" />
       <!--  <div class="lj_input top">
			<input type="text" name="inviter" placeholder="邀请人" class="place_input"/>
		</div> -->
		<div class="open">开启属于你的时代</div>
		<div class="guess">
			<div class="like">
			<p>在您之前,已有<span class="num">{{num}}</span>位提交咨询</p> 
			</div>
		</div>
		<br> 
		<div class="datum lj_data">您的资料我们会给予保密，敬请放心！</div>
		<div class="datum data_bottom">稍后会有客服人员回电，给您提供优质的服务！</div>
		<div class="wang">www.soolife.cn</div>
	</div>
	<div id="alert_mark"> </div>
	<div class="success">
		<div id="alert_success">
			<h4>提交成功</h4>
			<p>属于你的时代即将开启</p>
			<div class="gondss">好的</div>
		</div>
	</div>
	<div class="lj_iphones"><a href="tel:{{res['mobile']}}"><img src="/public/mobile/img/investment/iphones.png"></a></div>
	 </div>
</body>
<script type="text/javascript" src="/public/mobile/js/investment/rem.js"></script>
<script type="text/javascript" src="/public/mobile/js/investment/jquery.-1.8.3.min.js"></script>
<script type="text/javascript" src="/public/mobile/js/weixin/jssdk.js"></script>
<script type="text/javascript" src="/public/mobile/js/investment/brands.js"></script>
<script type="text/javascript" src="/public/mobile/js/investment/markwxshare.js"></script>
</html>