<?php
$css = $this->assets->get('header');
$css -> addCss("public/css/basic.css");
$js  = $this->assets->get('footer');
?>
<div class="row main">
    <div class="col-sm-12" style="margin: 0;padding: 0;">
        <div class="col-sm-5">
            <div class="row">
                <div class="col-sm-12" style="margin-bottom: 10px;">
                    <img src="../public/img/about/developmentHistory01.jpg" alt="如此生活">
                </div>
                <div class="col-sm-6">
                    <img src="../public/img/about/developmentHistory02.jpg" alt="如此生活">
                </div>
                <div class="col-sm-5" style="margin-left: 15px;">
                    <img src="../public/img/about/developmentHistory03.jpg" alt="如此生活" style="padding-bottom: 5px;">
                    <img src="../public/img/about/developmentHistory04.jpg" alt="如此生活">
                </div>
            </div>
        </div>
        <div class="col-sm-7 desc">
            <div style="border-left: 6px solid #36a0da;padding-left:20px;">
                <h2>公司简介</h2>
                <p>About Us</p>
            </div>
            <div class="row" style="margin-top: 20px;line-height: 24px;font-size: 12px;">
            <div class="col-sm-6" style="text-indent: 2em;color: #8f8f8f;">
                <p>鸿惠（上海）信息技术服务有限公司是一家拥有独创技术和跨平台发展的创新型企业，总部位于上海，产业涉及互联网电子商务、连锁零售、本地生活服务等多个不同领域，曾经荣获上海市诚信企业认证，并于2014年5月在上海股权交易中心成功挂牌，企业名称：鸿惠信息（企业代码：200777），创始人吴存松先生本着一生只做一件事的宏伟愿望，以“为人们创造美好生活，是我们奋斗的唯一目标！”作为公司战略目标，公司员工秉承着诚信团结、以人为本、求实创新、社会责任的核心价值观，通过互联网和信息化服务技术，开创了前所未有的崭新天地！
                </p>
                <p>SooLife”品牌，凭借独创的商业模式、强大的技术研发能力、创新的互动体验，全新打造了一个与消费者多频次、近距离接触的互动体验新平台。通过独有的（网络端、移动端、体验端和仓储端）四维一体的互动体验模式，让消费者在获得优惠的同时，也深度体验到全方位生活的乐趣。
                </p>
            </div>
            <div class="col-sm-6" style="text-indent: 2em;color: #8f8f8f;">
                <p>
                    针对商家的多元化服务，让更多中小企业主受益，提高了品牌知名度和商品的销量；与此同时，也为那些拥有梦想的人提供了绝佳的创业良机，帮助他们建立自己的商铺，开拓广袤的消费市场，建立属于自己的商业帝国；相信未来每一个人都将在“SooLife”平台上绽放出多彩的生活！</p>
                    <p>公司在北京、广州等地区设有分公司，员工总数500多人，业务覆盖华东、华北、华南等多个省市，涉及服装百货、食品饮料、家居美妆、母婴用品、数码电器等众多领域，公司目前已与万达商业地产、宝龙集团达成战略合作，分别在上海、厦门、镇江万达广场、宝龙广场开设3000平米以上大型体验店7家，未来将会覆盖全中国核心城市，门店总数超过500家以上。</p>
                    <p>公司立志成为中国未来最大的一站式服务平台，为实现让民众受益，让商家营利的宏伟愿景而不断奋斗！</p>
                </p>
            </div>
            </div>
        </div>
    </div>
</div>