<?php
$css = $this->assets->get('header');
$css -> addCss("public/css/p/view.futurTendency.css");

$js  = $this->assets->get('footer');
?>
<div class="lj_core">
	<ul>
		<li>
			<img alt="如此生活" src="../public/img/about/core1.png">
			<div class="lj_corefot">
				<div class="lj_coreleft">
					<p>吴存松先生</p>
					<p>(如此生活品牌创始人)</p>
				</div>
				<div class="lj_coreright"><img alt="如此生活" src="../public/img/about/corebtn.png"></div>
			</div>
			
		</li>
		<li>
			<img alt="如此生活" src="../public/img/about/core2.png">
			<div class="lj_corefot">
				<div class="lj_coreleft">
					<p>张峰先生</p>
					<p>(服务中心负责人)</p>
				</div>
				<div class="lj_coreright"><img alt="如此生活" src="../public/img/about/corebtn.png"></div>
			</div>	
		</li>
		<li>
			<img alt="如此生活" src="../public/img/about/core3.png">
			<div class="lj_corefot">
				<div class="lj_coreleft">
					<p>邢冬云女士</p>
					<p>(财务中心负责人)</p>
				</div>
				<div class="lj_coreright"><img alt="如此生活" src="../public/img/about/corebtn.png"></div>
			</div>
		</li>
		<li>
			<img alt="如此生活" src="../public/img/about/core4.png">
			<div class="lj_corefot">
				<div class="lj_coreleft">
					<p>孙祥先生</p>
					<p>(营销中心负责人)</p>
				</div>
				<div class="lj_coreright"><img alt="如此生活" src="../public/img/about/corebtn.png"></div>
			</div>
		</li>
		<li>
			<img alt="如此生活" src="../public/img/about/core5.png">
			<div class="lj_corefot">
				<div class="lj_coreleft">
					<p>汪肄敏先生</p>
					<p>(技术中心负责人)</p>
				</div>
				<div class="lj_coreright"><img alt="如此生活" src="../public/img/about/corebtn.png"></div>
			</div>
		</li>
		<li>
			<img alt="如此生活" src="../public/img/about/core6.png">
			<div class="lj_corefot">
				<div class="lj_coreleft">
					<p>王勇先生</p>
					<p>(运营中心负责人)</p>
				</div>
				<div class="lj_coreright"><img alt="如此生活" src="../public/img/about/corebtn.png"></div>
			</div>
		</li>
	</ul>
</div>
