<?php
$css = $this->assets->get('header');
$css -> addCss("public/css/p/view.cultrue.css");

$js  = $this->assets->get('footer');
?>
<div class="row">
    <div class="col-sm-12 main">
        <div class="col-sm-5">
            <div class="row">
                <div class="col-sm-6">
                    <img src="../public/img/about/culture1.jpg" alt="如此生活">
                </div>
                <div class="col-sm-6">
                    <img src="../public/img/about/culture2.jpg" alt="如此生活" style="padding-left: 4px;padding-bottom: 4px;">
                </div>
                <div class="col-sm-12" style="margin-bottom: 4px;">
                    <img src="../public/img/about/culture3.jpg" alt="如此生活">
                </div>
                <div class="col-sm-6">
                    <img src="../public/img/about/culture4.jpg" alt="如此生活">
                </div>
                <div class="col-sm-5" style="margin-left: 2px;">
                    <img src="../public/img/about/culture5.jpg" alt="如此生活" style="padding-bottom: 4px;">
                    <img src="../public/img/about/culture6.jpg" alt="如此生活">
                </div>
            </div>
        </div>
        <div class="col-sm-7">
            <div class="model" style="border-left: 6px solid #36a0da;padding-left:20px">
                <h2>品牌使命</h2>
                <p>Brand mission</p>
            </div>
            <p class="text">为人们创造美好生活</p>
        </div>
        <div class="col-sm-7">
            <div class="model" >
                <h2>品牌理念</h2>
                <p>Brand concept</p>
            </div>
            <p class="text">让民众受益、让商家营利</p>
        </div>
        <div class="col-sm-7">
            <div class="model" >
                <h2>品牌定位</h2>
                <p>Brand positioning</p>
            </div>
            <p class="text">全球体验式生活领导者</p>
        </div>
        <div class="col-sm-7">
            <div class="model" >
                <h2>品牌目标</h2>
                <p>Brand goal</p>
            </div>
            <p class="text">为企业主、消费者、合伙人提供一种全新生活体验方式</p>
        </div>
        <div class="col-sm-7">
            <div class="model" >
                <h2>品牌业务</h2>
                <p>Brand business</p>
            </div>
            <p class="text">购物共赢生态体系</p>
        </div>
        <div class="col-sm-7">
            <div class="model" >
                <h2>企业价值观</h2>
                <p>Enterprise value</p>
            </div>
            <p class="text">诚信团结、以人为本、求实创新、社会责任</p>
        </div>
        <div class="col-sm-7">
            <div class="model" >
                <h2>企业文化</h2>
                <p>Corporate culture</p>
            </div>
            <p class="text">拼搏、成长、感恩、分享</p>
        </div>
    </div>
</div>