<?php
$css = $this->assets->get('header');
$css -> addCss("public/css/basic.css");
$js  = $this->assets->get('footer');
?>
<div class="row main">
    <div class="col-sm-12" style="margin: 0;padding: 0;">
        <div class="col-sm-5">
            <div class="row">
                <div class="col-sm-12" style="margin-bottom: 10px;">
                    <img src="../public/img/about/companyProfile01.jpg" alt="如此生活">
                    <img src="../public/img/about/companyProfile02.jpg" alt="如此生活" style="padding-top: 10px;">
                </div>
            </div>
        </div>
        <div class="col-sm-7 desc">
            <div style="border-left: 6px solid #36a0da;padding-left:20px;">
                <h2>发展历程</h2>
                <p>Development history</p>
            </div>
            <div class="row" style="margin-top: 20px;line-height: 24px;">
                <ul class="col-sm-12 companyProfile">
                    <li>2013年1月<span>"如此生活"品牌正式成立</span></li>
                    <li>2013年3月<span>"如此生活"品牌项目正式启动</span></li>
                    <li>2014年4月<span>"如此生活"爱信捐赠活动，社区义卖活动正式启动</span></li>
                    <li>2014年5月<span>"如此生活"品牌与百度上海分公司达成战略合作</span></li>
                    <li>2014年5月<span>"如此生活"首家线下体验店试运营</span></li>
                    <li>2014年5月<span>"如此生活"上海股权交易中心正式挂牌</span></li>
                    <li>2014年6月<span>"如此生活"平台微信用户突破5万人</span></li>
                    <li>2014年7月<span>"如此生活"平台上海旗舰店项目启动</span></li>
                    <li>2014年8月<span>"如此生活"平台网上商城开通</span></li>
                    <li>2014年10月<span>"如此生活"平台网站2.0版本测试</span></li>
                    <li>2014年11月<span>"如此生活"平台获得上海市长宁区专精特新企业认证</span></li>
                    <li>2014年12月<span>"如此生活"平台一站式存储仓库落成启用</span></li>
                    <li>2015年1月<span>"如此生活"上海旗舰店正式签约</span></li>
                    <li>2015年2月<span>"如此生活"平台"羊威天下"大型年会成功举办</span></li>
                    <li>2015年3月<span>"如此生活"上海旗舰店效果图公布</span></li>
                    <li>2015年5月<span>"如此生活"平台网站正式上线运营</span></li>
                    <li>2015年6月<span>"如此生活"平台与上海交通大学合作开展O2O企业家课堂</span></li>
                    <li>2015年7月<span>"如此生活"品牌升级</span></li>
                    <li>2015年8月<span>"如此生活"杭州分公司成立</span></li>
                    <li>2015年9月<span>"如此生活"成功举办2015互联网+服装产业主题论坛</span></li>
                    <li>2015年10月<span>"如此生活"参与中国(杭州)国际电子商务博览会</span></li>
                    <li>2015年11月<span>"如此生活"与德国巴伐利亚-伊尔巴赫啤酒公司达成战略合作伙伴</span></li>
                    <li>2015年11月<span>"如此生活"太阳广场旗舰店试营业</span></li>
                    <li>2015年12月<span>"如此生活"太阳广场旗舰店正式营业</span></li>
                    <li>2016年3月<span>"如此生活"平台参加第26届华东进出口商品贸易会</span></li>
                    <li>2016年7月<span>"如此生活"平台总部乔迁长宁科技园区</span></li>
                    <li>2016年9月<span>"如此生活"平台APP成上线、全平台O2O贯通</span></li>
                    <li>2016年9月<span>"如此生活"上海嘉定宝龙广场店盛大开业</span></li>
                    <li>2016年9月<span>"如此生活"平台2016合作商大会在上海盛大召开</span></li>
                </ul>
            </div>
        </div>
    </div>
</div>
