<?php
$css = $this->assets->get('header');
$css -> addCss("public/css/p/view.futurTendency.css");

$js  = $this->assets->get('footer');
?>
<div class="lj_enhead">
	<p class="lj_enleft"><img alt="如此生活" src="../public/img/about/enter1.png"></p>
	<div class="lj_enright">
		<div class="lj_contop">
			<div style="border-left: 6px solid #36a0da;padding-left:20px">
                <h2>企业荣誉</h2>
                <p>Brand mission</p>
			</div>
		</div>
		<div class="lj_firm">
			<p>2014年5月公司正式在上海股权托管交易中心中小企业股权报价系统正式挂牌。企业名称：鸿惠信息，企业代码：200777。</p>
			<p>2014年5月公司和百度达成战略合作并成功签约。</p>
			<p>2014年公司获得上海市诚信企业认证、并且定期举办爱心捐赠活动，社区义卖活动等，积极投身社会公益。</p>
			<p>2014年12月公司获得上海市长宁区专精特新企业认证。</p>
			<p>2015年11月公司参与中国（杭州）国际电子商务博览会，并获得浙江省委常委、杭州市市委书记赵一德、市长张鸿铭的亲切接见。</p>
			<p>2015年12月公司获得《文明诚信》企业认证。</p>
			<p>2015年12月公司和体验店获得上海市长宁区副区长翁华建的参观考察。</p>
		</div>
	</div>
</div>
<div class="lj_honor">荣誉墙</div>
<!-- 轮播荣耀墙 -->
<div class="lj_banner">
	<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
	  <!-- Wrapper for slides -->
	  <div class="carousel-inner" role="listbox">
	    <div class="item active">
	      <img alt="如此生活" src="../public/img/about/enter4.jpg" >
	    </div>
	    <div class="item ">
	      <img alt="如此生活" src="../public/img/about/enter4.jpg" >
	    </div>
	  </div>
	  <a title="如此生活" class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
	    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
	  </a>
	  <a title="如此生活" class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
	    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
	  </a>
	</div>
</div>