<?php
$css = $this->assets->get('header');
$css -> addCss("public/css/p/view.futurTendency.css");

$js  = $this->assets->get('footer');
?>
<div class="lj_head">
	<div  class="lj_img"><img alt="如此生活" src="../public/img/about/futur1.png"></div>
	<div  class="lj_content">
		<div class="lj_contop">
<!-- 			<div class="lj_brand">
				<p>品牌战略</p>
				<p>Brand strategy</p>
			</div> -->
			<div style="border-left: 6px solid #36a0da;padding-left:20px">
                <h2>品牌战略</h2>
                <p>Brand strategy</p>
			</div>
		</div>
		<div class="lj_center">
			<p>建立全国营销中心和仓库配送中心</p>
			<p>四大区：上海、华北区、华南区、华中区</p>
			<p>营销中心：上海、北京、重庆、广东</p>
			<p>总部：上海</p>
		</div>
		<div class="lj_fen"><img alt="如此生活" src="../public/img/about/futur2.png"></div>
	</div>
</div>
<div class="lj_five">
	<div style="border-left: 6px solid #36a0da;padding-left:20px">
		<h2>五年计划</h2>
		<p>Five year plan</p>
	</div>
</div>
<div class="lj_fuimg"><img alt="如此生活" src="../public/img/about/futur3.png"></div>
