<?php
$css = $this->assets->get('header');
$css -> addCss("public/css/basic.css");
$js  = $this->assets->get('footer');
?>
<div class="row main">
	<div class="col-sm-12" style="margin: 0;padding: 0;">
		<div class="col-sm-5">
			<img alt="如此生活" src="../public/img/about/makeSpeech01.jpg" alt="如此生活">
		</div>
		<div class="col-sm-7 desc">
			<div style="border-left: 6px solid #36a0da;padding-left:20px;">
				<h2>董事长致辞</h2>
				<p>Remarks by Chairman</p>
			</div>
			
			<p class="two">我们是崭新的一代人,<br>胸怀梦想与希望,<br>肩负使命与责任,<br>源于我们共同的追求与信念。<br>未来是由我们创造,<br>生活是由我们主导，<br>梦想是由我们实现。<br>今天,我们相聚在一起,<br>是为了共同创造幸福美好的人生。<br>美好生活，从此开始！</p>
		</div>
	</div>
</div>
