<?php
	$css = $this->assets->get('header');
	$css -> addCss("public/css/p/view.shopapply.css");

	$js  = $this->assets->get('footer');
?>
<div class="lj_content">
	<img alt="如此生活" src="/public/img/sop/online/1.jpg">
	<img alt="如此生活" src="/public/img/sop/online/2.jpg">
	<img alt="如此生活" src="/public/img/sop/online/3.jpg">
	<img alt="如此生活" src="/public/img/sop/online/4.jpg">
	<img alt="如此生活" src="/public/img/sop/online/5.jpg">
	<img alt="如此生活" src="/public/img/sop/online/6.jpg">
	<img alt="如此生活" src="/public/img/sop/online/7.jpg">
	<img alt="如此生活" src="/public/img/sop/online/8.jpg">
	<img alt="如此生活" src="/public/img/sop/online/9.jpg">
</div>
<div class="lj_down">
	<a title="如此生活" href="/sop/download"><div class="matters">下载文件</div></a>
</div>
