<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>如此生活|满额抽奖</title>
    <meta name="viewport" content="width=device-width, initial-scale=1,maximum-scale=1,user-scalable=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <link rel="stylesheet" type="text/css" href="/public/ext/css/soo.m.ui.css"/>
    <link rel="stylesheet" href="/public/ext/css/download.css">
    <link rel="stylesheet" href="/public/ext/css/swiper.css">
    <link rel="stylesheet" type="text/css" href="/public/css/lottery/regulation.css"/>
</head>
<body>
    <!-- 头部 -->
    <div id="soo-header">
        <div id="header-left"><a onclick = "window.history.go(-1)"> <img src="../public/img/lottery/shop_back_black@2x.png" alt=""></a></div>
        <div id="header-center">满额抽奖</div>
    </div>
    <div class="regula-back">
        <p class="regula-h1">满额即可抽大奖！</p>
        <p class="regula-h2">奖品总额高达一千万！</p>
        <p class="regula-text1">1、订单支付完成后,用户直接获得抽奖机会提示,可以参与抽奖;</p>
        <p class="regula-text2">2、若用户点击关闭抽奖提示页面,则视为放弃此次抽奖机会,将不再显示抽奖;</p>
        <p class="regula-text3">3、每次订单只有一次抽奖机会;</p>
        <p class="regula-text4">4、若用户在抽中奖品后,发起退款申请,则需将奖品及购买商品一起返还,否则无法通过退款;</p>
        <p class="regula-text5">5、抽奖商品无法提供相应发票;</p>
        <p class="regula-text6">6、在法律允许范围内,如此生活拥有活动的最终解释权;</p>
        <a href="homepage.html" class="regula-btn">我要抽奖</a>
    </div>
</body>

</html>
<script src="/public/js/rem.js"></script> 
<script src="/public/ext/js/jquery-1.8.3.min.js"></script>
<script src="/public/ext/js/download.js"></script>
<script src="/public/js/jquery.base64.js"></script>
<script type="text/javascript" src="/public/ext/js/swiper.min.js"></script>
<script src="/public/js/rem.js"></script>