

	<head>
		<meta charset="utf-8" />
		<title>松仕箱包</title>
		<link rel="stylesheet" href="/theme/activity/2016_09_Luggage/pc/css/pc_index.css" />
	</head>

	<body>
		<div class="f_complete">
			<!--banner-->
			<div class="f_pc_luggage">
				<img src="/theme/activity/2016_09_Luggage/pc/img/banner/banner_one.jpg" alt="" align="top" />
				<img src="/theme/activity/2016_09_Luggage/pc/img/banner/banner_two.jpg" alt="" align="top" />
				<img src="/theme/activity/2016_09_Luggage/pc/img/banner/banner_three.jpg" alt="" align="top" />
				<img src="/theme/activity/2016_09_Luggage/pc/img/banner/banner_four.jpg" alt="" align="top" />
				<img src="/theme/activity/2016_09_Luggage/pc/img/banner/banner_five.jpg" alt="" align="top" />
					<img src="/theme/activity/2016_09_Luggage/pc/img/banner/banner_six.jpg" alt="" align="top" />
						<img src="/theme/activity/2016_09_Luggage/pc/img/banner/banner_seven.jpg" alt="" align="top" />
							<img src="/theme/activity/2016_09_Luggage/pc/img/banner/banner_eight.jpg" alt="" align="top" />
			</div>
			<!--产品-->
			<div class="f_pc_first">
				<div class="first_row">
					<ul>
						<li class="first_one">
							<a href="http://item.soolife.cn/26229.html">
								<img src="/theme/activity/2016_09_Luggage/pc/img/picture/picture_one.jpg" alt="" data="opengoodsdetail"/>
							</a>
						</li>
						<li class="first_two">
							<a href="http://item.soolife.cn/26228.html">
								<img src="/theme/activity/2016_09_Luggage/pc/img/picture/picture_two.jpg" alt="" data="opengoodsdetail"/>
							</a>
						</li>
					</ul>
				</div>
				<div class="f_pc_picture">
					<ul>
						<li class="picture_one">
							
							<a href="http://item.soolife.cn/22385.html">
								<div class="f_color">
								<img src="/theme/activity/2016_09_Luggage/pc/img/picture/picture_three.png" alt="" data="opengoodsdetail"/>
								</div>
								<div class="picture_font">
									<div class="activity">
										<span class="activity_buy">活动价：</span><span class="money">216.30</span><span class="activity_buy"> 元</span>
										<p class="black">原价：309元</p>
									</div>
									<div class="narrate">
										<p class="f_whone">百事原形拉链箱20寸</p>
										<p class="f_white">金属拉杆  独特质感</p>
									</div>
									<div class="immediately" data="openinstantbuy">
										<span>立即购买</span>
									</div>
								</div>
							</a>
							
						</li>
						<li>
							
							<a href="http://item.soolife.cn/22386.html">
								<div class="f_color">
								<img src="/theme/activity/2016_09_Luggage/pc/img/picture/picture_four.png" alt="" data="opengoodsdetail"/>
								</div>
								<div class="picture_font">
									<div class="activity">
										<span class="activity_buy">活动价：</span><span class="money">216.30</span><span class="activity_buy"> 元</span>
										<p class="black">原价：309元</p>
									</div>
									<div class="narrate">
										<p class="f_whone">百事可乐拉链箱20寸蓝</p>
										<p class="f_white">工匠美学  颠覆之作</p>
									</div>
									<div class="immediately" data="openinstantbuy">
										<span>立即购买</span>
									</div>
								</div>
							</a>
							
						</li>
						<li>
							
							<a href="http://item.soolife.cn/22387.html">
								<div class="f_color">
								<img src="/theme/activity/2016_09_Luggage/pc/img/picture/picture_five.png" alt="" data="opengoodsdetail"/>
								</div>
								<div class="picture_font">
									<div class="activity">
										<span class="activity_buy">活动价：</span><span class="money">237.30</span><span class="activity_buy"> 元</span>
										<p class="black">原价：339元</p>
									</div>
									<div class="narrate">
										<p class="f_whone">百事可乐拉链箱24寸黑</p>
										<p class="f_white">高标配置  超大容量</p>
									</div>
									<div class="immediately" data="openinstantbuy">
										<span>立即购买</span>
									</div>
								</div>
							</a>
							
						</li>
						<li>
							
							<a href="http://item.soolife.cn/22388.html">
								<div class="f_color">
								<img src="/theme/activity/2016_09_Luggage/pc/img/picture/picture_six.png" alt="" data="opengoodsdetail"/>
								</div>
								<div class="picture_font">
									<div class="activity">
										<span class="activity_buy">活动价：</span><span class="money">237.30</span><span class="activity_buy"> 元</span>
										<p class="black">原价：339元</p>
									</div>
									<div class="narrate">
										<p class="f_whone">百事可乐拉链箱24寸蓝</p>
										<p class="f_white">轻盈箱体 坚固耐压</p>
									</div>
									<div class="immediately" data="openinstantbuy">
										<span>立即购买</span>
									</div>
								</div>
							</a>
							
						</li>
						<li class="picture_one">
							
							<a href="http://item.soolife.cn/22411.html">
								<div class="f_color">
								<img src="/theme/activity/2016_09_Luggage/pc/img/picture/picture_seven.png" alt="" data="opengoodsdetail"/>
								</div>
								<div class="picture_font">
									<div class="activity">
										<span class="activity_buy">活动价：</span><span class="money">216.30</span><span class="activity_buy"> 元</span>
										<p class="black">原价：309元</p>
									</div>
									<div class="narrate">
										<p class="f_whone">百事原形拉链箱20寸</p>
										<p class="f_white">金属拉杆  独特质感</p>
									</div>
									<div class="immediately" data="openinstantbuy">
										<span>立即购买</span>
									</div>
								</div>
							</a>
							
						</li>
						<li>
							
							<a href="http://item.soolife.cn/26230.html">
								<div class="f_color">
								<img src="/theme/activity/2016_09_Luggage/pc/img/picture/picture_eight.png" alt=""data="opengoodsdetail" />
								</div>
								<div class="picture_font">
									<div class="activity">
										<span class="activity_buy">活动价：</span><span class="money">237.30</span><span class="activity_buy"> 元</span>
										<p class="black">原价：339元</p>
									</div>
									<div class="narrate">
										<p class="f_whone">百事迷彩拉链箱24寸</p>
										<p class="f_white">轻盈其质  炫彩其色</p>
									</div>
									<div class="immediately" data="openinstantbuy">
										<span>立即购买</span>
									</div>
								</div>
							</a>
							
						</li>
						<li>
							
							<a href="http://item.soolife.cn/26227.html">
								<div class="f_color">
								<img src="/theme/activity/2016_09_Luggage/pc/img/picture/picture_nine.png" alt=""data="opengoodsdetail" />
								</div>
								<div class="picture_font">
									<div class="activity">
										<span class="activity_buy">活动价：</span><span class="money">237.30</span><span class="activity_buy"> 元</span>
										<p class="black">原价：339元</p>
									</div>
									<div class="narrate">
										<p class="f_whone">百事原形拉链箱24寸</p>
										<p class="f_white">超大容量  坚固耐用</p>
									</div>
									<div class="immediately" data="openinstantbuy">
										<span>立即购买</span>
									</div>
								</div>
							</a>
							
						</li>
						<li>
							
							<a href="http://item.soolife.cn/26231.html">
								<div class="f_color">
								<img src="/theme/activity/2016_09_Luggage/pc/img/picture/picture_ten.png" alt="" data="opengoodsdetail"/>
								</div>
								<div class="picture_font">
									<div class="activity">
										<span class="activity_buy">活动价：</span><span class="money">237.30</span><span class="activity_buy"> 元</span>
										<p class="black">原价：339元</p>
									</div>
									<div class="narrate">
										<p class="f_whone">百事98拉链箱24寸</p>
										<p class="f_white">美妙伴侣  爱在旅途</p>
									</div>
									<div class="immediately" data="openinstantbuy">
										<span>立即购买</span>
									</div>
								</div>
							</a>
							
						</li>
						<li class="picture_one">
							
							<a href="http://item.soolife.cn/22413.html">
								<div class="f_color">
								<img src="/theme/activity/2016_09_Luggage/pc/img/picture/picture_eleven.png" alt="" data="opengoodsdetail"/>
								</div>
								<div class="picture_font">
									<div class="activity">
										<span class="activity_buy">活动价：</span><span class="money">216.30</span><span class="activity_buy"> 元</span>
										<p class="black">原价：309元</p>
									</div>
									<div class="narrate">
										<p class="f_whone">百事横纹拉链箱20寸黑</p>
										<p class="f_white">酷雅绅士  有型有款</p>
									</div>
									<div class="immediately" data="openinstantbuy">
										<span>立即购买</span>
									</div>
								</div>
							</a>
							
						</li>
						<li>
							
							<a href="http://item.soolife.cn/22414.html">
								<div class="f_color">
								<img src="/theme/activity/2016_09_Luggage/pc/img/picture/picture_twety.png" alt="" data="opengoodsdetail"/>
								</div>
								<div class="picture_font">
									<div class="activity">
										<span class="activity_buy">活动价：</span><span class="money">216.30</span><span class="activity_buy"> 元</span>
										<p class="black">原价：309元</p>
									</div>
									<div class="narrate">
										<p class="f_whone">百事可乐拉链箱20寸蓝</p>
										<p class="f_white">密封防水  时尚经典</p>
									</div>
									<div class="immediately" data="openinstantbuy">
										<span>立即购买</span>
									</div>
								</div>
							</a>
							
						</li>
						<li>
							
							<a href="http://item.soolife.cn/22415.html">
								<div class="f_color">
								<img src="/theme/activity/2016_09_Luggage/pc/img/picture/picture_thirty.png" alt="" data="opengoodsdetail"/>
									</div>
								<div class="picture_font">
									<div class="activity">
										<span class="activity_buy">活动价：</span><span class="money">216.30</span><span class="activity_buy"> 元</span>
										<p class="black">原价：309元</p>
									</div>
									<div class="narrate">
										<p class="f_whone">百事横纹拉链箱20寸银</p>
										<p class="f_white">价格适中  防撬设计</p>
									</div>
									<div class="immediately" data="openinstantbuy">
										<span>立即购买</span>
									</div>
								</div>
							</a>
						
						</li>
						<li>
							
							<a href="http://item.soolife.cn/22433.html">
								<div class="f_color">
								<img src="/theme/activity/2016_09_Luggage/pc/img/picture/picture_fourty.png" alt="" data="opengoodsdetail"/>
								</div>
								<div class="picture_font">
									<div class="activity">
										<span class="activity_buy">活动价：</span><span class="money">236.30</span><span class="activity_buy"> 元</span>
										<p class="black">原价：339元</p>
									</div>
									<div class="narrate">
										<p class="f_whone">百事横纹拉链箱24寸黑</p>
										<p class="f_white">正品行货  三包服务</p>
									</div>
									<div class="immediately" data="openinstantbuy">
										<span>立即购买</span>
									</div>
								</div>
							</a>
							
						</li>
					</ul>
				</div>
			</div>
			<!--新品推荐-->
			<div id="new_product">
				<img src="/theme/activity/2016_09_Luggage/pc/img/banner/new_product_banner.jpg" alt="" />
			</div>
			<div class="f_pc_first">
			<div class="f_pc_picture">
					<ul>
						<li class="picture_one">
							
							<a href="http://item.soolife.cn/22434.html">
								<div class="f_color">
								<img src="/theme/activity/2016_09_Luggage/pc/img/new_product/new_product_one.png" alt=""data="opengoodsdetail" />
								</div>
								<div class="picture_font">
									<div class="activity">
										<span class="activity_buy">活动价：</span><span class="money">237.30</span><span class="activity_buy"> 元</span>
										<p class="black">原价：339元</p>
									</div>
									<div class="narrate">
										<p class="f_whone">百事横纹拉链箱24寸蓝</p>
										<p class="f_white">放任个性  安全之旅</p>
									</div>
									<div class="immediately" data="openinstantbuy">
										<span>立即购买</span>
									</div>
								</div>
							</a>
							
						</li>
						<li>
							
							<a href="http://item.soolife.cn/22435.html">
								<div class="f_color">
								<img src="/theme/activity/2016_09_Luggage/pc/img/new_product/new_product_two.png" alt="" data="opengoodsdetail"/>
								</div>
								<div class="picture_font">
									<div class="activity">
										<span class="activity_buy">活动价：</span><span class="money">216.30</span><span class="activity_buy"> 元</span>
										<p class="black">原价：309元</p>
									</div>
									<div class="narrate">
										<p class="f_whone">百事横纹拉链箱20寸黑</p>
										<p class="f_white">时尚拉杆  成功首选</p>
									</div>
									<div class="immediately" data="openinstantbuy">
										<span>立即购买</span>
									</div>
								</div>
							</a>
							
						</li>
						<li>
							
							<a href="http://item.soolife.cn/22454.html">
								<div class="f_color">
								<img src="/theme/activity/2016_09_Luggage/pc/img/new_product/new_product_three.png" alt="" data="opengoodsdetail"/>
								</div>
								<div class="picture_font">
									<div class="activity">
										<span class="activity_buy">活动价：</span><span class="money">216.30</span><span class="activity_buy"> 元</span>
										<p class="black">原价：309元</p>
									</div>
									<div class="narrate">
										<p class="f_whone">百事竖纹拉链箱20寸黑</p>
										<p class="f_white">时尚经典  酷派绅士</p>
									</div>
									<div class="immediately" data="openinstantbuy">
										<span>立即购买</span>
									</div>
								</div>
							</a>
							
						</li>
						<li>
							
							<a href="http://item.soolife.cn/22455.html">
								<div class="f_color">
								<img src="/theme/activity/2016_09_Luggage/pc/img/new_product/new_product_four.png" alt="" data="opengoodsdetail"/>
								</div>
								<div class="picture_font">
									<div class="activity">
										<span class="activity_buy">活动价：</span><span class="money">216.30</span><span class="activity_buy"> 元</span>
										<p class="black">原价：309元</p>
									</div>
									<div class="narrate">
										<p class="f_whone">百事竖纹拉链箱20寸蓝</p>
										<p class="f_white">魅力随行  轻松方便</p>
									</div>
									<div class="immediately" data="openinstantbuy">
										<span>立即购买</span>
									</div>
								</div>
							</a>
							
						</li>
						<li class="picture_one">
							
							<a href="http://item.soolife.cn/22461.html">
								<div class="f_color">
								<img src="/theme/activity/2016_09_Luggage/pc/img/new_product/new_product_five.png" alt="" data="opengoodsdetail"/>
								</div>
								<div class="picture_font">
									<div class="activity">
										<span class="activity_buy">活动价：</span><span class="money">216.30</span><span class="activity_buy"> 元</span>
										<p class="black">原价：309元</p>
									</div>
									<div class="narrate">
										<p class="f_whone">百事竖纹拉链箱20寸黑</p>
										<p class="f_white">时尚简约  便捷出行</p>
									</div>
									<div class="immediately" data="openinstantbuy">
										<span>立即购买</span>
									</div>
								</div>
							</a>
							
						</li>
						<li>
							
							<a href="http://item.soolife.cn/22462.html">
								<div class="f_color">
								<img src="/theme/activity/2016_09_Luggage/pc/img/new_product/new_product_six.png" alt="" data="opengoodsdetail"/>
								</div>
								<div class="picture_font">
									<div class="activity">
										<span class="activity_buy">活动价：</span><span class="money">237.30</span><span class="activity_buy"> 元</span>
										<p class="black">原价：339元</p>
									</div>
									<div class="narrate">
										<p class="f_whone">百事竖纹拉链箱24寸蓝</p>
										<p class="f_white">时尚优雅  坚固耐压</p>
									</div>
									<div class="immediately" data="openinstantbuy">
										<span>立即购买</span>
									</div>
								</div>
							</a>
							
						</li>
						<li>
							
							<a href="http://item.soolife.cn/22478.html">
								<div class="f_color">
								<img src="/theme/activity/2016_09_Luggage/pc/img/new_product/new_product_seven.png" alt=""data="opengoodsdetail" />
								</div>
								<div class="picture_font">
									<div class="activity">
										<span class="activity_buy">活动价：</span><span class="money">216.30</span><span class="activity_buy"> 元</span>
										<p class="black">原价：309元</p>
									</div>
									<div class="narrate">
										<p class="f_whone">百事logo拉链箱20寸黑</p>
										<p class="f_white">智能收纳  商旅必备</p>
									</div>
									<div class="immediately" data="openinstantbuy">
										<span>立即购买</span>
									</div>
								</div>
							</a>
							
						</li>
						<li>
							
							<a href="http://item.soolife.cn/22481.html">
								<div class="f_color">
								<img src="/theme/activity/2016_09_Luggage/pc/img/new_product/new_product_ten.png" alt="" data="opengoodsdetail"/>
								</div>
								<div class="picture_font">
									<div class="activity">
										<span class="activity_buy">活动价：</span><span class="money">216.30</span><span class="activity_buy"> 元</span>
										<p class="black">原价：309元</p>
									</div>
									<div class="narrate">
										<p class="f_whone">百事logo拉链箱20寸蓝</p>
										<p class="f_white">奢华大气  稳重典雅</p>
									</div>
									<div class="immediately" data="openinstantbuy">
										<span>立即购买</span>
									</div>
								</div>
							</a>
							
						</li>
						<li class="picture_one">
							
							<a href="http://item.soolife.cn/22480.html">
								<div class="f_color">
								<img src="/theme/activity/2016_09_Luggage/pc/img/new_product/new_product_nine.png" alt="" data="opengoodsdetail"/>
								</div>
								<div class="picture_font">
									<div class="activity">
										<span class="activity_buy">活动价：</span><span class="money">216.30</span><span class="activity_buy"> 元</span>
										<p class="black">原价：309元</p>
									</div>
									<div class="narrate">
										<p class="f_whone">百事logo拉链箱20寸白</p>
										<p class="f_white">优雅白色  气质出行</p>
									</div>
									<div class="immediately" data="openinstantbuy">
										<span>立即购买</span>
									</div>
								</div>
							</a>
							
						</li>
						<li>
							
							<a href="http://item.soolife.cn/22479.html">
								<div class="f_color">
								<img src="/theme/activity/2016_09_Luggage/pc/img/new_product/new_product_eight.png" alt="" data="opengoodsdetail"/>
								</div>
								<div class="picture_font">
									<div class="activity">
										<span class="activity_buy">活动价：</span><span class="money">216.30</span><span class="activity_buy"> 元</span>
										<p class="black">原价：309元</p>
									</div>
									<div class="narrate">
										<p class="f_whone">百事logo拉链箱20寸银</p>
										<p class="f_white">不然尘世  别具一格</p>
									</div>
									<div class="immediately" data="openinstantbuy">
										<span>立即购买</span>
									</div>
								</div>
							</a>
							
						</li>
						<li>
							
							<a href="http://item.soolife.cn/22498.html">
								<div class="f_color">
								<img src="/theme/activity/2016_09_Luggage/pc/img/new_product/new_product_eleven.png" alt=""data="opengoodsdetail" />
									</div>
								<div class="picture_font">
									<div class="activity">
										<span class="activity_buy">活动价：</span><span class="money">237.30</span><span class="activity_buy"> 元</span>
										<p class="black">原价：309元</p>
									</div>
									<div class="narrate">
										<p class="f_whone">百事logo拉链箱24寸黑</p>
										<p class="f_white">加大容量  就是能装</p>
									</div>
									<div class="immediately" data="openinstantbuy">
										<span>立即购买</span>
									</div>
								</div>
							</a>
						
						</li>
						<li>
							
							<a href="http://item.soolife.cn/22499.html">
								<div class="f_color">
								<img src="/theme/activity/2016_09_Luggage/pc/img/new_product/new_product_twety.png" alt="" data="opengoodsdetail"/>
								</div>
								<div class="picture_font">
									<div class="activity">
										<span class="activity_buy">活动价：</span><span class="money">237.30</span><span class="activity_buy"> 元</span>
										<p class="black">原价：339元</p>
									</div>
									<div class="narrate">
										<p class="f_whone">百事logo拉链箱24寸蓝</p>
										<p class="f_white">高贵品质  彰显格调</p>
									</div>
									<div class="immediately" data="openinstantbuy">
										<span>立即购买</span>
									</div>
								</div>
							</a>
							
						</li>
					</ul>
				</div>
				<div class="f_bottom">
					<a href="http://item.soolife.cn/22501.html">
						<img src="/theme/activity/2016_09_Luggage/pc/img/bottom/bottom_one.jpg" alt="" data="opengoodsdetail"/>
						<div data="openinstantbuy" class="purchase_one"></div>
					</a>
					<a href="http://item.soolife.cn/22500.html">
						<img class="bottom_first" src="/theme/activity/2016_09_Luggage/pc/img/bottom/bottom_two.jpg" alt="" data="opengoodsdetail"/>
						<div data="openinstantbuy" class="purchase_two"></div>
					</a>
				</div>
				</div>
				
				<div class="bottom_three">
					<img src="/theme/activity/2016_09_Luggage/pc/img/bottom/banner_three.jpg" alt="" />
				</div>
		</div>
	</body>

