

	<head>
		<meta charset="utf-8" />
		<title>金九团圆惠</title>
		<link rel="stylesheet" href="/theme/activity/2016_09_Chinese Moon Festival/pc/css/pc_reunion.css" />
	</head>

	<body>
		<div class="f_pc_reunion">
			<!--banner-->
			<div class="f_pc_banner">
				<img src="/theme/activity/2016_09_Chinese Moon Festival/pc/img/banner/banner_one.jpg" alt="" align="top" />
				<img src="/theme/activity/2016_09_Chinese Moon Festival/pc/img/banner/banner_two.jpg" alt="" align="top" />
				<img src="/theme/activity/2016_09_Chinese Moon Festival/pc/img/banner/banner_three.jpg" alt="" align="top" />
			</div>
			<div class="f_reunion_size">
				<!--文字-->
				<div class="f_size">
					<img src="/theme/activity/2016_09_Chinese Moon Festival/pc/img/banner/banner_up.png" alt="" />
				</div>
				<!--9元秒杀-->
				<div class="f_nine">
					<img src="/theme/activity/2016_09_Chinese Moon Festival/pc/img/nine_prefecture/nine_prefecture.png" alt="" />
				</div>
				<div class="f_background">
					<div></div>
					<div class="f_product">
						<ul>
							<li>
								<a href="http://item.soolife.cn/28932.html">
									<img src="/theme/activity/2016_09_Chinese Moon Festival/pc/img/nine_prefecture/prefecture_one.png" alt="" data="opengoodsdetail"/>
									<div data="openinstantbuy" class="purchase_one"></div>
									<div class="typeface">
										<p class="disinfect">银京消毒擦片</p>
										<p class="disinfect">随身携带 更易使用</p>
										<div class="bg_white">
											<div class=wbg_white></div>
											<span class="seckill">秒杀价:</span>
											<span class="nine_yuan">9元</span>
											<span class="immediately">立即抢购</span>
										</div>
									</div>
								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/29560.html">
									<img src="/theme/activity/2016_09_Chinese Moon Festival/pc/img/nine_prefecture/prefecture_two.png" alt="" data="opengoodsdetail"/>
									<div data="openinstantbuy" class="purchase_two"></div>
									<div class="typeface">
										<p class="disinfect">洁斯家垃圾袋</p>
										<p class="disinfect">坚韧耐用 滴水不漏</p>
										<div class="bg_white">
											<div class=wbg_white></div>
											<span class="seckill">秒杀价:</span>
											<span class="nine_yuan">9元</span>
											<span class="immediately">立即抢购</span>
										</div>
									</div>
								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/29433.html">
									<img src="/theme/activity/2016_09_Chinese Moon Festival/pc/img/nine_prefecture/prefecture_three.png" alt="" data="opengoodsdetail"/>
									<div data="openinstantbuy" class="purchase_three"></div>
									<div class="typeface">
										<p class="disinfect">湘妹子香辣腐乳</p>
										<p class="disinfect">湘味难挡 醇香可口</p>
										<div class="bg_white">
											<div class=wbg_white></div>
											<span class="seckill">秒杀价:</span>
											<span class="nine_yuan">9元</span>
											<span class="immediately">立即抢购</span>
										</div>
									</div>
								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/33449.html">
									<img src="/theme/activity/2016_09_Chinese Moon Festival/pc/img/nine_prefecture/prefecture_four.png" alt=""data="opengoodsdetail" />
									<div data="openinstantbuy" class="purchase_four"></div>
									<div class="typeface">
										<p class="disinfect">多情玫瑰洗衣皂</p>
										<p class="disinfect">深层去污 馨香怡人</p>
										<div class="bg_white">
											<div class=wbg_white></div>
											<span class="seckill">秒杀价:</span>
											<span class="nine_yuan">9元</span>
											<span class="immediately">立即抢购</span>
										</div>
									</div>
								</a>
							</li>
						</ul>
					</div>
				</div>
				<!--半价-->
				<div class="f_nine">
					<img src="/theme/activity/2016_09_Chinese Moon Festival/pc/img/half_price/half_price.png" alt="" />
				</div>
				<div class="f_half">
					<ul>
						<li>
							<a href="http://item.soolife.cn/23329.html">
								<img src="/theme/activity/2016_09_Chinese Moon Festival/pc/img/half_price/product_one.png" alt="" data="opengoodsdetail"/>
								<div data="openinstantbuy" class="purchase_one"></div>
								<div class="half_size">
									<p class="jiangshu">江苏裕德隆 熊掌菇</p>
									<p class="nutrition">肉质肥厚 营养丰富</p>
									<div class="f_layout">
										<span class="activity">活动价:</span><span class="rmb">64.4元</span>
										<div class="bg_white"></div>
										<span class="buy">立即购买</span>
									</div>
									<p class="bazaar">市场价：128元</p>
								</div>

							</a>
						</li>
						<li class="f_nine_two">
							<a href="http://item.soolife.cn/34149.html">
								<img src="/theme/activity/2016_09_Chinese Moon Festival/pc/img/half_price/product_two.png" alt="" data="opengoodsdetail"/>
								<div data="openinstantbuy" class="purchase_two"></div>
								<div class="half_size">
									<p class="jiangshu">品味高脚杯</p>
									<p class="nutrition">时尚设计 品味生活</p>
									<div class="f_layout">
										<span class="activity">活动价:</span><span class="rmb">39.9元</span>
										<div class="bg_white"></div>
										<span class="buy">立即购买</span>
									</div>
									<p class="bazaar">市场价：79.8元</p>
								</div>
							</a>
						</li>
						<li class="f_nine_two">
							<a href="http://item.soolife.cn/24367.html">
								<img src="/theme/activity/2016_09_Chinese Moon Festival/pc/img/half_price/product_three.png" alt="" data="opengoodsdetail"/>
								<div data="openinstantbuy" class="purchase_three"></div>
								<div class="half_size">
									<p class="jiangshu">激浪 碳酸饮料</p>
									<p class="nutrition">爆款必BUY 火爆抢购</p>
									<div class="f_layout">
										<span class="activity">活动价:</span><span class="rmb">1元</span>
										<div class="bg_white"></div>
										<span class="buy">立即购买</span>
									</div>
									<p class="bazaar">市场价：2.1元</p>
								</div>
							</a>
						</li>
					</ul>
				</div>
				<!--热销爆款-->
				<div class="f_nine">
					<img src="/theme/activity/2016_09_Chinese Moon Festival/pc/img/moldbaby/moldbaby_size.png" alt="" />
				</div>
				<div class="sell_like">
					<div>
						<ul>
							<li class="first_sell">
								<a href="http://item.soolife.cn/29568.html">
									<img src="/theme/activity/2016_09_Chinese Moon Festival/pc/img/moldbaby/commodity_one.png" alt="" data="opengoodsdetail"/>
									<div data="openinstantbuy" class="purchase_one"></div>
									<div id="entirety">
										<div class="first_line">
											<p class="olive_oil">特级初榨橄榄油 </p>
											<p class="olive_oil">特级初榨 健康安全</p>
										</div>
										<div class="price">
											<div class="marketplace">
												<span class="activity">活动价：</span><span class="element">100元</span>
												<span class="bazaar">市场价：200元</span>
											</div>
											<div class="buy_Now">
												<span>立即 购买</span>
											</div>
										</div>
									</div>

								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/30759.html">
									<img src="/theme/activity/2016_09_Chinese Moon Festival/pc/img/moldbaby/commodity_two.png" alt="" data="opengoodsdetail"/>
									<div data="openinstantbuy" class="purchase_one"></div>
									<div id="entirety">
										<div class="first_line">
											<p class="olive_oil">恒大兴安 米油套装 </p>
											<p class="olive_oil">买的放心 吃的安心</p>
										</div>
										<div class="price">
											<div class="marketplace">
												<span class="activity">活动价：</span><span class="element">99元</span>
												<span class="bazaar">市场价：228元</span>
											</div>
											<div class="buy_Now">
												<span>立即 购买</span>
											</div>
										</div>
									</div>

								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/33312.html">
									<img src="/theme/activity/2016_09_Chinese Moon Festival/pc/img/moldbaby/commodity_three.png" alt="" data="opengoodsdetail"/>
									<div data="openinstantbuy" class="purchase_one"></div>
									<div id="entirety">
										<div class="first_line">
											<p class="olive_oil">瑞德小麦啤酒 </p>
											<p class="olive_oil">德国金奖 纯正口感</p>
										</div>
										<div class="price">
											<div class="marketplace">
												<span class="activity">活动价：</span><span class="element">10元</span>
												<span class="bazaar">市场价：36元</span>
											</div>
											<div class="buy_Now">
												<span>立即 购买</span>
											</div>
										</div>
									</div>

								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/34004.html">
									<img src="/theme/activity/2016_09_Chinese Moon Festival/pc/img/moldbaby/commodity_four.png" alt="" data="opengoodsdetail"/>
									<div data="openinstantbuy" class="purchase_one"></div>
									<div id="entirety">
										<div class="first_line">
											<p class="olive_oil">森淼 冻干枸杞 </p>
											<p class="olive_oil">美味健康 源于自然</p>
										</div>
										<div class="price">
											<div class="marketplace">
												<span class="activity">活动价：</span><span class="element">38.4元</span>
												<span class="bazaar">市场价：68元</span>
											</div>
											<div class="buy_Now">
												<span>立即 购买</span>
											</div>
										</div>
									</div>

								</a>
							</li>
						</ul>
					</div>
				</div>
				<!--新品推荐-->
				<div class="f_nine">
					<img src="/theme/activity/2016_09_Chinese Moon Festival/pc/img/boutique/recommend_size.png" alt="" />
				</div>
				<div class="f_half">
					<ul>
						<li>
							<a href="http://item.soolife.cn/29411.html">
								<img src="/theme/activity/2016_09_Chinese Moon Festival/pc/img/boutique/merchandise_one.png" alt="" data="opengoodsdetail"/>
								<div data="openinstantbuy" class="purchase_one"></div>
								<div class="half_size">
									<p class="jiangshu">西班牙干白葡萄酒</p>
									<p class="nutrition">原装进口 买一赠一</p>
									<div class="f_layout">
										<span class="activity">活动价:</span><span class="rmb">100元</span>
										<div class="bg_white"></div>
										<span class="buy">立即购买</span>
									</div>
									<p class="bazaar">市场价：100元</p>
								</div>

							</a>
						</li>
						<li class="f_nine_two">
							<a href="http://item.soolife.cn/15450.html">
								<img src="/theme/activity/2016_09_Chinese Moon Festival/pc/img/boutique/merchandise_two.png" alt="" data="opengoodsdetail"/>
								<div data="openinstantbuy" class="purchase_two"></div>
								<div class="half_size">
									<p class="jiangshu">蜂毒原液面膜 </p>
									<p class="nutrition">天然温和 极致再生</p>
									<div class="f_layout">
										<span class="activity">活动价:</span><span class="rmb">205.6元</span>
										<div class="bg_white"></div>
										<span class="buy">立即购买</span>
									</div>
									<p class="bazaar">市场价：368元</p>
								</div>
							</a>
						</li>
						<li class="f_nine_two">
							<a href="http://item.soolife.cn/36364.html">
								<img src="/theme/activity/2016_09_Chinese Moon Festival/pc/img/boutique/merchandise_three.png" alt="" data="opengoodsdetail"/>
								<div data="openinstantbuy" class="purchase_three"></div>
								<div class="half_size">
									<p class="jiangshu">磨砂面防刮旅行箱</p>
									<p class="nutrition">品质生活 时尚旅行</p>
									<div class="f_layout">
										<span class="activity">活动价:</span><span class="rmb">199元</span>
										<div class="bg_white"></div>
										<span class="buy">立即购买</span>
									</div>
									<p class="bazaar">市场价：1599元</p>
								</div>
							</a>
						</li>
					</ul>
				</div>
				<div class="new_product">
					<ul>
						<li >
							<a href="http://item.soolife.cn/36349.html">
								<img src="/theme/activity/2016_09_Chinese Moon Festival/pc/img/boutique/merchandise_four.png" alt="" data="opengoodsdetail"/>
								<div data="openinstantbuy" class="purchase_one"></div>
								<div id="entirety">
										<div class="first_line">
											<p class="olive_oil">镜面万向轮拉杆箱 </p>
											<p class="olive_oil">智能收纳  商旅必备</p>
										</div>
										<div class="price">
											<div class="marketplace">
												<span class="activity">活动价：</span><span class="element">239元</span>
												<span class="bazaar">市场价：2288元</span>
											</div>
											<div class="buy_Now">
												<span>立即 购买</span>
											</div>
										</div>
									</div>
							</a>
						</li>
						<li class="red_dates">
							<a href="http://item.soolife.cn/33322.html">
								<img src="/theme/activity/2016_09_Chinese Moon Festival/pc/img/boutique/merchandise_five.png" alt="" data="opengoodsdetail"/>
								<div data="openinstantbuy" class="purchase_one"></div>
								<div id="entirety">
										<div class="first_line">
											<p class="olive_oil">麦卢卡蜂蜜 </p>
											<p class="olive_oil">原生态  好蜂蜜</p>
										</div>
										<div class="price">
											<div class="marketplace">
												<span class="activity">活动价：</span><span class="element">398元</span>
												<span class="bazaar">市场价：639元</span>
											</div>
											<div class="buy_Now">
												<span>立即 购买</span>
											</div>
										</div>
									</div>
							</a>
						</li>
						<li class="red_dates">
							<a href="http://item.soolife.cn/33278.html">
								<img src="/theme/activity/2016_09_Chinese Moon Festival/pc/img/boutique/merchandise_six.png" alt=""data="opengoodsdetail" />
								<div data="openinstantbuy" class="purchase_one"></div>
								<div id="entirety">
										<div class="first_line">
											<p class="olive_oil">红枣夹核桃礼盒装 </p>
											<p class="olive_oil">甄选食材  双重美味</p>
										</div>
										<div class="price">
											<div class="marketplace">
												<span class="activity">活动价：</span><span class="element">138元</span>
												<span class="bazaar">市场价：140元</span>
											</div>
											<div class="buy_Now">
												<span>立即 购买</span>
											</div>
										</div>
									</div>
							</a>
						</li>
						<li class="red_dates">
							<a href="http://item.soolife.cn/33448.html">
								<img src="/theme/activity/2016_09_Chinese Moon Festival/pc/img/boutique/merchandise_seven.png" alt="" data="opengoodsdetail"/>
								<div data="openinstantbuy" class="purchase_one"></div>
								<div id="entirety">
										<div class="first_line">
											<p class="olive_oil">多情玫瑰洗衣液 </p>
											<p class="olive_oil">洁净亮丽  炫彩如新</p>
										</div>
										<div class="price">
											<div class="marketplace">
												<span class="activity">活动价：</span><span class="element">31.6元</span>
												<span class="bazaar">市场价：42元</span>
											</div>
											<div class="buy_Now">
												<span>立即 购买</span>
											</div>
										</div>
									</div>
							</a>
						</li>
						
					</ul>
				</div>
				<!--精选美食-->
				<div class="f_nine_cate">
					<img src="/theme/activity/2016_09_Chinese Moon Festival/pc/img/cate/cate_size.png" alt="" />
				</div>
				<div class="f_cate">
					<ul>
						<li>
							<a href="http://item.soolife.cn/35849.html">
								<img src="/theme/activity/2016_09_Chinese Moon Festival/pc/img/cate/commodity_one.png" alt=""data="opengoodsdetail" />
								<div data="openinstantbuy" class="purchase_one"></div>
								<div class="appetizing">
									<div class="currant">
										<span class="f_activity">活动价：</span><span class="forty">40元</span><span class="f_buy">立即购买</span>

									</div>
									<p>市场价45元</p>
								</div>
							</a>
						</li>
						<li>
							<a href="http://item.soolife.cn/34139.html">
								<img src="/theme/activity/2016_09_Chinese Moon Festival/pc/img/cate/commodity_two.png" alt="" data="opengoodsdetail"/>
								<div data="openinstantbuy" class="purchase_two"></div>
								<div class="appetizing">
									<div class="currant cranberry">
										<span class="f_activity">活动价：</span><span class="forty">26元</span><span class="f_buy">立即购买</span>
									</div>
									<p class="twenty_nine">市场价29元</p>
								</div>
							</a>
						</li>
					</ul>
				</div>
				<div class="sell_like">
					<div>
						<ul>
							<li class="first_sell">
								<a href="http://item.soolife.cn/27158.html">
									<img src="/theme/activity/2016_09_Chinese Moon Festival/pc/img/cate/commodity_three.png" alt="" data="opengoodsdetail"/>
									<div data="openinstantbuy" class="purchase_one"></div>
									<div id="entirety">
										<div class="first_line">
											<p class="olive_oil">上岛混合型冻干咖啡 </p>
											<p class="olive_oil">口感醇厚  提神醒目</p>
										</div>
										<div class="price">
											<div class="marketplace">
												<span class="activity">活动价：</span><span class="element">32元</span>
												<span class="bazaar">市场价：42元</span>
											</div>
											<div class="buy_Now">
												<span>立即 购买</span>
											</div>
										</div>
									</div>

								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/35907.html">
									<img src="/theme/activity/2016_09_Chinese Moon Festival/pc/img/cate/commodity_four.png" alt="" data="opengoodsdetail"/>
									<div data="openinstantbuy" class="purchase_one"></div>
									<div id="entirety">
										<div class="first_line">
											<p class="olive_oil">奥克之魅葡萄酒 </p>
											<p class="olive_oil">源自法国  品质保障</p>
										</div>
										<div class="price">
											<div class="marketplace">
												<span class="activity">活动价：</span><span class="element">128元</span>
												<span class="bazaar">市场价：158元</span>
											</div>
											<div class="buy_Now">
												<span>立即 购买</span>
											</div>
										</div>
									</div>

								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/31091.html">
									<img src="/theme/activity/2016_09_Chinese Moon Festival/pc/img/cate/commodity_five.png" alt="" data="opengoodsdetail"/>
									<div data="openinstantbuy" class="purchase_one"></div>
									<div id="entirety">
										<div class="first_line">
											<p class="olive_oil">茱迪亚红葡萄酒 </p>
											<p class="olive_oil">入口饱满  余味悠长</p>
										</div>
										<div class="price">
											<div class="marketplace">
												<span class="activity">活动价：</span><span class="element">61.2元</span>
												<span class="bazaar">市场价：108元</span>
											</div>
											<div class="buy_Now">
												<span>立即 购买</span>
											</div>
										</div>
									</div>

								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/26426.html">
									<img src="/theme/activity/2016_09_Chinese Moon Festival/pc/img/cate/commodity_six.png" alt="" data="opengoodsdetail"/>
									<div data="openinstantbuy" class="purchase_one"></div>
									<div id="entirety">
										<div class="first_line">
											<p class="olive_oil">嘉友特浓牛乳味饼干  </p>
											<p class="olive_oil">解馋神物  贴心之选</p>
										</div>
										<div class="price">
											<div class="marketplace">
												<span class="activity">活动价：</span><span class="element">11.8元</span>
												<span class="bazaar">市场价：12.8元</span>
											</div>
											<div class="buy_Now">
												<span>立即 购买</span>
											</div>
										</div>
									</div>

								</a>
							</li>
						</ul>
					</div>
				</div>

			</div>
			<div>
				<img src="/theme/activity/2016_09_Chinese Moon Festival/pc/img/banner/footer.png" alt="" />
			</div>
		</div>
	</body>
