<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>如此生活|满额抽奖</title>
    <meta name="viewport" content="width=device-width, initial-scale=1,maximum-scale=1,user-scalable=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <link rel="stylesheet" type="text/css" href="/public/css/page404.css"/>
</head>
<body>
    <!-- 头部 -->
    <div id="soo-header">
        <div id="header-left"><a href="{{url_m}}/mindex/index.html"> <img src="../public/img/lottery/shop_back_black@2x.png" alt=""></a></div>
    </div>
    <div class="hkl-nr">
        <img src="/public/img/page1@2x.png" alt="">
        <p>咦，出错误啦~</p>
    </div>
</body>

</html>

<script src="/public/js/rem.js"></script>