<!DOCTYPE html>
<html>

	<head>
		<meta charset="utf-8" />
		<title>水杯大促</title>
		<link rel="stylesheet" type="text/css" href="/theme/activity/2016_08_glass/mobile/css/app_water.css" />
		<link rel="stylesheet" type="text/css" href="/public/mobile/css/foot.css" />
	</head>

	<body>
		<div class="f_water">
			<!--banner-->
			<div class="f_banner">
				<img src="/theme/activity/2016_08_glass/mobile/img/banner/banner.png" alt="" />
			</div>
			<!--爆款直降-->
			<div class="f_moldbaby">
				<div class="descend">
					<img src="/theme/activity/2016_08_glass/mobile/img/blast/blast_one.png" alt="" />
				</div>
				<div class="discount">
					<a href="http://item.soolife.cn/28791.html">
						<img src="/theme/activity/2016_08_glass/mobile/img/blast/blast_three.png" alt="" />
					</a>
					<a href="http://item.soolife.cn/28785.html">
						<img src="/theme/activity/2016_08_glass/mobile/img/blast/blast_three.png" alt="" />
					</a>
				</div>
				<!--五折-->
				<div class="five_discount">
					<div class="five_dis">
						<a href="">
							<img src="/theme/activity/2016_08_glass/mobile/img/five_fold/five-discount.png" alt="" />
						</a>
					</div>
					<div class="f_product">
						<ul>
							<li>
								<a href="http://item.soolife.cn/28836.html">
									<img src="/theme/activity/2016_08_glass/mobile/img/five_fold/commodity-one.jpg" alt="" />
									<div class="down_content">
										<div class="character">
											<p class="cat">爵士猫PC杯YH-6103</p>
											<p class="livelihood">缤纷色彩 多彩生活</p>
										</div>
										<div class="cost">
											<span class="scalping">活动价：</span><span class="much">35.25 </span><span class="scalping">元</span><span class="original_cost">原价:70.5元</span>
										</div>
										<div date="" class="instantbuy">
											<a href="">
												<img src="/theme/activity/2016_08_glass/mobile/img/eight_fold/immediately.jpg" alt="" />
											</a>
										</div>
									</div>
								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/28815.html">
									<img src="/theme/activity/2016_08_glass/mobile/img/five_fold/commodity-two.jpg" alt="" />
									<div class="down_content">
										<div class="character">
											<p class="cat">爵士猫PC杯YH-6003</p>
											<p class="livelihood">独特格调 尊贵气质</p>
										</div>
										<div class="cost">
											<span class="scalping">活动价：</span><span class="much">36.75 </span><span class="scalping">元</span><span class="original_cost">原价:73.5元</span>
										</div>
										<div date="" class="instantbuy">
											<a href="">
												<img src="/theme/activity/2016_08_glass/mobile/img/eight_fold/immediately.jpg" alt="" />
											</a>
										</div>
									</div>
								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/28802.html">
									<img src="/theme/activity/2016_08_glass/mobile/img/five_fold/commodity-three.jpg" alt="" />
									<div class="down_content">
										<div class="character">
											<p class="cat">爵士猫PC杯YH-6012</p>
											<p class="livelihood">环保材质 健康无害</p>
										</div>
										<div class="cost">
											<span class="scalping">活动价：</span><span class="much">32.25 </span><span class="scalping">元</span><span class="original_cost">原价:64.5元</span>
										</div>
										<div date="" class="instantbuy">
											<a href="">
												<img src="/theme/activity/2016_08_glass/mobile/img/eight_fold/immediately.jpg" alt="" />
											</a>
										</div>
									</div>
								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/28807.html">
									<img src="/theme/activity/2016_08_glass/mobile/img/five_fold/commodity-four.jpg" alt="" />
									<div class="down_content">
										<div class="character">
											<p class="cat">爵士猫PC杯YH-6013</p>
											<p class="livelihood">缤纷色彩 多彩生活</p>
										</div>
										<div class="cost">
											<span class="scalping">活动价：</span><span class="much">36.75 </span><span class="scalping">元</span><span class="original_cost">原价:73.5元</span>
										</div>
										<div date="" class="instantbuy">
											<a href="">
												<img src="/theme/activity/2016_08_glass/mobile/img/eight_fold/immediately.jpg" alt="" />
											</a>
										</div>
									</div>
								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/28829.html">
									<img src="/theme/activity/2016_08_glass/mobile/img/five_fold/commodity-five.jpg" alt="" />
									<div class="down_content">
										<div class="character">
											<p class="cat">爵士猫PC杯YH-6101</p>
											<p class="livelihood">长久保温 耐寒耐热</p>
										</div>
										<div class="cost">
											<span class="scalping">活动价：</span><span class="much">25.25 </span><span class="scalping">元</span><span class="original_cost">原价:50.5元</span>
										</div>
										<div date="" class="instantbuy">
											<a href="">
												<img src="/theme/activity/2016_08_glass/mobile/img/eight_fold/immediately.jpg" alt="" />
											</a>
										</div>
									</div>
								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/28842.html">
									<img src="/theme/activity/2016_08_glass/mobile/img/five_fold/commodity-six.jpg" alt="" />
									<div class="down_content">
										<div class="character">
											<p class="cat">爵士猫PC杯YH-6505</p>
											<p class="livelihood">精致生活 源自细节</p>
										</div>
										<div class="cost">
											<span class="scalping">活动价：</span><span class="much">35.25 </span><span class="scalping">元</span><span class="original_cost">原价:70.5元</span>
										</div>
										<div date="" class="instantbuy">
											<a href="">
												<img src="/theme/activity/2016_08_glass/mobile/img/eight_fold/immediately.jpg" alt="" />
											</a>
										</div>
									</div>
								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/28848.html">
									<img src="/theme/activity/2016_08_glass/mobile/img/five_fold/commodity-seven.jpg" alt="" />
									<div class="down_content">
										<div class="character">
											<p class="cat">爵士猫PC杯YH-6506</p>
											<p class="livelihood">爆款五折 先买先得</p>
										</div>
										<div class="cost">
											<span class="scalping">活动价：</span><span class="much">39.75 </span><span class="scalping">元</span><span class="original_cost">原价:79.5元</span>
										</div>
										<div date="" class="instantbuy">
											<a href="">
												<img src="/theme/activity/2016_08_glass/mobile/img/eight_fold/immediately.jpg" alt="" />
											</a>
										</div>
									</div>
								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/28795.html">
									<img src="/theme/activity/2016_08_glass/mobile/img/five_fold/commodity-eight.jpg" alt="" />
									<div class="down_content">
										<div class="character">
											<p class="cat">爵士猫PC杯YH-6007</p>
											<p class="livelihood">时尚潮流 乐享生活</p>
										</div>
										<div class="cost">
											<span class="scalping">活动价：</span><span class="much">28.25 </span><span class="scalping">元</span><span class="original_cost">原价:56.5元</span>
										</div>
										<div date="" class="instantbuy">
											<a href="">
												<img src="/theme/activity/2016_08_glass/mobile/img/eight_fold/immediately.jpg" alt="" />
											</a>
										</div>
									</div>
								</a>
							</li>
						</ul>
					</div>
				</div>
				<!--八折-->
				<div class="five_discount">
					<div class="five_dis">
						<a href="">
							<img src="/theme/activity/2016_08_glass/mobile/img/eight_fold/eight-discount.png" alt="" />
						</a>
					</div>
					<div class="f_product">
						<ul>
							<li>
								<a href="http://item.soolife.cn/21848.html">
									<img src="/theme/activity/2016_08_glass/mobile/img/eight_fold/product-one.jpg" alt="" />
									<div class="down_content">
										<div class="character">
											<p class="cat">高真空保温杯6821-025</p>
											<p class="livelihood">轻巧便携 8色可选</p>
										</div>
										<div class="cost">
											<span class="scalping">活动价：</span><span class="much">99.00 </span><span class="scalping">元</span><span class="original_cost">原价:134.1元</span>
										</div>
										<div date="" class="instantbuy">
											<a href="">
												<img src="/theme/activity/2016_08_glass/mobile/img/eight_fold/immediately.jpg" alt="" />
											</a>
										</div>
									</div>
								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/21871.html">
									<img src="/theme/activity/2016_08_glass/mobile/img/eight_fold/product-two.jpg" alt="" />
									<div class="down_content">
										<div class="character">
											<p class="cat">高真空保温杯6821-035</p>
											<p class="livelihood">环保轻便 女神必备</p>
										</div>
										<div class="cost">
											<span class="scalping">活动价：</span><span class="much">111.0 </span><span class="scalping">元</span><span class="original_cost">原价:144.5元</span>
										</div>
										<div date="" class="instantbuy">
											<a href="">
												<img src="/theme/activity/2016_08_glass/mobile/img/eight_fold/immediately.jpg" alt="" />
											</a>
										</div>
									</div>
								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/21952.html">
									<img src="/theme/activity/2016_08_glass/mobile/img/eight_fold/product-three.jpg" alt="" />
									<div class="down_content">
										<div class="character">
											<p class="cat">高真空保温杯6892-030</p>
											<p class="livelihood">新品首发 至轻体验</p>
										</div>
										<div class="cost">
											<span class="scalping">活动价：</span><span class="much">148.8 </span><span class="scalping">元</span><span class="original_cost">原价:193.4元</span>
										</div>
										<div date="" class="instantbuy">
											<a href="">
												<img src="/theme/activity/2016_08_glass/mobile/img/eight_fold/immediately.jpg" alt="" />
											</a>
										</div>
									</div>
								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/23292.html">
									<img src="/theme/activity/2016_08_glass/mobile/img/eight_fold/product-four.jpg" alt="" />
									<div class="down_content">
										<div class="character">
											<p class="cat">施密特灵动直杯</p>
											<p class="livelihood">超轻杯身 滴水不漏</p>
										</div>
										<div class="cost">
											<span class="scalping">活动价：</span><span class="much">84.80 </span><span class="scalping">元</span><span class="original_cost">原价:148元</span>
										</div>
										<div date="" class="instantbuy">
											<a href="">
												<img src="/theme/activity/2016_08_glass/mobile/img/eight_fold/immediately.jpg" alt="" />
											</a>
										</div>
									</div>
								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/22040.html">
									<img src="/theme/activity/2016_08_glass/mobile/img/eight_fold/product-five.jpg" alt="" />
									<div class="down_content">
										<div class="character">
											<p class="cat">施密特灵动直杯500</p>
											<p class="livelihood">高端品质 低端价格</p>
										</div>
										<div class="cost">
											<span class="scalping">活动价：</span><span class="much">92.80 </span><span class="scalping">元</span><span class="original_cost">原价:120.6元</span>
										</div>
										<div date="" class="instantbuy">
											<a href="">
												<img src="/theme/activity/2016_08_glass/mobile/img/eight_fold/immediately.jpg" alt="" />
											</a>
										</div>
									</div>
								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/22163.html">
									<img src="/theme/activity/2016_08_glass/mobile/img/eight_fold/product-six.jpg" alt="" />
									<div class="down_content">
										<div class="character">
											<p class="cat">施密特名仕直杯</p>
											<p class="livelihood">时间在走 温暖依旧</p>
										</div>
										<div class="cost">
											<span class="scalping">活动价：</span><span class="much">92.80 </span><span class="scalping">元</span><span class="original_cost">原价:120.6元</span>
										</div>
										<div date="" class="instantbuy">
											<a href="">
												<img src="/theme/activity/2016_08_glass/mobile/img/eight_fold/immediately.jpg" alt="" />
											</a>
										</div>
									</div>
								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/22141.html">
									<img src="/theme/activity/2016_08_glass/mobile/img/eight_fold/product-seven.jpg" alt="" />
									<div class="down_content">
										<div class="character">
											<p class="cat">施密特名仕直杯320</p>
											<p class="livelihood">圆润杯身 超长保温</p>
										</div>
										<div class="cost">
											<span class="scalping">活动价：</span><span class="much">84.80 </span><span class="scalping">元</span><span class="original_cost">原价:110.2元</span>
										</div>
										<div date="" class="instantbuy">
											<a href="">
												<img src="/theme/activity/2016_08_glass/mobile/img/eight_fold/immediately.jpg" alt="" />
											</a>
										</div>
									</div>
								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/21742.html">
									<img src="/theme/activity/2016_08_glass/mobile/img/eight_fold/product-eight.jpg" alt="" />
									<div class="down_content">
										<div class="character">
											<p class="cat">清水木纹不锈钢咖啡</p>
											<p class="livelihood">结实耐用 时尚美观</p>
										</div>
										<div class="cost">
											<span class="scalping">活动价：</span><span class="much">119.1 </span><span class="scalping">元</span><span class="original_cost">原价:148.9元</span>
										</div>
										<div date="" class="instantbuy">
											<a href="">
												<img src="/theme/activity/2016_08_glass/mobile/img/eight_fold/immediately.jpg" alt="" />
											</a>
										</div>
									</div>
								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/32836.html">
									<img src="/theme/activity/2016_08_glass/mobile/img/eight_fold/product-nine.jpg" alt="" />
									<div class="down_content">
										<div class="character">
											<p class="cat">单层玻璃直筒杯</p>
											<p class="livelihood">健康材质 手工雕琢</p>
										</div>
										<div class="cost">
											<span class="scalping">活动价：</span><span class="much">63.20 </span><span class="scalping">元</span><span class="original_cost">原价:99.0元</span>
										</div>
										<div date="" class="instantbuy">
											<a href="">
												<img src="/theme/activity/2016_08_glass/mobile/img/eight_fold/immediately.jpg" alt="" />
											</a>
										</div>
									</div>
								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/21774.html">
									<img src="/theme/activity/2016_08_glass/mobile/img/eight_fold/product-ten.jpg" alt="" />
									<div class="down_content">
										<div class="character">
											<p class="cat">清水翻盖双层玻璃杯</p>
											<p class="livelihood">单手操作 一键开盖</p>
										</div>
										<div class="cost">
											<span class="scalping">活动价：</span><span class="much">151.2 </span><span class="scalping">元</span><span class="original_cost">原价:196.5元</span>
										</div>
										<div date="" class="instantbuy">
											<a href="">
												<img src="/theme/activity/2016_08_glass/mobile/img/eight_fold/immediately.jpg" alt="" />
											</a>
										</div>
									</div>
								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/32838.html">
									<img src="/theme/activity/2016_08_glass/mobile/img/eight_fold/product-eleven.jpg" alt="" />
									<div class="down_content">
										<div class="character">
											<p class="cat">清水曲线形单层玻璃杯</p>
											<p class="livelihood">青春白边 水果色彩</p>
										</div>
										<div class="cost">
											<span class="scalping">活动价：</span><span class="much">79.20 </span><span class="scalping">元</span><span class="original_cost">原价:129元</span>
										</div>
										<div date="" class="instantbuy">
											<a href="">
												<img src="/theme/activity/2016_08_glass/mobile/img/eight_fold/immediately.jpg" alt="" />
											</a>
										</div>
									</div>
								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/32841.html">
									<img src="/theme/activity/2016_08_glass/mobile/img/eight_fold/product-twenty.jpg" alt="" />
									<div class="down_content">
										<div class="character">
											<p class="cat">清水双层玻璃直筒杯</p>
											<p class="livelihood">双层 耐高温</p>
										</div>
										<div class="cost">
											<span class="scalping">活动价：</span><span class="much">103.2 </span><span class="scalping">元</span><span class="original_cost">原价:149元</span>
										</div>
										<div date="" class="instantbuy">
											<a href="">
												<img src="/theme/activity/2016_08_glass/mobile/img/eight_fold/immediately.jpg" alt="" />
											</a>
										</div>
									</div>
								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/32839.html">
									<img src="/theme/activity/2016_08_glass/mobile/img/eight_fold/product-thirteen.jpg" alt="" />
									<div class="down_content">
										<div class="character">
											<p class="cat">清水双层办公杯</p>
											<p class="livelihood">商务穿梭 儒雅气质</p>
										</div>
										<div class="cost">
											<span class="scalping">活动价：</span><span class="much">175.2 </span><span class="scalping">元</span><span class="original_cost">原价:239元</span>
										</div>
										<div date="" class="instantbuy">
											<a href="">
												<img src="/theme/activity/2016_08_glass/mobile/img/eight_fold/immediately.jpg" alt="" />
											</a>
										</div>
									</div>
								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/32831.html">
									<img src="/theme/activity/2016_08_glass/mobile/img/eight_fold/product-fourteen.jpg" alt="" />
									<div class="down_content">
										<div class="character">
											<p class="cat">清水单层玻璃杯</p>
											<p class="livelihood">水晶支杆 抗裂防爆</p>
										</div>
										<div class="cost">
											<span class="scalping">活动价：</span><span class="much">55.20 </span><span class="scalping">元</span><span class="original_cost">原价:79.0元</span>
										</div>
										<div date="" class="instantbuy">
											<a href="">
												<img src="/theme/activity/2016_08_glass/mobile/img/eight_fold/immediately.jpg" alt="" />
											</a>
										</div>
									</div>
								</a>
							</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</body>

</html>