
	<head>
		<meta charset="utf-8" />
		<title>惊喜狂欢购</title>
		<link rel="stylesheet" href="/theme/activity/2016_09_purchasing/mobile/css/index.css" />
<link rel="stylesheet" type="text/css" href="/public/mobile/css/foot.css" />
	</head>
	<body>
		<div class="f_carnival_purchasing">
			<div id="">
				<img src="/theme/activity/2016_09_purchasing/mobile/img/banner/banner_one.jpg" alt=""align="top" />
				<img src="/theme/activity/2016_09_purchasing/mobile/img/banner/banner_two.jpg" alt=""align="top" />
				<img src="/theme/activity/2016_09_purchasing/mobile/img/banner/banner_three.jpg" alt=""align="top" />
				<img src="/theme/activity/2016_09_purchasing/mobile/img/banner/banner_four.jpg" alt=""align="top" />
				<img src="/theme/activity/2016_09_purchasing/mobile/img/banner/banner_five.jpg" alt=""align="top" />
				<img src="/theme/activity/2016_09_purchasing/mobile/img/banner/banner_six.jpg" alt=""align="top" />
				<img src="/theme/activity/2016_09_purchasing/mobile/img/banner/banner_seven.jpg" alt=""align="top" />
				<img src="/theme/activity/2016_09_purchasing/mobile/img/banner/banner_eight.jpg" alt=""align="top" />
				<img src="/theme/activity/2016_09_purchasing/mobile/img/banner/banner_nine.jpg" alt=""align="top" />
				<img src="/theme/activity/2016_09_purchasing/mobile/img/banner/banner_ten.jpg" alt=""align="top" />
			</div>
			<!--ta是理财师-->
				<div class="fdsf">
				<div id="f_planner">
					<img src="/theme/activity/2016_09_purchasing/mobile/img/ta_financial_planner/financial_planner_banner.png" alt="" />
				</div>
				<div class="zipper">
					<a href="http://item.soolife.cn/m/36779.html">
					<img src="/theme/activity/2016_09_purchasing/mobile/img/ta_financial_planner/financial_planner_first.png" alt=""data="opengoodsdetail" />
					</a>
				</div>
				</div>
				<div class="f_content">
					<div class="tetrad">
						<ul>
							<li>
								<a href="http://item.soolife.cn/m/36799.html">
									<img src="/theme/activity/2016_09_purchasing/mobile/img/ta_financial_planner/financial_planner_one.jpg" alt="" align="top"data="opengoodsdetail"/>
								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/m/36790.html">
									<img src="/theme/activity/2016_09_purchasing/mobile/img/ta_financial_planner/financial_planner_two.jpg" alt="" align="top"data="opengoodsdetail"/>
								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/m/36256.html">
									<img src="/theme/activity/2016_09_purchasing/mobile/img/ta_financial_planner/financial_planner_three.jpg" alt=""align="top" data="opengoodsdetail"/>
								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/m/36308.html">
									<img src="/theme/activity/2016_09_purchasing/mobile/img/ta_financial_planner/financial_planner_four.jpg" alt=""align="top" data="opengoodsdetail"/>
								</a>
							</li>
						</ul>
					</div>
				</div>
				<!--ta是采购狂人-->
				<div class="fdsf">
				<div id="f_planner">
					<img src="/theme/activity/2016_09_purchasing/mobile/img/ta_purchase/purchase_banner.png" alt="" />
				</div>
				<div class="zipper">
					<a href="http://item.soolife.cn/m/31174.html">
					<img src="/theme/activity/2016_09_purchasing/mobile/img/ta_purchase/purchase_first.png" alt="" data="opengoodsdetail"/>
					</a>
				</div>
				</div>
					<div class="f_content">
					<div class="tetrad">
						<ul>
							<li>
								<a href="http://item.soolife.cn/m/31219.html">
									<img src="/theme/activity/2016_09_purchasing/mobile/img/ta_purchase/purchase_one.jpg" alt="" align="top"data="opengoodsdetail"/>
								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/m/31208.html">
									<img src="/theme/activity/2016_09_purchasing/mobile/img/ta_purchase/purchase_two.jpg" alt="" align="top"data="opengoodsdetail"/>
								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/m/29186.html">
									<img src="/theme/activity/2016_09_purchasing/mobile/img/ta_purchase/purchase_three.jpg" alt=""align="top" data="opengoodsdetail"/>
								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/m/29262.html">
									<img src="/theme/activity/2016_09_purchasing/mobile/img/ta_purchase/purchase_four.jpg" alt=""align="top" data="opengoodsdetail"/>
								</a>
							</li>
						</ul>
					</div>
				</div>
				<!--ta是新鲜达人-->
				<div class="fdsf">
				<div id="f_planner">
					<img src="/theme/activity/2016_09_purchasing/mobile/img/ta_fresh/fresh_banner.png" alt="" />
				</div>
				<div class="zipper">
					<a href="http://item.soolife.cn/m/36777.html">
					<img src="/theme/activity/2016_09_purchasing/mobile/img/ta_fresh/fresh_first.png" alt="" data="opengoodsdetail"/>
					</a>
				</div>
				</div>
					<div class="f_content">
					<div class="tetrad">
						<ul>
							<li>
								<a href="http://item.soolife.cn/m/31744.html">
									<img src="/theme/activity/2016_09_purchasing/mobile/img/ta_fresh/fresh_one.jpg" alt="" align="top"data="opengoodsdetail"/>
								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/m/34181.html">
									<img src="/theme/activity/2016_09_purchasing/mobile/img/ta_fresh/fresh_two.jpg" alt="" align="top"data="opengoodsdetail"/>
								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/m/34108.html">
									<img src="/theme/activity/2016_09_purchasing/mobile/img/ta_fresh/fresh_three.jpg" alt=""align="top" data="opengoodsdetail"/>
								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/m/33419.html">
									<img src="/theme/activity/2016_09_purchasing/mobile/img/ta_fresh/fresh_four.jpg" alt=""align="top"data="opengoodsdetail" />
								</a>
							</li>
						</ul>
					</div>
				</div>
				<!--ta是时尚掌门人-->
					<div class="fdsf">
				<div id="f_planner">
					<img src="/theme/activity/2016_09_purchasing/mobile/img/ta_fashion/fashion_banner.png" alt="" />
				</div>
				<div class="zipper">
					<a href="http://item.soolife.cn/m/15455.html">
					<img src="/theme/activity/2016_09_purchasing/mobile/img/ta_fashion/fashion_first.png" alt=""data="opengoodsdetail" />
					</a>
				</div>
				</div>
					<div class="f_content">
					<div class="tetrad">
						<ul>
							<li>
								<a href="http://item.soolife.cn/m/27221.html">
									<img src="/theme/activity/2016_09_purchasing/mobile/img/ta_fashion/fashion_one.jpg" alt="" align="top"data="opengoodsdetail"/>
								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/m/27192.html">
									<img src="/theme/activity/2016_09_purchasing/mobile/img/ta_fashion/fashion_two.jpg" alt="" align="top"data="opengoodsdetail"/>
								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/m/12911.html">
									<img src="/theme/activity/2016_09_purchasing/mobile/img/ta_fashion/fashion_three.jpg" alt=""align="top" data="opengoodsdetail"/>
								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/m/12911.html">
									<img src="/theme/activity/2016_09_purchasing/mobile/img/ta_fashion/fashion_four.jpg" alt=""align="top" data="opengoodsdetail"/>
								</a>
							</li>
						</ul>
					</div>
				</div>
				<!--ta是凑单达人-->
							<div class="fdsf">
				<div id="f_planner">
					<img src="/theme/activity/2016_09_purchasing/mobile/img/ta_collect/collect_banner.png" alt="" />
				</div>
				<div class="zipper">
					<a href="http://item.soolife.cn/m/27678.html">
					<img src="/theme/activity/2016_09_purchasing/mobile/img/ta_collect/collect_first.png" alt="" data="opengoodsdetail"/>
					</a>
				</div>
				</div>
					<div class="f_content">
					<div class="tetrad">
						<ul>
							<li>
								<a href="http://item.soolife.cn/m/27687.html">
									<img src="/theme/activity/2016_09_purchasing/mobile/img/ta_collect/collect_one.jpg" alt="" align="top"data="opengoodsdetail"/>
								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/m/26433.html">
									<img src="/theme/activity/2016_09_purchasing/mobile/img/ta_collect/collect_two.jpg" alt="" align="top"data="opengoodsdetail"/>
								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/m/26939.html">
									<img src="/theme/activity/2016_09_purchasing/mobile/img/ta_collect/collect_three.jpg" alt=""align="top" data="opengoodsdetail"/>
								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/m/26434.html">
									<img src="/theme/activity/2016_09_purchasing/mobile/img/ta_collect/collect_four.jpg" alt=""align="top" data="opengoodsdetail"/>
								</a>
							</li>
						</ul>
					</div>
				</div>
				<!--ta是家庭主妇-->
							<div class="fdsf">
				<div id="f_planner">
					<img src="/theme/activity/2016_09_purchasing/mobile/img/ta_housewife/housewife_banner.png" alt="" />
				</div>
				<div class="zipper">
					<a href="http://item.soolife.cn/m/29613.html">
					<img src="/theme/activity/2016_09_purchasing/mobile/img/ta_housewife/housewife_first.png" alt=""data="opengoodsdetail" />
					</a>
				</div>
				</div>
					<div class="f_content">
					<div class="tetrad">
						<ul>
							<li>
								<a href="http://item.soolife.cn/m/29604.html">
									<img src="/theme/activity/2016_09_purchasing/mobile/img/ta_housewife/housewife_one.jpg" alt="" align="top"data="opengoodsdetail"/>
								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/m/35919.html ">
									<img src="/theme/activity/2016_09_purchasing/mobile/img/ta_housewife/housewife_two.jpg" alt="" align="top"data="opengoodsdetail"/>
								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/m/35921.html">
									<img src="/theme/activity/2016_09_purchasing/mobile/img/ta_housewife/housewife_three.jpg" alt=""align="top" data="opengoodsdetail"/>
								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/m/35934.html">
									<img src="/theme/activity/2016_09_purchasing/mobile/img/ta_housewife/housewife_four.jpg" alt=""align="top" data="opengoodsdetail"/>
								</a>
							</li>
						</ul>
					</div>
				</div>
		</div>
	</body>
<script src="/public/mobile/js/jquery-3.0.0.min.js"></script>
	  <script src="/public/js/sdk.js"></script>	
	    <script src="/public/mobile/js/websdk.js"></script>
