
	<head>
		<meta charset="utf-8" />
		<title>金九团圆惠</title>
		<link rel="stylesheet" href="/theme/activity/2016_09_Chinese Moon Festival/mobile/css/app_index.css" />
		 <link rel="stylesheet" type="text/css" href="/public/mobile/css/foot.css" />
	</head>
	<body>
		<div class="f_reunion">
			<!--banner-->
			<div class="f_banner">
				<img src="/theme/activity/2016_09_Chinese Moon Festival/mobile/img/banner/banner_one.jpg" alt="" align="top"/>
				<img src="/theme/activity/2016_09_Chinese Moon Festival/mobile/img/banner/banner_two.jpg" alt="" align="top"/>
				<img src="/theme/activity/2016_09_Chinese Moon Festival/mobile/img/banner/banner_three.jpg" alt="" align="top"/>
				<img src="/theme/activity/2016_09_Chinese Moon Festival/mobile/img/banner/banner_four.jpg" alt="" align="top"/>
				<img src="/theme/activity/2016_09_Chinese Moon Festival/mobile/img/banner/banner_five.jpg" alt="" align="top"/>
			</div>
			<!--9元秒杀-->
			<div class="f_nine_prefecture">
				<ul>
					<li>
						<a href="http://item.soolife.cn/m/28932.html">
							<img src="/theme/activity/2016_09_Chinese Moon Festival/mobile/img/nine_prefecture/product_one.jpg" alt="" align="top" data="opengoodsdetail"/>
							<div data="openinstantbuy" class="purchase_one"></div>
						</a>
					</li>
					<li>
						<a href="http://item.soolife.cn/m/29560.html">
							<img src="/theme/activity/2016_09_Chinese Moon Festival/mobile/img/nine_prefecture/product_two.jpg" alt="" align="top"data="opengoodsdetail"/>
							<div data="openinstantbuy" class="purchase_two"></div>
						</a>
					</li>
					<li>
						<a href="http://item.soolife.cn/m/29433.html">
							<img src="/theme/activity/2016_09_Chinese Moon Festival/mobile/img/nine_prefecture/product_three.jpg" alt="" align="top"data="opengoodsdetail"/>
							<div data="openinstantbuy" class="purchase_three"></div>
						</a>
					</li>
					<li>
						<a href="http://item.soolife.cn/m/33449.html">
							<img src="/theme/activity/2016_09_Chinese Moon Festival/mobile/img/nine_prefecture/product_four.jpg" alt=""align="top" data="opengoodsdetail"/>
							<div data="openinstantbuy" class="purchase_four"></div>
						</a>
					</li>
				</ul>	
			</div>
			<!--半价-->
			<div class="half_price">
				<div class="f_half">
					<img src="/theme/activity/2016_09_Chinese Moon Festival/mobile/img/half_price/half_banner.png" alt="" />
				</div>
				<div class="product_first">
					<a href="http://item.soolife.cn/m/23329.html">
						<img src="/theme/activity/2016_09_Chinese Moon Festival/mobile/img/half_price/half_product_banner.png" alt="" data="opengoodsdetail"/>
						<div data="openinstantbuy" class="purchase_banner"></div>
					</a>
				</div>
				<div class="product_second">
					<ul>
						<li>
							<a href="http://item.soolife.cn/m/34149.html">
								<img src="/theme/activity/2016_09_Chinese Moon Festival/mobile/img/half_price/half_product_one.png" alt="" data="opengoodsdetail"/>
								<div data="openinstantbuy" class="purchase_product_one"></div>
							</a>
						</li>
						<li>
							<a href="http://item.soolife.cn/m/24267.html">
								<img src="/theme/activity/2016_09_Chinese Moon Festival/mobile/img/half_price/half_product_two.png" alt="" data="opengoodsdetail"/>
								<div data="openinstantbuy" class="purchase_four"></div>
								<div data="openinstantbuy" class="purchase_product_one"></div>
							</a>
						</li>
					</ul>
				</div>
			</div>
			<!--热销爆款-->
			<div id="f_moldbaby_entirety">
				<div class="f_moldbaby">
					<img src="/theme/activity/2016_09_Chinese Moon Festival/mobile/img/moldbaby/moldbaby_banner.png" alt="" data="opengoodsdetail"/>
				</div>
				<div class="f_moldbaby_product">
					<ul>
						<li>
							<a href="http://item.soolife.cn/m/29568.html">
								<img src="/theme/activity/2016_09_Chinese Moon Festival/mobile/img/moldbaby/moldbaby_one.jpg" alt="" align="top"data="opengoodsdetail"/>
								<div data="openinstantbuy" class="purchase_moldbaby_two"></div>
							</a>
						</li>
						<li>
							<a href="http://item.soolife.cn/m/30759.html">
								<img src="/theme/activity/2016_09_Chinese Moon Festival/mobile/img/moldbaby/moldbaby_two.jpg" alt="" align="top"data="opengoodsdetail"/>
								<div data="openinstantbuy" class="purchase_moldbaby_one"></div>
							</a>
						</li>
						<li>
							<a href="http://item.soolife.cn/m/33312.html">
								<img src="/theme/activity/2016_09_Chinese Moon Festival/mobile/img/moldbaby/moldbaby_three.jpg" alt=""align="top" data="opengoodsdetail"/>
								<div data="openinstantbuy" class="purchase_moldbaby_three"></div>
							</a>
						</li>
						<li>
							<a href="http://item.soolife.cn/m/34004.html">
								<img src="/theme/activity/2016_09_Chinese Moon Festival/mobile/img/moldbaby/moldbaby_four.jpg" alt=""align="top" data="opengoodsdetail"/>
								<div data="openinstantbuy" class="purchase_moldbaby_four"></div>
							</a>
						</li>
					</ul>
				</div>
			</div>
			<!--新品推荐-->
			<div>
				<div class="f_moldbaby">
					<img src="/theme/activity/2016_09_Chinese Moon Festival/mobile/img/recommend/recommend_banner.png" alt="" />
				</div>
				<div class="f_goblet">
					<a href="http://item.soolife.cn/m/15450.html">
						<img src="/theme/activity/2016_09_Chinese Moon Festival/mobile/img/recommend/recommend_one.png" alt="" data="opengoodsdetail"/>
						<div data="openinstantbuy" class="purchase_recommend_one"></div>
					</a>
				</div>
				<div class="f_mo_picture">
					<ul>
						<li>
							<a href="http://item.soolife.cn/m/29411.html">
								<img src="/theme/activity/2016_09_Chinese Moon Festival/mobile/img/recommend/recommend_two.png" alt="" data="opengoodsdetail"/>
								<div data="openinstantbuy" class="purchase_recommend_two"></div>
							</a>
						</li>
						<li>
							<a href="http://item.soolife.cn/m/36364.html">
								<img src="/theme/activity/2016_09_Chinese Moon Festival/mobile/img/recommend/recommend_three.png" alt="" data="opengoodsdetail"/>
								<div data="openinstantbuy" class="purchase_recommend_five"></div>
							</a>
						</li>
						<li>
							<a href="http://item.soolife.cn/m/36349.html">
								<img src="/theme/activity/2016_09_Chinese Moon Festival/mobile/img/recommend/recommend_four.png" alt="" data="opengoodsdetail"/>
								<div data="openinstantbuy" class="purchase_recommend_three"></div>
							</a>
						</li>
						<li>
							<a href="http://item.soolife.cn/m/33322.html">
								<img src="/theme/activity/2016_09_Chinese Moon Festival/mobile/img/recommend/recommend_five.png" alt="" data="opengoodsdetail"/>
								<div data="openinstantbuy" class="purchase_recommend_six"></div>
							</a>
						</li>
						<li>
							<a href="http://item.soolife.cn/m/33278.html">
								<img src="/theme/activity/2016_09_Chinese Moon Festival/mobile/img/recommend/recommend_six.png" alt=""data="opengoodsdetail" />
								<div data="openinstantbuy" class="purchase_recommend_four"></div>
							</a>
						</li>
						<li>
							<a href="http://item.soolife.cn/m/33448.html">
								<img src="/theme/activity/2016_09_Chinese Moon Festival/mobile/img/recommend/recommend_seven.png" alt="" data="opengoodsdetail"/>
								<div data="openinstantbuy" class="purchase_recommend_seven"></div>
							</a>
						</li>
					</ul>
				</div>
			</div>
			<!--精品美食-->
			<div class="f_cate">
				<div class="f_cate_banner">
					<img src="/theme/activity/2016_09_Chinese Moon Festival/mobile/img/cate/cate_banner.png" alt="" />
				</div>
				<div class="f_cate_piuter">
					<ul>
						<li>
							<a href="http://item.soolife.cn/m/35849.html">
								<img src="/theme/activity/2016_09_Chinese Moon Festival/mobile/img/cate/cate_one.jpg" alt="" align="top" data="opengoodsdetail"/>
								<div data="openinstantbuy" class="purchase_cate_one"></div>
							</a>
						</li>
						<li>
							<a href="http://item.soolife.cn/m/34139.html">
								<img src="/theme/activity/2016_09_Chinese Moon Festival/mobile/img/cate/cate_two.jpg" alt=""  align="top" data="opengoodsdetail" />
								<div data="openinstantbuy" class="purchase_cate_two"></div>
							</a>
						</li>
						<li>
							<a href="http://item.soolife.cn/m/27158.html">
								<img src="/theme/activity/2016_09_Chinese Moon Festival/mobile/img/cate/cate_three.jpg" alt=""  align="top" data="opengoodsdetail"/>
								<div data="openinstantbuy" class="purchase_cate_three"></div>
							</a>
						</li>
						<li>
							<a href="http://item.soolife.cn/m/35907.html">
								<img src="/theme/activity/2016_09_Chinese Moon Festival/mobile/img/cate/cate_four.jpg" alt=""  align="top" data="opengoodsdetail"/>
								<div data="openinstantbuy" class="purchase_cate_four"></div>
							</a>
						</li>
						<li>
							<a href="http://item.soolife.cn/m/31091.html">
								<img src="/theme/activity/2016_09_Chinese Moon Festival/mobile/img/cate/cate_five.jpg" alt=""  align="top" data="opengoodsdetail"/>
								<div data="openinstantbuy" class="purchase_cate_five"></div>
							</a>
						</li>
						<li>
							<a href="http://item.soolife.cn/m/26426.html">
								<img src="/theme/activity/2016_09_Chinese Moon Festival/mobile/img/cate/cate_six.jpg" alt=""  align="top" data="opengoodsdetail"/>
								<div data="openinstantbuy" class="purchase_cate_six"></div>
							</a>
						</li>
					</ul>
				</div>
			</div>
			<div>
				<img src="/theme/activity/2016_09_Chinese Moon Festival/mobile/img/banner/bottom_banner.jpg" alt=""data="opengoodsdetail" />
			</div>
		</div>
	</body>
<script src="/public/mobile/js/jquery-3.0.0.min.js"></script>
	  <script src="/public/js/sdk.js"></script>	
	    <script src="/public/mobile/js/websdk.js"></script>
