<?php
$css = $this -> assets -> get('header');
$css -> addCss("public/v3.0.1/css/pc.vip.css");
$js = $this -> assets -> get('footer');
$js -> addJs("public/v3.0.1/js/pc.vip.js");
$style = '';
if (!empty($banner))
{
	$item = current($banner);
	$style = @"background: {$item['bgcolor']} url('{$this->utility->get_advert_picture($item['bgimage'])}') no-repeat center center;";
}
?>
<div id="vip_banner" class="banner" style="{{ style }}">
	<div class="vip_banner main-container">
		<div class="vip_banner_carousel">
			<div class="vip_banner_layer">
				<div class="avatar">
					<img src="/public/v3.0.1/img/icon/avatar-male.png" />
				</div>
				<div class="content">
					{% if m_id > 0 %}
					<p>昵称 {{m_nickname}}</p>
						<p class="coin">你目前有 <i class="icon-xingbi" title="星币数量：{{asset['coin']}} 个">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</i> <span class="coin_num">{{asset['coin']}}</span> 星币</p>
					{% else %}
						<p>亲，来领取点星币，免费的哟！</p><p></p>
					{% endif %}
				</div>
				<div class="control">
					{% if m_id > 0 %}
						{% if asset['is_gain']==1 %}
							<button id="btn_gain" type="button" class="btn btn-coin">可领取{{asset['gain']}}个星币</button>
						{% else %}
							<button type="button" class="btn btn-default">今日已领取{{asset['gain']}}个星币</button>
						{% endif %}
					{% else %}
						<button id="btn_login" type="button" class="btn btn-coin" data-url="{{url_member}}/login.html">亲，请登录</button>
					{% endif %}
				</div>
				<div class="rule">
					<p>星币积累方式，首日可领5个，连续第二天可领10个，连续第三天15个...最多每天可获得35个星币。</p>
					<p>星币价值： 1星币=1元人民币</p>
				</div>
			</div>
			<!-- begin carousel -->
			<div id="carousel-index"  class="carousel slide" data-ride="carousel">
				<ol class="carousel-indicators">
					{% if banner %}
						{% for d in banner %}
							<li data-target="#carousel-index" data-slide-to="{{loop.index0}}" {% if loop.first %} class="active" {% endif %}></li>
						{% endfor %}
					{% endif %}
				</ol>
				<div class="carousel-inner" role="listbox">
					{% if banner %}
						{% for d in banner %}
						<div class="item  {% if loop.first %} active {% endif %}" 
							data-bgcolor="{{d['bgcolor']}}" 
							data-bgimage="<?php echo $this->utility->get_advert_picture($d['bgimage']); ?>"
							data-link="{{d['link']}}" 
							data-id="{{d['id']}}">
							<a href="{{d['link']}}" target="_blank">
								<img class="carousel-images" src="<?php echo $this->utility->get_advert_picture($d['picture']); ?>" alt="{{d['title']}}">
							</a>
						</div>
						{% endfor %}
					{% endif %}
				</div>
			</div>
			<!-- end carousel -->
		</div>
	</div>
</div>

<div id="show_gain" class="gain_coin">
	<div class="box">
		<img src="/public/v3.0.1/img/vip/gain_star.gif" alt="">
		<img class="close" src="/public/v3.0.1/img/close.png" alt="">
		<span>您今日已领取<b> 0 </b>星币</span>
	</div>
</div>

<!-- 限量抢购 -->
<div id="limited" class="row-container clearfix">
	<div class="limited main-container">
		<div class="limited_content">
			<div class="limited_first left frame">
				<div class="move">
					<?php echo $this->utility->get_advert_html('pc.vip.banner.002',$ads); ?>
				</div>
			</div>
			<div class="limited_second left frame">
				<div class="move">
					<?php echo $this->utility->get_advert_html('pc.vip.banner.003',$ads); ?>
				</div>
			</div>
			<div class="limited_third left frame ">
				<div class="move">
					<?php echo $this->utility->get_advert_html('pc.vip.banner.004',$ads); ?>
				</div>
			</div>
			<div class="limited_fourth right">
				<div class="limited_fourth_top frame">
					<div class="move">
						<?php echo $this->utility->get_advert_html('pc.vip.banner.005',$ads); ?>
					</div>
				</div>
				<div class="limited_fourth_bottom frame">
					<div class="move">
					<?php echo $this->utility->get_advert_html('pc.vip.banner.006',$ads); ?>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="full-column main-container">
		<?php echo $this->utility->get_advert_html('pc.vip.banner.column',$ads); ?>
	</div>
</div>

<!-- 星粉秀 -->
<div id="fans" class="row-container clearfix">
	<div class="fans main-container">
		<div class="fans_title">
			<span>星粉秀</span>
		</div>
		<div class="fans_content">
			<div class="fans_content_column left">
				<?php echo $this->utility->get_advert_html('pc.vip.show.001',$ads); ?>
			</div>
			<div class="fans_content_column left">
				<div class="fans_content_column_top">
					<?php echo $this->utility->get_advert_html('pc.vip.show.002',$ads); ?>
				</div>
				<div class="fans_content_column_bottom">
					<?php echo $this->utility->get_advert_html('pc.vip.show.004',$ads); ?>
				</div>
			</div>
			<div class="fans_content_column left">
				<div class="fans_content_column_top">
					<?php echo $this->utility->get_advert_html('pc.vip.show.003',$ads); ?>
				</div>
				<div class="fans_content_column_bottom">
					<?php echo $this->utility->get_advert_html('pc.vip.show.005',$ads); ?>
				</div>
			</div>
			<div class="fans_content_column left">
				<?php echo $this->utility->get_advert_html('pc.vip.show.006',$ads); ?>
			</div>
			<div class="fans_content_column left">
				<div class="fans_content_column_top">
					<?php echo $this->utility->get_advert_html('pc.vip.show.007',$ads); ?>
				</div>
				<div class="fans_content_column_bottom">
					<?php echo $this->utility->get_advert_html('pc.vip.show.008',$ads); ?>
				</div>
			</div>
		</div>
	</div>
	<div class="full-column main-container">
		<?php echo $this->utility->get_advert_html('pc.vip.show.column',$ads); ?>
	</div>
</div>

<!-- 星换购 -->
<div id="buys" class="row-container clearfix">
	<div class="buys main-container">
		<div class="buys_title">
			<span>星换购</span>
		</div>
		<div class="buys_content">
			<script type="text/javascript" src="/assets/goods_coin_20.js"></script>
		</div>
	</div>
	<div class="full-column main-container">
		<?php echo $this->utility->get_advert_html('pc.vip.exchange.003',$ads); ?>
	</div>
</div>

<!-- 星品牌 -->
<div id="brands" class="row-container clearfix">
	<div class="brands main-container">
		<div class="brands_title">
			<span>星品牌</span>
		</div>
		<div class="brands_content">
			<ul>
				<li class="frame">
					<div class="move">
						<?php echo $this->utility->get_advert_html('pc.vip.brand.001',$ads); ?>
					</div>
				</li>
				<li class="frame">
					<div class="move">
						<?php echo $this->utility->get_advert_html('pc.vip.brand.002',$ads); ?>
					</div>
				</li>
				<li class="frame right">
					<div class="move">
						<?php echo $this->utility->get_advert_html('pc.vip.brand.003',$ads); ?>
					</div>
				</li>
				<li class="frame">
					<div class="move">
						<?php echo $this->utility->get_advert_html('pc.vip.brand.004',$ads); ?>
					</div>
				</li>
				<li class="frame">
					<div class="move">
						<?php echo $this->utility->get_advert_html('pc.vip.brand.005',$ads); ?>
					</div>
				</li>
				<li class="frame right">
					<div class="move">
						<?php echo $this->utility->get_advert_html('pc.vip.brand.006',$ads); ?>
					</div>
				</li>
			</ul>
		</div>
	</div>
	<div class="full-column main-container">
		<?php echo $this->utility->get_advert_html('pc.vip.brand.column',$ads); ?>
	</div>
</div>

<!-- 星兑换 -->
<div id="exchange" class="row-container clearfix">
	<div class="exchange main-container">
		<div class="exchange_title">
			<span>星兑换</span>
		</div>
		<div class="exchange_content">
			<ul>
			{% if ads['pc.vip.exchange.001'] %}
				{% for d in ads['pc.vip.exchange.001'] %}
					<li {% if (loop.index%2)==1 %} class="left" {% endif %}>
						<a href="{{d['pc_link']}}" target="_blank" title="{{d['title']}}">
					 		<img class="lazy" src="/public/v3.0.1/img/s.gif" data-original="<?php echo $this->utility->get_advert_picture($d['picture']); ?>" title="{{d['title']}}" alt="{{d['title']}}" />
					 	</a>
					</li>
				{% endfor %}
			{% endif %}
			</ul>
			<div class="clearfix"></div>
		</div>
	</div>
	<div class="full-column main-container">
		<?php echo $this->utility->get_advert_html('pc.vip.exchange.002',$ads); ?>
	</div>
</div>
