
	<head>
		<meta charset="utf-8" />
		<title>无线端</title>
		<link rel="stylesheet" href="/theme/activity/2016_08_Cleaning/mobile/css/index.css" />
		 <link rel="stylesheet" type="text/css" href="/public/mobile/css/foot.css" />
				 <link rel="stylesheet" type="text/css" href="/public/mobile/css/foot.css" />

	</head>
	<body>
		<div class="f_wireless">
			<div id="f_banner">
				<img src="/theme/activity/2016_08_Cleaning/mobile/img/banner/banner_one.jpg" alt="" align="top"/>
				<img src="/theme/activity/2016_08_Cleaning/mobile/img/banner/banner_two.jpg" alt="" align="top"/>
				<img src="/theme/activity/2016_08_Cleaning/mobile/img/banner/banner_three.jpg" alt="" align="top"/>
			</div>
			<div id="wash_product">
				<a href="http://item.soolife.cn/m/36739.html"><img src="/theme/activity/2016_08_Cleaning/mobile/img/body_Hair/protection_one.png" alt="" data="opengoodsdetail"/></a>
				<a href="http://item.soolife.cn/m/36738.html"><img src="/theme/activity/2016_08_Cleaning/mobile/img/body_Hair/protection_two.png" alt="" data="opengoodsdetail"/></a>
				<a href="http://item.soolife.cn/m/12963.html"><img src="/theme/activity/2016_08_Cleaning/mobile/img/body_Hair/protection_three.png" alt="" data="opengoodsdetail"/></a>
				<a href="http://item.soolife.cn/m/32657.html"><img src="/theme/activity/2016_08_Cleaning/mobile/img/body_Hair/protection_four.png" alt="" data="opengoodsdetail"/></a>
			</div>
			<div class="single_product">
				<ul>
					<li>
						<a href="http://item.soolife.cn/m/15506.html">
							<img src="/theme/activity/2016_08_Cleaning/mobile/img/body_Hair/protection_five.png" alt="" data="opengoodsdetail" />
							<div class="f_gomai" data="openinstantbuy"></div>
						</a>
						
					</li>
					<li>
						<a href="http://item.soolife.cn/m/15494.html">
							<img src="/theme/activity/2016_08_Cleaning/mobile/img/body_Hair/protection_six.jpg" alt="" data="opengoodsdetail" />
							<div class="f_gomai" data="openinstantbuy"></div>
						</a>
						
					</li>
					<li>
						<a href="http://item.soolife.cn/m/15496.html">
							<img src="/theme/activity/2016_08_Cleaning/mobile/img/body_Hair/protection_seven.png" alt="" data="opengoodsdetail" />
							<div class="f_gomai" data="openinstantbuy"></div>
						</a>
						
					</li>
					<li>
						<a href="http://item.soolife.cn/m/12965.html">
							<img src="/theme/activity/2016_08_Cleaning/mobile/img/body_Hair/protection_eight.png" alt="" data="opengoodsdetail" />
							<div class="f_gomai" data="openinstantbuy"></div>
						</a>
						
					</li>
					<li>
						<a href="http://item.soolife.cn/m/12964.html">
							<img src="/theme/activity/2016_08_Cleaning/mobile/img/body_Hair/protection_nine.png" alt="" data="opengoodsdetail" />
							<div class="f_gomai" data="openinstantbuy"></div>
						</a>
						
					</li>
					<li>
						<a href="http://item.soolife.cn/m/12961.html">
							<img src="/theme/activity/2016_08_Cleaning/mobile/img/body_Hair/protection_ten.jpg" alt="" data="opengoodsdetail" />
							<div class="f_gomai" data="openinstantbuy"></div>
						</a>
						
					</li>
					
				</ul>
			</div>
			<div class="f_shower">
				<img src="/theme/activity/2016_08_Cleaning/mobile/img/take_shower/shower_banner.jpg" alt="" />
			</div>
			<div class="single_product">
				<ul>
					<li>
						<a href="http://item.soolife.cn/m/12913.html">
							<img src="/theme/activity/2016_08_Cleaning/mobile/img/take_shower/shower_one.jpg" alt="" data="opengoodsdetail" />
							<div class="f_gomai" data="openinstantbuy"></div>
						</a>
						
					</li>
					<li>
						<a href="http://item.soolife.cn/m/12915.html">
							<img src="/theme/activity/2016_08_Cleaning/mobile/img/take_shower/shower_two.jpg" alt="" data="opengoodsdetail" />
							<div class="f_gomai" data="openinstantbuy"></div>
						</a>
						
					</li>
					<li>
						<a href="http://item.soolife.cn/m/12916.html">
							<img src="/theme/activity/2016_08_Cleaning/mobile/img/take_shower/shower_three.jpg" alt="" data="opengoodsdetail" />
							<div class="f_gomai" data="openinstantbuy"></div>
						</a>
						
					</li>
					<li>
						<a href="http://item.soolife.cn/m/15510.html">
							<img src="/theme/activity/2016_08_Cleaning/mobile/img/take_shower/shower_four.jpg" alt="" data="opengoodsdetail" />
							<div class="f_gomai" data="openinstantbuy"></div>
						</a>
						
					</li>
					<li>
						<a href="http://item.soolife.cn/m/12923.html">
							<img src="/theme/activity/2016_08_Cleaning/mobile/img/take_shower/shower_five.jpg" alt="" data="opengoodsdetail" />
							<div class="f_gomai" data="openinstantbuy"></div>
						</a>
						
					</li>
					<li>
						<a href="http://item.soolife.cn/m/15503.html">
							<img src="/theme/activity/2016_08_Cleaning/mobile/img/take_shower/shower_six.jpg" alt=""  data="opengoodsdetail"/>
								<div class="f_gomai" data="openinstantbuy"></div>
						</a>
					
					</li>
					
				</ul>
			</div>
			<div class="f_shower">
				<img src="/theme/activity/2016_08_Cleaning/mobile/img/do_laundry/laundry_banner.jpg" alt="" />
			</div>
			<div class="single_product">
				<ul>
					<li>
						<a href="http://item.soolife.cn/m/33441.html">
							<img src="/theme/activity/2016_08_Cleaning/mobile/img/do_laundry/laundry_one.png" alt="" data="opengoodsdetail" />
							<div class="f_gomai" data="openinstantbuy"></div>
						</a>
						
					</li>
					<li>
						<a href="http://item.soolife.cn/m/33444.html">
							<img src="/theme/activity/2016_08_Cleaning/mobile/img/do_laundry/laundry_two.jpg" alt="" data="opengoodsdetail" />
							<div class="f_gomai" data="openinstantbuy"></div>
						</a>
						
					</li>
					<li>
						<a href="http://item.soolife.cn/m/31862.html">
							<img src="/theme/activity/2016_08_Cleaning/mobile/img/do_laundry/laundry_three.jpg" alt="" data="opengoodsdetail" />
							<div class="f_gomai" data="openinstantbuy"></div>
						</a>
						
					</li>
					<li>
						<a href="http://item.soolife.cn/m/31869.html">
							<img src="/theme/activity/2016_08_Cleaning/mobile/img/do_laundry/laundry_four.jpg" alt="" data="opengoodsdetail" />
							<div class="f_gomai" data="openinstantbuy"></div>
						</a>
						
					</li>
					<li>
						<a href="http://item.soolife.cn/m/31870.html">
							<img src="/theme/activity/2016_08_Cleaning/mobile/img/do_laundry/laundry_five.jpg" alt="" data="opengoodsdetail" />
							<div class="f_gomai" data="openinstantbuy"></div>
						</a>
						
					</li>
					<li>
						<a href="http://item.soolife.cn/m/33443.html">
							<img src="/theme/activity/2016_08_Cleaning/mobile/img/do_laundry/laundry_six.png" alt="" data="opengoodsdetail" />
							<div class="f_gomai" data="openinstantbuy"></div>
						</a>
						
					</li>
					
				</ul>
			</div>
		</div>
	</body>
<script src="/public/mobile/js/jquery-3.0.0.min.js"></script>
	  <script src="/public/js/sdk.js"></script>	
	    <script src="/public/mobile/js/websdk.js"></script>

