<?php
	$css = $this->assets->get('header');
	$css -> addCss("public/css/p/view.index.css");
	$js  = $this->assets->get('footer');
?>
<div style="margin-top:20px" id="carousel-example-generic" class="carousel slide" data-ride="carousel">
	<ol class="carousel-indicators">
		<li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
		<li data-target="#carousel-example-generic" data-slide-to="1"></li>
		<li data-target="#carousel-example-generic" data-slide-to="2"></li>
	</ol>
	<div class="carousel-inner" role="listbox">
		<div class="item active">
			<a title="如此生活" href="/partner/brandinvestment.html"><img src="public/img/index/bannersec(1).jpg" alt="如此生活"></a>
		</div>
		<div class="item">
		 	<a title="如此生活" href="/partner/experience.html"><img src="public/img/index/bannersec(3).jpg" alt="如此生活"></a>
		</div>
		<div class="item">
		 	<a title="如此生活" href="/partner/newcityagent.html"><img src="public/img/index/bannersec(2).jpg" alt="如此生活"></a>
		</div>
	</div>
	<a title="如此生活" class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
		<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
	</a>
	<a title="如此生活" class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
		<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
	</a>
</div>
<div class="model_title">
	<h3>公司动态</h3>
<!-- 	<p><a title="如此生活" href="#">more <i class="fa fa-angle-right" aria-hidden="true"></i></a></p> -->
</div>
<div class="row">
	<div class="col-xs-4">
		<a title="如此生活" href="/report/leadervisit.html">
		<div><img src="public/img/index/shrinkleadervisit.png" alt="如此生活" class="circularbead"></div>
			<div class="row model">
				<div class="col-xs-3">
					<p class="year">2017</p>
					<p class="day">03-29</p>
				</div>
				<div class="col-xs-9 border-l">
					<h4>常熟市董浜镇政府领导来如此生活平台考察</h4>
					<p class="text">3月29日，下午4时许，常熟董浜镇政府领导一行来到如此生活总部参观考察...</p>
				</div>
			</div>
		</a>
	</div>
	<div class="col-xs-4">
		<a title="如此生活" href="/report/newsthailand.html">
		<div><img src="public/img/index/indeximg(9).png" alt="如此生活" class="circularbead"></div>
			<div class="row model">
				<div class="col-xs-3">
					<p class="year">2017</p>
					<p class="day">03-17</p>
				</div>
				<div class="col-xs-9 border-l">
					<h4>如此生活在泰领馆参加纺织服装交流活动</h4>
					<p class="text">3月17日，【如此生活】平台在泰领馆应邀参加泰国纺织服装协会交流活动...</p>
				</div>				
			</div>
		</a>
	</div>
	<div class="col-xs-4">
		<a title="如此生活" href="/report/newsvisit.html">
		<div><img src="public/img/index/indeximg(0).png" alt="如此生活" class="circularbead"></div>
			<div class="row model">
				<div class="col-xs-3">
					<p class="year">2016</p>
					<p class="day">12-21</p>
				</div>
				<div class="col-xs-9 border-l">
					<h4>嘉兴市箱包行业协会参观如此生活平台</h4>
					<p class="text">为更好地为会员提供服务，协助会员企业加强互联网电商平台的销售待公...</p>
				</div>
			</div>
		</a>
	</div>
	<!-- <div class="col-xs-4">
		<a title="如此生活" href="/report/newsGlory.html">
		<div><img src="public/img/index/indeximg(2).png" alt="如此生活"></div>
			<div class="row model">
				<div class="col-xs-3">
					<p class="year">2017</p>
					<p class="day">01-07</p>
				</div>
				<div class="col-xs-9 border-l">
					<h4>赢战鸡年  共创辉煌 </h4>
					<p class="text">2017年1月7日，如此生活2017年会在佘山月湖会馆盛大举办。如此生活董事...</p>
				</div>
			</div>
		</a>
	</div> -->
</div>
<div class="model_title">
	<h3>新闻报道</h3>
<!-- 	<p><a title="如此生活" href="#">more <i class="fa fa-angle-right" aria-hidden="true"></i></a></p> -->
</div>
<div class="row">
	<div class="col-xs-4">
		<a title="如此生活" href="/report/videoCoverage.html">
		<div>
			<img src="public/img/index/indeximg(10).jpg" alt="如此生活">
			<p class="wen">上海小童星活动</p>
		</div>
		</a>
	</div>
	<div class="col-xs-4">
		<a title="如此生活" href="/report/videoCoverage.html">
		<div>
			<img src="public/img/index/indeximg(3).png" alt="如此生活">
			<p class="wen">华交会第一财经采访</p>
		</div>
		</a>
	</div>
	<div class="col-xs-4">
		<a title="如此生活" href="/report/videoCoverage.html">
			<div>
				<img src="public/img/index/indeximg(5).png" alt="如此生活">
				<p class="wen">品牌商大会第一财经报道</p>
			</div>
		</a>
	</div>	
</div>
<div class="model_title">
	<h3>合作</h3>
<!-- 	<p><a title="如此生活" href="#">more <i class="fa fa-angle-right" aria-hidden="true"></i></a></p> -->
</div>
<div class="row">
	<div class="col-xs-4">
		<div>
		<a title="如此生活" href="/partner/newcityagent.html">
		<img src="public/img/index/indeximg(6).png" alt="如此生活"></a></div>
	</div>
	<div class="col-xs-4">
		<div>
		<a title="如此生活" href="/partner/brandinvestment.html">
		<img src="public/img/index/indeximg(7).png" alt="如此生活"></a></div>
	</div>
	<div class="col-xs-4">
		<div>
		<a title="如此生活" href="/partner/experience.html">
		<img src="public/img/index/indeximg(8).png" alt="如此生活"></a></div>
	</div>	
</div>
<div class="model_title">
	<h3>体验店</h3>
<!-- 	<p><a title="如此生活" href="#">more <i class="fa fa-angle-right" aria-hidden="true"></i></a></p> -->
</div>
<div class="shop">
	<div class="marl_no marg">
		<a title="如此生活" href="/business/experienceCenter.html">
			<img src="public/img/index/song.png" alt="如此生活">
		</a>
		<p>松江店</p>
	</div>
	<div class="marg">
		<a title="如此生活" href="/business/experienceCenter.html"><img src="public/img/index/jia.png" alt="如此生活"></a>
		<p>嘉定店</p>
	</div>
	<div class="marg">
		<a title="如此生活" href="/business/experienceCenter.html"><img src="public/img/index/zhen.png" alt="如此生活"></a>
		<p>镇江店</p>
	</div>
	<div class="marg">
		<a title="如此生活" href="/business/experienceCenter.html"><img src="public/img/index/xia.png" alt="如此生活"></a>
		<p>厦门店</p>
	</div>
	<div class="marr_no marg">
		<a title="如此生活" href="/business/experienceCenter.html"><img src="public/img/index/su.png" alt="如此生活"></a>
		<p>苏州店</p>
	</div>
</div>


