
	<head>
		<meta charset="UTF-8">
		<title></title>
		<link rel="stylesheet" href="/theme/activity/2016_08_Cleaning/pc/css/index.css" />
	</head>
	<body>
		<div class="cleaning_boby">
			<div class="banner">
				<img src="/theme/activity/2016_08_Cleaning/pc/img/banner.jpg" algin="top" />
			<img src="/theme/activity/2016_08_Cleaning/pc/img/banner_two.jpg" algin="top"/>
	
			<img src="/theme/activity/2016_08_Cleaning/pc/img/banner_three.jpg" algin="top"/>

			</div>
			<div class="subjectival">
				<div class="prefecture">
					<div class="title">
						<img src="/theme/activity/2016_08_Cleaning/pc/img/title_c.jpg"  />
					</div>
					<div class="single">
						<div>
							<a href="http://item.soolife.cn/36739.html" target="_blank"><img src="/theme/activity/2016_08_Cleaning/pc/img/sp_s.jpg" /></a>
						</div>
						<div>
							<a href="http://item.soolife.cn/36738.html" target="_blank"><img src="/theme/activity/2016_08_Cleaning/pc/img/sp_t.jpg" /></a>
						</div>
						<div >
							<a href="http://item.soolife.cn/12963.html" target="_blank"><img src="/theme/activity/2016_08_Cleaning/pc/img/sp_z.jpg" /></a>
						</div>
						<div>
							<a href="http://item.soolife.cn/32657.html" target="_blank"><img src="/theme/activity/2016_08_Cleaning/pc/img/sp_y.jpg" /></a>
						</div>
						<div class="hairdressing">
							<ul>
								<li>
									<a href="http://item.soolife.cn/15506.html" target="_blank">
										<p class="impact">美丽秀发的新生秘密</p>
										<div>
											<img src="/theme/activity/2016_08_Cleaning/pc/img/sp_b.jpg" />
										</div>
										<p class="name">水之密语 净澄水活洗发露</p>
										<div class="price clearfix">
											<div class="fl">
												<span class="qiangg">抢购价:</span><span class="price_p">68</span>
											</div>
											<div class="fr">
												<img src="/theme/activity/2016_08_Cleaning/pc/img/go.png" />
											</div>
										</div>
									</a>
								</li>
								<li>
									<a href="http://item.soolife.cn/15494.html" target="_blank">
										<p class="impact">亮丽发丝的随心舞动</p>
										<div>
											<img src="/theme/activity/2016_08_Cleaning/pc/img/sp_a.jpg" />
										</div>
										<p class="name">丝蓓绮 炫魅赋活洗发露 </p>
										<div class="price clearfix">
											<div class="fl">
												<span class="qiangg">抢购价:</span><span class="price_p">108</span>
											</div>
											<div class="fr">
												<img src="/theme/activity/2016_08_Cleaning/pc/img/go.png" />
											</div>
										</div>
									</a>
								</li>
								<li>
									<a href="http://item.soolife.cn/15496.html" target="_blank">
										<p class="impact">给你的秀发做个spa</p>
										<div>
											<img src="/theme/activity/2016_08_Cleaning/pc/img/sp_c.jpg" />
										</div>
										<p class="name">丝蓓绮 炫魅赋活护发素</p>
										<div class="price clearfix">
											<div class="fl">
												<span class="qiangg">抢购价:</span><span class="price_p">108</span>
											</div>
											<div class="fr">
												<img src="/theme/activity/2016_08_Cleaning/pc/img/go.png" />
											</div>
										</div>
									</a>
								</li>
								<li>
									<a href="http://item.soolife.cn/12965.html" target="_blank">
										<p class="impact">滋养秀发与有效去屑</p>
										<div>
											<img src="/theme/activity/2016_08_Cleaning/pc/img/sp_d.jpg" />
										</div>
										<p class="name">约翰娜 秀波系列 去屑护发素</p>
										<div class="price clearfix">
											<div class="fl">
												<span class="qiangg">抢购价:</span><span class="price_p">99</span>
											</div>
											<div class="fr">
												<img src="/theme/activity/2016_08_Cleaning/pc/img/go.png" />
											</div>
										</div>
									</a>
								</li>
								<li>
									<a href="http://item.soolife.cn/12964.html" target="_blank">
										<p class="impact">滋养秀发与有效去屑</p>
										<div>
											<img src="/theme/activity/2016_08_Cleaning/pc/img/sp_d.jpg" />
										</div>
										<p class="name">约翰娜 秀波系列 去屑洗发水</p>
										<div class="price clearfix">
											<div class="fl">
												<span class="qiangg">抢购价:</span><span class="price_p">99</span>
											</div>
											<div class="fr">
												<img src="/theme/activity/2016_08_Cleaning/pc/img/go.png" />
											</div>
										</div>
									</a>
								</li>
								<li>
									<a href="http://item.soolife.cn/12961.html" target="_blank">
										<p class="impact">心中丁香花香秀于发</p>
										<div>
											<img src="/theme/activity/2016_08_Cleaning/pc/img/sp_f.jpg" />
										</div>
										<p class="name">约翰娜 欧丁香花 平衡洗发水</p>
										<div class="price clearfix">
											<div class="fl">
												<span class="qiangg">抢购价:</span><span class="price_p">99</span>
											</div>
											<div class="fr">
												<img src="/theme/activity/2016_08_Cleaning/pc/img/go.png" />
											</div>
										</div>
									</a>
								</li>
							</ul>
						</div>
					</div>
				</div>
			    <div class="laundry">
			    	<div class="title">
			    		<img src="/theme/activity/2016_08_Cleaning/pc/img/title_d.jpg" />
			    	</div>
			    	<div class="single">
			    		<div class="background_fs clearfix">
			    			<div class="individual fl">
			    				<a href="http://item.soolife.cn/12913.html" target="_blank">
				    				<p class="impact">持久留香 魅惑宠肤</p>
									<div>
										<img src="/theme/activity/2016_08_Cleaning/pc/img/sp_h.jpg" />
									</div>
									<p class="name">维他波 野玫瑰沐浴露 药妆护肤</p>
									<div class="price clearfix">
										<div class="fl">
											<span class="qiangg">抢购价:</span><span class="price_p">89</span>
										</div>
										<div class="fr">
											<img src="/theme/activity/2016_08_Cleaning/pc/img/go.png" />
										</div>
									</div>
								</a>
			    			</div>
			    			<div class="individual fr">
			    				<a href="http://item.soolife.cn/12915.html" target="_blank">
				    				<p class="impact">随心选择 魅力升级</p>
									<div>
										<img src="/theme/activity/2016_08_Cleaning/pc/img/sp_i.jpg" />
									</div>
									<p class="name">维他波 野玫瑰洗护套装 药妆护肤</p>
									<div class="price clearfix">
										<div class="fl">
											<span class="qiangg">抢购价:</span><span class="price_p">188</span>
										</div>
										<div class="fr">
											<img src="/theme/activity/2016_08_Cleaning/pc/img/go.png" />
										</div>
									</div>
								</a>
			    			</div>
			    		</div>
			    		<div class="background_ls clearfix">
			    			<div class="individual fl">
			    				<a href="http://item.soolife.cn/12916.html" target="_blank">
				    				<p class="impact">滋润保湿 清凉一夏</p>
									<div>
										<img src="/theme/activity/2016_08_Cleaning/pc/img/sp_o.jpg" />
									</div>
									<p class="name">约翰娜 益肤健润洗护套装 白桦叶汁精华</p>
									<div class="price clearfix">
										<div class="fl">
											<span class="qiangg">抢购价:</span><span class="price_p">148</span>
										</div>
										<div class="fr">
											<img src="/theme/activity/2016_08_Cleaning/pc/img/go.png" />
										</div>
									</div>
								</a>
			    			</div>
			    			<div class="individual fr">
			    				<a href="http://item.soolife.cn/15510.html" target="_blank"> 
				    				<p class="impact">去除污垢 持久滋润</p>
									<div>
										<img src="/theme/activity/2016_08_Cleaning/pc/img/sp_p.jpg" />
									</div>
									<p class="name">水之密语 凝润柔肤沐浴露 </p>
									<div class="price clearfix">
										<div class="fl">
											<span class="qiangg">抢购价:</span><span class="price_p">62</span>
										</div>
										<div class="fr">
											<img src="/theme/activity/2016_08_Cleaning/pc/img/go.png" />
										</div>
									</div>
								</a>
			    			</div>
			    		</div>
			    		<div class="background_hs clearfix">
			    			<div class="individual fl">
			    				<a href="http://item.soolife.cn/12923.html" target="_blank">
				    				<p class="impact">沁透滋润 活力清新</p>
									<div>
										<img src="/theme/activity/2016_08_Cleaning/pc/img/sp_r.jpg" />
									</div>
									<p class="name">约翰娜 益肤凝润润肤乳 葡萄籽油</p>
									<div class="price clearfix">
										<div class="fl">
											<span class="qiangg">抢购价:</span><span class="price_p">79</span>
										</div>
										<div class="fr">
											<img src="/theme/activity/2016_08_Cleaning/pc/img/go.png" />
										</div>
									</div>
								</a>
			    			</div>
			    			<div class="individual fr">
			    				<a href="http://item.soolife.cn/15503.html" target="_blank">
				    				<p class="impact">奢华泡沫 细腻滑润</p>
									<div>
										<img src="/theme/activity/2016_08_Cleaning/pc/img/sp_q.jpg" />
									</div>
									<p class="name">可悠然 美肌沐浴露</p>
									<div class="price clearfix">
										<div class="fl">
											<span class="qiangg">抢购价:</span><span class="price_p">56</span>
										</div>
										<div class="fr">
											<img src="/theme/activity/2016_08_Cleaning/pc/img/go.png" />
										</div>
									</div>
								</a>
			    			</div>
			    		</div>
			    	</div>
			    </div>
			    <div class="laundry">
			    	<div class="title">
			    		<img src="/theme/activity/2016_08_Cleaning/pc/img/title_b.jpg" />
			    	</div>
			    	<div class="single">
			    		
			    		<div class="background_ls clearfix">
			    			<div class="individual fl">
			    				<a href="http://item.soolife.cn/33441.html" target="_blank">
				    				<p class="impact">从里到外 洁净如新</p>
									<div>
										<img src="/theme/activity/2016_08_Cleaning/pc/img/sp_g.jpg" />
									</div>
									<p class="name">多情玫瑰洗衣液rcsh-0517</p>
									<div class="price clearfix">
										<div class="fl">
											<span class="qiangg">抢购价:</span><span class="price_p">23.9</span>
										</div>
										<div class="fr">
											<img src="/theme/activity/2016_08_Cleaning/pc/img/go.png" />
										</div>
									</div>
								</a>
			    			</div>
			    			<div class="individual fr">
			    				<a href="http://item.soolife.cn/33444.html" target="_blank">
				    				<p class="impact">白衣更白 彩衣更鲜</p>
									<div>
										<img src="/theme/activity/2016_08_Cleaning/pc/img/sp_j.jpg" />
									</div>
									<p class="name">多情玫瑰洗衣液rcsh-0579  </p>
									<div class="price clearfix">
										<div class="fl">
											<span class="qiangg">抢购价:</span><span class="price_p">32.3</span>
										</div>
										<div class="fr">
											<img src="/theme/activity/2016_08_Cleaning/pc/img/go.png" />
										</div>
									</div>
								</a>
			    			</div>
			    		</div>
			    		<div class="background_shs clearfix">
			    			<div class="individual fl">
			    				<a href="http://item.soolife.cn/31862.html" target="_blank">
				    				<p class="impact">清洁必备 去污彻底</p>
									<div>
										<img src="/theme/activity/2016_08_Cleaning/pc/img/sp_l.jpg" />
									</div>
									<p class="name">菲玛斯婴儿洗衣液（小红帽）</p>
									<div class="price clearfix">
										<div class="fl">
											<span class="qiangg">抢购价:</span><span class="price_p">49</span>
										</div>
										<div class="fr">
											<img src="/theme/activity/2016_08_Cleaning/pc/img/go.png" />
										</div>
									</div>
								</a>
			    			</div>
			    			<div class="individual fr">
			    				<a href="http://item.soolife.cn/31869.html" target="_blank">
				    				<p class="impact">深层洁净 全面保护</p>
									<div>
										<img src="/theme/activity/2016_08_Cleaning/pc/img/sp_k.jpg" />
									</div>
									<p class="name">菲玛斯女性内衣洗衣液</p>
									<div class="price clearfix">
										<div class="fl">
											<span class="qiangg">抢购价:</span><span class="price_p">59</span>
										</div>
										<div class="fr">
											<img src="/theme/activity/2016_08_Cleaning/pc/img/go.png" />
										</div>
									</div>
								</a>
			    			</div>
			    		</div>
			    		<div class="background_hs clearfix">
			    			<div class="individual fl">
			    				<a href="http://item.soolife.cn/31870.html" target="_blank">
				    				<p class="impact">深层洁净 高效洗涤</p>
									<div>
										<img src="/theme/activity/2016_08_Cleaning/pc/img/sp_m.jpg" />
									</div>
									<p class="name">菲玛斯黑洗</p>
									<div class="price clearfix">
										<div class="fl">
											<span class="qiangg">抢购价:</span><span class="price_p">59</span>
										</div>
										<div class="fr">
											<img src="/theme/activity/2016_08_Cleaning/pc/img/go.png" />
										</div>
									</div>
								</a>
			    			</div>
			    			<div class="individual fr">
			    				<a href="http://item.soolife.cn/33443.html" target="_blank">
				    				<p class="impact">深层去渍 馨香怡人</p>
									<div>
										<img src="/theme/activity/2016_08_Cleaning/pc/img/sp_n.jpg" />
									</div>
									<p class="name">多情玫瑰洗衣液rcsh-0548</p>
									<div class="price clearfix">
										<div class="fl">
											<span class="qiangg">抢购价:</span><span class="price_p">32.3</span>
										</div>
										<div class="fr">
											<img src="/theme/activity/2016_08_Cleaning/pc/img/go.png" />
										</div>
									</div>
								</a>
			    			</div>
			    		</div>
			    	</div>
			    </div>
			</div>
		</div>
	</body>
<script src="/public/pc/js/common.js"></script>
