<!DOCTYPE html>
<html>

	<head>
		<meta charset="utf-8" />
		<title>母婴反季惠</title>
		<link rel="stylesheet" href="/theme/activity/2016_10_infantmom/pc/css/index.css" />
	</head>

	<body>
		<div class="f_infant_mom">
			<!--banner-->
			<div class="f_banner">
				<img src="/theme/activity/2016_10_infantmom/pc/img/banner/banner_one.jpg" alt="" align="top" />
				<img src="/theme/activity/2016_10_infantmom/pc/img/banner/banner_two.jpg" alt="" align="top" />
				<img src="/theme/activity/2016_10_infantmom/pc/img/banner/banner_three.jpg" alt="" align="top" />
				<img src="/theme/activity/2016_10_infantmom/pc/img/banner/banner_four.jpg" alt="" align="top" />
				<img src="/theme/activity/2016_10_infantmom/pc/img/banner/banner_five.jpg" alt="" align="top" />
			</div>
			<!--1200-->
			<div class="f_entirety">
				
				<!--超值1元 限量疯抢-->
				<div class="f_unitary">
					<img src="/theme/activity/2016_10_infantmom/pc/img/unitary/unitary_banner.png" alt="" />
				</div>
				<div>
					<img src="/theme/activity/2016_10_infantmom/pc/img/unitary/towel_paper.jpg" alt="" />
				</div>

			</div>
			<!--1000-->
			<div class="subject">
				<div class="grow_up">
					<img src="/theme/activity/2016_10_infantmom/pc/img/grow_up/grow_up_banner.png" alt="" />
				</div>
				<!--成长爆款 宝妈必备-->
				<div class="f_grow_up">
					<div class="mongolian_yurt">
						<ul>
							<li>
								<a href="http://item.soolife.cn/6325.html">
									<div class="environmental">
										<img class="pink" src="/theme/activity/2016_10_infantmom/pc/img/grow_up/grow_up_one.jpg" alt="" data="opengoodsdetail"/>
										<div class="four_seasons">
											<p class="camera">泰嘉贝camera蒙古包</p>
											<p class="comfortable">便捷舒心 四季适用</p>
											<div class="juzhong">
												<span class="original_cost">原价：488.00</span><span class="activity">  活动价：</span><span class="price">228.00</span>
											</div>
											<div class="purchase">
												<img src="/theme/activity/2016_10_infantmom/pc/img/grow_up/buy.jpg" alt="" />
											</div>
										</div>

									</div>
								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/13240.html">
									<div class="environmental">
										<img src="/theme/activity/2016_10_infantmom/pc/img/grow_up/grow_up_two.jpg" alt="" data="opengoodsdetail"/>
										<div class="four_seasons">
											<p class="camera">泰嘉贝camera婴儿隔尿垫</p>
											<p class="comfortable">纯棉面料 环保印染</p>
											<div class="juzhong">
												<span class="original_cost">原价：196.00</span><span class="activity">  活动价：</span><span class="price">68.00</span>
											</div>
											<div class="purchase">
												<img src="/theme/activity/2016_10_infantmom/pc/img/grow_up/buy.jpg" alt="" />
											</div>
										</div>

									</div>
								</a>
							</li>
						</ul>
					</div>
					<div class="cart">
						<ul>
							<li>
								<a href="http://item.soolife.cn/13220.html">
									<img class="car" src="/theme/activity/2016_10_infantmom/pc/img/grow_up/grow_up_three.jpg" alt="" data="opengoodsdetail"/>
									<div class="four_seasons">
										<p class="camera">泰嘉贝cameraLite5轻便婴儿推车</p>
										<p class="comfortable">收放自如  安心保护</p>
										<div class="juzhong">
											<span class="original_cost">原价：709.00</span><span class="activity">  活动价：</span><span class="price">318.00</span>
										</div>
										<div class="purchase">
											<img src="/theme/activity/2016_10_infantmom/pc/img/grow_up/buy.jpg" alt="" />
										</div>
									</div>

								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/6084.html">
									<img class="car" src="/theme/activity/2016_10_infantmom/pc/img/grow_up/grow_up_four.jpg" alt="" data="opengoodsdetail"/>
									<div class="four_seasons">
										<p class="camera">可换向摇椅婴儿推车Q-3001</p>
										<p class="comfortable">婴儿推车  舒适安全</p>
										<div class="juzhong">
											<span class="original_cost">原价：1078.00</span><span class="activity">  活动价：</span><span class="price">498.00</span>
										</div>
										<div class="purchase">
											<img src="/theme/activity/2016_10_infantmom/pc/img/grow_up/buy.jpg" alt="" />
										</div>
									</div>

								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/13227.html">
									<img class="car" src="/theme/activity/2016_10_infantmom/pc/img/grow_up/grow_up_five.jpg" alt="" data="opengoodsdetail"/>
									<div class="four_seasons">
										<p class="camera">Ziibra超轻便婴儿推车</p>
										<p class="comfortable">天然温和  强韧耐用</p>
										<div class="juzhong">
											<span class="original_cost">原价：480.00</span><span class="activity">  活动价：</span><span class="price">248.00</span>
										</div>
										<div class="purchase">
											<img src="/theme/activity/2016_10_infantmom/pc/img/grow_up/buy.jpg" alt="" />
										</div>
									</div>

								</a>
							</li>
						</ul>
					</div>
				</div>
				<!--品质典范-->
				<div class="character">
					<img src="/theme/activity/2016_10_infantmom/pc/img/character/character_banner.png" alt="" />
				</div>
				<div class="quality">
					<div class="trait measure">
						<ul>
							<li>
								<a href="http://item.soolife.cn/34684.html">
									<div class="shell_fabric">
										<img class="protection" src="/theme/activity/2016_10_infantmom/pc/img/character/character_one.png" alt="" data="opengoodsdetail"/>
										<div class="four_seasons">
											<p class="camera">weegoamigo 婴儿多功能竹棉针织毯礼盒</p>
											<p class="comfortable">澳洲进口  品质保证</p>
											<div class="juzhong">
												<span class="original_cost">原价：799.00</span><span class="activity">  活动价：</span><span class="price">698.00</span>
											</div>
											<div class="purchase">
												<img src="/theme/activity/2016_10_infantmom/pc/img/grow_up/buy.jpg" alt="" />
											</div>
										</div>

									</div>
								</a>
							</li>
						</ul>
					</div>
					<div class="gauze">
						<ul>
							<li>
								<a href="http://item.soolife.cn/34915.html">
									<div class="shell_fabric">
										<img src="/theme/activity/2016_10_infantmom/pc/img/character/character_two.jpg" alt=""data="opengoodsdetail" />
										<div class="four_seasons">
											<p class="camera">weegoamigo 婴儿多功能纯竹纤维薄纱布</p>
											<p class="comfortable">丝般触感  贴身放心</p>
											<div class="juzhong">
												<span class="original_cost">原价：698.00</span><span class="activity">  活动价：</span><span class="price">498.00</span>
											</div>
											<div class="purchase">
												<img src="/theme/activity/2016_10_infantmom/pc/img/grow_up/buy.jpg" alt="" />
											</div>
										</div>

									</div>
								</a>
							</li>
						</ul>
					</div>
					<div class="natural">
						<ul>
							<li>
								<a href="http://item.soolife.cn/34930.html">
									<div class="">
										<img src="/theme/activity/2016_10_infantmom/pc/img/character/character_three.jpg" alt="" data="opengoodsdetail"/>
										<div class="four_seasons">
											<p class="camera">婴儿多功能纯棉薄纱巾</p>
											<p class="comfortable">柔软亲肤  安全天然</p>
											<div class="juzhong">
												<span class="original_cost">原价：599.00</span><span class="activity">  活动价：</span><span class="price">378.00</span>
											</div>
											<div class="purchase">
												<img src="/theme/activity/2016_10_infantmom/pc/img/grow_up/buy.jpg" alt="" />
											</div>
										</div>
									</div>
								</a>
							</li>
							<li class="outside">
								<a href="http://item.soolife.cn/34974.html">
									<div class="antisepsis">
										<img class="maoj" src="/theme/activity/2016_10_infantmom/pc/img/character/character_four.png" alt="" data="opengoodsdetail"/>
										<div class="four_seasons">
											<p class="camera">婴儿竹棉四季透气蜂窝毯</p>
											<p class="comfortable">吸湿透气  抗菌抑菌</p>
											<div class="juzhong">
												<span class="original_cost">原价：528.00</span><span class="activity">  活动价：</span><span class="price">228.00</span>
											</div>
											<div class="purchase">
												<img src="/theme/activity/2016_10_infantmom/pc/img/grow_up/buy.jpg" alt="" />
											</div>
										</div>
									</div>
								</a>
							</li>
							<li class="outside">
								<a href="http://item.soolife.cn/35028.html">
									<div class="">
										<img src="/theme/activity/2016_10_infantmom/pc/img/character/character_five.jpg" alt="" data="opengoodsdetail"/>
										<div class="four_seasons">
											<p class="camera"> 婴儿多功能纯竹纤维薄纱布毯</p>
											<p class="comfortable">纯竹纤维  柔软呵护</p>
											<div class="juzhong">
												<span class="original_cost">原价：399.00</span><span class="activity">  活动价：</span><span class="price">188.00</span>
											</div>
											<div class="purchase">
												<img src="/theme/activity/2016_10_infantmom/pc/img/grow_up/buy.jpg" alt="" />
											</div>
										</div>
									</div>
								</a>
							</li>
						</ul>
					</div>
				</div>
				<!--宝宝智慧加分-->
				<div class="bonus_point">
					<img src="/theme/activity/2016_10_infantmom/pc/img/intelligence/intelligence_baner.png" alt="" />
				</div>
				<div class="lambkin">
					<div class="trait">
						<ul>
							<li>
								<a href="http://item.soolife.cn/34100.html">
									<div class="shell_fabric">
										<img class="knickknack" src="/theme/activity/2016_10_infantmom/pc/img/intelligence/intelligence_one.png" alt="" data="opengoodsdetail"/>
										<div class="four_seasons">
											<p class="camera">乐乐趣拉鲁斯儿童立体百科全书-伟大发明</p>
											<p class="comfortable">伟大发明  百科全书</p>
											<div class="juzhong">
												<span class="original_cost">原价：98.80</span><span class="activity">  活动价：</span><span class="price">57.30</span>
											</div>
											<div class="purchase">
												<img src="/theme/activity/2016_10_infantmom/pc/img/grow_up/buy.jpg" alt="" />
											</div>
										</div>

									</div>
								</a>
							</li>
						</ul>
					</div>
					<div class="trait adjacency">
						<ul>
							<li>
								<a href="http://item.soolife.cn/34102.html">
									<div class="shell_fabric">
										<img class=" contaminate" src="/theme/activity/2016_10_infantmom/pc/img/intelligence/intelligence_two.png" alt=""data="opengoodsdetail" />
										<div class="four_seasons">
											<p class="camera">乐乐趣赛车总动员 神奇赛车故事书（新）</p>
											<p class="comfortable">神奇赛车故事书</p>
											<div class="juzhong">
												<span class="original_cost">原价：188.00</span><span class="activity">  活动价：</span><span class="price">109.00</span>
											</div>
											<div class="purchase">
												<img src="/theme/activity/2016_10_infantmom/pc/img/grow_up/buy.jpg" alt="" />
											</div>
										</div>

									</div>
								</a>
							</li>
						</ul>
					</div>
					<div class="natural one_piece">
						<ul>
							<li >
								<a href="http://item.soolife.cn/37546.html">
									<div class="antisepsis">
										<img class="diapers" src="/theme/activity/2016_10_infantmom/pc/img/intelligence/intelligence_three.png" alt="" data="opengoodsdetail"/>
										<div class="four_seasons">
											<p class="camera">看里面低幼版第二辑（4册）套装</p>
											<p class="comfortable">因为品质  所以卓越</p>
											<div class="juzhong">
												<span class="original_cost">原价：299.00</span><span class="activity">  活动价：</span><span class="price">275.20</span>
											</div>
											<div class="purchase">
												<img src="/theme/activity/2016_10_infantmom/pc/img/grow_up/buy.jpg" alt="" />
											</div>
										</div>
									</div>
								</a>
							</li>
							<li class="outside">
								<a href="http://item.soolife.cn/31132.html">
									<div class="antisepsis">
										<img class="lyq" src="/theme/activity/2016_10_infantmom/pc/img/intelligence/intelligence_four.png" alt="" data="opengoodsdetail"/>
										<div class="four_seasons">
											<p class="camera">条纹孕妇装中长款衬衫连衣裙女</p>
											<p class="comfortable">新品上市  现货抢购</p>
											<div class="juzhong">
												<span class="original_cost">原价：75.00</span><span class="activity">  活动价：</span><span class="price">68.00</span>
											</div>
											<div class="purchase">
												<img src="/theme/activity/2016_10_infantmom/pc/img/grow_up/buy.jpg" alt="" />
											</div>
										</div>
									</div>
								</a>
							</li>
							<li class="outside">
								<a href="http://item.soolife.cn/10044.html">
									<div class="antisepsis">
										<img class="protection" src="/theme/activity/2016_10_infantmom/pc/img/intelligence/intelligence_five.png" alt="" data="opengoodsdetail"/>
										<div class="four_seasons">
											<p class="camera">汉婗喂奶巾</p>
											<p class="comfortable">哺乳遮巾  使用方便</p>
											<div class="juzhong">
												<span class="original_cost">原价：188.00</span><span class="activity">  活动价：</span><span class="price">118.00</span>
											</div>
											<div class="purchase">
												<img src="/theme/activity/2016_10_infantmom/pc/img/grow_up/buy.jpg" alt="" />
											</div>
										</div>
									</div>
								</a>
							</li>
						</ul>
					</div>
				</div>
				
				<!--早教学习-->
				<div class="education">
					<img src="/theme/activity/2016_10_infantmom/pc/img/early_education/early_education_banner.png" alt="" />
				</div>
				<div class="snatch_up">
					<div class="modelling">
						<ul>
							<li>
								<a href="http://item.soolife.cn/28375.html">
									<img src="/theme/activity/2016_10_infantmom/pc/img/early_education/母婴反惠季-pc_03.jpg" alt="" align="top"data="opengoodsdetail"/>
								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/28384.html">
									<img src="/theme/activity/2016_10_infantmom/pc/img/early_education/母婴反惠季-pc_04.jpg" alt=""  align="top"data="opengoodsdetail"/>
								</a>
							</li>
						</ul>
						</div>
						<div class="sureness">
							<ul>
								<li>
									<a href="http://item.soolife.cn/29535.html">
										<div>
											<img class="first"src="/theme/activity/2016_10_infantmom/pc/img/early_education/early_education_three.png" alt="" data="opengoodsdetail"/>
											<div class="four_seasons">
											<p class="camera">I'M TOY狗狗敲击台</p>
											<p class="comfortable">进口水漆  安全无毒</p>
											<div class="juzhong">
												<span class="original_cost">原价：360.00</span><span class="activity">  活动价：</span><span class="price">180.00</span>
											</div>
											<div class="purchase">
												<img src="/theme/activity/2016_10_infantmom/pc/img/grow_up/buy.jpg" alt="" />
											</div>
										</div>
										</div>
									</a>
								</li>
								<li>
									<a href="http://item.soolife.cn/32201.html">
										<div>
											<img class="second"src="/theme/activity/2016_10_infantmom/pc/img/early_education/early_education_four.png" alt=""data="opengoodsdetail" />
											<div class="four_seasons">
											<p class="camera">BCL逻辑关联2式拼图</p>
											<p class="comfortable">爱的智慧  寓教于乐</p>
											<div class="juzhong">
												<span class="original_cost">原价：68.00</span><span class="activity">  活动价：</span><span class="price">34.00</span>
											</div>
											<div class="purchase">
												<img src="/theme/activity/2016_10_infantmom/pc/img/grow_up/buy.jpg" alt="" />
											</div>
										</div>
										</div>
									</a>
								</li>
								<li>
									<a href="http://item.soolife.cn/29530.html">
										<div>
											<img class="three"src="/theme/activity/2016_10_infantmom/pc/img/early_education/early_education_five.png" alt="" data="opengoodsdetail"/>
											<div class="four_seasons">
											<p class="camera">BCL小狗字母拼图</p>
											<p class="comfortable">益智娱乐  字母拼图</p>
											<div class="juzhong">
												<span class="original_cost">原价：88.00</span><span class="activity">  活动价：</span><span class="price">44.00</span>
											</div>
											<div class="purchase">
												<img src="/theme/activity/2016_10_infantmom/pc/img/grow_up/buy.jpg" alt="" />
											</div>
										</div>
										</div>
									</a>
								</li>
							</ul>
						</div>
				</div>
			</div>
		</div>
	</body>

</html>