<!DOCTYPE html>
<html>

	<head>
		<meta charset="UTF-8">
		<title></title>
		<link rel="stylesheet" type="text/css" href="/theme/activity/2016_09_Pentacles/pc/css/pentacle.css" />
	</head>

	<body>
		<div class="lj_wrap">

			<!--头部样式 静图-->
			<div class="lj_header">
				<img src="/theme/activity/2016_09_Pentacles/pc/img/pentaclefirst.jpg" alt="" />
				<img src="/theme/activity/2016_09_Pentacles/pc/img/pentaclefsecond.jpg" alt="" />
				<img src="/theme/activity/2016_09_Pentacles/pc/img/pentaclethree.jpg" alt="" />
				<img src="/theme/activity/2016_09_Pentacles/pc/img/pentaclefour.jpg" alt="" />
				<img src="/theme/activity/2016_09_Pentacles/pc/img/pentaclefive.jpg" alt="" />
				<img src="/theme/activity/2016_09_Pentacles/pc/img/pentaclesix.jpg" alt="" />
				<img src="/theme/activity/2016_09_Pentacles/pc/img/pentacleseven.jpg" alt="" />
				<img src="/theme/activity/2016_09_Pentacles/pc/img/pentacleeight.jpg" alt="" />
			</div>
			<!--中间部分商品展示-->
			<div class="lj_center">
				<!--精品集结-->
				<ul class="center_sift">
					<li>
						<a href="http://item.soolife.cn/23292.html"><img src="/theme/activity/2016_09_Pentacles/pc/img/cup.jpg" data="opengoodsdetail"/>
						<img class="pricefirst" data="openinstantbuy" src="/theme/activity/2016_09_Pentacles/pc/img/siftone.jpg" />
						<p class="oldprice">原价：106.0元</p>
						<p class="brand">施密特灵动直杯360 </p>
						<p class="trait">时尚设计 放心材质</p>
						</a>
					</li>
					<li>
						<a href="http://item.soolife.cn/5121.html"><img src="/theme/activity/2016_09_Pentacles/pc/img/massage.jpg" data="opengoodsdetail"/>
						<img class="price" src="/theme/activity/2016_09_Pentacles/pc/img/sifttwo.jpg" data="openinstantbuy"/>
						<p class="oldprice">原价：156.0元</p>
						<p class="brand">敲敲乐颈肩按摩器</p>
						<p class="trait">明星产品 全新升级</p>
						</a>
					</li>
					<li>
						<a href="http://item.soolife.cn/13624.html"><img src="/theme/activity/2016_09_Pentacles/pc/img/Dior.jpg" data="opengoodsdetail"/>
						<img class="price" src="/theme/activity/2016_09_Pentacles/pc/img/siftthree.jpg" data="openinstantbuy"/>
						<p class="oldprice">原价：169.5元</p>
						<p class="brand">科夫氏 超能蜗牛霜</p>
						<p class="trait">收缩毛孔 提拉紧致</p>
						</a>
					</li>
					<li>
						<a href="http://item.soolife.cn/32758.html"><img src="/theme/activity/2016_09_Pentacles/pc/img/Ragdoll.jpg" data="opengoodsdetail" />
						<img class="price" src="/theme/activity/2016_09_Pentacles/pc/img/siftfour.jpg" data="openinstantbuy" />
						<p class="oldprice">原价：79.90元</p>
						<p class="brand">悠悠琦奇大咀猴 </p>
						<p class="trait">别样礼物 多色可选</p>
						</a>
					</li>
				</ul>
				<!--发现好品牌-->
				<ul class="center_find">
					<li>
						<a href="http://item.soolife.cn/35977.html"><img src="/theme/activity/2016_09_Pentacles/pc/img/Donlim.jpg" data="opengoodsdetail" />
						<img class="price" src="/theme/activity/2016_09_Pentacles/pc/img/findone.jpg" data="openinstantbuy"/>
						<p class="oldprice">原价：299元</p>
						<p class="brand">九阳豆浆机</p>
						<p class="trait">经典升级 让爱豆留</p>
						</a>
					</li>
					<li>
						<a href="http://item.soolife.cn/36349.html"><img src="/theme/activity/2016_09_Pentacles/pc/img/Luggage.jpg" data="opengoodsdetail" />
						<img class="price" src="/theme/activity/2016_09_Pentacles/pc/img/findtwo.jpg" data="openinstantbuy" />
						<p class="oldprice">原价：239元</p>
						<p class="brand">经典镜面款拉杆箱 </p>
						<p class="trait">实用设计 简约气质</p>
						</a>
					</li>
					<li>
						<a href="http://item.soolife.cn/11136.html"><img src="/theme/activity/2016_09_Pentacles/pc/img/footspa.jpg" data="opengoodsdetail"/>
						<img class="price" src="/theme/activity/2016_09_Pentacles/pc/img/findthree.jpg" data="openinstantbuy" />
						<p class="oldprice">原价：398.0元</p>
						<p class="brand">自动按摩足浴盆</p>
						<p class="trait">一键控制 温热按摩</p>
						</a>
					</li>
					<li>
						<a href="http://item.soolife.cn/21198.html"><img src="/theme/activity/2016_09_Pentacles/pc/img/Air.jpg" data="opengoodsdetail"/>
						<img class="price" src="/theme/activity/2016_09_Pentacles/pc/img/findfour.jpg" data="openinstantbuy"/>
						<p class="oldprice">原价：599.0</p>
						<p class="brand">甩脂塑腰美臀机 </p>
						<p class="trait">舒服享受 美臀塑型</p>
						</a>
					</li>
				</ul>
				<!--特惠食品-->
				<ul class="center_food">
					<li>
						<a href="http://item.soolife.cn/13976.html"><img src="/theme/activity/2016_09_Pentacles/pc/img/whitewine.jpg" data="opengoodsdetail"/>
						<img class="price" src="/theme/activity/2016_09_Pentacles/pc/img/food_one.jpg" data="openinstantbuy" />
						<p class="oldprice">原价：70.0元</p>
						<p class="brand">白甜型起泡葡萄酒</p>
						<p class="trait">闲暇优雅 品质情调</p>
						</a>
					</li>
					<li>
						<a href="http://item.soolife.cn/30904.html"><img src="/theme/activity/2016_09_Pentacles/pc/img/cookie.jpg" data="opengoodsdetail"/>
						<img class="price" src="/theme/activity/2016_09_Pentacles/pc/img/food_two.jpg" data="openinstantbuy"/>
						<p class="oldprice">原价：14.9元</p>
						<p class="brand">青稞膳食纤维饼干 </p>
						<p class="trait">膳食纤维 蔓越莓味</p>
						</a>
					</li>
					<li>
						<a href="http://item.soolife.cn/23329.html"><img src="/theme/activity/2016_09_Pentacles/pc/img/bearclaw.jpg" data="opengoodsdetail"/>
						<img class="price" src="/theme/activity/2016_09_Pentacles/pc/img/food_three.jpg"  data="openinstantbuy"/>
						<p class="oldprice">原价：128.0元</p>
						<p class="brand">江苏裕德隆 熊掌菇</p>
						<p class="trait">肉质肥厚 营养丰富 </p>
						</a>
					</li>
					<li>
						<a href="http://item.soolife.cn/34007.html"><img src="/theme/activity/2016_09_Pentacles/pc/img/medlar.jpg" data="opengoodsdetail"/>
						<img class="price" src="/theme/activity/2016_09_Pentacles/pc/img/food_four.jpg" data="openinstantbuy"/></a>
						<p class="oldprice">原价：338.0元</p>
						<p class="brand">森淼冻干枸杞贡果级</p>
						<p class="trait">冻干枸杞 粒大味甜</p>
						</a>
					</li>
					<li>
						<a href="http://item.soolife.cn/31036.html"><img src="/theme/activity/2016_09_Pentacles/pc/img/lehua.jpg" data="opengoodsdetail"/>
						<img class="price" src="/theme/activity/2016_09_Pentacles/pc/img/food_five.jpg" data="openinstantbuy" />
						<p class="oldprice">原价：150.0元</p>
						<p class="brand">乐华红葡萄酒 </p>
						<p class="trait">口感甘甜 入口顺滑</p>
						</a>
					</li>
					<li>
						<a href="http://item.soolife.cn/13979.html"><img src="/theme/activity/2016_09_Pentacles/pc/img/spumante.jpg" data="opengoodsdetail"/>
						<img class="price" src="/theme/activity/2016_09_Pentacles/pc/img/food_six.jpg" data="openinstantbuy" />
						<p class="oldprice">原价：90.0元</p>
						<p class="brand">绝干起泡葡萄酒</p>
						<p class="trait">原装进口 回味悠长</p>
						</a>
					</li>
					<li>
						<a href="http://item.soolife.cn/13980.html"><img src="/theme/activity/2016_09_Pentacles/pc/img/whitewine.jpg" data="opengoodsdetail"/>
						<img class="price" src="/theme/activity/2016_09_Pentacles/pc/img/food_seven.jpg" data="openinstantbuy" />
						<p class="oldprice">原价：180.0元</p>
						<p class="brand">高泡起泡葡萄酒</p>
						<p class="trait">味道甜美 口感温和</p>
						</a>
					</li>
					<li>
						<a href="http://item.soolife.cn/28350.html"><img src="/theme/activity/2016_09_Pentacles/pc/img/honeydate.jpg" data="opengoodsdetail"/>
						<img class="price" src="/theme/activity/2016_09_Pentacles/pc/img/food_eight.jpg" data="openinstantbuy" />
						<p class="oldprice">原价：60.0元</p>
						<p class="brand">江中阿胶蜜枣</p>
						<p class="trait">甜糯可口 甜而不腻</p>
						</a>
					</li>
				</ul>
				<!--个护彩妆-->
				<ul class="centet_cosmetics">
					<li>
						<a href="http://item.soolife.cn/15444.html"><img src="/theme/activity/2016_09_Pentacles/pc/img/apitoxin.jpg" data="opengoodsdetail"/>
						<img class="price" src="/theme/activity/2016_09_Pentacles/pc/img/cosmeticsone.jpg" data="openinstantbuy" />
						<p class="oldprice">原价：750.0元</p>
						<p class="brand">蜂毒原液超值5件套</p>
						<p class="trait">留住青春 锁住滋润</p>
						</a>
					</li>
					<li>
						<a href="http://item.soolife.cn/27289.html"><img src="/theme/activity/2016_09_Pentacles/pc/img/dentifrices.jpg" data="opengoodsdetail"/>
						<img class="price" src="/theme/activity/2016_09_Pentacles/pc/img/cosmeticstwo.jpg" data="openinstantbuy" />
						<p class="oldprice">原价：19.0元</p>
						<p class="brand">2080 青龈茶牙膏</p>
						<p class="trait">清新口气 健康生活</p>
						</a>
					</li>
					<li>
						<a href="http://item.soolife.cn/27146.html"><img src="/theme/activity/2016_09_Pentacles/pc/img/shampoo.jpg" data="opengoodsdetail"/>
						<img class="price" src="/theme/activity/2016_09_Pentacles/pc/img/cosmeticsthree.jpg" data="openinstantbuy" />
						<p class="oldprice">原价：59.9元</p>
						<p class="brand">自然雅舍水果香波</p>
						<p class="trait">柔顺易梳 远离静电</p>
						</a>
					</li>
					<li>
						<a href="http://item.soolife.cn/28917.html"><img src="/theme/activity/2016_09_Pentacles/pc/img/nature.jpg" data="opengoodsdetail"/>
						<img class="price" src="/theme/activity/2016_09_Pentacles/pc/img/cosmeticsfour.jpg" data="openinstantbuy" />
						<p class="oldprice">原价：765.0元</p>
						<p class="brand">自然系列套装</p>
						<p class="trait">水润肌肤 超强保湿</p>
						</a>
					</li>
				</ul>
				<!--日用百货-->
				<ul class="center_sears">
					<li>
						<a href="http://item.soolife.cn/34168.html"><img src="/theme/activity/2016_09_Pentacles/pc/img/watera.jpg" data="opengoodsdetail"/></a>
					</li>
					<li>
						<a href="http://item.soolife.cn/31777.html"><img src="/theme/activity/2016_09_Pentacles/pc/img/shampoos.jpg" data="opengoodsdetail"/></a>
					</li>
					<li>
						<a href="http://item.soolife.cn/35574.html"><img src="/theme/activity/2016_09_Pentacles/pc/img/towel.jpg" data="opengoodsdetail"/>
						<img class="price" src="/theme/activity/2016_09_Pentacles/pc/img/sear_one.jpg" data="openinstantbuy" />
						<p class="oldprice">原价：55.0元</p>
						<p class="brand">多功能清洁布擦手巾</p>
						<p class="trait">耐磨易洗 吸水性强</p>
						</a>
					</li>
					<li>
						<a href="http://item.soolife.cn/33834.html"><img src="/theme/activity/2016_09_Pentacles/pc/img/decanter.jpg" data="opengoodsdetail"/>
						<img class="price" src="/theme/activity/2016_09_Pentacles/pc/img/sear_two.jpg" data="openinstantbuy" />
						<p class="oldprice">原价：135.0元</p>
						<p class="brand">快速醒酒器珍藏版</p>
						<p class="trait">流体设计 中心进气</p>
						</a>
					</li>
					<li>
						<a href="http://item.soolife.cn/34132.html"><img src="/theme/activity/2016_09_Pentacles/pc/img/crisper.jpg" data="opengoodsdetail"/>
						<img class="price" src="/theme/activity/2016_09_Pentacles/pc/img/sear_three.jpg" data="openinstantbuy" />
						<p class="oldprice">原价：69.0元</p>
						<p class="brand">玻璃保鲜盒三件套</p>
						<p class="trait">简易方便 抗磨性好</p>
						</a>
					</li>
					<li>
						<a href="http://item.soolife.cn/34146.html"><img src="/theme/activity/2016_09_Pentacles/pc/img/goblet.jpg" data="opengoodsdetail"/>
						<img class="price" src="/theme/activity/2016_09_Pentacles/pc/img/sear_four.jpg" data="openinstantbuy" />
						<p class="oldprice">原价：44.9元</p>
						<p class="brand">品味高脚杯</p>
						<p class="trait">时尚耐用 手感舒适</p>
						</a>
					</li>
				</ul>
				<!--底部样式-->
				<div class="lj_footer">
					<img src="/theme/activity/2016_09_Pentacles/pc/img/footer.jpg" />
				</div>
			</div>

		</div>
	</body>

</html>