<?php
$css = $this->assets->get('header');
$css -> addCss("public/css/basic.css");
$js  = $this->assets->get('footer');
?>
<div class="row main">
    <div class="col-sm-12">       
        <div style="border-left: 6px solid #36a0da;">
            <h2 style="padding-left: 20px;padding-bottom: 10px;">市场背景</h2>
            <p style="padding-left: 20px;">Market Background</p>
        </div>
        <div style="text-indent: 2em;color: #666666; margin-top: 30px;font-size: 14px;">
        	<p>过去的30年,是中国商业环境迅速演变的30年。居民收入稳定增长,实惠产品日益丰富,消费者的购物方式与购物需求也发生了翻天覆地的变化。传统购物理念直面新挑战,购物中心不再单纯是购物场所,还兼备了吃喝玩乐等各种娱乐形态。互连网的普及和电子商务的兴起,将人们的购物环境无限扩展。</p>
            <p>然而伴随着日趋激励的市场竞争,品牌商暴力时代终结,提升消费者购物体验、改变经营方式已迫在眉睫。</p>
        </div>
        <div style="text-align: center;">
        	<h2 style="margin-top: 60px;color: #0068b6;font-size: 18px;margin-bottom: 40px;">中国消费者购物方式的演变轨迹</h2>
        	<ul class="track">
        		<li style="padding-left: 70px;color: #666666;">
        		<img src="../public/img/business/businessModel01.png" alt="如此生活">
        		<p style="padding-top: 20px;padding-right: 50px;">闭着眼就能赚钱的时代</p>
        		</li>
        		<li style="padding-left: 40px;color: #666666;">
        		<img src="../public/img/business/businessModel02.png" alt="如此生活">
        		<p style="padding-top: 20px;padding-right: 50px;">努力就能赚钱的时代</p>
        		</li>
        		<li style="padding-left: 40px;color: #666666;">
        		<img src="../public/img/business/businessModel03.png" alt="如此生活">
        		<p style="padding-top: 20px;">现在是个什么样的时代?</p>
        		</li>
        	</ul>
        </div>
    </div>
    <div class="col-sm-12" style="margin-top: 110px;">
    	<div class="col-sm-6">
    		<div style="border-left: 6px solid #36a0da;">
	            <h2 style="padding-left: 20px;padding-bottom: 10px;">商业环境</h2>
	            <p style="padding-left: 20px;">Business Environment</p>
        	</div>
        	<div style="text-indent: 2em; margin-top: 30px;color: #666666;">
        		<p>电商与实体店抱团成常态，全渠道已是大势所趋。2016年，互联网势必结束多年来的野蛮生长，进入下半场的竞技。与实体经济相结合，而不是依赖渠道红利，将为电商发展带来更大的发展契机。</p>
        		<p>"如此生活"平台的出发点正是基于大平台的全渠道策略而精心打造的。</p>
        	</div>
        	<div style="margin-top: 58px;">
        		<img src="../public/img/business/businessModel04.png" alt="如此生活">
        	</div>
    	</div>
    	<div class="col-sm-6" style="padding-left: 40px;">
    		<div style="border-left: 6px solid #36a0da;">
	            <h2 style="padding-left: 20px;padding-bottom: 10px;">数据分析</h2>
	            <p style="padding-left: 20px;">Data Analsis</p>
       		</div>
       		<div style="text-indent: 2em; margin-top: 30px;color: #666666;">
        		<p>生产经营成本的持续增加,导致企业普遍面临较大的压力,跑不赢运营成本的上涨速度,将无法持续增长,盈利越来越难。</p>
        	</div>
        	<div style="margin-top: 38px;">
        		<img src="../public/img/business/businessModel05.png" alt="如此生活">
        	</div>
    	</div>
    </div>
    <div class="col-sm-12" style="margin-top: 110px;">
    	<div class="col-sm-6">
    		<div style="border-left: 6px solid #36a0da;">
	            <h2 style="padding-left: 20px;padding-bottom: 10px;">市场趋势</h2>
	            <p style="padding-left: 20px;">Market Trends</p>
        	</div>
        	<div style="text-indent: 2em; margin-top: 30px;color: #666666;">
        		<p>网络权威数据分析出近年来各品牌销售排行榜,淘品牌销售被大咖品牌压制,单独做线上就能赚钱的时代已不复存在,经营方式亟待改变。</p>
        	</div>
        	<div style="margin-top: 58px;">
        		<img src="../public/img/business/businessModel06.png" alt="如此生活">
        	</div>
    	</div>
    	<div class="col-sm-6" style="padding-left: 40px;">
    		<div style="border-left: 6px solid #36a0da;">
	            <h2 style="padding-left: 20px;padding-bottom: 10px;">路在何方</h2>
	            <p style="padding-left: 20px;">Where is the way</p>
       		</div>
       		<div style="text-indent: 2em; margin-top: 30px;color: #666666;">
        		<p>当下市场,危机重重,商家该何去何从？</p>
        	</div>
        	<div style="margin-top: 38px;">
        		<img src="../public/img/business/businessModel07.png" alt="如此生活">
        	</div>
    	</div>
    </div>
    <div class="col-sm-12" style="margin-top: 110px;">
    	<div style="border-left: 6px solid #36a0da;">
            <h2 style="padding-left: 20px;padding-bottom: 10px;">商业模式</h2>
            <p style="padding-left: 20px;">Business Model</p>
        </div>
        <div style="color: #666666; margin-top: 30px;font-size: 14px;">
        	<p>soolife-如此生活是以O2O为基础,一站式服务为核心,数据云管理系统营销系统为支点打造的全新商业模式。</p>
        </div>
        <div style="margin-top: 38px;">
        	<div class="col-sm-12">
        		<img src="../public/img/business/businessModel08.png" alt="如此生活">
        	</div>
        	<div class="col-sm-12">
        		<img src="../public/img/business/businessModel09.png" alt="如此生活">
        	</div>
    	</div>
    </div>
    <div class="col-sm-12" style="margin-top: 110px;">
    	<div style="border-left: 6px solid #36a0da;">
            <h2 style="padding-left: 20px;padding-bottom: 10px;">一站式服务</h2>
            <p style="padding-left: 20px;">Business Model</p>
        </div>
        <div style="margin-top: 90px;">
            <img src="../public/img/business/businessModel.png" alt="如此生活">
<!--        	<div class="col-sm-6">
        		<ul>
        			<li>
        			   <img src="../public/img/business/businessModel10.png" alt="如此生活">
        			</li>
        			<li style="padding-top: 50px;">
        				<img src="../public/img/business/businessModel11.png" alt="如此生活">
        				</li>
        			<li style="padding-top: 50px;">
        				<img src="../public/img/business/businessModel12.png" alt="如此生活">
        			</li>
        		</ul>
        	</div>
        	<div class="col-sm-6">
        		<ul style="padding-left: 80px;">
        			<li><img src="../public/img/business/businessModel13.png" alt="如此生活"></li>
        			<li><img src="../public/img/business/businessModel14.png" alt="如此生活"></li>
        		</ul>
        	</div>-->
    	</div>
    </div>
</div>
