<?php
$css = $this->assets->get('header');
$css -> addCss("public/css/basic.css");
$js  = $this->assets->get('footer');
?>
<div class="row" style="margin-top:20px;"
	<div class="col-sm-12">
		<div class="col-sm-7" style="padding-left: 0;">
			<img src="../public/img/business/experienceCenter01.png" alt="如此生活">
		</div>
		<div class="col-sm-5">
			 <div style="border-left: 6px solid #36a0da; margin-top: 110px;">
	             <h2 style="padding-left: 10px;padding-bottom: 10px;">市场背景</h2>
	             <p style="padding-left: 10px;color: #666;">Boutique highlights</p>
        	 </div>
        	 <div style="margin-top: 30px;color: #666;line-height: 25px;">
        	 	<p>精：聚焦知名品牌的畅销精品，精心打造专属的购物空间与定制化服务。</p>
        	 	<p>特：聚焦众多奇特和先进的科技类产品，满足新新人类的猎奇体验需要。</p>
        	 	<p>潮：聚焦市场时尚流行前沿，打造潮品快时尚的年轻潮流文化。</p>
        	 	<p>星：聚焦明星代言和明星冠名的知名品牌商品，引领网红经济。</p>
        	 </div>
		</div>
	</div>
	<div class="col-sm-12" style="margin-top: 135px;">
		<div class="col-sm-5">
			<div style="border-left: 6px solid #36a0da;">
	             <h2 style="padding-left: 10px;padding-bottom: 10px;">互动体验亮点</h2>
	             <p style="padding-left: 10px;color: #666;">Interavtive experience highlights</p>
	    	 </div>
	    	 <div style="margin-top: 28px;">
	    	 	<h3 style="color: #0068b6;font-size: 18px;padding-bottom: 16px;">秀吧区</h3>
	    	 	<p style="color: #666666;padding-bottom: 16px;">每一个最美的一面都应该展示出来，让自己成为生活中一道风景！在这里会员可以展现自我，秀出美丽的自己！</p>
	    	 	<h3 style="color: #0068b6;font-size: 18px;padding-bottom: 16px;">书吧区</h3>
	    	 	<p style="color: #666666;padding-bottom: 16px;">每一个人的空间，都是一个五彩的世界，书内的世界，蕴藏着无限遐想！在这里我们为会延缓提供休闲的书籍和杂志，让心沉静在书的海洋，远离喧闹！</p>
	    	 	<h3 style="color: #0068b6;font-size: 18px;padding-bottom: 16px;">美吧区</h3>
	    	 	<p style="color: #666666;padding-bottom: 16px;">爱美之心，人皆有之；温馨的空间，帮您打造属于自己的美丽！在这里会员享有免费的美发、美甲、造型设计！</p>
	    	 	<h3 style="color: #0068b6;font-size: 18px;padding-bottom: 16px;">乐吧区</h3>
	    	 	<p style="color: #666666;padding-bottom: 16px;">儿童是我们的未来，正如早晨八九点钟的太阳，冉冉升起！在这里为每个儿童提供游戏空间和学习平台！</p>
	    	 	<h3 style="color: #0068b6;font-size: 18px;padding-bottom: 16px;">水吧区</h3>
	    	 	<p style="color: #666666;">生活的未来，正如浓郁的咖啡，散发着芬香，沁人心扉！在这里我们为会员提供免费饮品，让会员远离疲惫，尽享生活！</p>
	    	 </div>
		</div>
		<div class="col-sm-7">
			<div class="col-sm-12">
				<div class="col-sm-5" style="padding-left: 0;">
					<img src="../public/img/business/experienceCenter02.png" alt="如此生活">
				</div>
				<div class="col-sm-7">
					<img src="../public/img/business/experienceCenter03.png" alt="如此生活">
				</div>
			</div>
			<div class="col-sm-12">
				<img src="../public/img/business/experienceCenter04.png" alt="如此生活">
			</div>
		</div>
	</div>
	<div class="col-sm-12" style="margin-top: 80px;">
		<div class="col-sm-7">
			<img src="../public/img/business/experienceCenter05.png" alt="如此生活">
			<img src="../public/img/business/experienceCenter06.png" alt="如此生活">
		</div>
		<div class="col-sm-5">
			<div style="border-left: 6px solid #36a0da;">
	             <h2 style="padding-left: 10px;padding-bottom: 10px;">文化展示亮点</h2>
	             <p style="padding-left: 10px;color: #666;">Cultural highlights</p>
        	 </div>
        	 <div style="margin-top: 24px;color: #666;">
        	 	<p>这里有年轻一代互联网群，年轻化的装修特殊，这里是新潮流、新文化、新思想的发源地这里有商品互动体验，这里是感动、欢乐、自在的小天地;这里有创客们热血澎湃的奋斗故事；这里有感动自己的一封家书，写给未来的自己！</p>
        	 </div>
		</div>
	</div>
	<div class="col-sm-12" style="margin-top: 58px;">
		<div class="col-sm-5">
			<div style="border-left: 6px solid #36a0da;">
	             <h2 style="padding-left: 10px;padding-bottom: 10px;">营销活动亮点</h2>
	             <p style="padding-left: 10px;color: #666;">Marketing highlights</p>
	    	 </div>
	    	 <div style="margin-top: 28px;">
	    	 	<h3 style="color: #0068b6;font-size: 18px;padding-bottom: 16px;">当天送</h3>
	    	 	<p style="color: #666666;padding-bottom: 16px;">每日送出精美纪念品和免费赠品给新注册会员，转发也可以领取红包奖励</p>
	    	 	<h3 style="color: #0068b6;font-size: 18px;padding-bottom: 16px;">周活动</h3>
	    	 	<p style="color: #666666;padding-bottom: 16px;">每周组织线下线上活动，参与可以抽奖并有礼品，且分享也会有星币领取</p>
	    	 	<h3 style="color: #0068b6;font-size: 18px;padding-bottom: 16px;">月抄家</h3>
	    	 	<p style="color: #666666;padding-bottom: 16px;">每月组织商品特卖，精选众多商品进行特卖抢购，引爆市场消费，赢得关注</p>
	    	 </div>
		</div>
		<div class="col-sm-7">
			<img src="../public/img/business/experienceCenter07.png" alt="如此生活">
		</div>
	</div>
	<div class="col-sm-12" style="margin-top: 120px;">
		<div style="border-left: 6px solid #36a0da;margin-left: 500px;">
             <h2 style="padding-left: 10px;padding-bottom: 10px;">体验店坐落图</h2>
             <p style="padding-left: 10px;color: #666;">Experience store is located map</p>
    	 </div>
    	 <ul style="text-align: center;margin-top: 30px;">
    	 	<li><img src="../public/img/business/experienceCenter08.png" alt="如此生活"></li>
    	 	<li style="padding-bottom: 40px;"><img src="../public/img/business/experienceCenter09.png" alt="如此生活"></li>
    	 	<li><img src="../public/img/business/experienceCenter10.png" alt="如此生活"></li>
    	 	<li style="padding-bottom: 40px;"><img src="../public/img/business/experienceCenter11.png" alt="如此生活"></li>
    	 	<li><img src="../public/img/business/experienceCenter12.png" alt="如此生活"></li>
    	 	<li><img src="../public/img/business/experienceCenter13.png" alt="如此生活"></li>
    	 </ul>

	</div>
	<div class="col-sm-12" style="text-align: left;margin-top: 120px;">
		 <div class="col-sm-7" style="color: #666;">
    	 	<dl style="padding-left: 215px;">
	    		<dt style="padding-bottom: 20px;font-size: 18px;">上海</dt>
	    		<dd>上海嘉定宝龙商城如此生活店</dd>
	    		<dd>上海嘉定区宝塔路德富路嘉定宝龙广场2F</dd>
	    		<dd>上海松江万达百货如此生活</dd>
	    		<dd>上海市松江区广富林路658弄668号上海松江万达广场F4层</dd>
    	 	</dl>
    	 </div>	
    	 <div class="col-sm-5" style="color: #666;margin-bottom: 60px;">
    	 	<div class="col-sm-12">
    	 		<dl>
		    		<dt style="padding-bottom: 20px;font-size: 18px;">苏州</dt>
		    		<dd>苏州国发平江大厦如此生活店</dd>
		    		<dd>江苏省苏州市人民路3118号苏州国发平江大厦B1</dd>
		    	 </dl>
    	 	</div>
    	 	<div class="col-sm-12">
    	 		<dl>
		    		<dt style="padding-bottom: 20px;font-size: 18px;">镇江</dt>
		    		<dd>镇江宝龙广场如此生活店</dd>
		    		<dd>江苏省镇江市丹徒区谷阳中大道镇江宝龙广场3F</dd>
		    	 </dl>
    	 	</div>
    	 </div>
	</div>
</div>