<?php
$css = $this->assets->get('header');
$css -> addCss("public/css/basic.css");
$js  = $this->assets->get('footer');
?>
<div class="row" style="margin-bottom:100px;margin-top:20px;">
    <div class="col-sm-12" style="margin-bottom: 30px;">
        <div style="border-left: 6px solid #36a0da;" id="Brandadvantage">
            <h2 style="padding-left:10px;">品牌优势</h2>
            <p>Brand advantage</p>
        </div>
    </div>
    <div class="col-sm-12">
        <div class="col-sm-6">
            <div class="row">
                <div class="col-sm-12">
                    <div class="col-sm-6">
                        <h2 class="number" style="margin-left: 60px;">1</h2>
                        <p class="title" style="padding-left: 40px;">如此生活官网</p>
                        <p style="padding-top: 20px; color: #666666;">通过一站式服务理念,借助了平台四大<br>功能板块导流,增加了消费者与平台的<br>互动体验和粘度,帮助提高商家的品牌<br>知名度和销售,商家无需花钱投放广告<br>宣传。</p>
                    </div>
                    <div class="col-sm-6">
                        <img src="../public/img/business/platformIntroduction01.png" alt="如此生活"
                             style="margin-left: -100px;padding-top: 100px;">
                    </div>
                </div>
                <div class="col-sm-12">
                    <div class="row" style="text-align: center; margin-top: 80px;">
                        <div class="col-sm-12">
                            <h2 class="number" style="margin-left: 250px;">3</h2>
                            <p class="title">如此生活体验店</p>
                            <p style="padding-top: 20px; color: #666666;">通过一站式服务理念，平台提供体验店商品<br>展示和零售，商家无需自行建立产品专卖店，<br>就可以将商品进行线下销售，省了开店成本。</p>
                        </div>
                        <div class="col-sm-12" style="padding-top: 24px;">
                            <img src="../public/img/business/platformIntroduction03.png" alt="如此生活">
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="row" style="text-align: center;">
                <div class="col-sm-12">
                    <h2 class="number" style="margin-left: 260px;">2</h2>
                    <p class="title">移动端</p>
                    <p style="padding-top: 20px; color: #666666;">平台通过移动端，开通微商城、微店等功能模块，为上架店铺导流。</p>
                </div>
                <div class="col-sm-12" style="padding-top: 45px;">
                    <img src="../public/img/business/platformIntroduction02.png" alt="如此生活" style="">
                </div>
            </div>
            <div class="col-sm-12">
                <h2 class="number" style="margin-left:180px;  margin-top: 60px;">4</h2>
                <p class="title" style="margin-left: 100px;">一站式存储大仓、配送服务</p>
                <div class="row">
                    <div class="col-sm-8" style="margin: 0;padding: 0;">
                        <p style="padding-top: 20px; color: #666666;">通过一站式服务理念，平台提供商品存储和货物配送，商家无需自行建立存储仓库，就可以将商品全国区域存放，节省了储运成本。<br>
						平台提供商品一件代发和店内自提，商家<br>无需自行发货至客户，节省了物流管理成本
                        </p>
                    </div>
                    <div class="col-sm-4" style="margin-bottom: 5px;">
                        <img src="../public/img/business/platformIntroduction04.png" alt="如此生活" style="width: 100%;">
                    </div>
                </div>
            </div>
            <div class="col-sm-12">
                <img src="../public/img/business/platformIntroduction05.png" alt="如此生活" style="width: 100%;">
            </div>
        </div>
    </div>
</div>