<?php
$css = $this -> assets -> get('header');
$css -> addCss("public/v3.0.1/css/pc.discount.css");

$js = $this -> assets -> get('footer');
$js -> addJs("public/v3.0.1/js/pc.discount.js");

$style = '';
if (!empty($banner))
{
	$item = current($banner);
	$style = @"background: {$item['bgcolor']} url('{$this->utility->get_advert_picture($item['bgimage'])}') no-repeat center center;";
}
?>
<div id="banner" class="banner" style="{{ style }}">
	<div class="discount_banner main-container">
		<div class="discount_banner_carousel">
			<!-- begin carousel -->
			<div id="carousel-index"  class="carousel slide" data-ride="carousel">
				<ol class="carousel-indicators">
					{% if banner %}
						{% for d in banner %}
							<li data-target="#carousel-index" data-slide-to="{{loop.index0}}" {% if loop.first %} class="active" {% endif %}></li>
						{% endfor %}
					{% endif %}
				</ol>
				<div class="carousel-inner" role="listbox">
					{% if banner %}
						{% for d in banner %}
						<div class="item  {% if loop.first %} active {% endif %}" 
							data-bgcolor="{{d['bgcolor']}}" 
							data-bgimage="<?php echo $this->utility->get_advert_picture($d['bgimage']); ?>"
							data-link="{{d['link']}}" 
							data-id="{{d['id']}}">
							<a href="{{d['link']}}" target="_blank">
								<img class="carousel-images" src="<?php echo $this->utility->get_advert_picture($d['picture']); ?>" alt="{{d['title']}}">
							</a>
						</div>
						{% endfor %}
					{% endif %}
				</div>
			</div>
			<!-- end carousel -->
		</div>
	</div>
</div>

<div id="coupons" class="row-container clearfix">
	<div class="coupons main-container">
		<ul>
			{% if ads['pc.discount.floor.001'] %}
				{% for d in ads['pc.discount.floor.001'] %}
					<li>
						<a href="{{d['pc_link']}}" target="_blank" title="{{d['title']}}">
					 		<img class="lazy" src="/public/v3.0.1/img/s.gif" data-original="<?php echo $this->utility->get_advert_picture($d['picture']); ?>" title="{{d['title']}}" alt="{{d['title']}}" />
					 	</a>
					</li>
				{% endfor %}
			{% endif %}
		</ul>
		<div class="clearfix"></div>
	</div>
	<div class="full-column main-container">
		<?php echo $this->utility->get_advert_html('pc.discount.floor.column',$ads); ?>
	</div>
</div>