<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>如此生活|会员中心</title>
	<meta name="viewport" content="width=device-width, initial-scale=1,maximum-scale=1,user-scalable=no">
	<meta name="apple-mobile-web-app-capable" content="yes">
	<meta name="apple-mobile-web-app-status-bar-style" content="black">	
    <link rel="stylesheet" href="/public/ext/css/soo.m.ui.css">
    <link rel="stylesheet" href="/public/ext/css/download.css">
    <link rel="stylesheet" href="/public/ext/css/swiper.css">
	<link rel="stylesheet" type="text/css" href="/public/css/orders/common.css"/>
	<link rel="stylesheet" type="text/css" href="/public/css/i/common.css"/>
	<link rel="stylesheet" type="text/css" href="/public/css/orders/mylifeallstyle.css"/>
</head>
<body>
<div class="index_wrap">
	<div class="header">
	    <a onclick="window.history.go(-1)">
	        <img class="arrow"  src="/public/img/common/shop_back_black@1x.png " ></a>
		<span class="head_title">物流信息</span> 
	</div>
	<div class="main">
		<div class="deliverBriefBox clearfix">
			<div class="deliverMethod">
			    <input type="hidden" id="express_name" value="{{ result['express_name'] }}" name="">
				<img src="/public/img/orders/order_deli@3x.png"/>
			</div>
			<div class="deliverBrief">
				<p>
					物流公司：<span>{{ result['express_name'] }}</span>
				</p>
				<p>
					运单号码：<span>{{ result['express_code'] }}</span>
				</p>
				<p>
					物流状态：<span>{{ record }}</span>
				</p>
			</div>
		</div>
		<div class="deliverDetailBox clearfix">
			<div class="deliverDetailLine">
				<ul>
					{% for k,v in result['logs'] %}
					{% if k==0 %}
					<li>
						<i class="icon-circle recentlyUpdate">
						</i>
						<div class="line">
						</div>
					</li>
					{% else %}
					<li>
						<i class="icon-circle">
						</i>
						<div class="line">
						</div>
					</li>
					{% endif %}
					{% endfor %}
				</ul>
			</div>
			<div class="deliverinfoDetail">
				<ul>
					{% for k,v in result['logs'] %}
					<li class="deliverStep">
						<p>
							{{v['record']}}
						</p>
						<p class="deliverDate">
							{{date("Y-m-d H:i:s",v['create_time'])}}
						</p>
					</li>
					{% endfor %}
				</ul>
			</div>
		</div>
	</div>	
</div>
</body>
</html>
<script src="/public/ext/js/jquery-1.8.3.min.js"></script>
<script src="/public/js/jquery.base64.js"></script>
<script src="/public/ext/js/soo.m.ui.js"></script>
<script src="/public/ext/js/download.js"></script>
<!-- <script src="/public/js/orders/view.orders.comment.js"></script>
<script src="/public/js/orders/view.orders.index.js"></script>
<script src="/public/js/orders/view.orders.index.middle.js"></script> -->
<script src="/public/js/orders/view.orders.deliverinfo.js"></script>