<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>如此生活|会员中心</title>
	<meta name="viewport" content="width=device-width, initial-scale=1,maximum-scale=1,user-scalable=no">
	<meta name="apple-mobile-web-app-capable" content="yes">
	<meta name="apple-mobile-web-app-status-bar-style" content="black">	
    <link rel="stylesheet" href="/public/ext/css/soo.m.ui.css">
    <link rel="stylesheet" href="/public/ext/css/download.css">
    <link rel="stylesheet" href="/public/ext/css/swiper.css">
	<link rel="stylesheet" type="text/css" href="/public/css/orders/common.css"/>
	<link rel="stylesheet" type="text/css" href="/public/css/i/common.css"/>
	<link rel="stylesheet" type="text/css" href="/public/css/orders/mylifeallstyle.css"/>
</head>
<body>
<div class="index_wrap">
	<div class="header">
	    <a onclick="window.history.go(-1)">
	        <img class="arrow"  src="/public/img/common/shop_back_black@1x.png " ></a>
		<span class="head_title">售后申请详情</span> 
	</div>
{% if details %}
	<div class="particularsth"  aftersales-id = {{details['id']}} >
		<div class="matter">
				<h4>问题描述</h4>
			<div class="rebound">
				<p>{{details['description']}}</p>
			</div>
		</div>
		<div class="address">
			<h4>邮寄地址</h4>
			<div class="consignee">
				<span>收件人：</span><span>{{details['return_consignee']}}</span>
				<br />
				<span>地址：</span><span>{{details['return_address']}}</span>
			</div>
		</div>
	</div>
{% endif %}
{% if progress %}
	<div class="deliverDetailBox clearfix">
		<div class="deliverDetailLine">
			<ul>
				{% for k,v in progress %}
				{% if k==0 %}
				<li>
					<i class="icon-circle recentlyUpdate">
					</i>
					<div class="line">
					</div>
				</li>
				{% else %}
				<li>
					<i class="icon-circle">
					</i>
					<div class="line">
					</div>
				</li>
				{% endif %}
				{% endfor %}
			</ul>
		</div>
		<div class="deliverinfoDetail">
			<ul>
				{% for k,v in progress %}
				<li class="deliverStep">
					<p>
						{{v['record']}}
					</p>
					<p class="deliverDate">
						{{date("Y-m-d h:i:s",v['create_time'])}}
					</p>
				</li>
				{% endfor %}
			</ul>
		</div>
	</div>
	{% endif %}
	{% if details %}
	{% if details['status'] != 3%}
	<div class="particularsth_resolve clearfix">
		<p class="bianju fl">已解决</p><p class="fr">未解决</p>
	</div>
    {% endif %}
    {% endif %}


</div>
</body>
</html>
<script src="/public/ext/js/jquery-1.8.3.min.js"></script>
<script src="/public/js/jquery.base64.js"></script>
<script src="/public/ext/js/soo.m.ui.js"></script>
<script src="/public/ext/js/download.js"></script>
<script src="/public/js/orders/view.orders.particularsth.js"></script>