<head>
	<meta charset="utf-8" />
	<title>开业大典</title>
	<link rel="stylesheet" href="/theme/activity/2016_10_Opening&Ceremony/mobile/css/index.css" />
	<link rel="stylesheet" type="text/css" href="/public/mobile/css/foot.css" />
</head>
<body style="overflow-x:hidden ">
	<div class="f_start_business">
		<div class="f_start_banner">
			<img src="/theme/activity/2016_10_Opening&Ceremony/mobile/img/banner_01.jpg">
		</div>
		<div class="f_bg">
			<div id="discount_coupon">
				<ul>
					<li class="first">
						<a href=""> <img src="/theme/activity/2016_10_Opening&Ceremony/mobile/img/discount_coupon_one.jpg" alt="" /> </a>
					</li>
					<li>
						<a href=""> <img src="/theme/activity/2016_10_Opening&Ceremony/mobile/img/discount_coupon_one.jpg" alt="" /> </a>
					</li>
					<li>
						<a href=""> <img src="/theme/activity/2016_10_Opening&Ceremony/mobile/img/discount_coupon_one.jpg" alt="" /> </a>
					</li>

				</ul>
			</div>
			<div id="content">
				<!--热销-->
				<div class="f_hot_sell">
					<img src="/theme/activity/2016_10_Opening&Ceremony/mobile/img/hot_sell_banner.png" alt="" />
				</div>
				<div class="hot_style">
					<ul>
						<li>
							<a href="http://item.soolife.cn/m/15632.html"> <img src="/theme/activity/2016_10_Opening&Ceremony/mobile/img/cao_content_01.jpg" alt="" data="opengoodsdetail"/> </a>
						</li>
						<li>
							<a href="http://item.soolife.cn/m/29439.html"> <img src="/theme/activity/2016_10_Opening&Ceremony/mobile/img/cao_content_02.jpg" alt="" data="opengoodsdetail"/> </a>
						</li>
						<li>
							<a href="http://item.soolife.cn/m/34110.html"> <img src="/theme/activity/2016_10_Opening&Ceremony/mobile/img/cao_content_03.jpg" alt="" data="opengoodsdetail"/> </a>
						</li>
						<li>
							<a href="http://item.soolife.cn/m/34168.html"> <img src="/theme/activity/2016_10_Opening&Ceremony/mobile/img/cao_content_04.jpg" alt="" data="opengoodsdetail"/> </a>
						</li>
						<li>
							<a href="http://item.soolife.cn/m/37170.html"> <img src="/theme/activity/2016_10_Opening&Ceremony/mobile/img/cao_content_05.jpg" alt="" data="opengoodsdetail"/> </a>
						</li>
					</ul>
				</div>
				<!--畅销单品-->
				<div class="f_active_demand">
					<img src="/theme/activity/2016_10_Opening&Ceremony/mobile/img/active_demand_banner.png" alt="" />
				</div>
				<div class="hot_style">
					<ul>
						<li>
							<a href="http://item.soolife.cn/m/15627.html"> <img src="/theme/activity/2016_10_Opening&Ceremony/mobile/img/cao_content_06.jpg" alt="" data="opengoodsdetail"/> </a>
						</li>
						<li>
							<a href="http://item.soolife.cn/m/25350.html"> <img src="/theme/activity/2016_10_Opening&Ceremony/mobile/img/cao_content_07.jpg" alt="" data="opengoodsdetail"/> </a>
						</li>
						<li>
							<a href="http://item.soolife.cn/m/29661.html"> <img src="/theme/activity/2016_10_Opening&Ceremony/mobile/img/cao_content_08.jpg" alt="" data="opengoodsdetail"/> </a>
						</li>
						<li>
							<a href="http://item.soolife.cn/m/36968.html"> <img src="/theme/activity/2016_10_Opening&Ceremony/mobile/img/cao_content_09.jpg" alt="" data="opengoodsdetail"/> </a>
						</li>
						<li>
							<a href="http://item.soolife.cn/m/13467.html"> <img src="/theme/activity/2016_10_Opening&Ceremony/mobile/img/cao_content_10.jpg" alt="" data="opengoodsdetail"/> </a>
						</li>
					</ul>
				</div>
				<!--精选套餐-->
				<div class="f_combo">
					<img src="/theme/activity/2016_10_Opening&Ceremony/mobile/img/combo_banner.png" alt="" />
				</div>
				<div class="hot_style">
					<ul>
						<li>
							<a href="http://item.soolife.cn/m/38207.html"> <img src="/theme/activity/2016_10_Opening&Ceremony/mobile/img/cao_content_11.jpg" alt="" data="opengoodsdetail"/> </a>
						</li>
						<li>
							<a href="http://item.soolife.cn/m/28917.html"> <img src="/theme/activity/2016_10_Opening&Ceremony/mobile/img/cao_content_12.jpg" alt="" data="opengoodsdetail"/> </a>
						</li>
						<li>
							<a href="http://item.soolife.cn/m/15444.html"> <img src="/theme/activity/2016_10_Opening&Ceremony/mobile/img/cao_content_13.jpg" alt="" data="opengoodsdetail"/> </a>
						</li>
						<li>
							<a href="http://item.soolife.cn/m/12917.html"> <img src="/theme/activity/2016_10_Opening&Ceremony/mobile/img/cao_content_14.jpg" alt="" data="opengoodsdetail"/> </a>
						</li>
						<li>
							<a href="http://item.soolife.cn/m/33989.html"> <img src="/theme/activity/2016_10_Opening&Ceremony/mobile/img/cao_content_15.jpg" alt="" data="opengoodsdetail"/> </a>
						</li>
					</ul>
				</div>
				<!--凑单-->
				<div class="collect">
					<img src="/theme/activity/2016_10_Opening&Ceremony/mobile/img/collect_banner.png" alt="" />
				</div>
				<div class="hot_style">
					<ul>
						<li>
							<a href="http://item.soolife.cn/m/27310.html"> <img src="/theme/activity/2016_10_Opening&Ceremony/mobile/img/cao_content_16.jpg" alt="" data="opengoodsdetail"/> </a>
						</li>
						<li>
							<a href="http://item.soolife.cn/m/28981.html"> <img src="/theme/activity/2016_10_Opening&Ceremony/mobile/img/cao_content_17.jpg" alt="" data="opengoodsdetail"/> </a>
						</li>
						<li>
							<a href="http://item.soolife.cn/m/34020.html"> <img src="/theme/activity/2016_10_Opening&Ceremony/mobile/img/cao_content_18.jpg" alt="" data="opengoodsdetail"/> </a>
						</li>

					</ul>
				</div>
			</div>
		</div>
	</div>
</body>

<script src="/public/mobile/js/jquery-3.0.0.min.js"></script>
<script src="/public/js/sdk.js"></script>
<script src="/public/mobile/js/websdk.js"></script>