document.write('<div class="navbar">');
document.write('	<div class="nav">');
document.write('		<div class="category left">');
document.write('			<h4>全部商品分类<i class="fa fa-angle-down fa-lg"></i></h4>');
document.write('			<div class="category-dropdown {% if hide==1 %} hidden {% endif %}">');
document.write('				<div class="category-menus">');
document.write('					<ul>');
						{% for d in category %}
document.write('						<li>');
document.write('							<a href="{{url_search}}/cat/{{d['id']|lower}}.html">{{d['name']}}</a>');
document.write('							<i class="fa fa-angle-right fa-lg"></i>');
document.write('						</li>');
						{% endfor %}
document.write('					</ul>');
document.write('				</div>');
document.write('				<div class="category-pannel">');
<?php 
$i=1; 
?>
					{% for d in category %}
document.write('					<div class="pannel">');
document.write('						<div class="content" {% if d['code']|lower=='j' %} style="height: 840px;" {% endif %}>');
							{% for d2 in d['children'] %}
document.write('							<div class="tags-bd">');
document.write('								<h5><a href="{{url_search}}/cat/{{d2['id']|lower}}.html" target="_blank">{{d2['name']}}</a></h5>');
document.write('								<p>');

<?php if (array_key_exists('children', $d2)) { ?>
									{% for d3 in d2['children'] %}
document.write('									<a href="{{url_search}}/cat/{{d3['id']|lower}}.html" target="_blank">{{d3['name']}}</a>');
									{% endfor %}
<?php } ?>
document.write('								</p>');
document.write('							</div>');
							{% endfor %}
document.write('						</div>');
document.write('						<div class="adverts clearfix">');
document.write('							<div class="clearfix">');

<?php
$mm = str_pad($i,3,'0',STR_PAD_LEFT);

$key = "pc.catgoods.floor{$mm}.brands";
if (isset($ads) && array_key_exists($key, $ads))
{
	$brands = $ads[$key];
	foreach ($brands as $k1 => $v1) {
		
		?>
		document.write('								<div class="box-120x50 left">');
		document.write('									<a target="_blank" href="<?php echo $v1['pc_link'];?>">');
		document.write('										<img alt="<?php echo $v1['title'];?>" title="<?php echo $v1['title'];?>" src="<?php echo $this->utility->get_advert_picture($v1['picture']);?>" style="display: inline;"></a>');
		document.write('								</div>');
		<?php
	}
}
?>
document.write('							</div>');
document.write('							<div class="hr-20"></div>');
document.write('							<div class="clearfix">');
<?php
$key = "pc.catgoods.floor{$mm}.column";
if (isset($ads) && array_key_exists($key, $ads))
{
	$brands = $ads[$key];
	foreach ($brands as $k1 => $v1) {
		
		?>
		document.write('								<div class="box-250x120 left" >');
		document.write('									<a target="_blank" href="<?php echo $v1['pc_link'];?>">');
		document.write('										<img alt="<?php echo $v1['title'];?>" title="<?php echo $v1['title'];?>" src="<?php echo $this->utility->get_advert_picture($v1['picture']);?>" style="display: inline;"></a>');
		document.write('								</div>');
		<?php
	}
}
?>
document.write('							</div>');
document.write('						</div>');
document.write('					</div>');
<?php $i++; ?>
					{% endfor %}

document.write('				</div>');
document.write('			</div>');
document.write('		</div>');
document.write('		<div class="lists left">');
document.write('			<ul>');
document.write('				<li>');
document.write('					<a href="{{url_website}}/index.html" {% if nav=='home' %} class="active" {% endif %} target="_blank">首  页</a>');
document.write('				</li>');
document.write('				<li>');
document.write('					<a href="{{url_website}}/overseas.html" {% if nav=='overseas' %} class="active" {% endif %}  target="_blank">海外精品</a>');
document.write('				</li>');
document.write('				<!--li-->');
document.write('					<!--a href="/market.html" {% if nav=='market' %} class="active" {% endif %}  target="_blank">星超市</a-->');
document.write('				<!--/li-->');
document.write('				<li>');
document.write('					<a href="{{url_website}}/clothes.html" {% if nav=='clothes' %} class="active" {% endif %}  target="_blank">星范儿</a>');
document.write('				</li>');
document.write('				<li>');
document.write('					<a href="{{url_website}}/discount.html" {% if nav=='discount' %} class="active" {% endif %}  target="_blank">星特惠</a>');
document.write('				</li>');
document.write('				<li>');
document.write('					<a href="{{url_website}}/vip.html" {% if nav=='vip' %} class="active" {% endif %}  target="_blank">星粉专区</a>');
document.write('				</li>');
document.write('			</ul>');
document.write('		</div>');
document.write('	</div>');
document.write('</div>');