{% if hot %}
	{% for d in hot %}
	{% set css = loop.last?'right':'' %}
document.write('	<div class="item {{css}}">');
document.write('		<div class="logo frame">');
document.write('			<div class="move">');
document.write('				<a href="{{url_goods}}/{{d['sku_id']}}.html" target="_blank"><img class="lazy" src="/public/v3.0.1/img/s.gif"  data-original="<?php echo $this -> utility -> get_goods_picture($d['logo']); ?>" title="{{d['sku_name']}}" alt="{{d['sku_name']}}"/> </a>');
document.write('			</div>');
document.write('		</div>');
document.write('		<div class="name">');
document.write('			<p class="line-70">');
document.write('				<a href="{{url_goods}}/{{d['sku_id']}}.html" target="_blank"> {{d['sku_name']}} </a>');
document.write('			</p>');
document.write('			<p  class="line-40">');
document.write('				<span class="price orange">&yen; {{d['act_price']}}</span>');
document.write('				<span class="price orange"><?php echo $d['coin'] ? " + ".$d['coin']." 星币" : "";?></span>');
document.write('			</p>');
document.write('		</div>');
document.write('		<div class="button">');
document.write('			<a href="{{url_goods}}/{{d['sku_id']}}.html" target="_blank"> 我要购买 </a>');
document.write('		</div>');
document.write('	</div>');
	{% endfor %}
{% endif %}
