<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
	<link rel="stylesheet" type="text/css" href="/public/mobile/css/lucky/old_timey.css">
	<title>往期活动</title>
</head>
<body>
	<div class="wrap">
			<!-- 头部 -->
	<!-- 	<div class="header">
			<span><a onclick="history.go(-1)"><img src="/public/mobile/img/lucky/starh.png " class="lefter" onclick="history.go(-1)"></a></span><span class="lj_srt">往期活动</span> --> <!-- <a href="#"><img src="/public/mobile/img/lucky/stari.png" class="share"></a> -->
		<!-- </div> -->
		{% for d in data %}
			<div class="lj_acte">
				<img src="{{ d['pic'] }}">
				<p class="lj_fis">{{ d['S_BeginTime'] }}月活动已结束</p>
				<p class="lj_clik"><a href="/m/lucky/past/{{ d['S_LuckyID'] }}.html">点击查看</a></p>
			</div>
		{% endfor %}
		<p class="last"></p>
	</div>
</body>
<script type="text/javascript" src="/public/mobile/js/lucky/rem.js"></script>
<script src="/public/mobile/js/lucky/sdk.2.2.js" type="text/javascript" charset="utf-8"></script>
<script type="text/javascript" src="/public/mobile/js/lucky/jquery.-1.8.3.min.js"></script>
</html>