<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
	<link rel="stylesheet" type="text/css" href="/public/mobile/css/lucky/starold.css">
	<title>中奖名单</title>
</head>
<body>
	<div class="wrap">
		<p class="lj_list">星集结08月04日获奖名单公布</p>
		<div class="lj_car">
		 	<div class="lj_first"><img src="/public/mobile/img/lucky/new/lj_oneer.jpg"></div>
		 	<div class="lj_one">136****1235</div>
		</div>
		<div class="lj_phone">
		 	<div class="lj_two"><img src="/public/mobile/img/lucky/new/lj_twoer.jpg"></div>
		 	<div class="lj_person">
		 		<ul>
		 			<li>136****1867</li>
		 			<li>130****5241</li>
		 			<li>173****3352</li>
		 			<li>151****8841</li>
		 			<li>130****2640</li>
		 			<li>131****1245</li>
		 			<li>132****8554</li>
		 			<li>133****3287</li>
		 			<li>135****3234</li>
		 			<li>170****2648</li>
		 			<li>133****8852</li>
		 			<li>150****2541</li>
		 			<li>187****8854</li>
		 			<li>132****3642</li>
		 			<li>133****3132</li>
		 			<li>135****6947</li>
		 			<li>189****5496</li>
		 			<li>138****3541</li>
		 			<li>159****2605</li>
		 			<li>152****8953</li>
		 		</ul>
		 	</div>
		</div>
		<div class="lj_phone">
		 	<div class="lj_two"><img src="/public/mobile/img/lucky/new/lj_threeer.jpg"></div>
		 	<div class="lj_person">
		 		<ul class="lj_data">
		 			<li>158****4999</li>
		 			<li>136****0254</li>
		 			<li>136****5714</li>
		 			<li>139****2124</li>
		 			<li>181****8670</li>
		 			<li>136****2628</li>
		 			<li>183****9403</li>
		 			<li>151****1628</li>
		 			<li>136****5714</li>
		 			<li>138****3457</li>
		 			<li>177****0215</li>
		 			<li>131****7908</li>
		 			<li>135****0597</li>
		 			<li>135****6855</li>
		 			<li>188****8840</li>
		 			<li>133****3310</li>
		 			<li>134****2015</li>
		 			<li>189****5641</li>
		 			<li>133****8679</li>
		 			<li>132****2546</li> 
		 		</ul>
		 		<p class="lj_load">下拉加载更多...</p>
		 	</div>
		</div>
	</div>
</body>
<script type="text/javascript" src="/public/mobile/js/lucky/rem.js"></script>
<script src="/public/mobile/js/lucky/sdk.2.2.js" type="text/javascript" charset="utf-8"></script>
<script type="text/javascript" src="/public/mobile/js/lucky/jquery.-1.8.3.min.js"></script>
<script src='/public/mobile/js/lucky/starold.js'></script>
</html>