<!DOCTYPE html>
<html>

	<head>
		<meta charset="UTF-8">
		
		<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
		<link rel="stylesheet" href="/theme/activity/2016_08_olympic/mobile/css/index.css" />
		 <link rel="stylesheet" type="text/css" href="/public/mobile/css/foot.css" />
	</head>

	<body>
		<div class="snatchgold">
			<div class="banner">
				<img src="/theme/activity/2016_08_olympic/mobile/img/banner_a.jpg" align="top" />
				<img src="/theme/activity/2016_08_olympic/mobile/img/banner_b.jpg" align="top" />
				<img src="/theme/activity/2016_08_olympic/mobile/img/banner_c.jpg" align="top" />
			
				<div class="modal">
					<div class="jinp">
						<a href="http://item.soolife.cn/28186.html">
							<img src="/theme/activity/2016_08_olympic/mobile/img/jp.png" />
						</a>
						<div class="jiangli clearfix">
							<div class="bottom fl">
							    <a href="http://item.soolife.cn/33320.html">
								    <img src="/theme/activity/2016_08_olympic/mobile/img/yp.png" />
								</a>
							</div>
							<div class="bottom fr">
								<a href="http://item.soolife.cn/33319.html">
									<img src="/theme/activity/2016_08_olympic/mobile/img/tp.png" />
								</a>
							</div>
					</div>
					</div>
					
				</div>
			</div>
			<!-- 庆功大典-->
			<div class="dbj_a">
				<div class="title">
					<img src="/theme/activity/2016_08_olympic/mobile/img/title_a.jpg" />
				</div>
				<div class="qingd">
					<div class="left_qd clearfix">
						<div class="shagpt_a fl">
							<a href="http://item.soolife.cn/32153.html">
								<img src="/theme/activity/2016_08_olympic/mobile/img/sp_aa.jpg" />
							</a>
						</div>
						<div class="xiangq_a fr">
							<a href="http://item.soolife.cn/32153.html">
								<p class="name">女款流线型S925银项链</p>
								<p class="jies">璀璨 灵动 宠爱你</p>
								<p class="jies">持久新亮 不易褪色</p>
								<div class="price_p clearfix">
									<div class="left fl">
										<div class="jiag">
										    <span>欢庆价¥</span><span class="price_xj">99.0</span><span>元</span>
										</div>
										<p class="y_price">原价:268.0元</p>
								    </div>
									<div class="right fr">
										<img src="/theme/activity/2016_08_olympic/mobile/img/ljggg.png" />
									</div>
								</div>
						    </a>
					    </div>
					</div>
					<div class="right_qd">
						<ul>
							<li>
								<a href="http://item.soolife.cn/32161.html">
									<img src="/theme/activity/2016_08_olympic/mobile/img/sp_c.jpg" />
									<div class="right_p">
										<p class="name">美人鱼尾吊坠</p>
										<p class="jies">美人鱼尾 你的饰界由此改变</p>
										<div class="price_a">
											<div class="jiag">
												<span>欢庆价¥</span><span class="price_xj">88.00</span><span>元</span>
											</div>
											<p class="y_price">原价:268.00元</p>
										</div>
									</div>
								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/32267.html">
									<img src="/theme/activity/2016_08_olympic/mobile/img/sp_a.jpg" />
									<div class="right_p">
										<p class="name">花朵银耳钉</p>
										<p class="jies">浪漫♥形，经典百搭浪漫紫</p>
										<div class="price_a">
											<div class="jiag">
												<span>欢庆价¥</span><span class="price_xj">68.00</span><span>元</span>
											</div>
											<p class="y_price">原价:198.00元</p>
												
										</div>
									</div>
								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/32275.html">
									<img src="/theme/activity/2016_08_olympic/mobile/img/sp_d.jpg" />
									<div class="right_p">
										<p class="name">璀璨之星银耳环</p>
										<div class="jies">
											<p>为爱冠冕，宠爱一生</p>
										</div>
										<div class="price_a">
											<div class="jiag">
												<span>欢庆价¥</span><span class="price_xj">88.00</span><span>元</span>
											</div>
											<p class="y_price">原价:198.00元</p>
										</div>
									</div>
								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/14944.html">
									<img src="/theme/activity/2016_08_olympic/mobile/img/sp_e.jpg" />
									<div class="right_p">
										<p class="name">方形锆石耳钉</p>
										<p class="jies">低调奢华</p>
										<div class="price_a">
											<div class="jiag">
												<span>欢庆价¥</span><span class="price_xj">58.00</span><span>元</span>
											</div>
											<p class="y_price">原价:158.00元</p>
										</div>
									</div>
								</a>
							</li>
						</ul>
					</div>
				</div>
			</div>
			<!--  精彩奥运-->
			<div class="dbj_b">
				<div class="title">
					<img src="/theme/activity/2016_08_olympic/mobile/img/title_q.jpg" />
				</div>
				<div class="jcai_a">
					<div class="left_qd clearfix">
						<div class="shagpt_b fl">
							<a href="http://item.soolife.cn/25398.html">
								<img src="/theme/activity/2016_08_olympic/mobile/img/sp_bb.jpg" />
							</a>
						</div>
						<div class="xiangq_a fr">
							<a href="http://item.soolife.cn/25398.html">
								<p class="name">塔梅尔除甲醛空气净化器 </p>
								<p class="jies">向空气say no！</p>
								<p class="jies">让您净距离呼吸空气</p>
								<div class="price_p clearfix">
									<div class="left fl">
										<div class="jiag">
											<span>欢庆价¥</span><span class="price_xj">2500.0</span><span>元</span>
										</div>
										<p class="y_price">原价:3400.0元</p>
									</div>
									<div class="right fr">
										<img src="/theme/activity/2016_08_olympic/mobile/img/ljggg.png" />
									</div>
								</div>
							</a>
						</div>
					</div>
					<div class="right_qd">
						<ul>
							<li>
								<a href="http://item.soolife.cn/30781.html">
									<img src="/theme/activity/2016_08_olympic/mobile/img/sp_f.jpg" />
									<div class="right_p">
										<p class="name">迪士尼 充电宝</p>
										<div class="jies">
											<p>捎上我 想电谁就电谁</p>
										</div>
										<div class="price_a">
											<div class="jiag">
												<span>欢庆价¥</span><span class="price_xj">158.00</span><span>元</span>
											</div>
											<p class="y_price">原价:298.00元</p>
										</div>
									</div>
								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/26762.html">
									<img src="/theme/activity/2016_08_olympic/mobile/img/sp_b.jpg" />
									<div class="right_p">
										<p class="name">体感平衡车</p>
										<div class="jies">
											<p>出门不止一种车！</p>
										</div>
										<div class="price_a">
											<div class="jiag">
												<span>欢庆价¥</span><span class="price_xj">1268.00</span><span>元</span>
											</div>
											<p class="y_price">原价:1350.00元</p>	
										</div>
									</div>
								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/5213.html">
									<img src="/theme/activity/2016_08_olympic/mobile/img/sp_g.jpg" />
									<div class="right_p">
										<p class="name">两用折叠躺椅</p>
										<div class="jies">
											<p>一椅多用  躺着看奥运</p>
										</div>
										<div class="price_a">
											<div class="jiag">
												<span>欢庆价¥</span><span class="price_xj">129.00</span><span>元</span>
											</div>
											<p class="y_price">原价:248.00元</p>
										</div>
									</div>
								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/13481.html">
								    <img src="/theme/activity/2016_08_olympic/mobile/img/sp_h.jpg" />
									<div class="right_p">
										<p class="name">无铅陶瓷泡茶杯</p>
										<div class="jies">
											<p>不妥协的实用主义 </p>
										</div>
	
										<div class="price_a">
											<div class="jiag">
												<span>欢庆价¥</span><span class="price_xj">127.60</span><span>元</span>
											</div>
											<p class="y_price">原价:290.00元</p>
										</div>
									</div>
								</a>
							</li>
						</ul>
					</div>
				</div>
			</div>
			<!--中国加油-->
			<div class="dbj_c">
				<div class="title">
					<img src="/theme/activity/2016_08_olympic/mobile/img/title_d.jpg" />
				</div>
				<div class="zgjyou">
					<div class="left_qd clearfix">
						<div class="shagpt_c fl">
							<a href="http://item.soolife.cn/15444.html">
								<img src="/theme/activity/2016_08_olympic/mobile/img/sp_cc.jpg" />
							</a>
						</div>
						<div class="xiangq_a fr">
							<a href="http://item.soolife.cn/15444.html">
								<p class="name">蜂毒原液超值5件套</p>
								<p class="jies">蜂浆补水 一步到位</p>
								<p class="jies">锁住水分</p>
								<div class="price_p clearfix">
									<div class="left  fl">
										<div class="jiag">
											<span>欢庆价¥</span><span class="price_xj">517.5</span><span>元</span>
										</div>
										<p class="y_price">原价860.00元</p>
									</div>
									<div class="right fr">
										<img src="/theme/activity/2016_08_olympic/mobile/img/ljggg.png" />
									</div>
								</div>
							 </a>
						</div>
					</div>
					<div class="right_qd">
						<ul>
							<li>
								<a href="http://item.soolife.cn/27005.html">
								    <img src="/theme/activity/2016_08_olympic/mobile/img/sp_i.jpg" />
									<div class="right_p">
										<p class="name">夜光健康体重秤</p>
										<p class="jies">我的健康我掌握</p>
	
										<div class="price_a">
											<div class="jiag">
												<span>欢庆价¥</span><span class="price_xj">39.00</span><span>元</span>
											</div>
										    <p class="y_price">原价:89.00元</p>
										</div>
									</div>
								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/5358.html">
									<img src="/theme/activity/2016_08_olympic/mobile/img/sp_k.jpg" />
									<div class="right_p">
										<p class="name">专业防滑瑜伽垫</p>
										<p class="jies">瑜悦生活 拒绝亚健康</p>
										<div class="price_a">
											<div class="jiag">
												<span>欢庆价¥</span><span class="price_xj">49.00</span><span>元</span>
											</div>
											<p class="y_price">原价:99.00元</p>
										</div>
									</div>
								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/13626.html">
									<img src="/theme/activity/2016_08_olympic/mobile/img/sp_l.jpg" />
									<div class="right_p">
										<p class="name">特级蜗牛防晒霜</p>
										<p class="jies">再不抹上 你就黑了</p>
										<div class="price_a">
											<div class="jiag">
												<span>欢庆价¥</span><span class="price_xj">66.00</span><span>元</span>
											</div>
											<p class="y_price">原价:120.00元</p>
										</div>
									</div>
								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/9151.html">
									<img src="/theme/activity/2016_08_olympic/mobile/img/sp_m.jpg" />
									<div class="right_p">
										<p class="name">魔术师BB霜  </p>
										<p class="jies">无痕遮瑕     质地轻盈 </p>
										<div class="price_a">
											<div class="jiag">
												<span>欢庆价¥</span><span class="price_xj">96.00</span><span>元</span>
											</div>
											<p class="y_price">原价:146.00元</p>
										</div>
									</div>
								</a>
							</li>
						</ul>
					</div>
				</div>
			</div>
			<!--揍单专区-->
			<div class="dbj_d">
				<div class="title">
					<img src="/theme/activity/2016_08_olympic/mobile/img/title_c.jpg" />
				</div>
				<div class="zdzq_a ">
					<div class="left_qd clearfix">
						<div class="shagpt_d fl">
							<a href="http://item.soolife.cn/12908.html">
								<img src="/theme/activity/2016_08_olympic/mobile/img/sp_dd.jpg" />
							</a>
						</div>
						<div class="xiangq_a fr">
							<a href="http://item.soolife.cn/12908.html">
								<p class="name">天然碱性山泉水570ml </p>
								<p class="jies">醒酒 醒酒 醒酒</p>
								<p class="jies">重要的事情说三遍</p>
								<div class="price_p clearfix">
									<div class="left fl">
										<div class="jiag">
											<span>欢庆价¥</span><span class="price_xj">1.00</span><span>元</span>
										</div>
										<p class="y_price">原价10.80元</p>
									</div>
									<div class="right fr">
										<img src="/theme/activity/2016_08_olympic/mobile/img/ljggg.jpg" />
									</div>
								</div>
							</a>
						</div>
					</div>
					<div class="right_qd">
						<ul>
							<li>
								<a href="http://item.soolife.cn/34018.html">
									<img src="/theme/activity/2016_08_olympic/mobile/img/sp_n.jpg" />
									<div class="right_p">
										<p class="name">昆仑山矿泉水</p>
										<p class="jies">黄金纬度   品质好水</p>
										<div class="price_a">
											<div class="jiag">
												<span>欢庆价¥</span><span class="price_xj">3.00</span><span>元</span>
											</div>
											<p class="y_price">原价:6.00元</p>
										</div>
									</div>
								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/30904.html">
									<img src="/theme/activity/2016_08_olympic/mobile/img/sp_o.jpg" />
									<div class="right_p">
										<p class="name">膳食纤维饼干</p>
										<p class="jies"> 原自雪域高原  酥脆可口</p>
										<div class="price_a">
											<div class="jiag">
												<span>欢庆价¥</span><span class="price_xj">6.00</span><span>元</span>
											</div>
											<p class="y_price">原价:18.00元</p>
										</div>
									</div>
								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/32759.html">
									<img src="/theme/activity/2016_08_olympic/mobile/img/sp_q.jpg" />
									<div class="right_p">
										<p class="name">悠悠琦奇大咀猴</p>
										<p class="jies">大“嘴”猴   we are family</p>
										<div class="price_a">
											<div class="jiag">
												<span>欢庆价¥</span><span class="price_xj">39.90</span><span>元</span>
											</div>
											<p class="y_price">原价:60.00元</p>
										</div>
									</div>
								</a>
							</li>
							<li>
								<a href="http://item.soolife.cn/25376.html">
									<img src="/theme/activity/2016_08_olympic/mobile/img/sp_p.jpg"  /> 
									<div class="right_p">
										<p class="name">超长夜用卫生巾 </p>
										<p class="jies">透气贴身无拘束 </p>
										<div class="price_a">
										    <div class="jiag">
												<span>欢庆价¥</span><span class="price_xj">11.90</span><span>元</span>
											</div>
											<p class="y_price">原价:22.00元</p>
										</div>
									</div>
								</a>
							</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</body>
</html>