<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>如此生活|忘记密码</title>
	<meta name="viewport" content="width=device-width, initial-scale=1,maximum-scale=1,user-scalable=no">
	<meta name="apple-mobile-web-app-capable" content="yes">
	<meta name="apple-mobile-web-app-status-bar-style" content="black">
	<link rel="stylesheet" type="text/css" href="/public/css/forget/forget.css"/>
</head>
<body>
	<div class="wrap">
		<div class="header" id="header">
			<span onclick="window.history.go(-1)">
				<img src="/public/img/brandhui/xingxingsha_back@2x.png " class="lefter">
			</span>
			<span class="lj_srt">忘记密码</span> 
		</div>
		<div class="void"></div>
		<!-- 获取验证码 -->
		<div class="jianxi">
			<div class="iphone" id="iphone">
				<input type="text" name="phone" maxlength="11" placeholder="手机号">
			</div>
			<div class="iphone  security">  
				<input id="code" type="text" name="vcode" maxlength="6" placeholder="验证码">
				<div id="btn" name="" >获取验证码</div>
				<div id="s_box" ></div>
			</div>
			<div class="ensure sure1">确定</div>
		</div>
		<!--  设置新密码-->
		<div class="jianxi2">
			<div class="iphone">
				<input id="password1" type="password" name="password1" maxlength="20" placeholder="输入新的6-20位数字、字母组合">
			</div>
			<div class="iphone  security">  
				<input id="password2" type="password" name="" maxlength="20" placeholder="再次输入密码">
			</div>
			<div class="ensure sure2">确定</div>
		</div>
		<div id="alert_mark"></div>
	</div>
</body>
<script src="/public/js/rem.js"></script> 
<script src="/public/ext/js/jquery-1.8.3.min.js"></script>
<script type="text/javascript" src="/public/js/forget/forget.js"></script>
</html>