<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>招商|如此生活</title>
	<meta name="viewport" content="width=device-width, initial-scale=1,maximum-scale=1,user-scalable=no">
	<meta name="apple-mobile-web-app-capable" content="yes">
	<meta name="apple-mobile-web-app-status-bar-style" content="black">
	<link rel="stylesheet" type="text/css" href="/public/mobile/css/business.css"/>
    <link rel="stylesheet" href="/public/mobile/css/idangerous.swiper.css">
</head>
<body>
<div class="lcy_business">
	<!-- 头部 -->
	<header class="head">
		<div class="back"></div>
		<div class="title">
			如此生活招商
		</div>
		<div class="back2"></div>
	</header>
	<!-- 头部logo -->
	<div class="logo_box">
		<img class="logo" src="/public/mobile/img/business/logo.png"/>
		<p class="phone">招商电话：<span>400-068-5151</span></p>
	</div>
	<div class="t_banner">
		<img src="/public/mobile/img/business/banner.jpg" alt="">
		<div class="word">
			<p class="word_t">让商家获利，让百姓受益</p>
			<p class="word_c">全球一站式新零售体验领带品牌</p>
			<p class="word_b">全国开发品牌招商开始了</p>
		</div>
	</div>
	<!-- four_box -->
	<div class="four_box">
		<div class="four_l box">
			<p>竞争不公</p>
			<p>市场恶化生存困难</p>
		</div>
		<div class="four_r box">
			<p>销售下降</p>
			<p>市场需求减少</p>
		</div>
		<div class="four_l box">
			<p>成本高涨</p>
			<p>投入获利成反比</p>
		</div>
		<div class="four_r box">
			<p>利润低下</p>
			<p>不良竞争价格血拼</p>
		</div>
	</div>
	<!-- 小人 -->
	<div class="men_box">
		<img src="/public/mobile/img/business/men.png">
		<div class="word">
			获取本月品牌入驻优惠政策信息，请咨询客服
		</div>
	</div>
	<!-- 如此生活的服务 -->
	<div class="service">如此生活的服务</div>
	<div class="service_box">
		<div class="serivce_l">
			<p class="title">商家服务</p>
			<p>1.去团队</p>
			<p>(线上线下无需运营人员)</p>
			<p>2.去广告</p>
			<p>(线上线下全平台立体化无广告推广)</p>
			<p>3.去开店</p>
			<p>(线上线下开设店铺)</p>
			<p>4.去仓储</p>
			<p>(线下商品代存代发)</p>
		</div>
		<div class="serivce_l">
			<p class="title">消费者服务</p>
			<p>1.购便利</p>
			<p>(时间便利、下单便利、提货便利)</p>
			<p>2.购快乐</p>
			<p>(秀时尚、修生活、秀体验)</p>
			<p>3.购优惠</p>
			<p>(购物优惠、活动优惠、特卖优惠)</p>
			<p>4.购增值</p>
			<p>(礼品增值、赠品增值、奖品增值)</p>
		</div>
	</div>
	<!-- 主体 -->
	<div class="item">
		<img src="/public/mobile/img/business/item.png" alt="">
	</div>
	<!-- 品牌 -->
	<div class="shops item">
		<img src="/public/mobile/img/business/shops.jpg" alt="">
		<div class="word">
			<p class="title">八大品类</p>
			<p>运动户外、母婴玩具、服装鞋帽、智能电配</p>
			<p>箱包配饰、日用百货、个护化妆、食品酒水</p>
		</div>
	</div>
	<!-- 合作 -->
	<div class="item">
		<img src="/public/mobile/img/business/commet.jpg" alt="">
	</div>
	<!-- 体验店图片 -->
	<div class="service">体验店图片</div>
	<div class="img_box">
		<img src="/public/mobile/img/business/img1.jpg" alt="">
		<img src="/public/mobile/img/business/img2.jpg" alt="">
		<img src="/public/mobile/img/business/img3.jpg" alt="">
	</div>
	<!-- 多个体验店图片 -->
	<div class="service">多个体验店图片</div>
  	<div class="swiper-container">
	    <div class="swiper-wrapper">
	      	<div class="swiper-slide">
	        	<img src="/public/mobile/img/business/shopimg1.jpg" alt="">
	      	</div>
	      	<div class="swiper-slide">
	        	<img src="/public/mobile/img/business/shopimg2.jpg" alt="">
	      	</div>
	      	<div class="swiper-slide">
	        	<img src="/public/mobile/img/business/shopimg3.jpg" alt="">
	      	</div>
	    </div>
	    <div class="pagination"></div>
  	</div>
  	<!-- title -->
  	<div class="address_title">上海</div>
  	<div class="address">
		<p class="big_w">上海太阳City广场如此生活店</p>
		<p>上海市静安区恒丰路299路</p>
  	</div>
  	<div class="address">
		<p class="big_w">上海嘉定宝龙城商场如此生活店</p>
		<p>上海市嘉定区宝塔路德富路嘉定宝龙广场2F</p>
  	</div>
  	<div class="address">
		<p class="big_w">上海松江万达百货如此生活店</p>
		<p>上海市松江区广富林路658弄668号上海松江万达广场4F层</p>
  	</div>
  	<div class="address_title">苏州</div>
  	<div class="address">
		<p class="big_w">苏州国发平江大厦如此生活店</p>
		<p>江苏省苏州市人民路3118号苏州国发平江大厦B1</p>
  	</div>
  	<div class="address_title">镇江</div>
  	<div class="address">
		<p class="big_w">镇江宝龙广场如此生活店</p>
		<p>江苏省镇江市丹徒区谷阳中大道镇江宝龙广场3F</p>
  	</div>
  	<!-- 联系我们 -->
	<div class="service">联系我们</div>
	<div class="relation">
		<div class="message">
			<p class="phone">加盟热线：<span class="red_w">400-068-5151</span></p>
			<p class="home">公司：鸿惠（上海）信息技术服务有限公司</p>
			<p class="adress">地址：上海市长宁区淞虹路207号C座5层</p>
		</div>
	</div>
	<!-- 输入框 -->
	<div class="inp_box">
		<p><span>*</span>姓名：</p><input class="w_box" type="text" name="name" id="name" placeholder="请输入姓名">
	</div>
	<div class="inp_box">
		<p><span>*</span>电话：</p><input class="w_box" type="text" name="tel" id="tel" placeholder="请输入电话号码" maxlength="11">
	</div>
	<div class="inp_box">
		<p><span>*</span>公司：</p><input class="w_box" type="text" name="company" id="company" placeholder="请输入公司名称">
	</div>
	<div class="inp_box">
		<p><span>*</span>职位：</p><input class="w_box" type="text" name="work" id="work" placeholder="请输入相关职位">
	</div>
	<div class="inp_box">
		<p><span class="no_color">*</span>城市：</p><input readonly class="w_box address_btn select_btn" type="text" name="address" id="address" placeholder="点击选择城市">
	</div>
	<div class="inp_box rela_top inp_dress">
		<p class="text_top"><span class="no_color">*</span>留言：</p><textarea rows="6" name="message" id="message"></textarea>
	</div>
	<div id="error" class="error"></div>
	<div class="btn_box">
		<button type="reset" class="rest">重置</button>
		<button class="submit">提交信息</button>
	</div>
	<a href="tel:400-068-5151"><button class="call"><img src="/public/mobile/img/business/w_phone.png" alt="">预约电话</button></a>
	<!-- 城市选择遮罩 -->
	<div class="mark mark_css">
		<div class="box">
			<!-- 省份 -->
			<div class="select_cell">
				<label>省份：</label>
				<select id="province" name="province" class="province" style="width: 150px;height:30px"></select>
			</div>
			<!-- 城市 -->
			<div class="select_cell">
				<label>城市：</label>
				<select id="city" name="city" class="city" style="width: 150px;height:30px"></select>
			</div>
			<!-- 县区 -->
			<div class="select_cell">
				<label>区县：</label>
				<select id="region" name="region" class="region" style="width: 150px;height:30px"></select>
			</div>
			<button class="sure" id="addaddress-sure">确定</button>
		</div>
	</div>

	<!-- 弹出层遮罩层 -->
	<div class="mark_css mark_alert">
		<div class="alert">
			<p></p>
			<div class="btn">确&nbsp;定</div>
		</div>
	</div>
</div>	<!-- end -->

</body>
	<script src="/public/mobile/js/rem.js"></script>
	<script src="/public/mobile/js/jquery-3.1.0.js"></script>
    <script src="/public/mobile/js/idangerous.swiper.min.js"></script>
	<script src="/public/mobile/js/business.js"></script>
</html>
