<meta http-equiv="Content-Type"  charset="utf-8" content="text/html; charset=utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="generator"      content="soolife.cn">
<meta name="keywords"       content="{{keywords}}">
<meta name="description"    content="{{description}}">
<meta name="viewport"       content="width=1200px, initial-scale=0.8">
<meta name="author" content="Tony Wang">
<title>{{ title }}</title>
<link rel="dns-prefetch" href="http://img.soolife.cn" />
<link rel="dns-prefetch" href="http://static.soolife.cn" />
<link rel="dns-prefetch" href="http://www.soolife.cn" />
<link rel="shortcut icon"                                   href="http://static.soolife.cn/asset/icon/favicon.ico">
<link rel="icon"                                            href="http://static.soolife.cn/asset/icon/favicon.gif"  type="image/gif">

{{assets.outputCss('header')}}
<!--[if IE 7]>
<link href="http://cdn.bootcss.com/font-awesome/3.2.1/css/font-awesome-ie7.min.css" rel="stylesheet" type="text/css">
<![endif]-->
<!--[if lt IE 7]> 
<script src="http://static.soolife.cn/asset/js/show_model-ie<?php echo $version;?>.js"></script>
<![endif]-->