<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>如此生活|全民商探</title>
	<meta name="viewport" content="width=device-width, initial-scale=1,maximum-scale=1,user-scalable=no">
	<meta name="apple-mobile-web-app-capable" content="yes">
	<meta name="apple-mobile-web-app-status-bar-style" content="black">
	<link rel="stylesheet" type="text/css" href="/public/css/shopseek/shopreport.css ">
	<link rel="stylesheet" type="text/css" href="/public/css/shopseek/LArea.css ">
</head>
<body>
	<div class="wrap">
		<div class="header" id="header">
			<span onclick="window.history.go(-1)">
				<img src="/public/img/setting/xingfaner_back@2x.png" class="lefter">
			</span>
			<span class="lj_srt">商家报备</span>
		</div>
		<div class="void" id="void"></div>
		<form class="form-horizontal" id="addsupplier">
			<div class="recom">
				<div class="recoms">
					<span>推荐人:</span>
					<input class="lj_lines" type="text" name="referrer" readonly="true" value="{{ nickname }}">
				</div>
			</div>
			<!-- 公司基本信息 -->
			<div class="company">
				 <ul>
				 	<li>
				 		<span class="message">公司基本信息</span>
				 	</li>
				 	<li>
				 		<span >公司名称:</span>
						<input type="text" name="gongsiname" value="">
				 	</li>
				 	<li>
				 		<span >公司行业:</span>
						<input type="text" name="industry" value="">
				 	</li>
				 	<li>
				 		<span >所在区域:</span>
						<input id="demo1" type="text" name="area" value="">
						<input id="value1" type="hidden" value=" "/>
				 	</li>
				 	<li>
				 		<span >详细地址:</span>
						<input type="text" name="address" value="" >
						
				 	</li>
				 	<li>
				 		<span >公司电话:</span>
						<input type="text" name="gongsiiphone" value="">
				 	</li>
				 </ul>
			</div>
			<!-- 联系信息 -->
			<div class="company">
				 <ul>
				 	<li>
				 		<span class="message">联系信息</span>
				 	</li>
				 	<li>
				 		<span >公司负责人:</span>
						<input class="lj_line" type="text" name="toppersoner" value="">
				 	</li>
				 	<li>
				 		<span >联系人:</span>
						<input class="lj_line" type="text" name="linkname" value="">
				 	</li>
				 	<li>
				 		<span >联系人电话:</span>
						<input class="lj_line" type="text" name="linktel" value="">
				 	</li>
				 </ul>
			</div>
			<!-- 补充信息 -->
			<div class="companys">
				 <ul>
				 	<li>
				 		<span class="message">补充信息</span>
				 	</li>
				 	<li class="source">
				 		<span >信息来源:</span>
				 		<div class="firend">
				 		<input type="hidden" name="fuzhi" value="">
				 			<div>
					 			<img class="slect" data-v="1" src="/public/img/shopseek/mine_zhifu_yuan@2x.png">
					 			<span>亲友</span>
				 			</div>
				 			<div>
					 			<img class="slect" data-v="2" src="/public/img/shopseek/mine_zhifu_yuan@2x.png">

					 			<span>朋友介绍</span>
				 			</div>
				 			<div>
					 			<img class="slect" data-v="3" src="/public/img/shopseek/mine_zhifu_yuan@2x.png">

					 			<span>网络</span>
				 			</div>
				 			<div>
					 			<img class="slect other" data-v="4" src="/public/img/shopseek/mine_zhifu_yuan@2x.png">

					 			<span>其他渠道</span>
				 			</div>
				 		</div>
				        <div class="sour"><input type="text" name="" placeholder="其他信息来源"></div>
				 	</li>
				 	<li class="source">
				 		<span >联系与否:</span>
				 		<div class="firend">
				 		<input type="hidden" name="lianxi" value="">
				 			<div>
					 			<img class="slects" data-s="1" src="/public/img/shopseek/mine_zhifu_yuan@2x.png">
					 			<span>已告知</span>
				 			</div>
				 			<div>
					 			<img class="slects" data-s="2" src="/public/img/shopseek/mine_zhifu_yuan@2x.png">
					 			<span>已介绍过如此生活</span>
				 			</div>
				 			<div>
					 			<img class="slects" data-s="3" src="/public/img/shopseek/mine_zhifu_yuan@2x.png">
					 			<span>没有联系</span>
				 			</div>
				 		</div>
				 	</li>
				 </ul>
			</div>
			<div class="submit">提交</div>
		</form>
	</div>
	<div class="lj_alert"> </div>
</body>
<script>
	var isApp = /SoolifeApp/i.test(navigator.userAgent);
	if(isApp){
		document.getElementById('header').style.display = "none";
		document.getElementById('void').style.display = "none";
		document.getElementById('download-nav').style.display = "none";
	};
</script>
<script src="/public/js/rem.js"></script>
<script src="/public/ext/js/jquery-1.8.3.min.js"></script>
<script src="/public/js/shopseek/shopreport.js"></script>
<script src="/public/js/shopseek/LAreaData1.js"></script>
<script src="/public/js/shopseek/LArea.js"></script>
</html>