<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>如此生活|全民商探</title>
	<meta name="viewport" content="width=device-width, initial-scale=1,maximum-scale=1,user-scalable=no">
	<meta name="apple-mobile-web-app-capable" content="yes">
	<meta name="apple-mobile-web-app-status-bar-style" content="black"> 
	<link rel="stylesheet" type="text/css" href="/public/css/shopseek/shopseek.css ">
</head>
<body>
	<div class="wrap">
		<div class="header" id="header">
			<span onclick="window.history.go(-1)">
				<img src="/public/img/setting/xingfaner_back@2x.png " class="lefter">
			</span>
			<span class="lj_srt">全民商探</span> 
		</div>
		<div class="void" id="void"></div> 
			<div class="content"> 
				<!-- <img src="/public/img/shopseek/mine_probe_image@2x.png"> -->
				<img src="/public/img/shopseek/sjdp_one.jpg">
				<img src="/public/img/shopseek/sjdp_two.jpg">
				<img src="/public/img/shopseek/sjdp_tree.jpg">
				<img src="/public/img/shopseek/sjdp_four.jpg">
				<img src="/public/img/shopseek/sjdp_five.jpg">
				<img src="/public/img/shopseek/sjdp_six.jpg">
				<img src="/public/img/shopseek/sjdp_seven.jpg">
				<img src="/public/img/shopseek/sjdp_eight.jpg">
				<img src="/public/img/shopseek/sjdp_nine.jpg">
				<img src="/public/img/shopseek/sjdp_ten.jpg">
				<p class="title">全民商探</p>
				<p class="join">门槛低，有资源就能赚钱！</p>
				<!-- <a href="/shopseek/shopmodel.html"> -->
					<div class="need">我要做商探</div>
				<!-- </a> -->
			</div> 
			<!-- 协议-->
			<div class="lj_agreement">
				<div class="lj_content">
					<p class="lj_sign">签约 <span class="lj_close">关闭</span></p>
					<div class="sign_content">
						<h3>“如此生活”电子商务交易平台用户开通“全民商探”</h3>
						<h3>功能模块补充协议</h3>
本协议是您与“如此生活”电子商务交易平台（简称"本站"，网址：http://www.soolife.cn）所有者（以下简称为"如此生活"）之间就开通“如此生活”电子商务交易平台的“全民商探”功能模块等相关事宜所订立的契约，也是《如此生活服务协议》（网址：http://www.soolife.cn/about/agreement.html）的补充协议。请您仔细阅读本协议，您点击"同意并继续"按钮后，本协议即构成对双方有约束力的法律文件。<br>

第1条 什么是“全民商探”？ <br>
1.1 “全民商探”功能介绍<br>
   “全民商探”是指如此生活会员根据自己现有的（商家）资源，将相应的商家信息提交到如此生活平台，由如此生活成功签约该商家，或会员直接促成商家签约并提交完整入驻资料成功通过审核后，将给予会员相应余额或现金奖励。<br>


1.2 “全民商探”执行政策<br>
1.2.1用户开通“全民商探”功能模块后，可以向本站提交商家信息。根据用户提交的商家信息，本站成功签约该品牌商家的，用户的钱包余额将可获得1000元/家的返现，钱包余额只能用户如此生活平台的消费购物，不可提现转出。<br>
 
1.2.2用户开通“全民商探”功能模块后，直接促成品牌商家与本站签约的，用户账户钱包的现金余额将可获得3000元/家的返现，现金余额中的钱款将由如此生活平台每月定期打入到用户绑定的银行卡中。<br>
1.2.3本站享有“全民商探”执行政策的最终解释权。<br>
第2条 开通“全民商探”功能服务条款的确认和同意<br>
2.1本站的“全民商探”功能模块的所有权和运作权归如此生活所有。用户同意所有协议条款并完成开通程序，才能使用“全民商探”功能。用户确认：本协议条款是处理双方权利义务的契约，始终有效，法律另有强制性规定或双方另有特别约定的，依其规定。<br>
2.2用户点击同意本协议的，即视为用户确认自己具有享受“全民商探”功能模块服务相应的权利能力和行为能力，能够独立承担法律责任。<br>
2.3如果您在18周岁以下，您只能在父母或监护人的监护参与下才能使用“全民商探”功能。<br>
2.4如此生活保留在中华人民共和国大陆地区法施行之法律允许的范围内独自决定拒绝服务、关闭“全民商探”功能、清除或编辑“全民商探”功能模块内容的权利。<br>
第3条 使用“全民商探”功能模块服务的前提<br>
3.1如此生活通过互联网依法为用户提供“全民商探”功能模块服务，用户在完全同意本协议、《如此生活服务协议》及本站规定的情况下，方有权使用“全民商探”功能模块服务。<br>
3.2用户必须自行准备如下设备和承担如下开支：<br>（1）上网设备，包括并不限于电脑或者其他上网终端、调制解调器及其他必备的上网装置；<br>（2）上网开支，包括并不限于网络接入费、上网设备租用费、手机流量费等。<br>
3.3用户应自行诚信向本站提供注册资料，用户同意其提供的注册资料真实、准确、完整、合法有效，用户注册资料如有变动的，应及时更新其注册资料。如果用户提供的注册资料不合法、不真实、不准确、不详尽的，用户需承担因此引起的相应责任及后果，并且如此生活保留终止用户使用“全民商探”功能模块服务及其他各项服务的权利。<br>
3.4用户在本站使用“全民商探”功能模块服务时，涉及用户真实姓名/名称、通信地址、联系电话、电子邮箱等隐私信息的，本站将予以严格保密，除非得到用户的授权或法律另有规定，本站不会向外界披露用户隐私信息。<br>
3.5用户开通使用“全民商探”功能模块服务成功后，应谨慎合理的使用。用户若发现任何非法使用本功能或存在安全漏洞的情况，请立即通知本站并向公安机关报案。<br>
3.6用户同意，如此生活拥有通过邮件、短信电话等形式，向使用使用“全民商探”功能模块服务的用户告知信息的权利。<br>
3.7用户不得将在本站开通“全民商探”功能模块服务后借给他人使用，否则用户应承担由此产生的全部责任，并与实际使用人承担连带责任。<br>
3.8用户同意，如此生活有权使用用户的注册信息、用户名、密码等信息，登录进入用户的注册账户，进行证据保全，包括但不限于公证、见证等。<br>
第4条 依据国家相关法律法规规章制定，用户同意使用该功能模块向本站提供信息时严格遵守以下义务：<br>
（1）不得传输或发表：煽动抗拒、破坏宪法和法律、行政法规实施的言论，煽动颠覆国家政权，推翻社会主义制度的言论，煽动分裂国家、破坏国家统一的的言论，煽动民族仇恨、民族歧视、破坏民族团结的言论；<br>
（2）从中国大陆向境外传输资料信息时必须符合中国有关法规；<br>
（3）不得利用本站从事洗钱、窃取商业秘密、窃取个人信息等违法犯罪活动；<br>
（4）不得干扰本站的正常运转，不得侵入本站及国家计算机信息系统；<br>
（5）不得传输或发表任何违法犯罪的、骚扰性的、中伤他人的、辱骂性的、恐吓性的、伤害性的、庸俗的，淫秽的、不文明的等信息资料；<br>
（6）不得传输或发表损害国家社会公共利益和涉及国家安全的信息资料或言论；<br>
（7）不得教唆他人从事本条所禁止的行为；<br>
（8）不得利用在本站注册的账户进行牟利性经营活动；<br>
（9）不得发布任何侵犯他人著作权、商标权等知识产权或合法权利的内容；<br>
用户应不时关注并遵守本站不时公布或修改的各类合法规则规定。<br>
本站保有删除站内各类不符合法律政策或不真实的信息内容而无须通知用户的权利。<br>
若用户未遵守以上规定的，本站有权作出独立判断并采取暂停或关闭用户使用“全民商探”功能模块及用户帐号等措施。用户须对自己在网上的言论和行为承担法律责任。<br>

第5条  协议更新<br>
根据国家法律法规变化及网站运营需要，如此生活有权对本协议条款不时地进行修改，修改后的协议一旦被张贴在本站上即生效，并代替原来的协议。用户可随时登录查阅最新协议；用户有义务不时关注并阅读最新版的协议及网站公告。如用户不同意更新后的协议，可以且应立即停止接受本站依据本协议提供本功能模块的服务；如用户继续使用本网站提供的本功能模块的服务的，即视为同意更新后的协议。如此生活建议您在使用本站之前阅读本协议及本站的公告。 如果本协议中任何一条被视为废止、无效或因任何理由不可执行，该条应视为可分的且并不影响任何其余条款的有效性和可执行性。<br>
第6条 法律管辖和适用<br>
本协议的订立、执行和解释及争议的解决均应适用在中华人民共和国大陆地区适用之有效法律（但不包括其冲突法规则）。 <br>如发生本协议与适用之法律相抵触时，则这些条款将完全按法律规定重新解释，而其它有效条款继续有效。 如缔约方就本协议内容或其执行发生任何争议，双方应尽力友好协商解决；协商不成时，任何一方均可向有管辖权的中华人民共和国大陆地区法院提起诉讼。<br>
第7条 其他<br>
7.1本站所有者是指在政府部门依法许可或备案的本网站的经营主体。<br>
7.2如此生活尊重用户的合法权利，本协议及本网站上发布的各类规则、声明等其他内容，均是为了更好的、更加便利的为用户提供服务。<br>
7.3本协议内容中若有以黑体、加粗、下划线、斜体等方式显著标识的条款，请务必着重阅读。<br>
7.4您点击"同意并继续"按钮即视为您完全接受本协议，在点击之前请您再次确认已知悉并完全理解本协议的全部内容。<br> 
					</div>
					<div class="lj_agree">
						<input class="check" type="checkbox" name="checkbox" value="">
						<span class="agree">我同意</span>
					</div>
					<div class="lj_consent">签约</div>
					<div class="lj_cod"></div>
				</div>
			</div>
	</div>
</body>
<script>
		var isApp = /SoolifeApp/i.test(navigator.userAgent);
		if(isApp){
			document.getElementById('header').style.display = "none";
			document.getElementById('void').style.display = "none";
			document.getElementById('download-nav').style.display = "none";
		}; 
</script> 
<script src="/public/js/rem.js"></script> 
<script src="/public/ext/js/jquery-1.8.3.min.js"></script>
<script src="/public/js/shopseek/shopseek.js"></script>
</html>