<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>如此生活|扫码登录</title>
	<meta name="viewport" content="width=device-width, initial-scale=1,maximum-scale=1,user-scalable=no">
	<meta name="apple-mobile-web-app-capable" content="yes">
	<meta name="apple-mobile-web-app-status-bar-style" content="black">
	<link rel="stylesheet" type="text/css" href="/public/css/iphonesure/iphonesure.css"/>
</head>
<body>
	<div class="wrap">
		<div class="header" id="header">
			<span onclick="window.history.go(-1)">
				<img src="/public/img/brandhui/xingxingsha_back@2x.png " class="lefter">
			</span>
			<span class="lj_srt">扫码登录</span> 
		</div>
		<div class="void"></div>
		<div class="scan">
			<img src="/public/img/login/Scan code entry@2x.png">
		</div>
		<p class="soosure">如此生活登录确认</p>
		<p class="dont">请不要扫描来源不明的二维码</p>
		<div class="enter">确认登录</div>
		<div class="abolish">取消</div>
	</div>
</body>
</html>