<div class="header" id="header">
	<!-- begin 微信二维码 -->
	<div class="modal fade modal-qrcode" id="qr_weixin" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal">
						<span aria-hidden="true">×</span><span class="sr-only">Close</span>
					</button>
					<h5 class="modal-title">关注<b class="orange">如此生活</b>官方微信</h5>
				</div>
				<div class="modal-body">
					<div class="code-weixin">
						<img alt="关注如此生活 官方微信" src="/public/v3.0.1/img/code/qr_weixin.jpg">
					</div>
				</div>
				<div class="modal-footer">
					<a class="cancel_btn" data-dismiss="modal"> 关闭 </a>
				</div>
			</div>
		</div>
	</div>
	<!-- end 微信二维码 -->

	<!-- begin 微博二维码 -->
	<div class="modal fade modal-qrcode" id="qr_weibo">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal">
						<span aria-hidden="true">×</span><span class="sr-only">Close</span>
					</button>
					<h5 class="modal-title">关注<b class="orange">如此生活</b>官方微博</h5>
				</div>
				<div class="modal-body">
					<div class="code-sina">
						<img alt="关注如此生活 官方微博" src="/public/v3.0.1/img/code/qr_weibo.jpg">
					</div>
				</div>
				<div class="modal-footer">
					<a class="cancel_btn" data-dismiss="modal"> 关闭 </a>
				</div>
			</div>
		</div>
	</div>
	<!-- end 微博二维码 -->
	<div class="main-container clearfix">
		<div class="tips left">
			<label>Hi, 欢迎来到如此生活</label>
			<a href="#" target="_blank"> 登录 </a><em class="separator">|</em>
			<a href="#" target="_blank"> 免费注册 </a><em class="separator">|</em>

			<a title="关注如此生活 官方微信" href="#" data-target="#qr_weixin" data-toggle="modal" class="green"><i class="fa fa-weixin fa-lg"></i></a>
			<a title="关注如此生活 官方微博" href="#" data-target="#qr_weibo" data-toggle="modal" class="red"><i class="fa fa-weibo  fa-lg"></i></a>
		</div>
		<div class="nav right">
			<div class="dropdown right">
				<a id="dLabel" data-target="#" href="http://i.soolife.cn" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> 我的生活 <span class="caret"></span> </a>
				<ul class="dropdown-menu" aria-labelledby="dLabel">
					<li>
						<a href="http://www.soolife.cn/order.html">我的订单</a>
					</li>
					<li>
						<a href="http://www.soolife.cn/assets/credit">星币查询</a>
					</li>
					<li>
						<a href="http://www.soolife.cn/assets/balance">交易记录</a>
					</li>
					<li>
						<a href="http://www.soolife.cn/assets/coupon">我的优惠券</a>
					</li>
				</ul>
			</div>
			<em class="separator right">|</em>
			<div  class="right">
				<a target="_blank" href="http://sop.soolife.cn/">商家入驻</a>
			</div>
			<em class="separator right">|</em>
			<div class="dropdown right">
				<a id="dLabel" data-target="#" href="http://help.soolife.cn" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> 帮助中心 <span class="caret"></span> </a>
				<ul class="dropdown-menu" aria-labelledby="dLabel">
					<li>
						<a href="http://www.soolife.cn/help/index.html">帮助首页</a>
					</li>
					<!-- <li>
						<a href="http://www.soolife.cn/feedback/complain">我要投诉</a>
					</li> -->
					<li>
						<a href="http://www.soolife.cn/help/help_A_D01.html">售后服务</a>
					</li>
				</ul>
			</div>
			<em class="separator right">|</em>
			<div class="dropdown right">
				<a id="dLabel" data-target="#" href="http://www.soolife.cn" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> 更多导航 <span class="caret"></span> </a>
				<ul class="dropdown-menu" aria-labelledby="dLabel">
					<li>
						<a href="http://www.soolife.cn/index.html" target="_blank">首页</a>
					</li>
					<li>
						<a href="http://www.soolife.cn/market.html" target="_blank">星超市</a>
					</li>
					<li>
						<a href="http://www.soolife.cn/mall.html" target="_blank">星商城</a>
					</li>
					<li>
						<a href="http://www.soolife.cn/clothes.html" target="_blank">服饰鞋包</a>
					</li>
					<li>
						<a href="http://www.soolife.cn/discount.html" target="_blank">品牌特惠</a>
					</li>
					<li>
						<a href="http://www.soolife.cn/zone.html" target="_blank">会员专区</a>
					</li>
				</ul>
			</div>
			<div class="clear"></div>
		</div>
	</div>
</div>