
	<head>
		<meta charset="UTF-8">
		<title></title>
		<link rel="stylesheet" href="/theme/activity/2016_09_nopay/pc/css/index.css" />
	</head>
	<body>
		<div class="qmd_body">
			<div class="banner_a">
				<img src="/theme/activity/2016_09_nopay/pc/img/banner_a.jpg"  align="top"/>
				<img src="/theme/activity/2016_09_nopay/pc/img/banner_b.jpg"  align="top"/>
			</div>
			<div class="centre">
				<div class="background_yhj">
					<div class="coupon clearfix">
						<div class="fl">
							<a href="##"><img src="/theme/activity/2016_09_nopay/pc/img/juan_a.png" /></a>
						</div>
						<div class="fr"  id="receive" data-value="0990188201609001">
							<a href="#"><img src="/theme/activity/2016_09_nopay/pc/img/juan_b.png" /></a>
						</div>
					</div>
				</div>
				<div class="background_relaxation">
					<ul>
						<li>
							<a href="http://item.soolife.cn/25433.html">
								<div class="picture">
									<img src="/theme/activity/2016_09_nopay/pc/img/sp_k.jpg" />
								</div>
								<div class="details">
									<p class="name">头层粒面牛皮商务男士皮鞋</p>
									<p class="name">店铺价：399元</p>
									<div class="price clearfix">
										<div class="fl">
											<p class="bazaar">市场价：1199元</p>
										</div>
										<div class="fr">
											<p data="openinstantbuy" class="lijgm">点击购买</p>
										</div>
									</div>
								</div>
							</a>
						</li>
						<li>
							<a href="http://item.soolife.cn/25467.html">
								<div class="picture">
									<img src="/theme/activity/2016_09_nopay/pc/img/sp_a.jpg" />
								</div>
								
								<div class="details">
									<p class="name">精致牛皮商务休闲男士皮鞋</p>
									<p class="name">店铺价：499元</p>
									<div class="price clearfix">
										<div class="fl">
											<p class="bazaar">市场价：1699元</p>
										</div>
										<div class="fr">
											<p data="openinstantbuy" class="lijgm">点击购买</p>
										</div>
									</div>
								</div>
							</a>
						</li>
						<li>
							<a href="http://item.soolife.cn/25528.html">
								<div class="picture">
									<img src="/theme/activity/2016_09_nopay/pc/img/sp_i.jpg" />
								</div>
								
								<div class="details">
									<p class="name">现代简约头层牛皮中帮男鞋</p>
									<p class="name">店铺价：529元</p>
									<div class="price clearfix">
										<div class="fl">
											<p class="bazaar">市场价：1699元</p>
										</div>
										<div class="fr">
											<p data="openinstantbuy" class="lijgm">点击购买</p>
										</div>
									</div>
								</div>
							</a>
						</li>
						<li>
							<a href="http://item.soolife.cn/25504.html">
								<div class="picture">
									<img src="/theme/activity/2016_09_nopay/pc/img/sp_b.jpg" />
								</div>
								
								<div class="details">
									<p class="name">时尚休闲动感男鞋</p>
									<p class="name">店铺价：429元</p>
									<div class="price clearfix">
										<div class="fl">
											<p class="bazaar">市场价：1699元</p>
										</div>
										<div class="fr">
											<p data="openinstantbuy" class="lijgm">点击购买</p>
										</div>
									</div>
								</div>
							</a>
						</li>
						<li>
							<a href="http://item.soolife.cn/25472.html">
								<div class="picture">
									<img src="/theme/activity/2016_09_nopay/pc/img/sp_c.jpg" />
								</div>
								<div class="details">
									<p class="name">时尚休闲男士皮鞋</p>
									<p class="name">店铺价：459元</p>
									<div class="price clearfix">
										<div class="fl">
											<p class="bazaar">市场价：1599元</p>
										</div>
										<div class="fr">
											<p data="openinstantbuy" class="lijgm">点击购买</p>
										</div>
									</div>
								</div>
							</a>
						</li>
						<li>
							<a href="http://item.soolife.cn/25395.html">
								<div class="picture">
									<img src="/theme/activity/2016_09_nopay/pc/img/sp_j.jpg" />
								</div>
								<div class="details">
									<p class="name">时尚休闲男士皮鞋</p>
									<p class="name">店铺价：459元</p>
									<div class="price clearfix">
										<div class="fl">
											<p class="bazaar">市场价：1599元</p>
										</div>
										<div class="fr">
											<p data="openinstantbuy" class="lijgm">点击购买</p>
										</div>
									</div>
								</div>
							</a>
						</li>
					</ul>
				</div>
				<div class="background_exercise">
					<ul>
						<li>
							<a href="http://item.soolife.cn/28596.html">
								<div class="picture">
									<img src="/theme/activity/2016_09_nopay/pc/img/sp_d.jpg" />
								</div>
								
								<div class="details">
									<p class="name">海尔斯慢跑运动鞋中性款</p>
									<p class="name">店铺价：119元</p>
									<div class="price clearfix">
										<div class="fl">
											<p class="bazaar">市场价：169元</p>
										</div>
										<div class="fr">
											<p data="openinstantbuy" class="lijgm">点击购买</p>
										</div>
									</div>
								</div>
							</a>
						</li>
						<li>
							<a href="http://item.soolife.cn/30707.html">
								<div class="picture">
									<img src="/theme/activity/2016_09_nopay/pc/img/sp_e.jpg">
								</div>
								
								<div class="details">
									<p class="name">轻质真皮慢跑运动鞋</p>
									<p class="name">店铺价：99元</p>
									<div class="price clearfix">
										<div class="fl">
											<p class="bazaar">市场价：139元</p>
										</div>
										<div class="fr">
											<p data="openinstantbuy" class="lijgm">点击购买</p>
										</div>
									</div>
								</div>
							</a>
						</li>
						<li>
							<a href="http://item.soolife.cn/30697.html">
								<div class="picture">
									<img src="/theme/activity/2016_09_nopay/pc/img/sp_f.jpg">
								</div>
								
								<div class="details">
									<p class="name">轻质真皮慢跑运动鞋</p>
									<p class="name">店铺价：99元</p>
									<div class="price clearfix">
										<div class="fl">
											<p class="bazaar">市场价：139元</p>
										</div>
										<div class="fr">
											<p data="openinstantbuy" class="lijgm">点击购买</p>
										</div>
									</div>
								</div>
							</a>
						</li>
						<li>
							<a href="http://item.soolife.cn/28625.html">
								<div class="picture">
									<img src="/theme/activity/2016_09_nopay/pc/img/sp_g.jpg">
								</div>
								
								<div class="details">
									<p class="name">海尔斯慢跑运动鞋中性款</p>
									<p class="name">店铺价：119元</p>
									<div class="price clearfix">
										<div class="fl">
											<p class="bazaar">市场价：169元</p>
										</div>
										<div class="fr">
											<p data="openinstantbuy" class="lijgm">点击购买</p>
										</div>
									</div>
								</div>
							</a>
						</li>
						<li>
							<a href="http://item.soolife.cn/31934.html">
								<div class="picture">
									<img src="/theme/activity/2016_09_nopay/pc/img/sp_e.jpg">
								</div>
								
								<div class="details">
									<p class="name">海尔斯慢跑运动鞋中性款</p>
									<p class="name">店铺价：99元</p>
									<div class="clearfix">
										<div class="fl">
											<p class="bazaar">市场价：139元</p>
										</div>
										<div class="fr">
											<p data="openinstantbuy" class="lijgm">点击购买</p>
										</div>
									</div>
								</div>
							</a>
						</li>
						<li>
							<a href="http://item.soolife.cn/28597.html">
								<div class="picture">
									<img src="/theme/activity/2016_09_nopay/pc/img/sp_h.jpg">
								</div>
								
								<div class="details">
									<p class="name">海尔斯慢跑运动鞋中性款</p>
									<p class="name">店铺价：119元</p>
									<div class="price clearfix">
										<div class="fl">
											<p class="bazaar">市场价：169元</p>
										</div>
										<div class="fr">
											<p data="openinstantbuy" class="lijgm">点击购买</p>
										</div>
									</div>
								</div>
							</a>
						</li>
					</ul>
				</div>
			</div>
			<div class="dibu">
				<img src="/theme/activity/2016_09_nopay/pc/img/dibu.jpg" />
			</div>
		</div>
		
	</body>
<?php
$css = $this -> assets -> get('header');

$js = $this -> assets -> get('footer');
$js -> addJs("public/pc/js/receive.js");


?>
