<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>10.18开业活动</title>
    <style></style>
    <link href="/theme/activity/2016_10_Opening&Ceremony/pc/css/base.css" rel="stylesheet">
</head>
<body>
<div class="cao_banner">
    <img src="/theme/activity/2016_10_Opening&Ceremony/pc/img/cao_banner_01.jpg">
</div>
<div class="cao_content">
    <div class="inner">
        <ul class=" active clearfix">
            <li><img src="/theme/activity/2016_10_Opening&Ceremony/pc/img/cao_content_01.jpg"></li>
            <li><img src="/theme/activity/2016_10_Opening&Ceremony/pc/img/cao_content_02.jpg"></li>
            <li><img src="/theme/activity/2016_10_Opening&Ceremony/pc/img/cao_content_03.jpg"></li>
        </ul>
        <!--///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////1F-->

        <div class="cao_content_theme">
            <a href="#"><img src="/theme/activity/2016_10_Opening&Ceremony/pc/img/cao_content_04.jpg" class="title"></a>
            <div class="commodity clearfix">
                <div class="left picone">
                    <a href="http://item.soolife.cn/15632.html" target="_blank"><img src="/theme/activity/2016_10_Opening&Ceremony/pc/img/cao_content_05.jpg"></a>
                </div>
                <div class="right">
                    <p class="desc">好的葡萄酒 一瓶还不够</p>
                    <p class="name">金萃梅乐红葡萄酒</p>
                    <p class="price">
                        <span>原价:328.00元</span>
                        活动价:<i>268.00</i>元
                    </p>
                    <a href="http://item.soolife.cn/15632.html" target="_blank"><img src="/theme/activity/2016_10_Opening&Ceremony/pc/img/cao_content_06.jpg" class="btn"></a>
                </div>
            </div>
            <div class="commodity clearfix">
                <div class="right">
                    <p class="desc">食材好 还要油好</p>
                    <p class="name">泰林茶叶籽油单瓶装500ml</p>
                    <p class="price">
                        <span>原价:128.00元</span>
                        活动价:<i>99.00</i>元
                    </p>
                    <a href="http://item.soolife.cn/29439.html" target="_blank"><img src="/theme/activity/2016_10_Opening&Ceremony/pc/img/cao_content_06.jpg" class="btn"></a>
                </div>
                <div class="left pic">
                    <a href="http://item.soolife.cn/29439.html" target="_blank"><img src="/theme/activity/2016_10_Opening&Ceremony/pc/img/cao_content_07.jpg"></a>
                </div>
            </div>
            <div class="commodity clearfix">
                <div class="left picone">
                    <a href="http://item.soolife.cn/34110.html" target="_blank"><img src="/theme/activity/2016_10_Opening&Ceremony/pc/img/cao_content_08.jpg"></a>
                </div>
                <div class="right">
                    <p class="desc">好杯子 一辈子</p>
                    <p class="name">八角直身杯FB30</p>
                    <p class="price">
                        <span>原价:12.9元</span>
                        活动价:<i>6.9</i>元
                    </p>
                    <a href="http://item.soolife.cn/34110.html" target="_blank"><img src="/theme/activity/2016_10_Opening&Ceremony/pc/img/cao_content_06.jpg" class="btn"></a>
                </div>
            </div>
            <div class="commodity clearfix">
                <div class="right">
                    <p class="desc">一天好心情 从清晨第一杯水开始</p>
                    <p class="name">八角壶凝彩水具5件套(冰蓝)</p>
                    <p class="price">
                        <span>原价:89.00元</span>
                        活动价:<i>59.00</i>元
                    </p>
                    <a href="http://item.soolife.cn/34168.html" target="_blank"><img src="/theme/activity/2016_10_Opening&Ceremony/pc/img/cao_content_06.jpg" class="btn"></a>
                </div>
                <div class="left picone">
                    <a href="http://item.soolife.cn/34168.html" target="_blank"><img src="/theme/activity/2016_10_Opening&Ceremony/pc/img/cao_content_09.jpg"></a>
                </div>
            </div>
            <div class="commodity clearfix">
                <div class="left picone">
                    <a href="http://item.soolife.cn/37170.html" target="_blank"><img src="/theme/activity/2016_10_Opening&Ceremony/pc/img/cao_content_10.jpg"></a>
                </div>
                <div class="right">
                    <p class="desc">把绿色带进家</p>
                    <p class="name">蔓草宝宝(种植机)MC001</p>
                    <p class="price">
                        <span>原价:598.00元</span>
                        活动价:<i>478.40</i>元
                    </p>
                    <a href="http://item.soolife.cn/37170.html" target="_blank"><img src="/theme/activity/2016_10_Opening&Ceremony/pc/img/cao_content_06.jpg" class="btn"></a>
                </div>
            </div>
        </div>
        <!--///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////2F-->
        <div class="cao_content_theme">
            <a href="#"><img src="/theme/activity/2016_10_Opening&Ceremony/pc/img/cao_content_11.jpg" class="title ac"></a>
            <div class="commodity clearfix">
                <div class="left picone">
                    <a href="http://item.soolife.cn/15627.html" target="_blank"><img src="/theme/activity/2016_10_Opening&Ceremony/pc/img/cao_content_12.jpg"></a>
                </div>
                <div class="right">
                    <p class="desc">鸟语花香 不如家中米香</p>
                    <p class="name">胜腾良友有机稻花香大米</p>
                    <p class="price">
                        <span>原价:98.00元</span>
                        活动价:<i>75.00</i>元
                    </p>
                    <a href="http://item.soolife.cn/15627.html" target="_blank"><img src="/theme/activity/2016_10_Opening&Ceremony/pc/img/cao_content_06.jpg" class="btn"></a>
                </div>
            </div>
            <div class="commodity clearfix">
                <div class="right">
                    <p class="desc">真的‘卫生’的卫生巾</p>
                    <p class="name">乐媛日用卫生巾</p>
                    <p class="price">
                        <span>原价:44.00元</span>
                        活动价:<i>32.80</i>元
                    </p>
                    <a href="http://item.soolife.cn/25350.html" target="_blank"><img src="/theme/activity/2016_10_Opening&Ceremony/pc/img/cao_content_06.jpg" class="btn"></a>
                </div>
                <div class="left picone">
                    <a href="http://item.soolife.cn/25350.html" target="_blank"><img src="/theme/activity/2016_10_Opening&Ceremony/pc/img/cao_content_13.jpg"></a>
                </div>
            </div>
            <div class="commodity clearfix">
                <div class="left picone">
                    <a href="http://item.soolife.cn/29661.html" target="_blank"><img src="/theme/activity/2016_10_Opening&Ceremony/pc/img/cao_content_14.jpg"></a>
                </div>
                <div class="right">
                    <p class="desc">宝贝堆堆高 未来节节高</p>
                    <p class="name">BCL普芬利 宝宝堆堆高</p>
                    <p class="price">
                        <span>原价:108.00元</span>
                        活动价:<i>68.00</i>元
                    </p>
                    <a href="http://item.soolife.cn/29661.html" target="_blank"><img src="/theme/activity/2016_10_Opening&Ceremony/pc/img/cao_content_06.jpg" class="btn"></a>
                </div>
            </div>
            <div class="commodity clearfix">
                <div class="right">
                    <p class="desc">如果性感是错 那这东西就犯大错了</p>
                    <p class="name">林诗梦银纤维聚拢型桃花韵</p>
                    <p class="price">
                        <span>原价:248.00元</span>
                        活动价:<i>175.00</i>元
                    </p>
                    <a href="http://item.soolife.cn/36968.html" target="_blank"><img src="/theme/activity/2016_10_Opening&Ceremony/pc/img/cao_content_06.jpg" class="btn"></a>
                </div>
                <div class="left picone">
                    <a href="http://item.soolife.cn/36968.html" target="_blank"><img src="/theme/activity/2016_10_Opening&Ceremony/pc/img/cao_content_15.jpg"></a>
                </div>
            </div>
            <div class="commodity clearfix">
                <div class="left picone">
                    <a href="http://item.soolife.cn/13467.html" target="_blank"><img src="/theme/activity/2016_10_Opening&Ceremony/pc/img/cao_content_16.jpg"></a>
                </div>
                <div class="right">
                    <p class="desc">让喝茶变得根本停不下来</p>
                    <p class="name">rtiart无铅陶瓷 茶具套装</p>
                    <p class="price">
                        <span>原价:269.00元</span>
                        活动价:<i>188.30元</i>元
                    </p>
                    <a href="http://item.soolife.cn/13467.html" target="_blank"><img src="/theme/activity/2016_10_Opening&Ceremony/pc/img/cao_content_06.jpg" class="btn"></a>
                </div>
            </div>
        </div>
        <!--//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////3F-->
        <div class="cao_content_theme">
            <a href="#"><img src="/theme/activity/2016_10_Opening&Ceremony/pc/img/cao_content_17.jpg" class="title ac"></a>
            <div class="commodity clearfix">
                <div class="left picone">
                    <a href="http://item.soolife.cn/38207.html" target="_blank"><img src="/theme/activity/2016_10_Opening&Ceremony/pc/img/cao_content_18.jpg"></a>
                </div>
                <div class="right">
                    <p class="desc">吃出身材 吃出健康</p>
                    <p class="name">玫瑰酵素饼干加一日三纤</p>
                    <p class="price">
                        <span>原价:16.8元</span>
                        活动价:<i>9.90元</i>元
                    </p>
                    <a href="http://item.soolife.cn/38207.html" target="_blank"><img src="/theme/activity/2016_10_Opening&Ceremony/pc/img/cao_content_06.jpg" class="btn"></a>
                </div>
            </div>
            <div class="commodity clearfix">
                <div class="right">
                    <p class="desc">让你毫无ps痕迹</p>
                    <p class="name">科夫氏自然系列套装</p>
                    <p class="price">
                        <span>原价:765.00元</span>
                        活动价:<i>153.00</i>元
                    </p>
                    <a href="http://item.soolife.cn/28917.html" target="_blank"><img src="/theme/activity/2016_10_Opening&Ceremony/pc/img/cao_content_06.jpg" class="btn"></a>
                </div>
                <div class="left picone">
                    <a href="http://item.soolife.cn/28917.html" target="_blank"><img src="/theme/activity/2016_10_Opening&Ceremony/pc/img/cao_content_19.jpg"></a>
                </div>
            </div>
            <div class="commodity clearfix">
                <div class="left pic">
                    <a href="http://item.soolife.cn/15444.html" target="_blank"><img src="/theme/activity/2016_10_Opening&Ceremony/pc/img/cao_content_20.jpg"></a>
                </div>
                <div class="right">
                    <p class="desc">蜜蜂贡献的不只是蜂蜜 还有你的肌肤</p>
                    <p class="name">觅丝米恩极致再生蜂毒原液</p>
                    <p class="price">
                        <span>原价:750.00元</span>
                        活动价:<i>517.50元</i>元
                    </p>
                    <a href="http://item.soolife.cn/15444.html" target="_blank"><img src="/theme/activity/2016_10_Opening&Ceremony/pc/img/cao_content_06.jpg" class="btn"></a>
                </div>
            </div>
            <div class="commodity clearfix">
                <div class="right">
                    <p class="desc">外出洗浴清洗 也就是随后一装</p>
                    <p class="name">约翰娜益肤旅行装杏仁油</p>
                    <p class="price">
                        <span>原价:89.00元</span>
                        活动价:<i>69.00</i>元
                    </p>
                    <a href="http://item.soolife.cn/12917.html" target="_blank"><img src="/theme/activity/2016_10_Opening&Ceremony/pc/img/cao_content_06.jpg" class="btn"></a>
                </div>
                <div class="left picone">
                    <a href="http://item.soolife.cn/12917.html" target="_blank"><img src="/theme/activity/2016_10_Opening&Ceremony/pc/img/cao_content_21.jpg"></a>
                </div>
            </div>
            <div class="commodity clearfix">
                <div class="left picone">
                    <a href="http://item.soolife.cn/33989.html" target="_blank"><img src="/theme/activity/2016_10_Opening&Ceremony/pc/img/cao_content_22.jpg"></a>
                </div>
                <div class="right">
                    <p class="desc">杯子的好归宿</p>
                    <p class="name">高档金属马克杯架</p>
                    <p class="price">
                        <span>原价:65.00元</span>
                        活动价:<i>52.00</i>元
                    </p>
                    <a href="http://item.soolife.cn/33989.html" target="_blank"><img src="/theme/activity/2016_10_Opening&Ceremony/pc/img/cao_content_06.jpg" class="btn"></a>
                </div>
            </div>
        </div>
        <!--//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////4F-->
        <div class="cao_content_theme">
            <a href="#"><img src="/theme/activity/2016_10_Opening&Ceremony/pc/img/cao_content_23.jpg" class="title ac"></a>
            <div class="commodity clearfix">
                <div class="left pic">
                    <a href="http://item.soolife.cn/27310.html" target="_blank"><img src="/theme/activity/2016_10_Opening&Ceremony/pc/img/cao_content_24.jpg" class="pic"></a>
                </div>
                <div class="right">
                    <p class="desc">刷牙刷出层次感</p>
                    <p class="name">2080超细软毛牙刷</p>
                    <p class="price">
                        <span>原价:15.90元</span>
                        活动价:<i>10.00</i>元
                    </p>
                    <a href="http://item.soolife.cn/27310.html" target="_blank"><img src="/theme/activity/2016_10_Opening&Ceremony/pc/img/cao_content_06.jpg" class="btn"></a>
                </div>
            </div>
            <div class="commodity clearfix">
                <div class="right">
                    <p class="desc">还你纯净的世界</p>
                    <p class="name">银京成人清洁滋润毛巾</p>
                    <p class="price">
                        <span>原价:14.10元</span>
                        活动价:<i>11.28元</i>元
                    </p>
                    <a href="http://item.soolife.cn/28981.html" target="_blank"><img src="/theme/activity/2016_10_Opening&Ceremony/pc/img/cao_content_06.jpg" class="btn"></a>
                </div>
                <div class="left pic">
                    <a href="http://item.soolife.cn/28981.html" target="_blank"><img src="/theme/activity/2016_10_Opening&Ceremony/pc/img/cao_content_25.jpg"></a>
                </div>
            </div>
            <div class="commodity clearfix last">
                <div class="left">
                    <a href="http://item.soolife.cn/34020.html" target="_blank" class="pic"><img src="/theme/activity/2016_10_Opening&Ceremony/pc/img/cao_content_26.jpg"></a>
                </div>
                <div class="right">
                    <p class="desc">吃饭只是为了show餐具</p>
                    <p class="name">小麦系列餐具套装</p>
                    <p class="price">
                        <span>原价:14.90元</span>
                        活动价:<i>11.92元</i>元
                    </p>
                    <a href="http://item.soolife.cn/34020.html" target="_blank"><img src="/theme/activity/2016_10_Opening&Ceremony/pc/img/cao_content_06.jpg" class="btn"></a>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="cao_footer">
    <img src="/theme/activity/2016_10_Opening&Ceremony/pc/img/cao_footer_01.jpg">
</div>
</body>
</html>