<!DOCTYPE html>
<html>

	<head>
		<meta charset="utf-8" />
		<title>松仕箱包</title>
		<link rel="stylesheet" href="/theme/activity/2016_09_cases/mobile/css/app_index.css" />
		 <link rel="stylesheet" type="text/css" href="/public/mobile/css/foot.css" />
	</head>
	<body>
		<div class="f_possessions">
			<div class="f_banner">
				<img src="/theme/activity/2016_09_cases/mobile/img/banner/banner_one.jpg" alt="" align="top"/>
				<img src="/theme/activity/2016_09_cases/mobile/img/banner/banner_two.jpg" alt="" align="top"/>
				<img src="/theme/activity/2016_09_cases/mobile/img/banner/banner_three.jpg" alt="" align="top"/>
				<img src="/theme/activity/2016_09_cases/mobile/img/banner/banner_four.jpg" alt="" align="top"/>
				<img src="/theme/activity/2016_09_cases/mobile/img/banner/banner_five.jpg" alt="" align="top"/>
				<img src="/theme/activity/2016_09_cases/mobile/img/banner/banner_six.jpg" alt="" align="top"/>
			</div>
			<div class="f_banner_up">
				<ul>
					<li class="f_photograph">
						<a href="http://item.soolife.cn/m/26229.html">
							<img src="/theme/activity/2016_09_cases/mobile/img/banner_up/picture_one.png" alt="" data="opengoodsdetail"/>
						</a>
					</li>
					<li class="f_photograph_one">
						<a href="http://item.soolife.cn/m/26228.html">
							<img src="/theme/activity/2016_09_cases/mobile/img/banner_up/picture_two.png" alt=""data="opengoodsdetail" />
						</a>
					</li>
				</ul>
			</div>
			<div class="first_picture">
				<ul>
					<li>
						<a href="http://item.soolife.cn/m/22385.html">
							<img src="/theme/activity/2016_09_cases/mobile/img/first/product_one.png" alt=""data="opengoodsdetail" />
						</a>
					</li>
					<li class="right">
						<a href="http://item.soolife.cn/m/22386.html">
							<img src="/theme/activity/2016_09_cases/mobile/img/first/product_two.png" alt="" data="opengoodsdetail"/>
						</a>
					</li>
					<li>
						<a href="http://item.soolife.cn/m/22387.html">
							<img src="/theme/activity/2016_09_cases/mobile/img/first/product_three.png" alt="" data="opengoodsdetail"/>
						</a>
					</li>
					<li class="right">
						<a href="http://item.soolife.cn/m/22388.html">
							<img src="/theme/activity/2016_09_cases/mobile/img/first/product_four.png" alt=""data="opengoodsdetail" />
						</a>
					</li>
					<li>
						<a href="http://item.soolife.cn/m/22411.html">
							<img src="/theme/activity/2016_09_cases/mobile/img/first/product_five.png" alt=""data="opengoodsdetail" />
						</a>
					</li>
					<li class="right">
						<a href="http://item.soolife.cn/m/26230.html">
							<img src="/theme/activity/2016_09_cases/mobile/img/first/product_six.png" alt="" data="opengoodsdetail"/>
						</a>
					</li>
					<li>
						<a href="http://item.soolife.cn/m/26227.html">
							<img src="/theme/activity/2016_09_cases/mobile/img/first/product_seven.png" alt="" data="opengoodsdetail"/>
						</a>
					</li>
					<li class="right">
						<a href="http://item.soolife.cn/m/26231.html">
							<img src="/theme/activity/2016_09_cases/mobile/img/first/product_eight.png" alt="" data="opengoodsdetail"/>
						</a>
					</li>
					<li>
						<a href="http://item.soolife.cn/m/22413.html">
							<img src="/theme/activity/2016_09_cases/mobile/img/first/product_nine.png" alt="" data="opengoodsdetail"/>
						</a>
					</li>
					<li class="right">
						<a href="http://item.soolife.cn/m/22414.html">
							<img src="/theme/activity/2016_09_cases/mobile/img/first/product_ten.png" alt="" data="opengoodsdetail"/>
						</a>
					</li>
					<li>
						<a href="http://item.soolife.cn/m/22415.html">
							<img src="/theme/activity/2016_09_cases/mobile/img/first/product_eleven.png" alt="" data="opengoodsdetail"/>
						</a>
					</li>
					<li class="right">
						<a href="http://item.soolife.cn/m/22433.html">
							<img src="/theme/activity/2016_09_cases/mobile/img/first/product_twety.png" alt="" data="opengoodsdetail"/>
						</a>
					</li>
					
				</ul>
			</div>
			<!--新品推荐-->
			<div class="f_new_product">
				<img src="/theme/activity/2016_09_cases/mobile/img/new_product/new_product_banner.jpg" alt="" data="opengoodsdetail"/>
			</div>
			<div class="first_picture">
				<ul>
					<li>
						<a href="http://item.soolife.cn/m/22434.html">
							<img src="/theme/activity/2016_09_cases/mobile/img/new_product/product_one.png" alt="" data="opengoodsdetail"/>
						</a>
					</li>
					<li class="right">
						<a href="http://item.soolife.cn/m/22435.html">
							<img src="/theme/activity/2016_09_cases/mobile/img/new_product/product_two.png" alt="" data="opengoodsdetail"/>
						</a>
					</li>
					<li>
						<a href="http://item.soolife.cn/m/22454.html">
							<img src="/theme/activity/2016_09_cases/mobile/img/new_product/product_three.png" alt="" data="opengoodsdetail"/>
						</a>
					</li>
					<li class="right">
						<a href="http://item.soolife.cn/m/22455.html">
							<img src="/theme/activity/2016_09_cases/mobile/img/new_product/product_four.png" alt=""data="opengoodsdetail" />
						</a>
					</li>
					<li>
						<a href="http://item.soolife.cn/m/22461.html">
							<img src="/theme/activity/2016_09_cases/mobile/img/new_product/product_five.png" alt=""data="opengoodsdetail" />
						</a>
					</li>
					<li class="right">
						<a href="http://item.soolife.cn/m/22462.html">
							<img src="/theme/activity/2016_09_cases/mobile/img/new_product/product_six.png" alt="" data="opengoodsdetail"/>
						</a>
					</li>
					<li>
						<a href="http://item.soolife.cn/m/22478.html">
							<img src="/theme/activity/2016_09_cases/mobile/img/new_product/product_seven.png" alt=""data="opengoodsdetail" />
						</a>
					</li>
					<li class="right">
						<a href="http://item.soolife.cn/m/22481.html">
							<img src="/theme/activity/2016_09_cases/mobile/img/new_product/product_eight.png" alt="" data="opengoodsdetail"/>
						</a>
					</li>
					<li>
						<a href="http://item.soolife.cn/m/22480.html">
							<img src="/theme/activity/2016_09_cases/mobile/img/new_product/product_nine.png" alt="" data="opengoodsdetail"/>
						</a>
					</li>
					<li class="right">
						<a href="http://item.soolife.cn/m/22479.html">
							<img src="/theme/activity/2016_09_cases/mobile/img/new_product/product_ten.png" alt="" data="opengoodsdetail"/>
						</a>
					</li>
					<li>
						<a href="http://item.soolife.cn/m/22498.html">
							<img src="/theme/activity/2016_09_cases/mobile/img/new_product/product_eleven.png" alt="" data="opengoodsdetail"/>
						</a>
					</li>
					<li class="right">
						<a href="http://item.soolife.cn/m/22499.html">
							<img src="/theme/activity/2016_09_cases/mobile/img/new_product/product_twety.png" alt="" data="opengoodsdetail"/>
						</a>
					</li>
					
				</ul>
			</div>
			<div class="f_bottom">
				<a href="http://item.soolife.cn/m/22501.html">
					<img src="/theme/activity/2016_09_cases/mobile/img/bottom/bottom_one.png" alt=""  data="opengoodsdetail"/>
				</a>
				<a href="http://item.soolife.cn/m/22500.html">
					<img src="/theme/activity/2016_09_cases/mobile/img/bottom/bottom_two.png" alt=""data="opengoodsdetail" />
				</a>
			</div>
			<div class="bottom">
				<img src="/theme/activity/2016_09_cases/mobile/img/bottom/图层 33.png" alt="" />
			</div>
		</div>
	</body>
<script src="/public/mobile/js/jquery-3.0.0.min.js"></script>
	  <script src="/public/js/sdk.js"></script>	
	    <script src="/public/mobile/js/websdk.js"></script></html>