<div class="header">
	<div class="header_top">
		<img alt="如此生活" src="/public/img/logo.png">
		<div class="header_top">
		{% if m_id > 0 %}
			<a title="如此生活" href="/logout.html" class="logout">退出</a>&nbsp;&nbsp;&nbsp;
		{% else %}
			<a title="如此生活" href="/sop/login.html" class="logout">登录</a>&nbsp;&nbsp;&nbsp;
		{% endif %}
			<img alt="如此生活" src="/public/img/tell.png">
			<span class="tell">400-6699-878</span>
			<span>中文</span>
		</div>
	</div>
</div>
<div class="nav">
	<div class="nav-main">
		<ul>
			{{ partial("layouts/inc_sidebar") }}
		</ul>
	</div>
</div>