<div class="footerdiv">
	<div class="footer_wrap">
		<div class="footer_nav">
			<ul>
				<li style="width:285px;">
					<dl class="footer_nav_first">
						<dt>新手指南</dt>
						<dd><a target="_blank" href="{{url_help}}/help_A_E01.html">免费注册</a></dd>
						<dd><a target="_blank" href="{{url_help}}/help_A_E02.html">搜索商品</a></dd>
						<dd><a target="_blank" href="{{url_help}}/help_A_E03.html">购买流程</a></dd>
						<dd><a target="_blank" href="{{url_help}}/help_A_E05.html">评论晒单</a></dd>
					</dl>
				</li>
				<li style="width:182px;">
					<dl>
						<dt>配送方式</dt>
						<dd><a target="_blank" href="{{url_help}}/help_A_B01.html">配送方式</a></dd>
						<dd><a target="_blank" href="{{url_help}}/help_A_B02.html">配送时间</a></dd>
					</dl>
				</li>
				<li style="width:180px;">
					<dl>
						<dt>支付方式</dt>
						<dd><a target="_blank" href="{{url_help}}/help_A_C01.html">支付宝支付</a></dd>
						<dd><a target="_blank" href="{{url_help}}/help_A_C02.html">银联卡支付</a></dd>
					</dl>
				</li>
				<li style="width:165px;">
					<dl>
						<dt>售后服务</dt>
						<dd><a target="_blank" href="{{url_help}}/help_A_D01.html">售后政策</a></dd>
						<dd><a target="_blank" href="{{url_help}}/help_A_D02.html">退款说明</a></dd>
						<dd><a target="_blank" href="{{url_help}}/help_A_D03.html">取消订单</a></dd>
					</dl>
				</li>
				<li style="width:193px;">
					<dl>
						<dt><a href="{{url_sop}}" target="_blank" style="font-size:16px;color:#666666;" onmouse="this.style.color='red'">招商合作</a></dt>
					</dl>
				</li>
				<li style="width:160px;">
					<dl>
						<dt>购物指南</dt>
						<dd><a target="_blank" href="{{url_help}}/help_A_A03.html">星币说明</a></dd>
						<dd><a target="_blank" href="{{url_help}}/help_A_A01.html">交易条款</a></dd>
						<dd><a target="_blank" href="{{url_help}}/help_A_A02.html">购物流程</a></dd>
						<dd><a target="_blank" href="{{url_help}}/help_A_A08.html">注册流程</a></dd>
						<dd><a target="_blank" href="{{url_help}}/help_A_A06.html">常见问题</a></dd>
					</dl>
				</li>
			</ul>
			<div class="clear">
			</div>
		</div>
	</div>
	<div class="foot-s">
		<div class="mainBox mainBoxim">
			<a class="s1" title="O2O双线开放" href="{{url_sop}}">O2O双线开放</a>
			<a class="s2" title="免年费返佣金" href="{{url_sop}}">免年费 返佣金</a>
			<a class="s3" title="仓储物流服务" href="{{url_sop}}">仓储物流服务</a>
		</div>
	</div>
	<div class="footer">
		<p>
			<a href="{{url_website}}/about/index.html" target="_blank">关于我们</a> |
			<a href="{{url_website}}/about/contact.html" target="_blank">联系我们</a> |
			<a href="{{url_website}}/job/index.html" target="_blank">诚聘英才</a> |
			<a href="{{url_website}}/about/brand.html" target="_blank">品牌介绍</a> |
			<a href="{{url_sop}}" target="_blank">商家入驻</a> |
			<a href="{{url_website}}/about/links.html" target="_blank">友情链接</a> |
			<a href="{{url_website}}/about/law.html" target="_blank">法律声明</a>
		</p>
		<p style="font-family: Verdana">
			&copy; 2014-2015
			<a href="http://www.soolife.cn">如此生活</a>
			版权所有 沪ICP备11038000号-2
		</p>
	</div>
</div>
