<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width,minimum-scale=1, maximum-scale=1, initial-scale=1.0,user-scalable=no" />
        <link rel="stylesheet" type="text/css" href="css/common.css"/>
        <title>报错页面</title>
        <style type="text/css">
        .errorbag{width:70%;display:block;margin:0 auto;margin-top:20%}
        .errorp{padding:10px;text-align: center;font-size: 14px;color:#5D5E5F}
        .errora{color:#009F95;}
        .erroediv{text-align: center;text-decoration: underline;}
        </style>
    </head>
    <body>  
        <img class="errorbag" src="/public/icon/zanwushuju.png"/>
        <p class="errorp">404 点击请重新登录</p>
        <div class="erroediv"><a href="" class="errora">i.soolife.loc/m/login.html</a></div>
    </body>
</html>