<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>如此生活|会员中心</title>
	<meta name="viewport" content="width=device-width, initial-scale=1,maximum-scale=1,user-scalable=no">
	<meta name="apple-mobile-web-app-capable" content="yes">
	<meta name="apple-mobile-web-app-status-bar-style" content="black">	
    <link rel="stylesheet" href="/public/ext/css/soo.m.ui.css">
    <link rel="stylesheet" href="/public/ext/css/download.css">
    <link rel="stylesheet" href="/public/ext/css/swiper.css">
	<link rel="stylesheet" type="text/css" href="/public/css/i/common.css"/>
	<link rel="stylesheet" type="text/css" href="/public/css/i/msg/index.css"/>
</head>
<body>
<div class="index_wrap">
	<div class="header">
	    <a onclick="window.history.go(-1)"><img class="arrow"  src="/public/img/common/shop_back_black@1x.png " ></a>
		<span class="head_title">资产消息</span> 
	</div>
	<!-- 下载框 -->
<!-- 	<div class="download_box" id="download-nav">
		<div class="remove" id="download-nav-hide"><img src="../public/img/common/icon_close@3x.png" alt=""></div>
		<div class="logo"><img src="../public/img/common/logo@3x.png" alt=""></div>
		<div class="word">下载如此生活客户端</div>
		<div class="sure" id="download-nav-sure"><div>下载</div></div>
	</div> -->
	<div id="wrap">
        {% if asset %}
        <input type="hidden" value="{{ asset['skip'] }}" id="asset_skip" />
        {% if asset['data'] %}
        <ul id="msgasset">
        {% for d in asset['data'] %}
        	<li>
        		<p class="asset_date">{{ d['createtime'] }}</p>
        		<div class="asset_con">
        			<p class="asset_title">{{ d['content']['title'] }}</p>
        			<div class="asset_txt">
                        <p class="asset_noimg">{{ d['content']['details'] }}</p>
        			</div>
        			<div class="asset_more">
	        			<a href="{{ d['url'] }}">
	        				<p>查看详情</p>
	        				<img src="/public/img/i/mine_xiayiye@3x.png">
	        			</a>
        			</div>
        		</div>
        	</li>
        {% endfor %}
        </ul>
		{% endif %}
		{% endif %}
		<p id="hidden" style="text-align:center;display:none;">没有更多消息了...</p>
    </div>
</div>
</body>
</html>
<script src="/public/js/rem.js"></script> 
<script src="/public/ext/js/jquery-1.8.3.min.js"></script>
<script src="/public/js/jquery.base64.js"></script>
<script src="/public/ext/js/soo.m.ui.js"></script>
<script src="/public/ext/js/download.js"></script>
<script src="/public/js/i/msg/msgasset.js"></script> 