<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>如此生活|会员中心</title>
	<meta name="viewport" content="width=device-width, initial-scale=1,maximum-scale=1,user-scalable=no">
	<meta name="apple-mobile-web-app-capable" content="yes">
	<meta name="apple-mobile-web-app-status-bar-style" content="black">	
    <link rel="stylesheet" href="/public/ext/css/soo.m.ui.css">
    <link rel="stylesheet" href="/public/ext/css/download.css">
    <link rel="stylesheet" href="/public/ext/css/swiper.css">
	<link rel="stylesheet" type="text/css" href="/public/css/i/common.css"/>
	<link rel="stylesheet" type="text/css" href="/public/css/i/msg/index.css"/>
</head>
<body>
<div class="index_wrap">
	<div class="header">
	    <a onclick="window.history.go(-1)"><img class="arrow"  src="/public/img/common/shop_back_black@1x.png " ></a>
		<span class="head_title">售后消息</span> 
	</div>
	<!-- 下载框 -->
<!-- 	<div class="download_box" id="download-nav">
		<div class="remove" id="download-nav-hide"><img src="../public/img/common/icon_close@3x.png" alt=""></div>
		<div class="logo"><img src="../public/img/common/logo@3x.png" alt=""></div>
		<div class="word">下载如此生活客户端</div>
		<div class="sure" id="download-nav-sure"><div>下载</div></div>
	</div> -->
	<div id="wrap">
		{% if service %}
		<input  type="hidden"  value="{{ service['skip'] }}"  id="service_skip" />
		{% if service['data'] %}
        <ul id="msgorder">
        {% for d in service['data'] %}
        	<li>
        		<a href="/orders/particularsth/{{ d['content']['apply_no']}}.html">
	        		<p class="order_date">{{ d['createtime'] }} </p>
	        		<div class="order_con">
	        		    <p class="service_title">{{ d['content']['status'] }}</p>
	        		    <div class="order_txt">
		        			<img src="{{ d['content']['logo'] }}">
		        			<div class="order_msg">
		        				<p class="order_intro">{{ d['content']['name'] }}</p>
		        				<p class="order_num">申请单编号:  {{ d['content']['apply_no'] }}</p>
		        			</div>
	        		    </div>
	        		</div>
        		</a>
        	</li>
        {% endfor %}
        </ul> 
        {% endif %}
        {% endif %}
        <p id="hidden" style="text-align:center;display:none;">没有更多信息了...</p>
    </div>
</div>
</body>
</html>
<script src="/public/js/rem.js"></script> 
<script src="/public/ext/js/jquery-1.8.3.min.js"></script>
<script src="/public/js/jquery.base64.js"></script>
<script src="/public/ext/js/soo.m.ui.js"></script>
<script src="/public/ext/js/download.js"></script>
<script src="/public/js/i/msg/msgservice.js"></script> 