<?php
$css = $this -> assets -> get('header');
$css -> addCss("public/v3.0.1/css/pc.about.css");
?>
<div class="row-container clearfix">
	<div class="aboutus  main-container">
		<ul class="bcrumb">
			<li><i class=" fa fa-home fa-lg"></i></li>
			<li><a href="/">如此生活</a><span class="divider">&gt;</span></li>
			<li><a href="/about/index.html">关于我们</a><span class="divider">&gt;</span></li>
			<li><a href="mbrCenter">品牌介绍</a></li>
		</ul>
		{{ partial("about/inc_crumb") }}
		<div class="prof-right" style="padding-right: 0px;">
			<!-- <div class="prof-right-tit">
				品牌介绍
			</div>-->
			<div class="brand prof-right-con">
				<div class="title">
					<h2>如此生活品牌介绍</h2>
					 <p>Brand Introduction</p>
				</div>
				<div class="content">
					<img style="float: left;" style="float: left;" src="/public/img/aboutus/brand/ppjs_02.jpg" alt="如此生活品牌介绍"/>
					<div class="info">
						<ul>
							<li><h3>品牌介绍</h3></li>
							<li>“如此生活”品牌诞生于2013年9月，源自于创始人——吴存松先生多年的商海历练和对待人生的深刻感悟，品牌源自于生活，但却跃然于生活之上。</li>
							<li> <strong>LOGO理念：</strong>五颗闪亮之星代表了生活在五大洲拥有不同肤色，不同信仰，不同国籍的无数社区居民，他们犹如天空中的点点繁星，彼此生活关联在一起，通过我们的平台从此开启人生中不一样的精彩生活。</li>
							<li> <strong>LOGO含义：</strong> SO→SOO强化SO的作用，两个SO代表联合，汇聚，家庭的和睦与温暖，LIFE是指生活不仅仅就是活着，它是一种方式和态度，让我们感叹生活还可以这样！这才是真正的生活！</li>
							<li> 蓝色代表了冷静，沉稳，勇敢，果断！<br />
  象征我们志存高远，不断进取的探索精神！</li>
							<li>  橙色代表了阳光，热情，快乐，幸福！<br />
  象征我们团结一心，努力向上，取得辉煌成就！</li>
							<li><h3>品牌创立时间</h3></li>
							<li>品牌自2013年1月份开始创立。</li>
							<li><h3>品牌愿景</h3></li>
							<li>为人们创造美好生活</li>
							<li><h3>品牌理念</h3></li>
							<li> 让民众受益，让商家营利</li>
							<li><h3>品牌目标 </h3></li>
							<li>为企业主、消费者、合伙人提供一种全新生活体验方式</li>
						</ul>
					</div>
					<img style="float: left;margin-top: -125px;margin-left: -20px;" src="/public/img/aboutus/brand/ppjs_04.jpg" alt="商家服务"/>
					<div class="business">
                        <div class="hkl_business">
    						<h3>品牌业务 </h3>
    						<p>以O2O为基础 一站式服务为核心</p>
                        </div>
						<img src="/public/img/aboutus/brand/ppjs_08.jpg" alt="消费者服务"/>
					</div>
				</div>
				<div class="valeur clearfix">
					<div class="left">
						<h3>品牌价值</h3>
						<p style="margin-top: 24px;">消费者、企业合伙人和员工，运用互联网思维，围绕着
							<br>“生活本质”重新书写商业规则，共同努力搭建与众不同的<br />
							“如此生活”商业平台，融入“家人”文化内涵，重树商业<br>
							标准，以“健康、可持续的生活方式”引领未来生活潮流！
						</p>
					</div>
					<img style="margin-left: 10px;" src="/public/img/aboutus/brand/ppjs_09.jpg" alt="全新生活体验方式"/>
				</div>
				<div class="bottom">
					<img style="margin-left: -20px;margin-top: -44px;float: left;" src="/public/img/aboutus/brand/ppjs_11.jpg" alt="品牌使用范围"/>
					<div>
						<h3>品牌使用范围</h3>
						<p>配合公司整体业务的发展，目前使用范围包括公司网站<br>
						www.soolif.cn体验店，手机移动端、本地合作商户、客户<br>
							会员卡、吉祥物礼品、社区慈善活动和企业宣传资料等。</p>
					</div>
					<img style="float: right;margin-top: 220px;" src="/public/img/aboutus/brand/ppjs_12.jpg" />
				</div>
				<div style="width: 920px;border-bottom: 1px dashed #dcdcdc;float: left;margin-left: 10px;"></div>
			</div>
		</div>
	</div>
</div>