<?php
$css = $this -> assets -> get('header');
$css -> addCss("public/v3.0.1/css/pc.about.css");
?>
<div class="row-container clearfix">
	<div class="aboutus  main-container">
		<ul class="bcrumb">
			<li>
				<i class=" icon-home icon-large"></i>
			</li>
			<li>
				<a href="/">如此生活</a><span class="divider">&gt;</span>
			</li>
			<li>
				<a href="/about/index.html">关于我们</a><span class="divider">&gt;</span>
			</li>
			<li>
				<a href="mbrCenter">联系我们</a>
			</li>
		</ul>
		{{ partial("about/inc_crumb") }}
		<div class="prof-right">
			<div class="prof-right-tit" style=" font-size: 28px; height: 90px; line-height:110px; padding-left: 40px; font-family: '微软雅黑'; color: #228dc1;">
				联系我们 <span style="font-size: 14px;">Contact us</span>
			</div>
			<div class="prof-right-con">
				<h5 style="text-align: center;font-size: 18px; height: 30px; line-height: 30px;"> SOOLIFE 如此生活-O2O平台-品牌招募 联系方式</h5>
				<div class="about">
					<table>
						<tbody>
							<tr>
								<th>行业分类</th>
								<th width="100">联系人</th>
								<th width="160">联系电话</th>
								<th width="180">联系邮箱</th>
							</tr>
							<tr>
								<td style="text-align: left;padding-left: 10px; font-size: 14px; height: 50px; line-height: 50px;">服饰鞋帽箱包 / 运动户外 </td>
								<td>郝先生</td>
								<td>15618864066</td>
								<td>ron_hao@soolife.com.cn</td>
							</tr>
							<tr>
								<td style="text-align: left;padding-left: 10px; font-size: 14px; height: 50px; line-height: 50px;">日用百货 / 小家电 / 化妆品 / 家居用品 / 3c数码 </td>
								<td>章先生</td>
								<td>18321922347</td>
								<td>wenbin_zhang@soolife.com.cn</td>
							</tr>
							<tr>
								<td style="text-align: left;padding-left: 10px; font-size: 14px; height: 50px; line-height: 50px;">母婴玩具 / 童装 / 食品饮料酒类生鲜 / 汽车用品</td>
								<td>王女士</td>
								<td>13564300895</td>
								<td>jessica_wang@soolife.com.cn</td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>