<?php
$css = $this -> assets -> get('header');
$css -> addCss("public/v3.0.1/css/pc.about.css");
?>
<div class="row-container clearfix">
	<div class="aboutus  main-container">
		<ul class="bcrumb">
			<li><i class="fa fa-home fa-lg"></i></li>
			<li><a href="/">如此生活</a><span class="divider">&gt;</span></li>
			<li><a href="/about/index.html">关于我们</a><span class="divider">&gt;</span>></li>
			<li><a href="mbrCenter">企业创始人</a></li>
		</ul>
		{{ partial("about/inc_crumb") }}
		<div class="prof-right">

			<div class="top1">
				<h2>如此生活创始人</h2>
				<p>
					Soolife Founder
				</p>
			</div>
			<div class="top2">
				<div class="top2_left">
					<img style="float: left;" src="/public/img/aboutus/founder/qy_03.jpg" alt="品牌创始人吴存松"/>
					<img style="margin-top: 87px;margin-left: 64px;" src="/public/img/aboutus/founder/qy_09.jpg" />
				</div>
				<div class="top2_right">
					<h3>吴存松</h3><span style="margin-left: 10px;">先生</span>
					<p style="margin-top: 22px;">
						“如此生活”品牌创始人
						<br />
						1981年出生于河北省沧州市。
					</p>
					<p>
						“如此生活”品牌诞生于2013年9月，源自于创始人——吴存松先生多年的商海历练和对待人生的深刻感悟，品牌源自于生活，但却跃然于生活之上。
					</p>
					<p>
						&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;吴存松先生毕业于吉林大学法学院，并在上海交通大学EMBA高级总裁研修班进修，创办过生产制造、户外媒体等企业。
					</p>
					<p>
						&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;获得过国家各项技术型专业二十余项，先后被授予“年轻创业企业家”、“优秀青年企业家”等荣誉称号，获得了各级政府和党政机关领导的亲切接待与表扬！在创办企业的过程中仍不忘投身公益事业，积极参与各项公益活动，回馈社会，奉献爱心!
					</p>
					<p>
						&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2012年率领公司进军互联网电子商务，创立“如此生活”品牌，以O2O为基础，一站式服务为核心，开辟全新战场，挑战传统电子商务的经营模式，用互联网思维进行大胆创新
						，提出“一站式买卖综合服务”概念，引领未来电子商务发展的新方向!
					</p>
					<img src="/public/img/aboutus/founder/qy_05.jpg" />
				</div>
			</div>
			<div style="clear: both;"></div>
			<div class="top3">
				<img style="float: right;" src="/public/img/aboutus/founder/qy_11.jpg" alt="吴存松"/>
				<p style="float: right;">
					品牌创始人--
				</p>
			</div>
			<div class="top4">
				<div style="float: left;">
					<h3>商海历练</h3>
					<p>
						&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
						吴存松先生早年初入社会时，到工厂务工，想通过自己努力获得认可，但是发现有些人却可以通过裙带关系和手段轻松获得各种机会，不公平的竞争让他愤然决定不再打工，踏入社会寻找自我发展更加广阔的空间，他没有受过正规商务的培训，却敢于深入市场，发掘契机。第一次拜访客户，被客户嘲讽和辱骂，深深的在他内心打下了奋发图强的烙印，虽然一次次被生活困境所洗礼，但从未动摇他成功的决心。
					</p>
				</div>
				<img style="margin-left: 52px;" src="/public/img/aboutus/founder/qy_14.jpg" />
			</div>
			<div class="top5">
				<p>
					&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
					通过在社会里的丰富历练，吴存松先生成功走出了一条属于自己的奋斗之路，不断的尝试，不断的受挫，不断的积累，不断的自我提升，在大多数年轻人还沉浸在青春岁月的时候，吴存松先生通过不断努力创造了属于自己的奇迹，25岁不到的年纪，早已是一名家喻户晓的年青企业家，由他创立的制造加工企业年产值上千万，盈利上百万元，为家乡的经济腾飞做出了巨大贡献。这一令人瞩目的辉煌成就并没有让吴存松先生停止前进的步伐。
				</p>
			</div>
			<div class="top6">
				<img style="float: left;margin-top: 60px;" src="/public/img/aboutus/founder/qy_16.jpg" />
				<p>
					&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
					公元2000年，他选择了中国经济的心脏，来到上海开设生产基地，凭借敏锐的洞察力，开创了商业净水领域一片天地，基地为全国众多品牌厂商加工生产净水设备，获得科技专利上百项，公司研发的专业净水设备在2010年上海世博会园区内为参观展览的7000万观众提供直饮纯净水。吴存松先生率先提出了“获得阳光、空气、水是人类均等的权利”，在企业发展的过程中，他身先士卒，一马当先，从研发生产、市场推广、品牌建设都付出了巨大的心血，也花费了大量的财力物力，他不断深入市场，发现有非常多的年轻企业家和他一样，生产优质的产品，为了打造品牌呕心沥血，然而却事与愿违，推广难，销货难，企业难以维计的比比皆是；市场的消费者买到的商品充斥着假货、次品，售后难、维权难。他陷入了沉思，企业利益与社会责任、民众权益如何能够协调共赢？作为当代企业家不仅要立足长三角的经济发展，着眼于未来国际化的市场，更要懂得重新诠释生活的含义，用创业带动就业，帮助更多人开创自己的梦想生活。
				</p>
			</div>
			<div class="top7">
				<p>
					&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
					经过深思熟虑，2011年，吴存松先生下定决心成为一个有责任心、对市场和社会做出积极贡献的企业家，他带着强烈的社会责任感，再次挺身而出，以“为人们创造美好生活”作为企业使命，2012年开始筹划创立“如此生活”商业平台，以他的睿智和勇气，带领年青一代的优秀员工进军互联网电子商务，以O2O为基础，一站式服务为核心，开辟全新战场，挑战传统电子商务的经营模式，用互联网思维进行大胆创新，提出“一站式服务”概念，助力中国中小企业和消费者全力迈向一个崭新生活！
				</p>
				<img src="/public/img/aboutus/founder/qy_19.jpg" />
			</div>
			<div style="width: 920px;border-bottom: 1px dashed #dcdcdc;margin-top: 60px;margin-left: 20px;"></div>
		</div>
	</div>
</div>

