<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title></title>
	    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
		<link rel="stylesheet" href="public/css/index/guid.css" />
	</head>
	<body>
		<div class="body_a">
			<div class="banner_a">
			   <img src="public/img/guid/banner.jpg" />
			</div>
			<div class="wuliu">
				<img src="public/img/guid/tu.png" />
			</div>
			<div class="fuli_a">
			</div>
			<div class="fuli_b">
				<img src="public/img/guid/fuli.png" />
			</div>
			<div class="tubiao">
				
			</div>
		</div>
	</body>
</html>
