<?php
$css = $this -> assets -> get('header');
$css -> addCss("public/v3.0.1/css/pc.about.css");
?>
<div class="row-container clearfix">
	<div class="aboutus  main-container">
		<ul class="bcrumb">
			<li>
				<i class=" icon-home icon-large"></i>
			</li>
			<li>
				<a href="/">如此生活</a><span class="divider">&gt;</span>
			</li>
			<li>
				<a href="/about/index.html">关于我们</a><span class="divider">&gt;</span>
			</li>
			<li>
				<a href="mbrCenter">联系我们</a>
			</li>
		</ul>
		{{ partial("about/inc_crumb") }}
		<div class="prof-right">
			<div class="prof-right-tit" style=" font-size: 28px; height: 90px; line-height:110px; padding-left: 40px; font-family: '微软雅黑'; color: #228dc1;">
				自提点 <span style="font-size: 14px;">Pick up</span>
			</div>
			<div class="prof-right-con" style="padding-left: 40px;">
				<p style="margin-top: 10px"><a href="#a" style="font-size: 16px;font-weight: 400;text-decoration:underline;">上海松江万达体验店</a></p>
				<p ><a href="#b" style="font-size: 16px;font-weight: 400;text-decoration:underline;">上海嘉定宝龙体验店</a></p>
				<p ><a href="#c" style="font-size: 16px;font-weight: 400;text-decoration:underline;">苏州国发大厦体验店</a></p>
				<p ><a href="#d" style="font-size: 16px;font-weight: 400;text-decoration:underline;">镇江宝龙体验店</a></p>
				<p ><a href="#e" style="font-size: 16px;font-weight: 400;text-decoration:underline;">厦门集美万达体验店</a></p>
				<div class="_home">
					<a name="a"></a>
					<h3>上海松江万达体验店</h3>
					<p >地址：上海市松江区广富林路658弄668号4楼</p>
					<p >电话：4000685151</p>
					<p>交通：地铁9号线松江大学城站（4号口），松江15路-松江客运中心站上车--工程技术大学站下车（5站），步行200米</p>
					<img src="/public/img/aboutus/home/u11.png" />
				</div>
				<div class="_home">
					<a name="b"></a>
					<h3>上海嘉定宝龙体验店</h3>
					<p >地址：上海市嘉定区阿克苏路1099号嘉定宝龙广场M1-2F</p>
					<p >电话：4000685151</p>
					<p>交通：地铁11号线白银站（1号口），嘉定18路-公交白银路站上车--阿克苏路宝塔路站下车（3站），步行160米</p>
					<img src="/public/img/aboutus/home/u18.png" />
				</div>
				<div class="_home">
					<a name="c"></a>
					<h3>苏州国发大厦体验店</h3>
					<p >地址：江苏省苏州市姑苏区人民路3118号苏州国发平江大厦B1</p>
					<p >电话：4000685151</p>
					<p>交通：地铁2号线平河路站（4号口），步行410米</p>
					<img src="/public/img/aboutus/home/u25.png" />
				</div>
				<div class="_home">
					<a name="d"></a>
					<h3>镇江宝龙体验店</h3>
					<p >地址：江苏省镇江市丹徒区谷阳中大道镇江宝龙广场3F</p>
					<p >电话：4000685151</p>
					<p>交通：139路-架鼓山路站下车，步行750米</p>
					<img src="/public/img/aboutus/home/u32.png" />
				</div>
				<div class="_home">
					<a name="e"></a>
					<h3>厦门集美万达体验店</h3>
					<p >地址：福建省厦门市集美区银江路137号万达广场2楼</p>
					<p >电话：4000685151</p>
					<p>交通：953路快运/950路-集美区政府站下车，步行320米</p>
					<img src="/public/img/aboutus/home/u39.png" />
				</div>
			</div>
		</div>
	</div>
</div>