<div class="prof-left ">
	<div class="prof-left-tit">
		<h2>如此生活</h2>
	</div>
	<div class="prof-left-con">
		<ul>
			<li {% if nav == 'about' %} class="cur" {% endif %} >
				<a href="index.html">关于我们</a>
			</li>
			<li {% if nav == 'founder' %} class="cur" {% endif %}>
				<a href="founder.html">企业创始人</a>
			</li>
			<li {% if nav == 'home' %} class="cur" {% endif %}>
				<a href="home.html">自提点</a>
			</li>
			<li {% if nav == 'contact' %} class="cur" {% endif %}>
				<a href="contact.html">联系我们</a>
			</li>
			<li {% if nav == 'sop' %} class="cur" {% endif %}>
				<a href="http://shop.test.soolife.cn" target="_blank">商家入驻</a>
			</li>
			<li {% if nav == 'brand' %} class="cur" {% endif %}>
				<a href="brand.html">品牌介绍</a>
			</li>
			<li {% if nav == 'links' %} class="cur" {% endif %}>
				<a href="links.html">友情链接</a>
			</li>
			<li {% if nav == 'law' %} class="cur" {% endif %}>
				<a href="law.html">法律声明</a>
			</li>
		</ul>
	</div>
	<div class="prof-left-footer"> </div>
</div>