<?php
$css = $this -> assets -> get('header');
$css -> addCss("public/v3.0.1/css/pc.about.css");
?>
<div class="row-container clearfix">
	<div class="aboutus  main-container">
		<ul class="bcrumb">
			<li><i class=" fa fa-home fa-lg"></i></li>
			<li><a href="/">如此生活平台</a><span class="divider">&gt;</span></li>
			<li><a href="javascript:void(0);" onclick="">关于我们</a></li>
		</ul>
		{{ partial("about/inc_crumb") }}
		<div class="prof-right" style="padding-left: 30px;">
			<div class="aboutus-title">
				<h2>关于如此生活</h2><span>About&nbsp; us</span>
			</div>
			<div class="top2">
				<img style="float: left;" src="/public/img/aboutus/abus_03.jpg" alt="如此生活"/>
				<div class="top2_b1">
					<p>
						&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
						鸿惠（上海）信息技术服务有限公司成立于2013年，是一家拥有独创技术和跨平台发展的创新型企业，公司总部位于上海，汇聚了来自互联网电子商务、市场品牌营销等多个不同领域，富有激情与梦想的行业精英，秉承着诚信团结、以人为本、求实创新、社会责任心的核心价值观，并通过互联网应用和信息化服务技术，开创了中国电子商务的崭新平台。
					</p>
					<p>
						&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
						“soolife”品牌，凭借独创的商业模式、强大的技术研发能力、创新的互动体验，全新打造了一个与消费者多频次、近距离接触的互动体验新平台。通过独有的（终端、网络、移动和本地化）四维一体的互动体验模式 ，让消费者在获得优惠的同时。让更多中小企业主受益，提高了品牌知名度和商品的销量，与此同时，也为那些拥有梦想的人们提供了绝佳的创业商机，帮助他们建立自己的商铺，开拓广袤的消费市场，建立属于自己的商业帝国；相惜未来每一个人都将在“soolife”平台上绽放出多彩的生活！
					</p>
					<p>
						&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
						公司立志成为中国未来最大的一站式服务平台，为实现让民众受益，让商家营利的宏伟愿景而不断奋斗！
					</p>
				</div>
			</div>
			<div class="top3">
				<h2>公司文化</h2><span>Company&nbsp; Culture</span>
			</div>
			<div class="top4">
				<img src="/public/img/aboutus/abus_06.jpg" />
				<div class="top4_div1">
					<ul>
						<li class="top4_l1">
							<strong>公司定位</strong>
						</li>
						<li>
							全球体验式生活领导者
						</li>
						<li class="top4_l2">
							<strong>品牌业务</strong>
						</li>
						<li>
							以O2O为基础&nbsp;一站式服务为核心
						</li>
						<li class="top4_l3">
							<strong>家人文化</strong>
						</li>
						<li>
							拼搏、成长、感恩、分享
						</li>
					</ul>
				</div>
				<img src="/public/img/aboutus/abus_08.jpg" />
				<div class="top4_div2">
					<ul>
						<li class="top4_l1">
							<strong>品牌愿景</strong>
						</li>
						<li>
							为人们创造更好生活
						</li>
						<li class="top4_l2">
							<strong>品牌目标</strong>
						</li>
						<li>
							为企业主、消费者、合伙人提供一种全新生活体验方式
						</li>
						<li class="top4_l3">
							<strong>公司理念</strong>
						</li>
						<li>
							让民众受益，让商家营利
						</li>
					</ul>
				</div>
			</div>
			<div class="mid1">
				<h2>公司模式</h2><span>Company&nbsp;Model</span>
			</div>
			<div class="mid2">
				<img style="float: left;" src="/public/img/aboutus/abus_12.jpg" alt="O2O平台为基础"/>
				<div class="mid2_div1">
					<h3>O2O平台为基础</h3>
					<p>
						&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;平台是由三大功能版块：网站、体验店、移动端构成综合立体化平台，本地仓储作为连接终端，将所有的功能和服务进行互动联合。
					</p>
				</div>
			</div>
			<div class="mid3">
				<div class="mid3_left">
					<ul>
						<li class="mid3_l1">
							<h3>一站式服务为核心</h3>
						</li>
						<li class="mid3_l2">
							商家服务
						</li>
						<li class="mid3_l3">
							1.去团队
						</li>
						<li style="color: #777777;">
							（线上线下无需运营人员）
						</li>
						<li class="mid3_l4">
							2.去广告
						</li>
						<li style="color: #777777;">
							（线上线下全平台化无广告推广）
						</li>
						<li class="mid3_l5">
							3.去开店
						</li>
						<li style="color: #777777;">
							（线上线下开设店铺）
						</li>
						<li class="mid3_l6">
							4.去仓储
						</li>
						<li style="color: #777777;">
							（线下商品代存代发）
						</li>
					</ul>
				</div>
				<img style="float: left;" src="/public/img/aboutus/abus_15.jpg" alt="商家服务"/>
			</div>
			<div class="mid4">
				<img style="float: left;" src="/public/img/aboutus/abus_16.jpg" alt="消费者服务"/>
				<div class="mid4_right">
					<ul>
						<li class="mid4_l1">
							<h3>一站式服务为核心</h3>
						</li>
						<li class="mid4_l2">
							消费者服务
						</li>
						<li class="mid4_l3">
							1.购便利
						</li>
						<li style="color: #777777;">
							（时间便利、下单便利、提货便利）
						</li>
						<li class="mid4_l4">
							2.购快乐
						</li>
						<li style="color: #777777;">
							（秀时尚、秀生活、秀体验）
						</li>
						<li class="mid4_l5">
							3.购优惠
						</li>
						<li style="color: #777777;">
							（购物优惠、活动优惠、特卖优惠）
						</li>
						<li class="mid4_l6">
							4.购增值
						</li>
						<li style="color: #777777;">
							（礼品增值、赠品增值、奖品增值）
						</li>
					</ul>
				</div>
			</div>
			<div class="mid5">
				<h3>战略目标</h3>
				<p style="margin-top: 5px;">
					2015年10月18日上海第一家体验店开业(位于上海市恒丰路与汉中路交叉口太阳城广场三楼整层)，面积
				</p>
				<p>
					4800平米，容纳1000个品牌，10000个以上SKU地处上海最繁华的静安区，交通便捷，靠近著名的南京西
				</p>
				<p>
					路和人民广场。
				</p>
			</div>
			<div class="mid6">
				<div class="mid6_div">
					<img src="/public/img/aboutus/abus_20.jpg" alt="soolife如此生活线下体验店1"/>
					<img style="margin-left: 10px;" src="/public/img/aboutus/abus_22.jpg" alt="soolife如此生活线下体验店2" />
					<img style="margin-top: 10px;" src="/public/img/aboutus/abus_27.jpg"  alt="soolife如此生活线下体验店3"/>
					<img style="margin-left: 10px;margin-top: 10px;" src="/public/img/aboutus/abus_28.jpg"  alt="soolife如此生活线下体验店4"/>
					<img src="/public/img/aboutus/abus_29.jpg" alt="5年发展战略目标"/>
				</div>
			</div>
			<div class="mid7">
				<h2>公司荣誉</h2><span>Company&nbsp;Honor</span>
			</div>
			<div style="clear: both;"></div>
			<div class="bot">
				<div class="bot_div1">
					<p>
						&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1、公司正式在上海股权托管交易中心中小企业股权报价系
					</p>
					<p>
						统正式挂牌。企业名称：鸿惠信息，企业代码：200777。
					</p>
					<p>
						&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2、公司目前和百度达成战略合作并成功签约。
					</p>
					<p>
						&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;3、公司获得上海市诚信企业认证、并且定期举办爱心捐赠
					</p>
					<p>
						活动，社区义卖活动等，积极投身社会公益。
					</p>
					<p>
						&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;4、公司获得上海市长宁区专精特新企业认证。
					</p>
				</div>
				<div class="bot_right">
					<img style="margin-top: 80px;" src="/public/img/aboutus/abus_32.jpg" />
					<img style="margin-top: 80px;margin-left: 12px;" src="/public/img/aboutus/abus_34.jpg" />
				</div>
				<div class="bot_bot">
					<img src="/public/img/aboutus/abus_39.jpg" />
					<img src="/public/img/aboutus/abus_41.jpg" />
					<img src="/public/img/aboutus/abus_43.jpg" />
					<img src="/public/img/aboutus/abus_45.jpg" />
					<img src="/public/img/aboutus/abus_47.jpg" />
				</div>
			</div>
		</div>
	</div>
</div>