<?php
$css = $this -> assets -> get('header');
$css -> addCss("public/v3.0.1/css/pc.about.css");
?>
<div class="row-container clearfix">
	<div class="aboutus  main-container">
		<ul class="bcrumb">
			<li>
				<i class=" icon-home icon-large"></i>
			</li>
			<li>
				<a href="/">如此生活</a><span class="divider">&gt;</span>
			</li>
			<li>
				<a href="/about/index.html">关于我们</a><span class="divider">&gt;</span>
			</li>
			<li>
				<a href="mbrCenter">友情链接</a>
			</li>
		</ul>
		{{ partial("about/inc_crumb") }}
		<div class="prof-right">
			<div class="prof-right-tit">
				友情链接
			</div>

			<div class="prof-right-con">

				<div class="prof-right-link">

					<ul >
						{% for vo in links %}
						<li>
							<div>
								<i class=" fa fa-external-link"></i>
								<a target="_blank" href="{{vo['target']}}" title="{{vo['title']}}">{{vo['title']}}</a>
							</div>
						</li>
						{% endfor %}
					</ul>
					<div class="clear"></div>
				</div>
			</div>
			<div class="prof-right-link">
				<div class="prof-right-tit">
					申请友情链接
				</div>
				<div class="prof-right-link-app">
					<div class="prof-right-con">
						<h5>申请步骤</h5>
						<p class="prof-right-para">
							1.请先在贵网站做好如此生活的文字友情链接：
						</p>
						<p class="prof-right-para">
							链接文字：如此生活链接地址：<a href="https://www.soolife.cn" target="_blank">https://www.soolife.cn</a>
						</p>
						<p class="prof-right-para">
							2.做好链接后，请在右侧填写申请信息。如此生活只接受申请文字友情链接。
						</p>
						<p class="prof-right-para">
							3. 已经开通我站友情链接且内容健康，符合本站友情链接要求的网站，经如此生活管理员审核后，可以显示在此友情链接页面。
						</p>
					</div>

					<h5>申请信息</h5>
					<form id="shop_form" class="form-horizontal" novalidate="novalidate">
						<div class="prof-right-link-line clearfix">
							<label>网站名称：</label>
							<div>
								<input type="text" name="title" value="">
							</div>
						</div>
						<div class="prof-right-link-line clearfix">
							<label>网    址：</label>
							<div>
								<input type="text" value="https://" name="website">
							</div>
						</div>
						<div class="prof-right-link-line clearfix">
							<label>电子邮箱：</label>
							<div>
								<input type="text" value="" name="email">
							</div>
						</div>
						<div class="prof-right-link-line clearfix">
							<label>网站介绍：</label>
							<div>
								<input type="text" value="" name="web">
							</div>
						</div>
						<div class="prof-right-link-line clearfix">
							<a class="sub" href="javascript:void(0)">提交申请</a>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="modal fade modal-small" id="myModal" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-border">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">
					<span aria-hidden="true">&times;</span>
				</button>
				<!-- <h4 class="modal-title">温馨提示</h4> -->
			</div>
			<div class="modal-body">
				<div class="hint color-orange">申请友情链接成功！</div>
			</div>
			<div class="modal-footer">
				<a class="cancel_btn" data-dismiss="modal"> 关闭 </a>
			</div>
		</div>
		</div>
	</div>
</div>
